### ISSUE TITLE
add stream does not work in 2.5.0-2

### ISSUE THREAD

**Issue by martincheco** [cmus/cmus#10]
command for adding streams

:add http://www.play.cz/radio/radio1-192.mp3.m3u

fails without an error message. Using arch linux with raspberry pi.
The stream works ok with cmus v2.4.2 on ubuntu.

**Comment by belugame** [comment]
What could be the reason if one stream does not work? I have a list of streams in a file and add the the whole file, all work except this one http://www.top-fm.de/stream/stream-top-fm.m3u
v.2.7.1
