### ISSUE TITLE
cmus closes after re-attaching HDMI cable to inactive output.

### ISSUE THREAD

**Issue by sklv** [cmus/cmus#1000]
1) `uname -a`:
```
Linux myhostname 5.4.72-gentoo #1 SMP Tue Oct 27 11:52:50 -00 2020 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
```

I have 2 GPUs, one attached to my host system, and one passed through via VFIO to a libvirtd VM.
My host WM, `sway`, is configured to idle the output after 10 minutes.
Previously, I had a cable from each GPU to my monitor, and used the monitor buttons to switch. This worked without issues.
Recently, to save the inconvenience of navingating the monitor menus, I switched to an HDMI switch (so a Y configuration) to switch outputs faster.
Since doing this, when switching from the guest output back to the host output, after the host output has beeen idled causes cmus to crash.
I built sway with the debug USE flag, and generated a cmus-debug.txt:
```
...
do_open: 
  frames: 128939, br: 102944 b/s, sr: 32000 Hz, ch: 2, layer: 3, joint stereo: 1
  dual channel: 0, vbr: 1, duration: 4641.8 s, xing: 1
ip_setup: pcm convert: scale=1 convert=0 convert_in_place=0
_pa_context_running_cb: pulse: context state has changed to PA_CONTEXT_TERMINATED
_pa_stream_running_cb: pulse: stream state has changed to PA_STREAM_TERMINATED
_pa_context_running_cb: pulse: context state has changed to PA_CONTEXT_CONNECTING
_pa_context_running_cb: pulse: context state has changed to PA_CONTEXT_AUTHORIZING
_pa_context_running_cb: pulse: context state has changed to PA_CONTEXT_SETTING_NAME
_pa_context_running_cb: pulse: context state has changed to PA_CONTEXT_READY
_pa_stream_running_cb: pulse: stream state has changed to PA_STREAM_CREATING
_pa_stream_running_cb: pulse: stream state has changed to PA_STREAM_READY
main_loop: vol changed
```
Finally, running `$?` in the shell where cmus was previously running returns `134` implying this is the code cmus exited with.

**Comment by sklv** [comment]
I suspect when the cable is disconnected, the HDMI audio output is removed, then when the cable is reconnected, an HDMI output is added, which somehow causes cmus to quit, even though I'm using my motherboard's `Starship/Mantisse HD Audio Controller`.

**Comment by pgaskin** [comment]
Can you upload a core dump along with the cmus binary and op/pulse.so so I can take a closer look at this issue?

**Comment by sklv** [comment]
I tried to reproduce this and wasn't able to.
