### ISSUE TITLE
Can't change the volume,which keeps being the biggest!

### ISSUE THREAD

**Issue by Onetopabove** [cmus/cmus#1003]
---

1) `uname -a`:
```
Linux ykc 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt
ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv m
p+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
```
When I change the volume, cmus will do it without any effect just changing the number.
![vol](https://user-images.githubusercontent.com/38457754/99807165-0b44e100-2b7a-11eb-8a5b-8dd67f7a5328.png)
The volume keep being the **biggest**,not to be bigger or smaller.But,I can just watch video on Chromium and can change the volume there.
I set the sound system from arch wiki,which is alsa and some basic configuration.And I use pacman to install cmus.

**Comment by sklv** [comment]
Does anything happen when you press `-` (should decrease volume) or `+`/`=` (should increase volume).
Can you change the volume with alsamixer?
If you use pulseaudio does the issue still happen?

**Comment by Onetopabove** [comment]
> Does anything happen when you press `-` (should decrease volume) or `+`/`=` (should increase volume)?
> Can you change the volume with alsamixer?
> If you use pulseaudio does the issue still happen?

Nothing happend but just the number indicating the volum changed, when I press `-`or`+/=`.

If I change the volume in alsamixer,the volume number changes as well in cmus.Meanwhile,If I change the volume in cmus,the volume number changes as well in alsamixer.But, it won't take effect.
![image](https://user-images.githubusercontent.com/38457754/99866127-b3de5980-2be9-11eb-8b38-3337da7f62a9.png)
The volume numbers above synchronize from 0 to 100 but don't equal.

I installed pulseaudio/pulseaudio-alsa/pulsemixer when I read the arch wiki(some may not be needed),and then type `pulsemixer` in terminal.Then, I see:
![image](https://user-images.githubusercontent.com/38457754/99866499-9bbc0980-2bec-11eb-8025-d89fca35f34d.png)
Now, I have no idea what to do next.It should be that I'm not ready to configure the sound system in Linux.

**Comment by sklv** [comment]
I'm not sure what the root cause of your issue is.
IMHO your audio system being misconfigured and a bug in cmus are just as likely.
In your pulsemixer screenshot, cmus is not using pulseaudio.
Here's what pulsemixer looks like when pulseaudio clients are using it: https://snapforum.s3.amazonaws.com/original/1X/3f89e81fc84d9b2b70c6de08c3061cb2397a3c67.png
As cmus is unmaintained and you're unlikely to resolve your issue here, I suggest you ask in the IRC for whichever distro you are using.

**Comment by Onetopabove** [comment]
Yes, you're supposed to be right.
In my PC, pulseaudio isn't necessary and is not invoked by cmus.There would be whatever problems I not clear about, so It needs more learning to configure the sound system correctly.
Thanks for your comments.

**Comment by nefthy** [comment]
Try :set softvol=true
