### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by pgaskin** [cmus/cmus#1022]
The new Travis CI billing model is a PITA.

@flyingmutant, do you want me to open a PR for this?

**Comment by flyingmutant** [comment]
Yes, that'd be great.

**Comment by pgaskin** [comment]
Do you want to stick with Ubuntu 14.04?

**Comment by flyingmutant** [comment]
> * Do you want to stick with Ubuntu 14.04?

I'd go with 20.04 LTS.

> * Do you want to add Windows builds?

Would be nice, and will be OK to settle for reduced amount of plugins if required.

> * Do you want to build on multiple Linux distros?

I am not against it but not sure if there is a real benefit.

> * Do you want to add clang-tidy (this would be in another PR)?

Would be nice -- but will probably have to clean up some warnings first.

> * Do you want to add clang-analyzer (this would be in another PR)?

Same here.
