### ISSUE TITLE
Arbitrary track metadata in status line

### ISSUE THREAD

**Issue by ruslaniv** [cmus/cmus#1028]
Is it possible to display any arbitrary track's metadata in the status line? 
For example sample rate, bits per sample, copyright, encoder, etc?

**Comment by nefthy** [comment]
Reading the friendly manual you get:  
```
 Format Strings
       Format strings control display of tracks in library, playlist and play queue views.

       NOTE: altformat_* options are used when there are no tags available.

       Special Keys:

              %a  %{artist}
              %A  %{albumartist}
              %l  %{album}
              %D  %{discnumber}
              %n  %{tracknumber}
              %X  %{play_count}
              %t  %{title}
              %g  %{genre}
              %c  %{comment}
              %y  %{date}
              %d  %{duration}
              %f  %{path}
              %F  %{filename}
                  %{albumduration}
                  %{originaldate}
                  %{maxdate}
                  %{bpm}
                  %{bitrate}
                  %{codec}
                  %{codec_profile}
                  %{rg_track_gain}
                  %{rg_track_peak}
                  %{rg_album_gain}
                  %{rg_album_peak}
                  %{arranger}
                  %{composer}
                  %{conductor}
                  %{lyricist}
                  %{performer}
                  %{remixer}
                  %{label}
                  %{publisher}
                  %{work}
                  %{opus}
                  %{partnumber}
                  %{part}
                  %{subtitle}
                  %{media}
              %=
                     start align right (use at most once)
              %%
                     literal %
              %?
                     literal ?

```

**Comment by ruslaniv** [comment]
Yes, I definitely did read the manpage. But I was I was rather interested in the tags not listed here.
Like "sample rate", "bits per sample" or custom tags like "copyright" and "encoder". 

![Screen Shot 2020-12-19 at 20 19 17](https://user-images.githubusercontent.com/7631314/102690368-852ebf80-4237-11eb-9ac9-317de1a2115e.png)
![Screen Shot 2020-12-19 at 20 19 31](https://user-images.githubusercontent.com/7631314/102690369-8829b000-4237-11eb-8469-5cc22fb93323.png)

**Comment by ruslaniv** [comment]
I tried adding different tags to the status line, like 
`%{encoder}` 
and 
`%{originalsamplerate}`
but I get 
`Error: invalid format string`

**Comment by nefthy** [comment]
Please review the list above for the available format strings.

**Comment by NebuPookins** [comment]
@nefthy it seems like you're not actually reading @ruslaniv 's request? They are submitting a feature request to support new metadata information.

**Comment by xeverse** [comment]
welll %{samplerate} & %{bitdepth} are absolutely necessary..

**Comment by pgaskin** [comment]
Due to the way cmus currently reads and stores metadata, it is not feasible to provide access to arbitrary fields, as some fields (e.g., lyrics, artwork) may contain large amounts of text or data, which would bloat `lib.pl` (and the memory usage of cmus).

Please open a new issue for each metadata field you would like cmus to store and support in expressions.
