### ISSUE TITLE
Feature request: Multiple library support

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#1029]
Feature request: Multiple library support

I would like to be able to manage and open different library files (not just multiple playlists)

**Comment by pgaskin** [comment]
As a workaround, you can create a wrapper script which sets `CMUS_HOME` to a different directory.

**Comment by zoozhi** [comment]
> As a workaround, you can create a wrapper script which sets `CMUS_HOME` to a different directory.

Yes I can do many work arounds, but it would be nice to have it as a feature capability, even as a command line argument will do me, even nicer to have it managable by a view

**Comment by nefthy** [comment]
There is little difference between:
```CMUS_HOME=/some/where cmus```
and
```cmus --home /some/where```

That said, integration of a new top level hierarchy "library" would require large changes across the whole codebase. This is quite unlikely to happen.
