### ISSUE TITLE
Delay before pausing a song

### ISSUE THREAD

**Issue by toniz4** [cmus/cmus#1032]
---

1) `uname -a`:
```
Linux gentoo 5.9.14-gentoo-x86_64-x230 #23 SMP Mon Dec 28 21:32:45 -03 2020 x86_64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz GenuineIntel GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  alsa
```

When i pause cmus using mpris, directly on the player or with cmus-remote there is a delay in between i pressing the button and the music stopping.

I had the same problem with mpd, but i could set `buffer_time "1"` to the alsa output and that would solve my problem. I tried setting buffer_seconds to 1 in cmus, but it didn't work.

**Comment by pgaskin** [comment]
What does the debug log say if you configure cmus with `DEBUG=2`?

**Comment by toniz4** [comment]
Sorry for the noobness, but where would the logs be?

**Comment by pgaskin** [comment]
There should be a `cmus-debug.txt` in your home folder.

**Comment by toniz4** [comment]
https://0x0.st/-rwD.txt here it is. I used a fresh config file.

**Comment by pgaskin** [comment]
It appears your soundcard doesn't have hardware pause support, but `snd_pcm_drop` *should* still work instantly. What is the output of `aplay -l`?

**Comment by toniz4** [comment]
Here it is:
```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC269VC Analog [ALC269VC Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by toniz4** [comment]
I managed to fix it by configuring alsa. I used this asoundrc configuration:
```
pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw           
        card 0
        buffer_size 0
}
```
source: https://www.alsa-project.org/main/index.php/Asoundrc
