### ISSUE TITLE
[Bug] Cmus "forgets" library after quiting the program -- Homebrew M1 Mac

### ISSUE THREAD

**Issue by IceCloud76** [cmus/cmus#1034]
---
#### Cmus was installed via Homebrew, and this is a native ARM build for M1 Macs **not** running in Rosetta 2.

*Expected Results:* Open Cmus. Add files to library. Quit Cmus (`:q`). Open cmus again and all the files added before are  present in the album/artist window.

*Actual Results:* Open Cmus. Add files to library. Quit Cmus (`:q`). Open cmus again and all the files added before are *gone* in the album/artist window. They must be added each time I start cmus.

1) `uname -a`:
```
Darwin macmini 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /opt/homebrew/Cellar/cmus/2.8.0_5/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /opt/homebrew/Cellar/cmus/2.8.0_5/lib/cmus/op
  coreaudio
```

**Comment by KamranMackey** [comment]
Have you tried *manually* saving the library state using `:save`? IIRC that should automatically save the `lib.pl` file in cmus' data directory.

**Comment by IceCloud76** [comment]
Manually saving using `:save` gets me a permissions error on /Users/foo/.config/cmus/lib.pl because it's owned by root and only root has write privileges. A simple `sudo chown foo /Users/foo/.config/cmus/lib.pl` fixes it.

I'm not sure why this file was ever assigned to root, homebrew (`brew`) is never run as root unlike a normal package manager. I'm also not sure if this is a bug of cmus or homebrew. But at least the workaround for now is easy.

**Comment by nefthy** [comment]
Cmus only creates files with the same user as the operating system process. So this is probably a problem external to cmus. If you find a way to reproduce this behaviour, feel free to reopen this bug.
