### ISSUE TITLE
[Feature request] Setting default directory for browser

### ISSUE THREAD

**Issue by l0f4r0** [cmus/cmus#1035]
It would be nice to be able to choose a default directory for browser.
Currently, I'm stuck in my ~ Desktop folder.

NB: Actually, to satisfy everyone, we could imagine having 2 modes:
* Default (configurable) directory
* Last opened directory (see [#942](https://github.com/cmus/cmus/issues/942))

**Comment by pgaskin** [comment]
> Default (configurable) directory

Add a line like `cd /path/to/default/directory` to `rc` in your config dir.

**Comment by l0f4r0** [comment]
Thanks @pgaskin ! :)
