### ISSUE TITLE
Cant find ncurses when running ./configure prefix=$HOME/cmus

### ISSUE THREAD

**Issue by bjonke** [cmus/cmus#1043]
---
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lncursesw)... no
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lncurses)... no
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lcurses)... no

have all the ncurses packages installed and working with other applications.

Checked 
1) `uname -a`:
```
(paste output here)
```
5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

2) `cmus --version`:
```
Latest
```

3) `cmus --plugins`:
```
None
```

**Comment by nefthy** [comment]
you also need the development packages: ```apt intall ncurses-dev```

**Comment by pgaskin** [comment]
Yes, and also, you'll probably want the development packages for the input/ouput plugin optional dependencies: https://github.com/cmus/cmus/blob/0aceac178204c6398e86edf30bdbe001dc88649b/.github/workflows/build.yml#L29-L35

**Comment by pgaskin** [comment]
I'm going to close this issue now since there hasn't been any response. @bjonke, if you still have this issue, feel free to reopen it.
