### ISSUE TITLE
Terminal tabs all labeled "cmus 2.7.0" even after uninstalling cmus

### ISSUE THREAD

**Issue by Rogue-Ishtar** [cmus/cmus#1047]
I installed cmus from the Debian Buster repository, to try it out. I uninstalled it later, but now my terminal window still shows "cmus 2.7.0" at the top of _every_ tab I open in it. (See attached screenshot.) Why? I have already uninstalled cmus. Besides, even when it's installed, shouldn't it only show "cmus" at the top of my terminal tab when cmus is actually running? It makes no sense that every tab is still labeled "cmus 2.7.0" after I have removed cmus from my system. (Note: I'm running Debian Buster on a VM on a Chromebook. The terminal emulator is Chrome's own, I believe.)

![Screenshot 2021-01-21 at 19 59 57](https://user-images.githubusercontent.com/77570593/105399891-80896c80-5c24-11eb-8d67-fceed2761238.png)

Sorry for the black theme. The "0 ~" is my prompt, in case that's not clear.

As for your required questions, here are the answers:

1) `uname -a`:
```
Linux penguin 5.4.48-06434-gd868196d13af #1 SMP PREEMPT Wed Jul 29 00:32:34 PDT 2020 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  ffmpeg:
    Priority: 30
    File Types: aa ac3 aif aifc aiff ape au mka shn tak tta wma webm aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by pgaskin** [comment]
This is a bug (or a feature) in your terminal emulator, not cmus. It probably remembers titles from previous sessions.

From the screenshot and uname, it looks like you're using Crostini. I found [something](https://www.reddit.com/r/Crostini/comments/hg137h/how_to_set_tab_namestitles_in_the_new_terminal/) about this, and it appears the solution is to make your prompt reset the title.

**Comment by Rogue-Ishtar** [comment]
> This is a bug (or a feature) in your terminal emulator, not cmus. It probably remembers titles from previous sessions.
Noted, with thanks.
