### ISSUE TITLE
15-30% CPU usage on JACK

### ISSUE THREAD

**Issue by RinRi-D** [cmus/cmus#1056]
I use JACK as output plugin. Cmus uses 15-30% of my CPU while playing various songs. If I play a 44.1 kHz track with 48 kHz JACK settings, CPU usage is about 15%. If I change JACK's sample rate to 44.1 kHz, CPU usage is only 2-3%. But I have various tracks, and if I play 96 kHz track CPU usage rises up to 30%.

---

1) `uname -a`:
```
Linux 5.10.12-artix1-1 #1 SMP PREEMPT x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

**Comment by nefthy** [comment]
That is because the jack plugin has to do resampling from 44.1k to 48k or 96k. The resampling is done by libsamplerate, if anyone knows of a more efficient library, I'd happy to give it a try.

**Comment by RinRi-D** [comment]
For example, in [mpv](https://github.com/mpv-player/mpv), there is no such problem.
`
(+) Audio --aid=1 (flac 2ch 96000Hz)
AO: [jack] 44100Hz stereo 2ch floatp
`
CPU usage is about 3-6%.

**Comment by nefthy** [comment]
by default the highest posible quality is used. You can lower that with `:set dsp.jack.resampling_quality = 1`
