### ISSUE TITLE
Show Hidden Files and Folders

### ISSUE THREAD

**Issue by TheTerrior** [cmus/cmus#1057]
Hello, I'm wondering how to show hidden files and folders in the file browser. I have much of my music organized by using periods and commas to shift the order that folders are displayed in, but inside cmus all folders with a period are hidden. How can I display them? Thank you in advance.

**Comment by pgaskin** [comment]
With the default keybindings, you can press `i` to show hidden files. Alternatively, you can set the `show_hidden` option.
