### ISSUE TITLE
99% CPU at *end* of song

### ISSUE THREAD

**Issue by AlbeyAmakiir** [cmus/cmus#1063]
Sometimes cmus freezes and gets locked into around 98-100% CPU usage, and can only be killed by a SIGKILL. I've discovered for me, unlike other issues that experience this, it happens at the _end_ of a song. It freezes once the song finishes and is _about_ to move to the next one. But when I play the next one without finishing the previous, it works fine.

Some conveniently free examples of music that triggers this for me (fan-made rearrangements of videogame music, because I'm _that_ person :stuck_out_tongue: ):

- https://ocremix.org/remix/OCR03483 "Dream of Green"
- https://ocremix.org/remix/OCR03019 "A Derelict Machine"

Most of the music there is fine. I haven't found a pattern.

---

1) `uname -a`:
```
Linux changeling 5.3.18-lp152.66-default #1 SMP Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv *
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  oss
```

**Comment by pgaskin** [comment]
Does `ffplay` play through it successfully?

**Comment by AlbeyAmakiir** [comment]
`ffplay` seems to play just fine. I even let it finish, then skipped back to see if it would fail, and it did not.

I seem to have been using `ffmpeg version 3.4.8`. I could try installing `ffmpeg-4`, but on openSUSE Leap it looks like a whole process to switch, and it seems to work with this version anyway.

I've noticed that, if I queue up just the one song in `cmus`, it doesn't freeze immediately upon finishing if there aren't other songs after. But when I add another song and start playing, _that's_ when it freezes, still with the previous song's time data in the status line.

**Comment by pgaskin** [comment]
Can you do a `strace -fp $(pidof cmus)` for a few seconds before and after the freeze and send the output?

**Comment by AlbeyAmakiir** [comment]
Sure: https://pastebin.com/grR54nXh

The part where it breaks is at the bottom. The output slowed heavily once that happened.

I do not have debugging symbols, unfortunately.

**Comment by pgaskin** [comment]
Which output plugin are you using?

**Comment by AlbeyAmakiir** [comment]
Didn't realise I could set that. I've only been using `cmus` for like a week.

`output_plugin         pulse`

**Comment by pgaskin** [comment]
In that case, I think this is related to a similar freeze I've been trying to track down recently. I'm still not sure exactly what causes it since I can't reproduce it consistently.

**Comment by AlbeyAmakiir** [comment]
Well, I'm getting `Error: opening audio device: No such file or directory` immediately upon starting playback, but it doesn't say which file. I don't know if this is my alsa config or cmus having an issue. I have little experience here.

**Comment by pgaskin** [comment]
```
:set output_plugin=alsa
:set dsp.alsa.device=default
:set mixer.alsa.device=default
:set mixer.alsa.channel=Master
```

**Comment by AlbeyAmakiir** [comment]
`Error: opening audio device: No such device or address` Which seems to be because `Cannot open shared library /usr/lib64/alsa-lib/libasound_module_pcm_jack.so` which is leftover from something I thought I removed cleanly. If this halts further investigation, I might need to get back to you later. <_<

**Comment by pgaskin** [comment]
Check your `asound.conf` for references to JACK.

**Comment by AlbeyAmakiir** [comment]
Ok, I've detangled alsa to test. And the result seems identical. Just to be sure, here's a new log: https://pastebin.com/ZPaW0xdD

**Comment by silenius** [comment]
just to add a "me too" here; cmus 2.9.1 running on FreeBSD 12.2-RELEASE, reading files from a NFSv4 mount..

**Comment by nefthy** [comment]
Could anyone, who is able to reproduce the problem, do a git bisect?

**Comment by AlbeyAmakiir** [comment]
Sure, I could give it a go. Though I don't know if there was ever a commit in which this worked, and also haven't been able to configure the cmus build correctly. `./configure CONFIG_PULSE=y CONFIG_FFMPEG=y` produces
```
[...]
checking for FFMPEG_LIBS (pkg-config)... no
*** Package libavformat was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libavformat.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libavformat' found
configure failed.
```

**Comment by pgaskin** [comment]
https://github.com/cmus/cmus/blob/0aceac178204c6398e86edf30bdbe001dc88649b/.github/workflows/build.yml#L29-L35

**Comment by AlbeyAmakiir** [comment]
I am unable to do this. Between library version dependency conflicts from openSuse's different package manager, and my inexperience with how C and `pkg-config` work in the first place, this is taking a lot more time than I am able to spend on it.
Perhaps @silenius can give this a go?

**Comment by benarmstead** [comment]
I'm also getting this same issue, 

uname -a:
`Linux parabola 5.11.11-hardened1-1-hardened #1 SMP PREEMPT Mon, 05 Apr 2021 18:15:00 +0000 x86_64 GNU/Linux`

**Comment by xmsk** [comment]
I'm having the same issue and without spending much time on it I tried running it in `ffplay` which worked fine but it seems like for all the affected songs that I know I get the following (more or less similar) line right at the end of playback

```
[mp3float @ 0x7fe37c008fc0] Header missing    0KB sq=    0B f=0/0
```

Not sure if someone can make any sense of that? If that helps I'm happy to do some more troubleshooting there. 

I'm running Arch Linux `Linux xxxx 5.11.13-arch1-1 #1 SMP PREEMPT Sat, 10 Apr 2021 20:47:14 +0000 x86_64 GNU/Linux` with `ffmpeg version n4.3.2`.

**Comment by xmsk** [comment]
@nefthy Just did a git bisect and found that for me the commit that introduced the behavior was 9877eb02381fd4c57059f9c77be03127c28d8f88 (coincidentally it looks like that was one of yours :P). @AlbeyAmakiir can you confirm this?

**Comment by AlbeyAmakiir** [comment]
I can't, I'm afraid. I don't know enough about building projects like this to be of use. At least not without more time than I have. :<

**Comment by nefthy** [comment]
@xmsk thanks for tracking this down. Could you provide a file that triggers the issue?

**Comment by boydlowr** [comment]
I would like to add, this problem is happening on Artix Linux aswell but I'm not sure how to reproduce this as it seems so random.

`Linux navi 5.11.16-artix1-1 #1 SMP PREEMPT Thu, 22 Apr 2021 15:59:09 +0000 x86_64 GNU/Linux`

**Comment by jayywolff** [comment]
I've been experiencing this issue as well with the cmus build in the Arch Linux package repo

System
`Linux archbox4 5.12.1-arch1-1 #1 SMP PREEMPT Sun, 02 May 2021 12:43:58 +0000 x86_64 GNU/Linux`

cmus 
`cmus 2.9.1-1`


I can confirm that downgrading cmus to `2.8.0-5` solves the issue.

**Comment by AlbeyAmakiir** [comment]
> I can confirm that downgrading cmus to `2.8.0-5` solves the issue.

Can similarly confirm it works with `cmus v2.8.0-rc0-88-gb595b8c`. (It happened to be the only other version in the openSUSE repo.)

**Comment by xmsk** [comment]
@nefthy unfortunately i did not see your comment, sorry. I just tested with @dryleev's commit and that seems to prevent the huge CPU usage and instead prints a message that there was an error reading the file, thanks for that!

**Comment by nefthy** [comment]
If you could provide a file that triggers the issue, it would help testing the PR etc. Unfortunately or maybe fortunately I have not triggered the issue with my audio collection.

**Comment by dryleev** [comment]
OP had actually provided two of them (if I got you right).

**Comment by AlbeyAmakiir** [comment]
Yes, @nefthy, both of the files I linked to trigger it for me are legally free.

**Comment by xmsk** [comment]
Unfortunately the files triggering the issue for me are copyrighted (I suppose) and I don't feel comfortable sharing them here. I would like to add, however, that the files provided by @AlbeyAmakiir do not trigger the issue for me.

**Comment by jayywolff** [comment]
I can reproduce this issue with some hip-hop mixtapes which don't have copyright protections and are free to download. Here's an example of one mixtape in my library that triggers this bug for me:

https://www.datpiff.com/Wiz-Khalifa-Kush-OJ-mixtape.112367.html

**Comment by dryleev** [comment]
@jayywolff Does #1080 fix it for you?

**Comment by jayywolff** [comment]
@dryleev tbh I'm not sure how to run my own compiled cmus on Arch Linux.

I tried
- cloning your fork
- switching to the branch with the ffmpeg fix
- configured with `./configure CONFIG_PULSE=y CONFIG_FFMPEG=y CONFIG_OPUS=n CONFIG_ROAR=n`
- ran `make`, it successfully compiles
- and when I launch it, it throws some errors that it was unable to find required libs
```
./usr/local/bin/cmus: Error: couldn't open directory `/usr/local/lib/cmus/ip': No such file or directory
./usr/local/bin/cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
```

I tried copying those directories there manually and then I dont get the error, but Im still not able to play any audio files. I just get
```
Error: opening file `/home/jayywolff/Music/test.mp3': unrecognized filename extension
```

How do you configure the compiled cmus binary to search for these in the local directory?

**Comment by nefthy** [comment]
you have to install cmus to a local directory. On top of my head that should go something like:
```
./configure ... prefix=~/cmus
make
make install
cd ~/cmus
./cmus
```

**Comment by jayywolff** [comment]
@nefthy Perfect, thanks that prefix flag is what I was missing.

@dryleev I can confirm when compiling against [cmus:master](https://github.com/cmus/cmus) it doesn't work cpu usage shot up after the song and cmus hangs.

When compiling against [dryleev:fix-ffmpeg-freeze](https://github.com/dryleev/cmus/tree/fix-ffmpeg-freeze) it was able to end the song and switched to the next track as normal.
The only odd thing is with this local install of cmus at the end of each song I see this:
`Error: reading file /home/jayywolff/Music/01-test-song.mp3: internal error`
Not sure if thats just a config issue or thats related to the changes in [dryleev:fix-ffmpeg-freeze](https://github.com/dryleev/cmus/tree/fix-ffmpeg-freeze)

**Comment by dryleev** [comment]
> The only odd thing is with this local install of cmus at the end of each song I see this:
>  `Error: reading file  /home/jayywolff/Music/01-test-song.mp3: internal error`

Not able to reproduce that. Added some debug output, please update then do `./configure DEBUG=2` (add more options if needed, e.g. `prefix`), make it emit that error and post generated ~/cmus-debug.txt here.

**Comment by xmsk** [comment]
I also get the internal error message when finishing one of the tracks that caused the issue. I just figured the files are slightly corrupted and that was expected. Anyways I configured `DEBUG=2` and got the following `cmus-debug.txt` https://gist.github.com/xmsk/9bf0fb269f09a26cdbef993c0e48deac

Btw for me it is located in the cmus config dir, not the home dir, not sure if there is a slight error in the docs?

**Comment by dryleev** [comment]
The line of interest from the `cmus-debug.txt` is this:

    ffmpeg_fill_buffer: avcodec_send_packet() returned -1094995529

If my understanding of ffmpeg [docs](https://www.ffmpeg.org/doxygen/3.4/group__lavc__decoding.html#ga58bc4bf1e0ac59e27362597e467efff3) is correct it corresponds to "legitimate decoding errors" and is what we get for a corrupt data. Looks like VLC silently [drops](https://github.com/videolan/vlc/blob/40664df3e951a17fc1f8da425d4d89c7b86a2af4/modules/codec/avcodec/audio.c#L396) such frames.

I have updated the commit in the linked PR with the call to `av_strerror()`, so please reiterate the test. Can you confirm that you get the error only for files which you know are corrupt?

> Btw for me it is located in the cmus config dir, not the home dir, not sure if there is a slight error in the docs?

Following `debug_init()` from debug.c, cmus first checks if `CMUS_HOME` environment variable is set and if it is not then falls back to `HOME`.

**Comment by xmsk** [comment]
Yes for me it looks like the error only shows up for files that are known to be broken, nice work!

Two minor things I noticed which are really more a cosmetic thing rather than a functional thing
* as far as I see the error message stays until you interact with cmus again (change track, scroll, etc.). Not really bad just found it a bit odd
* at the point where the error message shows up the track seconds jump from the correct time e.g. `2:50 / 3:00` to `00:00 / 03:00`  and then immediately back to the correct time. Again, not really an issue just found it strange.

Not sure how much effort you would have to put in to solve these two things but as far as I'm concerned this issue is resolved now.

**Comment by erwinlagu** [comment]
Fixed!

**Comment by jayywolff** [comment]
still waiting on this fix to be officially released
