### ISSUE TITLE
buffer

### ISSUE THREAD

**Issue by antonellocaroli** [cmus/cmus#1068]
I have seen that the buffer_seconds can be set up to 300.

I modified it so that it accepts more than 300.
so it loads all the track in the ram.
I understand that then it starts to reload the buffer with the next track.

The question is:

Isn't there a way to play an entire album? I mean, as if cmus considered it as one track?

The thing I would like to try is to have the possibility to have the whole album in the cache.

**Comment by nefthy** [comment]
no that is not possible.

**Comment by pgaskin** [comment]
And, it's probably not worth the additional complexity to implement this, especially when it doesn't have a clear benefit.
