### ISSUE TITLE
Alsa params

### ISSUE THREAD

**Issue by antonellocaroli** [cmus/cmus#1069]
do you think it would be possible to add the possibility to set alsa parameters? like squeezelite does?

![image](https://user-images.githubusercontent.com/11161093/112829236-1e6c3e00-9091-11eb-82f3-b14858c54575.png)

**Comment by nefthy** [comment]
Playback would not be correct, if the device parameters do not match the file parameters. Why do you need such a feature?

**Comment by antonellocaroli** [comment]
buffer time, period count and nmap (yes or not) do not change the file.
but from listening to the squeezelite it seems that the sound performance changes as these 3 parameters change. 
https://www.alsa-project.org/wiki/FramesPeriods

**Comment by nefthy** [comment]
cmus does not do sample rate conversion so if you play a 22kHz wav with an alsa device forced to 44kHz it will play at double speed. You will have garbage output if you play a 16bit file with a device set to 32bit. etc.

**Comment by nefthy** [comment]
> but from listening to the squeezelite it seems that the sound performance changes as these 3 parameters change.
Playing the file at its sample and bit rate gives you all the quality you can get.

**Comment by antonellocaroli** [comment]
in reality, these parameters do not affect the bitrate or sample rate, but only set the alsa buffer and its period count.

**Comment by nefthy** [comment]
> ![image](https://user-images.githubusercontent.com/11161093/112829236-1e6c3e00-9091-11eb-82f3-b14858c54575.png)

**Comment by pgaskin** [comment]
> cmus does not do sample rate conversion so if you play a 22kHz wav with an alsa device forced to 44kHz it will play at double speed. You will have garbage output if you play a 16bit file with a device set to 32bit. etc

And, sample rate conversion is a task for sound servers like PipeWire or PulseAudio. Sample rate conversion only takes additional CPU time and will not directly improve audio quality. In general, it's up to users using ALSA directly to configure their hardware to match their application.
