### ISSUE TITLE
FLAC with more than 5 channels broken

### ISSUE THREAD

**Issue by antonellocaroli** [cmus/cmus#1070]
It is not clear to me whether cmus supports high-resolution flac files.

**Comment by MineClashTV** [comment]
It does. Tested up to 24bit/192k on version 2.8.0:
![cmus](https://user-images.githubusercontent.com/30622888/113567137-52ee7580-960e-11eb-864c-2b4bf4c9b701.png)

**Comment by kajzersoze** [comment]
For me it crashes to terminal
This one for example : 
http://www.ploxis.de/music.htm
Tried only the first one, called Escalator II
It throws this in terminal and exits
`ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0`

mpv plays it fine

**Comment by MineClashTV** [comment]
> For me it crashes to terminal
> This one for example : 
> http://www.ploxis.de/music.htm
> Tried only the first one, called Escalator II
> It throws this in terminal and exits
> `ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0`
> 
> mpv plays it fine

Perhaps because it's 6 channel surround?

Can you try out the second track ("Networking") and test both the surround and stereo files?

**Comment by kajzersoze** [comment]
Well it could be, but I have 6 channel speakers, so I need that
Networking stereo works but surround one crashes in the same way as first track
Interestingly there's Escalator track second from the bottom, 5.1 surround flac, but 48khz instead of 96khz, and that one doesn't crash and it plays, but I can hear it only in stereo, when I play that same file with mpv (I have nothing else at the moment) it plays fine and on all channels
So, it's something in cmus for sure, I can try some other players tomorrow 
I don't know what cmus uses actually but I can see mpv using ffplay 
here's that output, maybe it helps maybe not 
```
ffplay version 4.3.2 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 10.2.0 (Gentoo Hardened 10.2.0-r5 p6)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/share/doc/ffmpeg-4.3.2/html --mandir=/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --nm=x86_64-pc-linux-gnu-nm --ranlib=x86_64-pc-linux-gnu-ranlib --pkg-config=x86_64-pc-linux-gnu-pkg-config --optflags='-O2 -pipe -march=native' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-optimizations --disable-libcelt --enable-nonfree --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=jack --disable-indev=sndio --disable-outdev=oss --disable-outdev=sndio --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --enable-gnutls --disable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libtls --disable-libxml2 --disable-lzma --enable-network --disable-opencl --enable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --disable-vaapi --enable-vdpau --enable-vulkan --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --enable-opengl --disable-libv4l2 --enable-libpulse --disable-libdrm --disable-libjack --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libcodec2 --enable-libdav1d --disable-libfdk-aac --disable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-mmal --disable-libmodplug --disable-libopus --disable-libilbc --disable-librtmp --disable-libssh --enable-libspeex --disable-libsrt --enable-librsvg --disable-ffnvcodec --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-cuda-llvm --disable-libflite --disable-frei0r --disable-libfribidi --disable-fontconfig --disable-ladspa --disable-libass --disable-libtesseract --disable-lv2 --enable-libfreetype --disable-libvidstab --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-libvo-amrwbenc --enable-libmp3lame --disable-libkvazaar --disable-libaom --disable-libopenh264 --disable-librav1e --disable-libsnappy --disable-libtheora --disable-libtwolame --disable-libwebp --enable-libx264 --disable-libx265 --enable-libxvid --disable-gnutls --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-vsx --disable-power8 --disable-amd3dnow --disable-amd3dnowext --disable-fma4 --disable-xop --enable-pic --cpu=host --disable-doc --disable-htmlpages --enable-manpages
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, flac, from 'Networking51-9624.flac':0KB sq=    0B f=0/0
  Metadata:
    ARTIST          : Andreas Hollämder
    COPYRIGHT       : Andreas Holländer
    DATE            : 2016
    GENRE           : Alternative
    TITLE           : Networking
  Duration: 00:05:05.39, start: 0.000000, bitrate: 5273 kb/s
    Stream #0:0: Audio: flac, 96000 Hz, 5.1, s32 (24 bit)
```

**Comment by kajzersoze** [comment]
Never mind the mpv, just 'ffplay flacfile' works.
I was looking at your code (flac.c) and it's pretty old, it's missing 6 channels support, I did a quick patch adding 6 channels but that wasn't enough, clearly more work needs to be done,
```
else if (channels == 6)
		mask = 0x60f;
```

**Comment by nefthy** [comment]
please check if PR #1072 fixes your issue.

**Comment by kajzersoze** [comment]
It's better, however I can't hear the sound from rear right speaker
I tried changing the order but that didn't help either
```
} else if (channels == 6) {
map[0] = CHANNEL_POSITION_FRONT_LEFT;
map[1] = CHANNEL_POSITION_FRONT_RIGHT;
map[2] = CHANNEL_POSITION_FRONT_CENTER;
map[3] = CHANNEL_POSITION_REAR_LEFT;
map[4] = CHANNEL_POSITION_REAR_RIGHT;
map[5] = CHANNEL_POSITION_LFE;
```

maybe it's my setup only, but I don't have problems like that elsewhere, I'll keep experimenting

96khz is still crashing though, so that's not related to number of channels and it's a separate problem

**Comment by nefthy** [comment]
The order is defined by the FLAC specification. I don't think thats the problem. Which output plugin are you using?

**Comment by nefthy** [comment]
Also please test this file, as it is known good: https://github.com/sfiera/flac-test-files/blob/master/surround51.flac

**Comment by kajzersoze** [comment]
Ah that test file is what I needed because it tests the channels, yeah they are wrong for some reason, in PR I mean.
When I play that file with ffplay they are correct.
I didn't do anything special in the config, it's default basically, except the number of channels (change from 2 to 6) and sample rate to 48k (from 44k)
```
Server Name: pulseaudio
Server Version: 14.2
Default Sample Specification: float32le 6ch 48000Hz
Default Channel Map: front-left,front-left-of-center,front-center,front-right,front-right-of-center,rear-center 
```

I'll fix the channels, with the order I get from ffplay, I'll let you know when I'm done with it, can't do it right away though, have some other things to do but say maybe in 2hrs tops.

**Comment by nefthy** [comment]
the problem probably is in op/pulse.c

**Comment by kajzersoze** [comment]
Actually 'ffplay' gives the exact same order, so PR is right, at least order of channels (mapping) 
Well, it's something else, I see you comment while I was typing ... could be that one, I don't know

**Comment by nefthy** [comment]
> the problem probably is in op/pulse.c

or could be I should say... The channel mapping code seems resonable in op/pulse.c

**Comment by kajzersoze** [comment]
Well, it's not flac related, I can tell you that
I just downloaded surround test file in wav format and it's a mess playing it with cmus, it's bad
this is becoming old but for the record, ffplay plays that one correctly
https://archive.org/details/5.1SurroundSoundTestFilesVariousFormatsAACAC3MP4DTSWAV

**Comment by kajzersoze** [comment]
Scratch that, surround 5.1 works in cmus, for whatever reason the above file didn't play correctly, but aplay failed to play it correctly as well. But now I tried different [test file](https://www.halfgaar.net/surround-sound-in-linux), it's also in wav format and it has 6 channels, while the previous one has 2, and it played as it should, the sound came from each speaker.
```
$ file surroundTestDTS.dts.wav
surroundTestDTS.dts.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
$ file chan-id.wav
chan-id.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, 6 channels 44100 Hz
```

So, I guess it's something in flac code after all, I'll play with it and see if I can solve it.

**Comment by kajzersoze** [comment]
ac3 format is affected as well, same way as with flac
channel mapping somewhere in the code isn't done properly, but in some cases it does work (chan-id.wav)
So, that's that I guess, don't know what I could do or try anymore, I would be happy to test any suggestion.

**Comment by kajzersoze** [comment]
Okay, I just had to do test it and installed Clementine, same thing happens there, so I guess there's nothing wrong with cmus.
Also, I [found](https://github.com/clementine-player/Clementine/issues/6662) people complaining about it but there was no answer
Could be codecs or something, I don't know.

96khz flac doesn't crash though and it plays, in stereo but it plays and doesn't crash, that's cmus for sure
