### ISSUE TITLE
playlist track windows always rendered as inactive

### ISSUE THREAD

**Issue by shenqshuoh** [cmus/cmus#1071]
---

1) `uname -a`:
```
Darwin ******.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  coreaudio
```

The track window in playlist view seems to be ```win_inactive``` (for color scheme) regardless of whether or not the track window is the active window.

Say, I have a color scheme where ```color_win_inactive_sel_attr=underline```, ```color_win_sel_attr=bold```, with all other fields left as default. No matter which window (playlist or track) I focus on, using the ```win_next``` command, the selected track in the right track window would be underlined instead of bold. The playlist window renders normally.

This issue was absent in 2.8.1.

**Comment by pgaskin** [comment]
I can confirm this. I suspect it might be a regression from #1008 which I didn't catch since my active color is nearly identical and I was still getting familiar with the UI code.

I'll take a look at this within the next day or two.

**Comment by tonyfischetti** [comment]
Would you like any assistance on this?

**Comment by pgaskin** [comment]
Yes, that would be appreciated since I haven't had enough time to debug this thoroughly yet, and the bug isn't obvious from a quick skim.

**Comment by pgaskin** [comment]
I've been looking into this more, and I'm still struggling to figure out why it frequently makes both windows inactive, even when pl_cursor_in_track_window is set to 1 and an update is manually triggered in gdb...

**Comment by pgaskin** [comment]
Actually, I think it's working properly, at least with the latest version of cmus. The library view behaves in the same way.

The attributes you mention (`color_win_inactive_sel_attr`, `color_win_sel_attr`) only apply to the currently selected track ***if it is not playing***, to the inactive and active windows respectively.

To set the attributes on the currently playing track, use `color_win_inactive_cur_sel_attr` and `color_win_cur_sel_attr`.
