### ISSUE TITLE
No Input or Output After Deleting /usr/local/lib

### ISSUE THREAD

**Issue by DrakoDom** [cmus/cmus#1077]
1) `uname -a`:
```
Linux Gentoo 5.11.13-gentoo #1 SMP Fri Apr 16 11:51:13 CDT 2021 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
cmus: Error: couldn't open directory `/usr/local/lib/cmus/ip': No such file or directory
cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
Input Plugins: /usr/local/lib/cmus/ip

Output Plugins: /usr/local/lib/cmus/op
```

I made a mistake earlier today that could have been catastrophic, but luckily I only ran `rm -rf on /usr/local/lib`, and not `/usr/local`. But now I have no output from cmus. I've tried reinstalling cmus & alsa-lib but this didn't help me.

**Comment by pgaskin** [comment]
That's your issue right there:

```
cmus: Error: couldn't open directory `/usr/local/lib/cmus/ip': No such file or directory
cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
Input Plugins: /usr/local/lib/cmus/ip

Output Plugins: /usr/local/lib/cmus/op
```

The input/output plugins are stored as dynamically loaded libraries in `prefix/lib/cmus/{ip,op}`. You'll need to build cmus again to put them back.
