### ISSUE TITLE
No way to exit win-sel-cur

### ISSUE THREAD

**Issue by spitemim** [cmus/cmus#1079]
I have found that after using :win-sel-cur or pressing `i` (the default keybinding) in the playlist view, there is no way to get one's cursor out of the playlist to select a different one. This is frustrating, because if I want to pick a specific song in a playlist, I have to either press `b` until the song comes on, or bite the bullet and press `i` to go into the playlist and select the song, knowing I will have to restart cmus to play a different playlist. If there is a way to do this, please let me know.

1) `uname -a`:
```
Linux server 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by pgaskin** [comment]
@spitemim, can you give more details on how to reproduce this issue? I wasn't able to reproduce it on v2.8.0 or v2.9.1. Although, if you mean what I think you do, have you tried pressing Tab to switch between the playlist list and tracklist?

**Comment by spitemim** [comment]
> @spitemim, can you give more details on how to reproduce this issue? I wasn't able to reproduce it on v2.8.0 or v2.9.1. Although, if you mean what I think you do, have you tried pressing Tab to switch between the playlist list and tracklist?

Tab works, I'm an idiot.
Thank you so much for the reply.

**Comment by pgaskin** [comment]
Also, if you `:set mouse=1` and update to cmus v2.9.1 or later, you'll be able to use your mouse to switch too.
