### ISSUE TITLE
[Feature request] multiple playlists/treat playlists like directories

### ISSUE THREAD

**Issue by losingkeys** [cmus/cmus#108]
I'm opening this issue to discuss the option of multiple playlists. If they were stored in a central spot (like ~/.cmus/playlists/), then the third view could just show the directory and have an option to make a new one.

Then if you open a playlist, it would work just like it does now, except there'd be a `../` at the top, like in the file browser, so you could go back and look at more playlists.

Thanks for this awesome music player!

**Comment by toogy** [comment]
Who goes for it?

**Comment by fin0** [comment]
+1 Would be so great. Managing multiple playlists in cmus is just a pain in the ass. I love that cmus has only the basic functionality and no dumb features but playlist support is a very very basic functionality..after that cmus would be close to perfection :)

**Comment by ald0n** [comment]
Totally agree. Zhora zapili, ochen' nado.

**Comment by toogy** [comment]
I switched to mpd + ncmpcpp in the meantime because I was really missing this feature :/

**Comment by mahkoh** [comment]
Friendly reminder that "+1", "me too", and "I'm leaving the fandom :/" won't make it happen. Someone who actually wants this has to sit down for a few hours and implement it. It's probably not even that hard.

**Comment by losingkeys** [comment]
I'm happy to take a crack at it with someone. It's been a few years since I've done C, but I'm sure it'll come back to me quickly :smile:. Email me if you want to pair on this, otherwise I'll open a pull if/when I think I've figured it out (though don't hold your breath if you'd rather solo).

**Comment by toogy** [comment]
@losingkeys, why not simply forking?

**Comment by losingkeys** [comment]
Because this thread is still open for discussion. We just need to come up
with some code :)

**Comment by z3t0** [comment]
Hello, is anyone still interested in working on this? I really like cmus but the lack of multiplaylist support really breaks my workflow. Although I am only an intermediate C programmer I would like to work on this feature if anyone else wants to join let me know!

**Comment by losingkeys** [comment]
I am! I also really want playlists in cmus. Let's discuss the design here
quick.

So far I think the plan is just to have a playlists directory; how about
.cmus/playlists/? To display them we could almost copy the library view,
but the sidebar would show all the playlist names from the playlists
folder, maybe showing a * next to the sidebar selected one? This might be
confusing because you could add to one playlist and play from another.
We'll also need to figure out how to deal with editing, but I'd like to
keep it super simple (like the rest of cmus, just a clean and fast
interface :). Maybe just create/rename/delete for the playlist, and keys to
add/delete playlist tracks?

As far as my C ability goes, I'm not new, but it's been awhile, and I've
never done it professionally. Do you want to pair on it? I could set up an
ec2 box with some tools and vim/emacs.

**Comment by z3t0** [comment]
Awesome! Yes I would love to work together on it. Feel free to email me at zetoslab@gmail.com or find me on #linux (irc) where my name is z3r0

**Comment by losingkeys** [comment]
Sounds good! I'm losingkeys on freenode. There's a #cmus channel, want to
meet there? What times generally work for you? I'm in utc-6, and evenings
(after 18:00) work best for me. Let's get this this going!

Unrelated idea: we could map space to "select playlist", then y could just
add to the currently selected playlist (like I think it does now). The only
place where this would be confusing is for users who use space to mark
songs to add them to the queue, or with multiple playlist support, to copy
then between playlists. I don't mark songs though, so it would be fine for
me. We could (and maybe should?) Just use a different key.

**Comment by flyingmutant** [comment]
Guys, once you'll come up with the design you want to implement (and you know *how* to implement, in terms of code) — please create a separate «RFC» issue for the discussion. Do not head to writing code straight away.

**Comment by z3t0** [comment]
@flyingmutant What's an RFC,?

@losingkeys Okay utc-6 is also my timezone! any time after 17:00 work for me. I'll see you on the cmus channel

Looking forward to working on this

**Comment by toogy** [comment]
@z3t0 Request For Comments. basically you describe what you want to do and how to do it and ask other developers (including maintainers) if your design is good enough (it generally isn't at first). You'll have to take remarks into account before actually writing the code.

**Comment by zv0n** [comment]
For anyone who wants a workaround for the time this feature is in development - you can create a playlist (normally add songs to default playlist), then do ":save *nameofplaylist*", this will save the playlist as the name you chose, then you can delete all songs from currently displayed playlist and do this multiple times while changing the playlist name. When you're done you can simply open the playlist like this: ":load *nameofplaylist*" (for better comfort save all playlists into a specific folder and then at the start of cmus do ":cd *foldername*")

**Comment by flyingmutant** [comment]
Fixed in #485.
