### ISSUE TITLE
Cmus needs output_plugin reset manually when switching to Airplay

### ISSUE THREAD

**Issue by 3marcusw** [cmus/cmus#109]
When I change the audio output on my mac from the internal speakers to Airplay,  cmus continues playing on internal speakers, until I manually do

```
:set output_plugin=ao
```

It happens when I switch from Airplay to internal speakers, as well. 
When I switch between these audio outputs, I would expect cmus to play on the new audio output automatically, but alas it is not the case. 

My system:
cmus 2.5.0
Mac OS 10.9.1

```
:~ > cmus --plugins
Input Plugins: /usr/local/Cellar/cmus/2.5.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.5.0/lib/cmus/op
  ao
```

**Comment by Wang-Yue** [comment]
Once my CoreAudio PR is in you can open the bug again. 
This should be easy to do since CoreAudio provides a listener for device switch. What should be the expected behavior when a listener callback is triggered? Just close the device and reopen it?
