### ISSUE TITLE
op/oss: 'fcntl()' vs. 'ioctl()'

### ISSUE THREAD

**Issue by cproc** [cmus/cmus#1103]
While debugging a port of cmus for the Genode OS framework I noticed that the `oss_reset()` function calls `fcntl()` with the `SNDCTL_DSP_RESET` command, which failed. On FreeBSD this call returned -1 as well, whereas it worked when using `ioctl()` instead.

https://github.com/cmus/cmus/blob/75ef523d5657cb37cc5a8f9869764faf2ede7348/op/oss.c#L44-L50

**Comment by nefthy** [comment]
@cproc could you test #1104 on your systems?
