### ISSUE TITLE
Jack2: 24bit .wav files lead to Error: opening audio device: sample format not supported

### ISSUE THREAD

**Issue by dcallea** [cmus/cmus#1106]
I am using jackd2. When i try to play 24bit .wav files in cmus, i get the error: ```Error: opening audio device: sample format not supported```. 16bit .wav files work. My interface (Steinberg UR22mkII) supports 24bit/192khz and i run Jack at 44.1khz.
Playing 24bit .wav files in mpv (through jack2) and through Alsa in cmus works just fine.

1) `uname -a`:
```
Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 p
sm
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:

  wav:                                                                                
    Priority: 50
    File Types: wav
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  ffmpeg:
    Priority: 30
    File Types: aa ac3 aif aifc aiff ape au mka shn tak tta wma webm aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by nefthy** [comment]
jack only supports a single sample format. you need to install libsamplerate if you want cmus to do sampleformat conversions with the jack plugin.

**Comment by dcallea** [comment]
> jack only supports a single sample format. you need to install libsamplerate if you want cmus to do sampleformat conversions with the jack plugin.

Thanks for the quick reply. I have libsamplerate installed, but it doesn't seem to work. Do i need to compile the program to include it?

**Comment by nefthy** [comment]
You need the development headers as well as libsamplerate installed, when you run configure for cmus. Also make sure that the dsp.jack.resampling_quality is not set to 0.

**Comment by dcallea** [comment]
I have libsamplerate0 and libsamplerate0-dev (on Debian) installed and it still doesn't seem to work. What exactly do you mean with "when you run configure for cmus"?

**Comment by pgaskin** [comment]
You need to build cmus from source or use the packages from [here](https://github.com/pgaskin/cmus/actions?query=event%3Apush+is%3Asuccess+branch%3Adebian-package).

**Comment by dcallea** [comment]
Thank you. It works now.
