### ISSUE TITLE
usage question for cmus-remote

### ISSUE THREAD

**Issue by nkh** [cmus/cmus#1110]
Hi, thanks for cmus!

I usually have a cmus running in a tmux session. I have written a file manager (terminal) which right now can play one song using mplayer or stop mplayer. It feels a bit funny to not use cmus.

here's how I'd like to use cmus remotely (I red the man page):

create a playlist, probably named after $$
add, remove files from that play list
play just from that play list
delete the playlist

It wasn't clear to me, in the man page, if creating the playlist was possible.

**Comment by nefthy** [comment]
closing as duplicate of #1066
