### ISSUE TITLE
mp4v2 not found if using TechSmith mp4v2 4.1.4 or later

### ISSUE THREAD

**Issue by ryandesign** [cmus/cmus#1112]
cmus fails to find mp4v2 if it's the TechSmith fork version 4.1.4 or later.
```
checking for header <mp4v2/mp4v2.h>... no
checking for header <mp4.h>... no
configure failed.
```
TechSmith mp4v2 4.1.3 and earlier work fine as does the original mp4v2 version 2.0.0.

Also reported to MacPorts: https://trac.macports.org/ticket/63297

Your configure script does not appear to leave a config.log like autotools configure scripts do so it was not as easy to figure out what the problem was, but I determined that your configure script checks for headers (`check_header`) by doing a trial compilation (`try_compile`) including that header. If I try this manually, we see what the problem is:

```
$ echo '#include <mp4v2/mp4v2.h>' | cc -I/opt/local/include -c -x c -
In file included from <stdin>:1:
In file included from /opt/local/include/mp4v2/mp4v2.h:58:
/opt/local/include/mp4v2/file.h:336:34: error: use of undeclared identifier 'nullptr'
    ShouldParseAtomCallback cb = nullptr );
                                 ^
1 error generated.
```

So this is the same kind of issue as https://github.com/cmus/cmus/issues/1076 and https://github.com/TechSmith/mp4v2/issues/47. So if it is desired to support the TechSmith fork, then a fix to the configure script is needed, in addition to fixing invocations of MP4Read to have a second parameter.

The proposed solution in https://github.com/cmus/cmus/pull/1078 of varying whether to use the second parameter of MP4Read based on the OS seems wrong to me.

I would also consider it a valid resolution of this issue to declare that TechSmith mp4v2 4.1.4 and later should not be used and can no longer be considered to be mp4v2 since they broke API compatibility.

---

1) `uname -a`:
```
Darwin REDACTED 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:

2.9.1

**Comment by ryandesign** [comment]
Even if they fix it to use DEFAULT, they've still added a second parameter to a function that used to take one parameter. That still at least breaks old binaries trying to use the new library, right? In any case, you should probably submit your proposed fix to the developers so they can consider it.

Meanwhile, I've reverted mp4v2 in MacPorts to 4.1.3 and have left instructions not to update it further unless upstream fixes the breakage.

**Comment by pgaskin** [comment]
Builds successfully with the enzo1982 fork, which most packagers have switched to.
