### ISSUE TITLE
Play music folder in cmus (without adding to library)

### ISSUE THREAD

**Issue by suuuehgi** [cmus/cmus#1115]
---

1) `uname -a`:
```
Linux hostname 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

Hi!

Can someone give me a hint: How can I consecutively play the music files in a folder with cmus from the Browser View?

I don't want to add them to the library first or create a playlist. Just play, what's there.

The default behavior seems to be to jump back to the library (2) after each track.

To me "Play everything in this folder" is kind of the basic functionality of a music player and I can't get it to do it.

Thanks a ton!

**Comment by rnkn** [comment]
You can do this via the Play Queue view (4) with `:add ~/my/folder`. It's not from the Browser view (5) though so perhaps not what you want.

**Comment by suuuehgi** [comment]
> You can do this via the Play Queue view (4) with `:add ~/my/folder`. It's not from the Browser view (5) though so perhaps not what you want.

Thank you! Yeah, it's not from the Browser View (5) and I have to type `all/of/the/very/long/path/to/the/folder` by hand what is quite inconvenient.

I'm really confused that I can't find a simple way to just "play whats in there". :/

**Comment by rnkn** [comment]
Actually you can! Just use `e` for `win-add-q`.

**Comment by suuuehgi** [comment]
> Actually you can! Just use `e` for `win-add-q`.

`e` indeed works! Thank you!

Meanwhile I fell in love with [`musikcube`](https://musikcube.com/) what did exactly what I wanted right out of the box in a transparent way. For now I'll stick with that -- let's see what happens in the long run.

**Comment by rnkn** [comment]
@suuuehgi I would like to try musikcube but can't get it to build.

**Comment by jlaznarte** [comment]
`win-add-q` works very well for adding folders to the queue. However, is there a way to empty the queue and directly play the selected folder, instead of queueing it? I know I can run `clear -q` before `win-add-q`, but if a song is being played at the moment, it keeps playing till it ends.

I would like to select a folder and just play its contents right away.

Cf. [#467](https://github.com/cmus/cmus/issues/467)

**Comment by rnkn** [comment]
@jlaznarte wouldn't that just be `clear -q RET e b`?

**Comment by agenbite** [comment]
Yeah, or even `X e b` if you set the appropriate binding for `clear -q` to `X`. However it'd still be nice to be able to chain commands and use a single key for "play this folder".

**Comment by suuuehgi** [comment]
> @suuuehgi I would like to try musikcube but can't get it to build.

Have a look [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=musikcube).
