### ISSUE TITLE
Stuttering, clipping and noise  when playing .FLAC 24-bit 96000Hz

### ISSUE THREAD

**Issue by bvvt** [cmus/cmus#1125]
This does not happen on files that are no 96khz.

---

1) `uname -a`:
```
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
/usr/local/Cellar/cmus/2.9.1/lib/cmus/op
  coreaudio

```

**Comment by yougotwill** [comment]
This might help you @bvvt https://github.com/cmus/cmus/issues/1130#issuecomment-1003324193

**Comment by pgaskin** [comment]
No response, likely duplicate of #1130.
