### ISSUE TITLE
Support MPRIS through the Basu library (drop-in replacement for elogind/systemd sd-bus)

### ISSUE THREAD

**Issue by capezotte** [cmus/cmus#1133]
[`basu`](https://git.sr.ht/~emersion/basu/) is a standalone version of the `sd-bus` library that isn't attached to any service or login manager, made by the Sway developers. 

I've successfully compiled and run `cmus` with it by using the following two-line patch:

```git
diff --git a/configure b/configure
index 4627126..37b8437 100755
--- a/configure
+++ b/configure
@@ -289,7 +289,7 @@ check_vorbis()
 
 check_libsystemd()
 {
-	pkg_config LIBSYSTEMD "libsystemd" || pkg_config LIBSYSTEMD "libelogind >= 239.3"
+	pkg_config LIBSYSTEMD "libsystemd" || pkg_config LIBSYSTEMD "libelogind >= 239.3" || pkg_config LIBSYSTEMD "basu"
 	return $?
 }
 
diff --git a/mpris.c b/mpris.c
index 0699b0c..2cd6b40 100644
--- a/mpris.c
+++ b/mpris.c
@@ -15,7 +15,7 @@
  * along with this program; if not, see <http://www.gnu.org/licenses/>.
  */
 
-#include <systemd/sd-bus.h>
+#include <basu/sd-bus.h>
 
 #include "mpris.h"
 #include "ui_curses.h"
```

I'd like to see it officially supported, though I do recognize Basu's avoidance of "claiming" `/usr/include/systemd` might require some changes to the build system.

**Comment by jbeich** [comment]
+1 from FreeBSD POV where systemd or libelogind will never exist (compared to InitWare but it's unfinished). I've applied the patch in https://github.com/freebsd/freebsd-ports/commit/0d52a1007da8e2731e07900b906a7450574a8630
