### ISSUE TITLE
Adding to library hangs

### ISSUE THREAD

**Issue by kkew3** [cmus/cmus#1146]
---

1) `uname -a`:
```
Darwin 192.168.0.100 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.9.1/lib/cmus/ip
```

When I tried to add `Music-Lake.m3u` (attached as `Music-Lake.m3u.txt` below, `cmus` hangs, can't quit ("Tracks are being added. Quit and truncate playlist(s)? [y/N]"), and if answering 'y', ncurses interface closes but the next terminal prompt won't show up until I suspend cmus.

[Music-Lake.m3u.txt](https://github.com/cmus/cmus/files/7746635/Music-Lake.m3u.txt)

Probably add a timeout somewhere when reading `m3u` files ? ...

**Comment by pgaskin** [comment]
Adding playlists with URLs isn't currently supported.
