### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by castilma** [cmus/cmus#1157]
Why hasn't there been a new release for almost one year?

Also, is there a way to donate to the project/the maintainers?

**Comment by nefthy** [comment]
> Why hasn't there been a new release for almost one year?

@flyingmutant could we introduce some sort of release schedule? Maybe once a quarter or every half year? This would have the advantage, that fixed get propagated to distro packages regularly.

> Also, is there a way to donate to the project/the maintainers?

Not as far as I know.

**Comment by flyingmutant** [comment]
It is probably better to just release important fixes ASAP -- waiting half a year does not sound ideal. Is there anything pending/missing that would prevent us from making a release now? We can pretend that we have a yearly release schedule :-)

**Comment by nefthy** [comment]
> It is probably better to just release important fixes ASAP -- waiting half a year does not sound ideal. 

Yeah, we just accumulate many small fixes over time, that don't get pushed to distros if we don't make a release. That was my reasoning for a time based release cycle.

> Is there anything pending/missing that would prevent us from making a release now?

Maybe #1152 and #1151

**Comment by gavtroy** [comment]
IMO there's no need to wait on them. It's also worth considering that changes made right before a release don't get any useful "beta testing" from git users.

**Comment by gavtroy** [comment]
@flyingmutant – still as good a time as any to make a release :slightly_smiling_face: Or if closing PRs is a better way to build momentum I didn't mean to suggest we can't do that.

**Comment by flyingmutant** [comment]
Yep! I'll try to find the time to cut a new release in the next couple of days.

**Comment by flyingmutant** [comment]
Here it is! [v2.10.0](https://github.com/cmus/cmus/releases/tag/v2.10.0)
