### ISSUE TITLE
Support for .nomedia file

### ISSUE THREAD

**Issue by fekir** [cmus/cmus#1168]
There exist the convention of using a .nomedia` files for telling program not to scan recursively for media files in specific folder.

AFAIK .nomedia files where first introduced on android (https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory#Android), but  music players for GNU/Linux and Windows systems like strawberry (https://forum.strawberrymusicplayer.org/topic/412/exclude-paths-directories-files-from-library) and clementine (https://github.com/clementine-player/Clementine/pull/5327) support it too, as other multimedia programs (kodi for example: https://kodi.wiki/view/Update_Music_Library)

cmus does not support it, which is... annoying as in my `~/Music` folder there are (sub)directories I would prefer it to skip entirely, just like other players do.

**Comment by flyingmutant** [comment]
Fixed in #1190.
