### ISSUE TITLE
Ctrl-S locks cmus

### ISSUE THREAD

**Issue by OlMon** [cmus/cmus#1171]
Greeting,

It is more of a question because I am not really sure where this is coming from. I have nothing bound on ^S, same happens even if I have, nothing happens and cmus locks. No input is recognized and the gui is not updated. I can press ^C to get the typical echo message and it works again. 

I tried different terminal emulators, st and xterm and different shells, zsh and bash. So maybe this is something in cmus that I don't know about?

Thanks for the good work, keep it up.

Cheers!

---

1) `uname -a`:
```
Linux *** 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
```

**Comment by gunqqer** [comment]
This is your terminal emulator doing this. ^s suspends all output to a 
terminal. Press ^q to resume. I'm surprised your terminal emulator 
didn't display a message as such, konsole does so.

**Comment by OlMon** [comment]
Thanks never new this was a thing, it never materialized in other situations. Read a little bit on it, thanks!
