### ISSUE TITLE
Theme suggestion

### ISSUE THREAD

**Issue by cain-dev** [cmus/cmus#1186]
Just one theme here (https://github.com/cmus/cmus/wiki/Themes), here is mine (i_hate_green.theme):

set color_win_title_bg=2                                             
set color_win_title_fg=8
set color_win_bg=234
set color_win_fg=15
set color_win_sel_bg=89
set color_win_sel_fg=230
set color_separator=2
set color_win_dir=1
set color_titleline_bg=2
set color_titleline_fg=8
set color_statusline_bg=2
set color_statusline_fg=8
set color_cmdline_bg=234
set color_cmdline_fg=15
set color_error=160
set color_info=2
set color_win_cur=40
set color_win_cur_sel_fg=40
set color_win_cur_sel_bg=89
set color_win_inactive_cur_sel_bg=89
set color_win_inactive_cur_sel_fg=8
set color_win_inactive_sel_bg=89
set color_win_inactive_sel_fg=8

**Comment by pgaskin** [comment]
Please open a PR for this if you wish for this to be included in cmus.
