### ISSUE TITLE
hide left panel in playlist view

### ISSUE THREAD

**Issue by aris-sk** [cmus/cmus#1187]
Greetingw to all and congratulations for the awesome project.
Is there any way to hide the left panel of the playlist and make it look like the older versions?
I wish i could do this. Thx in advance!

**Comment by vacuumbeef** [comment]
Looks like it is not possible.
Here is an old similar issue - https://github.com/cmus/cmus/issues/897

And yeah, I would like to hide that left panel too, very much.

**Comment by pgaskin** [comment]
Done in #1238.
