### ISSUE TITLE
Display album artist instead of artist

### ISSUE THREAD

**Issue by fekir** [cmus/cmus#1191]
Consider the [The Lion King](https://musicbrainz.org/release/f7ee8ab1-2bdc-4d38-a64e-faef69682be1) soundtrack, but the described "issue" holds for most compilations.

The Album Artist are [Elton John](https://musicbrainz.org/artist/b83bc61f-8451-4a5d-8b8e-7e9ed295e822) & [Hans Zimmer](https://musicbrainz.org/artist/e6de1f3b-6484-491c-88dd-6d619f142abc), while the artist of, for example, [Circle of Life](https://musicbrainz.org/recording/ba905205-612d-49e6-ad5e-30bbbbf20f56) is depending on the release you have, [Carmen Twillie](https://musicbrainz.org/artist/39331b2f-9df0-4de1-a3ee-c28dd103045c), [Elton John](https://musicbrainz.org/artist/b83bc61f-8451-4a5d-8b8e-7e9ed295e822) or [Carmen Twillie](https://musicbrainz.org/artist/39331b2f-9df0-4de1-a3ee-c28dd103045c) & [Lebo M](https://musicbrainz.org/artist/a966b097-7981-40c5-82b4-79c6fe28932c).

Other tracks generally have other artists, for example (again, depending on the exact release) [Hakuna Matata](https://musicbrainz.org/recording/b9c6c978-ffbe-4581-8fed-608854c4c7e8) from [Nathan Lane](https://musicbrainz.org/artist/6744daab-306b-483c-81c3-d4f7cafd90df) & [Ernie Sabella](https://musicbrainz.org/artist/dcd0cef2-9e39-485b-ba39-e10e6c2707a6).

For this reason, there exists both the metadata for Artist and Album Artist.

With the current approach of cmus, in the first view, where songs are grouped by artist and album, the main issue is that albums are splitted by the different artists.
If I have The Lion King](https://musicbrainz.org/release/f7ee8ab1-2bdc-4d38-a64e-faef69682be1) soundtrack, I will not be able to simply select the first song and play automatically through  them all.

Grouping songs per artist album and album is generally better, because with this approach an album is never splitted.

The only drawback of this approach, is that it is not possible to listen to all songs made by a single artist.
In this case, the grouping by album is less relevant, and the list view is just as good for playing all songs of a given artists, as they are listed by artist by default.

**Comment by gavtroy** [comment]
The are already grouped by album artist. Could your issue be tied to a specific file format?

**Comment by fekir** [comment]
🤦
 
You are right, my files where tagged wrongly, sorry for this ticket-
 
 
It would be nice if somehow it would be more clear what the view is actually showing...

I agree that "Album Artist / Album" does not look as nice as "Artist / Album", but also in the code, from what I saw, I was convinced that it was grouping by artist.

For example `struct album` has a `struct artist *artist;` member variable (I would have expected a `struct artist *album_artist;`, and I did not found where the different files are parsed.

Do you mind showing me where I could recognize in the code that `artist` is filled with the album artist?
I did not find yet the relevant place where the files are parsed.

Otherwise this issue can be closed, thanks.

**Comment by gavtroy** [comment]
`album.artist` holds the album artist while the track artist is held in the individual track_infos.

`album.artist` is set from `tree_artist_name()` which uses `track_info->albumartist`. This was previous populated with `comments_get_albumartist()` which in most cases just falls back to the Artist tag.

I'm just a random past contributor here, you might be able to close your own issues.
