### ISSUE TITLE
cmus for windows - link is broken

### ISSUE THREAD

**Issue by fekir** [cmus/cmus#1192]
Hi, I noticed on https://github.com/cmus/cmus/wiki/ that the download link for windows (https://linkify.me/Q8h8Cx6) is not reachable.

On the other hand, it might be noteworthy to add that cmus is available on Windows through cygwin (I've compiled the current release): https://cygwin.com/packages/summary/cmus.html

**Comment by lewisje** [comment]
I've had a hard time finding where that link was supposed to lead to; I just today heard about cmus.

**Comment by pgaskin** [comment]
https://github.com/cmus/cmus/wiki/Home/_compare/77ce818b51b085abe0705205615bf6bb338688ee...b3e39d319f1141e1746ecf5e12130db7d2f8f645
