### ISSUE TITLE
use name of directory and file if no metadata is available

### ISSUE THREAD

**Issue by Tabaluga** [cmus/cmus#1195]
Dear cmus developers,

**cmus** has become my default music player since I switched to Linux.

Thanks to the [modplug plugin](https://en.wikipedia.org/wiki/modplug) I can play many of my *game music modules*, but these file formats contain **partial or no metadata**, which is reflected in the view of the imported songs in cmus: they are displayed under the artist `<no name>` and the album `<no name>`.

Is it possible that cmus automatically imports all files that contain *partial or no metadata* (primarily all modplug plugin file types[^1], secondarily all other file types[^2]) according to the following scheme:

## Single Artist

- path and filename: `Alexander Brandon/Deus Ex (2000)/001 - Training Room.it`
- import with the following scheme: `album-artist/album-name (year-of-release)/tracknumber - title`

## Various Artists

- path and filename: `Various Artists/The C64 Grand Tour Challenge Musicdisk (2022)/001 - NecroPolo - Aegis VII.mid`
- import with the following scheme: `album-artist/album-name (year-of-release)/tracknumber - track-artist - title`

best regards

[^1]: mod, s3m, xm, it, 669, amf, ams, dbm, dmf, dsm, far, mdl, med, mtm, okt, ptm, stm, ult, umx, mt2, psm.
[^2]: all other files which contain *partial or no metadata* or are resulted in artist `<no name>` and album `<no name>`.

**Comment by nefthy** [comment]
Dealing with missing metadata beyond the scope of cmus. The way to go is to fix the metadata.
