### ISSUE TITLE
titleline not shown on startup

### ISSUE THREAD

**Issue by btjones0** [cmus/cmus#1204]
---

1) `uname -a`:
```
Darwin MacBook.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:40 PDT 2022; root:xnu-7195.141.29~1/RELEASE_ARM64_T8101 arm64
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /opt/homebrew/Cellar/cmus/2.10.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /opt/homebrew/Cellar/cmus/2.10.0/lib/cmus/op
  coreaudio
```

I don't know if this is a bug or an intended change with 2.10, but when starting `cmus`, the titleline is initially not shown.  As soon as a track is playing, the titleline then pops in.

On start:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/6777943/177901258-1b344d63-b3dc-41b4-9291-a5f4467d490b.png">

Compared to a song playing:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/6777943/177901334-5702e3fd-d53e-4b8a-8239-304136d4158c.png">

Whereas in 2.9, the titleline background was shown on startup:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/6777943/177901607-ee0a591b-2bd8-4d93-be93-b6fed19692e3.png">

**Comment by gavtroy** [comment]
It happens after a recent ncurses update, not from any change in cmus code. I noticed it too but so far haven't been particularly motivated to investigate. :slightly_smiling_face:
