### ISSUE TITLE
Current position in args for `status_display_program`

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#1207]
---

1) `uname -a`:
```
Linux lenovo 5.18.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
```

Hello! I have written a simple Go program that translates current Cmus status to Discord Rich Presence (https://github.com/snvmk/cmus-presence). I'm not using `cmus-remote -Q` in it, but rather parsing arguments given to it. And the problem is, that these arguments don't have the `position` key, and so I cannot actual timestamps to presence, because they reset after a pause. Is it intended that it isn't passed? Also the example parameters:
```
status playing file /home/snvmk/Music/Portishead - Biscuit.mp3 artist Portishead albumartist Portishead album Dummy tracknumber 10 title Biscuit date 1994 duration 305
```

**Comment by gavtroy** [comment]
Seems both reasonable and easy to add, if you'd be interested in making the PR?

It would also be nice to include the genre tag. I can't possibly imagine how that's less important than the musicbrainz_trackid.

**Comment by snvmk** [comment]
Yeah, i guess I can make a PR, though I never made one. will learn with this xD

**Comment by snvmk** [comment]
Tbh i already found a line where it does the thing :) Will try to do it...

**Comment by snvmk** [comment]
Okay, track_info structure doesn't have the `position` key. Now I need to where is this struct defined...

**Comment by snvmk** [comment]
This struct rather have a `time_t mtime` field... Interesting, what does this one contain?

**Comment by gavtroy** [comment]
You'll have to get it from the player_info. You can see where it's used in `cmd_status` or `mpris_seeked`. The mtime is probably the file modification time from when the track info was cached.

**Comment by pgaskin** [comment]
OP has disappeared.
