### ISSUE TITLE
run script on track, and then add results to cmus

### ISSUE THREAD

**Issue by cannyboy** [cmus/cmus#1208]
Is there a way to run a script on the currently selected track, which makes a new version of the track, and then adds the new track to cmus?

My use case is wanting to separate the vocals and instruments with https://github.com/facebookresearch/demucs and then add the resultant tracks to cmus:
`demucs PATH_TO_AUDIO_FILE`

Another use would be to make a slowed down (80% speed) version of current track and then add it to cmus.
`ffmpeg -i PATH_TO_AUDIO_FILE -af atempo=0.8 NEW_FILE`

**Comment by U1s2e3r4n5a6m7e** [comment]
I just wrote this script but it is only for `ffmpeg` because I'm not familiar with `demucs`'s output structure

Save this script as _any_script_name.sh_ to the `$HOME/.local/bin/` and add this script to the `status_display_program` in **cmus settings view[7]**. It should work
```bash
#!/bin/bash

SHA_DIR="/tmp/CMUS_SHA1"
OUTPUT_DIR="$HOME/Music"

while test $# -ge 2; do
	eval _$1='$2'
	shift
	shift
done

_ffmpeg() {
	_FUNCTION_NAME=${FUNCNAME[0]}
	_FILE=$(basename "$_file")
	_NAME=${_FILE%.*}
	_EXT=${_FILE##*.}
	OUTPUT_FILE="$OUTPUT_DIR/$_NAME$_FUNCTION_NAME.$_EXT"
	ID_=$(echo -n "$_file $_FUNCTION_NAME" | sha1sum | awk '{print $1}')

	[[ -d $SHA_DIR ]] || mkdir "$SHA_DIR"
	if [[ -f "$SHA_DIR/$ID_" ]]; then
		return 0
	fi

	if ! [[ -f $OUTPUT_FILE ]]; then
		### Main Stuff
		ffmpeg -i "$_file" -af atempo=0.8 "$OUTPUT_FILE"

		if [[ $? == 0 ]]; then
			touch "$SHA_DIR/$ID_"

			cmus-remote --library "$OUTPUT_FILE"
		fi
	fi
}

if test -n "$_file"; then
	_ffmpeg
	## _demucs
fi
```

**Comment by pgaskin** [comment]
This is a very specific use-case which is probably out-of-scope for cmus itself.

Extending upon what @U1s2e3r4n5a6m7e wrote above, you can use `cmus-remote -Q | sed -n 's/^file //p'` to get the currently playing file without needing a status_display_program.

If you want to specifically get the currently selected track in the UI, you can open another feature request to expose that to cmus-remote.
