### ISSUE TITLE
Cannot build Cmus from Source on Arch Linux

### ISSUE THREAD

**Issue by ghostfish0** [cmus/cmus#1209]
I'm on Arch Linux
I tried to build Cmus from source with these commands (I didn't use pacman because I wanted to apply some patches like cmus-youtube):
```
$ git clone https://github.com/cmus/cmus.git
$ cd cmus
$ make
```
and got the following error:
```
   CC     command_mode.o
In file included from command_mode.c:49:
mpris.h:22:10: fatal error: config/mpris.h: No such file or directory
   22 | #include "config/mpris.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [scripts/lib.mk:66: command_mode.o] Error 1
```
Can anyone help me with this? Thanks beforehand!

**Comment by gavtroy** [comment]
You just need to run `./configure` before `make`. You'll probably also need to run `make clean` to clean up the previous attempt or you'll get linker errors.

**Comment by ghostfish0** [comment]
I can build and install it now! Thank you ;)
