### ISSUE TITLE
The manpage has >1200 lines!

### ISSUE THREAD

**Issue by grammoboy2** [cmus/cmus#1210]
Interesting application, but a manpage with >1200 lines, is not Unix-like. Looking for suckless / KISS alternatives.

**Comment by nefthy** [comment]
good luck on your search!

**Comment by grammoboy2** [comment]
There is mocp.

Does cmus also has a config file for keybindings? Vim keybindings rock.

**Comment by nefthy** [comment]
`man cmus` :)
