### ISSUE TITLE
Segmentation fault: No such option input.mp4.priority

### ISSUE THREAD

**Issue by astralspurs** [cmus/cmus#1215]
Hi all, hoping to get some help with this. I'm on Fedora 36. Everything was working fine until I guess some component of my system got updated. Running cmus now gets me a segmentation fault right away.

```
~> cmus
cmus: Error: no such option input.mp4.priority
Segmentation fault (core dumped)
```
---

1) `uname -a`:
```
Linux hpenvy 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao
```

**Comment by gavtroy** [comment]
The input.mp4.priority line can probably be ignored as the mp4 plugin is currently disabled in many configurations. (The mp4 format is still supported through the ffmpeg plugin.)

To have a hint on what the issue is you'd have to generate a backtrace, e.g. "gdb cmus", "run", then "bt full" when it crashes. Although to be honest even this might not help much.

You might just want to rename/remove the ~/.cmus folder and hope it launches then, and that it continues to work when you add back your library.

**Comment by astralspurs** [comment]
Thanks gavtroy! I've removed the cmus folder and then it worked right away.

I appreciate the instruction around debugging too. I will explore that at some point.
