### ISSUE TITLE
Track title prints outside ncurses context

### ISSUE THREAD

**Issue by xxkfqz** [cmus/cmus#1217]
![bug](https://user-images.githubusercontent.com/52203435/183725175-4b6dba29-7775-4d73-be29-6e413b5dd804.gif)

---

1) `uname -a`:
```
Linux server 5.18.16-gentoo #1 SMP PREEMPT_DYNAMIC Sun Aug 7 21:07:07 +05 2022 x86_64 Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz GenuineIntel GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
mad:
Priority: 55
File Types: mp3 mp2
MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
cue:
Priority: 50
File Types:
MIME Types: application/x-cue
wav:
Priority: 50
File Types: wav
MIME Types:
modplug:
Priority: 50
File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
MIME Types:
ffmpeg:
Priority: 30
File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
MIME Types:

Output Plugins: /usr/lib64/cmus/op
pulse
alsa
```

**Comment by gavtroy** [comment]
Could you provide one of the files? I tried playing a file with a Title but no Artist/Album/track number and didn't see this happen.

**Comment by xxkfqz** [comment]
@gavtroy You can download "amphetamine" from [Mod Archive](https://api.modarchive.org/downloads.php?moduleid=138990#amphetamine.xm)

I have the same file with SHA256: `cb4a155d5853f9be279fa70a7fb6d2b2248420b6fbbc30ec421ceddcabef24d1`

**Comment by xxkfqz** [comment]
@gavtroy Fount it. This line cause the problem:
https://github.com/cmus/cmus/blob/ade6e2a7253d7a256e87fdac3da17c9158e6700e/ui_curses.c#L1291

But I do not understand why terminal title prints to stdout

**Comment by gavtroy** [comment]
Thanks. Still looks fine on my side, perhaps it's related to your terminal (or terminal configuration).

**Comment by xxkfqz** [comment]
@gavtroy This problem occurs on konsole (even on default profile) but not on st, linux tty, and cmus+tmux+konsole. It is really related to terminal, as you said
