### ISSUE TITLE
#cmus channel on Libera chat

### ISSUE THREAD

**Issue by c0dehu1k** [cmus/cmus#1219]
Can we update the readme to include IRC channel as well, we can hangout there for common problems and support. Current there are  only 4 people there.

@flyingmutant any thoughts? 
Or if there is existing please let me know

**Comment by flyingmutant** [comment]
I am not against adding the information to the README. Feel free to send a pull request (but please mention that the channel is unofficial).

**Comment by ersuniljoshi** [comment]
@flyingmutant  Thanks!
I have created a PR, please review and let me know if any changes required.
