### ISSUE TITLE
Cmus breaks with the new readline update

### ISSUE THREAD

**Issue by Bionicgitman** [cmus/cmus#1223]
I just updated readline and now Cmus doesn't work (shows the following:
cmus: Error: no such option input.cdio.cddb_url
cmus: Error: no such option input.cdio.priority
)
I am confident that the new readline update is the reason

**Comment by Bionicgitman** [comment]
Nvm

**Comment by muvment** [comment]
I'm having the same error message, would you mind sharing what you did to fix it?
