### ISSUE TITLE
can't use .cue with flac files 

### ISSUE THREAD

**Issue by evanescente-ondine** [cmus/cmus#1224]
just to to be sure I compilled the last version, but I still cannot use/open .cue files, at least when FLAC music is concerned. `couldn't get file informations`blablabl

1) `uname -a`:
```
Linux dr-80qr 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0-8-gdc2752c
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  alsa
  oss
  jack
  sndio
  ao```

**Comment by Vinfall** [comment]
Hi, would you elaborate more on the cue file (encoding, sample file etc)?

I have many OSTs cue files with `.flac`, `.ape` and `.tta`, and all of them work fine for me (installed from Void Linux, see #1225 for my setup). IIRC, the cue file works fine with various encoding including `GB-2312`, `ANSI`, `UTF-8`, `UTF-8 (BOM)`, `Shift-JIS` on cmus packaged by Debian (cannot remember clearly as I converted them to UTF-8 BOM someday).

> `couldn't get file informations` blablabl

TBH I've never seen such message when using cmus 😕. When the respective flac (the cue file refers to) have no music tags at all, cmus still manages to get a bit metadata from the cue file in my case.

**Comment by evanescente-ondine** [comment]
> Error: Couldn't get file information for /home/drm/Téléchargements/Burzum - Discography/Remastered/Albums/1994 - Hvis Lyset tar Oss (Remastered 2005)/Hvis Lyset Tar Oss.cue

> ﻿TITLE "Hvis Lyset Tar Oss"
PERFORMER Burzum
FILE "Hvis Lyset Tar Oss.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Det som en gang var"
    INDEX 00 00:00:00
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Hvis lyset tar oss"
    INDEX 00 14:25:50
    INDEX 01 14:25:50
  TRACK 03 AUDIO
    TITLE "Inn i slottet fra droemmem"
    INDEX 00 22:39:50
    INDEX 01 22:39:50
  TRACK 04 AUDIO
    TITLE Tomhet
    INDEX 00 30:36:50
    INDEX 01 30:36:50

I am not uploading the flac for it weights 850 Mo

**Comment by Vinfall** [comment]
Oh that's fine and I don't understand what's happening XD.

You can try [this Python script](https://gist.github.com/Vinfall/32a9c2b73f10c4fe75320647d5ee9f15) to split the FLAC after backing up the original files if you wish to have a temporary solution. I wrote this a while ago and hope it still works!

**Comment by Vinfall** [comment]
Sorry I didn't notice that the quoted part of your reply is the error info and `.cue` file.

It works in my test (see screenshot). I just copy the `.cue` file content, save it in `UTC-8 BOM` encoding, place it under a similar file structure like yours `xxx-path/Téléchargements/Burzum - Discography/Remastered/Albums/1994 - Hvis Lyset tar Oss (Remastered 2005)/Hvis Lyset Tar Oss.cue`, add it to cmus, and it works.

 The FLAC is actually another OST, I change the metadata to the ones in `Hvis Lyset Tar Oss.cue`.

![jYbgMfD2LY](https://user-images.githubusercontent.com/91039000/201504137-c873a6a4-0bf4-4b25-a674-b266eac31e5b.png)

My guess of possible reasons why it does not work for you:
1. System locale/File encoding mismatch, what's the output of `locale -a` and `export | grep LANG`? There should be a `xxx.utf-8` locale available.
2. There is something wrong with the FLAC file header/tag. You can see the metadata using tools like exiftool, mat2 or mp3tag.

**Comment by evanescente-ondine** [comment]
> ~> locale -a and export
C
C.UTF-8
en_US.utf8
fr_FR.utf8
POSIX

> exiftool Hvis\ Lyset\ Tar\ Oss.flac 
ExifTool Version Number         : 12.42
File Name                       : Hvis Lyset Tar Oss.flac
Directory                       : .
File Size                       : 1031 MB
File Modification Date/Time     : 2022:11:12 12:21:36+01:00
File Access Date/Time           : 2022:11:12 11:13:14+01:00
File Inode Change Date/Time     : 2022:11:12 12:21:36+01:00
File Permissions                : -rw-r--r--
File Type                       : FLAC
File Type Extension             : flac
MIME Type                       : audio/flac
Block Size Min                  : 4096
Block Size Max                  : 4096
Frame Size Min                  : 12772
Frame Size Max                  : 18812
Sample Rate                     : 96000
Channels                        : 2
Bits Per Sample                 : 24
Total Samples                   : 259162112
MD5 Signature                   : 5b32b442370841abe71014c5ef24a8df
Vendor                          : reference libFLAC 1.2.1 20070917
Album                           : Hvis lyset tar oss
Artist                          : Burzum
Asin                            : B0007ULJOO
Barcode                         : 0803341183827
Catalognumber                   : BOBV016LP
Cue Track 01 Musicbrainz Releasetrackid: 9557364b-649d-34e7-96c5-4cccb52d5ccf
Cue Track 01 Musicbrainz Trackid: b2dcd51b-342d-4ae4-9dde-eba13ba9ddff
Cue Track 02 Musicbrainz Releasetrackid: 3c3804ec-3127-35ec-9534-15f8c1f62ecd
Cue Track 02 Musicbrainz Trackid: d57a67ee-9cbc-460b-a8ea-8fa92353d35b
Cue Track 03 Musicbrainz Releasetrackid: ad6faef7-3f3d-3c44-a193-b734df5fd73c
Cue Track 03 Musicbrainz Trackid: 50ca4bd3-1524-46fe-bc51-d37ef9cc9f43
Cue Track 04 Musicbrainz Releasetrackid: d8c1f5a1-7c62-3b50-ab8d-29b4ba2ec0e8
Cue Track 04 Musicbrainz Trackid: ef022873-bf6c-456e-9a43-f6279f323e83
Cuesheet                        : REM DATE 2005-05-02..PERFORMER "Burzum"..TITLE "Hvis lyset tar oss"..FILE "CDImage.wav" WAVE..  TRACK 01 AUDIO..    TITLE "Det som en gang var"..    INDEX 01 00:00:00..  TRACK 02 AUDIO..    TITLE "Hvis lyset tar oss"..    INDEX 01 14:25:50..  TRACK 03 AUDIO..    TITLE "Inn i slottet fra drømmen"..    INDEX 01 22:39:50..  TRACK 04 AUDIO..    TITLE "Tomhet"..    INDEX 01 30:36:50..
Date                            : 2005-05-02
Label                           : Back on Black
Media                           : 12" Vinyl
Musicbrainz Albumid             : 270d2141-22a5-3426-b479-abea0f55d83a
Musicbrainz Albumstatus         : Official
Musicbrainz Albumtype           : Album
Musicbrainz Artistid            : 49cd96a6-42c3-44f6-ba2a-cd9301046b96
Musicbrainz Releasegroupid      : 135bd4e1-7453-300a-b994-d939d84732b1
Original Release Date           : 1994-04
Releasecountry                  : GB
Tracktotal                      : 4
Duration                        : 0:45:00

**Comment by gavtroy** [comment]
You're expected to add the .flac file to your library/playlist and cmus will look for a matching .cue file automatically. Judging by the error message it sounds like you're playing the .cue file directly, which I guess isn't supported. You've probably toggled hidden files in the browser tab (shortcut "i").

**Comment by evanescente-ondine** [comment]
Ah !
It reads NONE of the .cue, but instead .log files, and when there are none, he doesn't show the playlist. I verified.

**Comment by pgaskin** [comment]
I'm not entirely sure what you are asking, and there hasn't been any recent activity, so I'm going to close this for now.
