### ISSUE TITLE
add support pipewire backend

### ISSUE THREAD

**Issue by neuromagus** [cmus/cmus#1229]
mpv added in latest version, so... Maybe it's time to add in Cmus?

https://www.phoronix.com/news/MPV-0.35-Released

**Comment by HalanoSiblee** [comment]
2024 still waiting.

**Comment by gavtroy** [comment]
PipeWire supports the PulseAudio API, so is there a reason for us to add a direct PipeWire backend?

**Comment by neuromagus** [comment]
>PipeWire supports the PulseAudio API, so is there a reason for us to add a direct PipeWire backend?

Who knows... Better support this thing because Wayland won.

**Comment by neuromagus** [comment]
well, you're right. FF does not have Pipewire support. A clean minimal distribution without libpulse is now impossible. 

I'm done here.
