### ISSUE TITLE
it did not support airpods. 

### ISSUE THREAD

**Issue by TatsuhiroC** [cmus/cmus#1230]
---
when i use airpods for music, cmus cannot work. all i heard is noise instead of music.

1) `uname -a`:
```
(paste output here)
```
Darwin chenqizhengdeMacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

2) `cmus --version`:
```
(paste output here)
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors

3) `cmus --plugins`:
```
(paste output here)
```
Input Plugins: /opt/homebrew/Cellar/cmus/2.10.0_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /opt/homebrew/Cellar/cmus/2.10.0_1/lib/cmus/op
  coreaudio

**Comment by pgaskin** [comment]
Closing as stale. If you still have this issue, feel free to reopen it (and mention whether it happens with different input file formats).

**Comment by pgaskin** [comment]
Update: This duplicates #1136, will track there.
