### ISSUE TITLE
Strange text wrapping behaviour

### ISSUE THREAD

**Issue by Konglomneshued** [cmus/cmus#1236]
Weird wrap behaviour, unsure if this is intended:

![image](https://user-images.githubusercontent.com/94726665/206884218-2d85628e-183c-4272-8721-f82c21d47a4e.png)

---

1) `uname -a`:
```
Linux fedora 6.0.11-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao

```

**Comment by gavtroy** [comment]
If it's always that one file, could you share it? Or is it only after a certain action like hitting enter? I've never seen this sort of behavior myself. #1217 is a bit similar.

**Comment by Konglomneshued** [comment]
> If it's always that one file, could you share it? Or is it only after a certain action like hitting enter? I've never seen this sort of 

> Also, is Encoding set to Unicode|UTF-8 in Konsole

Yes.

>And is $TERM xterm-256color?

I get:
`bash: xterm-256color: command not found...`

> If it's always that one file

It happens with multiple files for me.
![image](https://user-images.githubusercontent.com/94726665/206934071-0d02e681-aa75-43f8-a126-9f9bb2762cd6.png)

I checked out the issue you mentioned.  Looks like it's related to Konsole.  I could try another terminal app.

**Comment by Konglomneshued** [comment]
I'm getting visual artifacts on Kitty.

![Screenshot from 2022-12-11 17-14-55](https://user-images.githubusercontent.com/94726665/206934715-1bebfe62-9db9-43d3-89d4-b96d9d3fe6da.png)

![Screenshot from 2022-12-11 17-16-18](https://user-images.githubusercontent.com/94726665/206934726-e6d2464a-15c6-4a11-9a1d-a5df7244f397.png)

**Comment by Konglomneshued** [comment]
This is the only artifact I get on Terminator (by resizing the window):

![image](https://user-images.githubusercontent.com/94726665/206934889-c083104b-7c16-4da4-8418-e6163f13b896.png)

When I switch to a different view, part of it goes away:
![image](https://user-images.githubusercontent.com/94726665/206934911-6d32aea8-ea14-4e25-b9b6-9f66b51b2ec6.png)

It completely disappears if I switch to the queue view:
![image](https://user-images.githubusercontent.com/94726665/206934922-aee37da7-50eb-4bdd-90e3-37df0323c195.png)

**Comment by Konglomneshued** [comment]
> This is the only artifact I get on Terminator (by resizing the window):

I get the same issue in Qterminal.  It's nothing like the one in Kitty or Konsole, though.  I can still use it regardless of the artifacts or terminal.

**Comment by Konglomneshued** [comment]
I don't have any issues in Alacritty.  [🥳](https://emojipedia.org/partying-face/)

**Comment by pgaskin** [comment]
This issue started happening for me too a month or two ago (with no changes to cmus). It's the title line being drawn into the current cursor position, but I haven't had time to track down exactly why this now happens yet.

I use xfce4-terminal on i3, but I don't think that matters.

**Comment by TorchedSammy** [comment]
this started happening to me too:
![](https://safe.kashima.moe/7qluj61ba83w.png)

noticed a week ago without any changes to cmus itself, but i also updated from fedora 36 to 37 (also also i use my fork, but i dont think thats an issue, might see after updating)

**Comment by gavtroy** [comment]
It seems to only happen with ncurses `6.3-20220312` to `6.3-20220529` which I skipped past. I'm not sure if cmus shares any of the blame but considering the issue is gone again with newer ncurses it's probably not worth investigating.

**Comment by Konglomneshued** [comment]
> noticed a week ago without any changes to cmus itself, but i also updated from fedora 36 to 37 (~also also i use my fork, but i dont think thats an issue, might see after updating.~ still happens)

Likely the Fedora update which also updated the ncurses rpm to the version with issues.  Fedora 36 uses a version prior to 6.3-20220312.

**Comment by gacallea** [comment]
hi all, FWIW this is happening to me as well on macOS:

macOS 12.16.2
iTerm 3.4.18
cmus 2.10.0

changing theme makes the UI "go blank":

<img width="1920" alt="Screenshot 2023-01-02 at 6 12 25 AM" src="https://user-images.githubusercontent.com/3269984/210197521-d2661047-2d14-430a-be9c-d383932c362e.png">

**Comment by nicolas-guerrier** [comment]
Facing same issue with ncurses 6.3-4.20220501.fc37

**Comment by drosinos** [comment]
> Facing same issue with ncurses 6.3-4.20220501.fc37

+1, same issue on exactly same configuration.

**Comment by pgaskin** [comment]
> It seems to only happen with ncurses 6.3-20220312 to 6.3-20220529 which I skipped past. I'm not sure if cmus shares any of the blame but considering the issue is gone again with newer ncurses it's probably not worth investigating.

I can confirm this. F37 ships the broken ncurses, but it's fine on F38.

**Comment by pgaskin** [comment]
Possibly related to https://bugs.gentoo.org/904263.

**Comment by pgaskin** [comment]
This is no longer an issue on recent ncurses versions.
