### ISSUE TITLE
Any way to rename song entries/files?

### ISSUE THREAD

**Issue by Konglomneshued** [cmus/cmus#1239]
I'm sorry but none of the guides, reference manuals, or documentation lists a way to rename files or something, so that I don't see
`home/untitled1/Music/SomeFolder/some-file.mp3` on every listing.

If there were a cmus community on Reddit or Discord I'd post there.  But there's only this Github.  This is the only place I can ask a real human being how to use this app.

**Comment by thesusian** [comment]
Hello
I don't think there is an option to rename files from cmus itself, what I would recommend is using an external application like [EasyTag](https://wiki.gnome.org/Apps/EasyTAG) to change the file's metadata (add artist, album name, song name, etc...) and then go back to cmus and press U to refresh your library 
and using this way your music will have the same information across all music players

**Comment by Konglomneshued** [comment]
That works for me, thank you.

**Comment by Konglomneshued** [comment]
That works for me, thank you.
