### ISSUE TITLE
cmus disables Multimedia Keys after quitting on KDE

### ISSUE THREAD

**Issue by CarterSnich** [cmus/cmus#1260]
Multimedia keys stops on working after quitting `cmus`. Won't work on any apps including `cmus` after quitting. I had to restart my computer to make it work again. I'm on KDE

---

1) `uname -a`:
```
Linux snich-20369 6.1.31-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue May 30 23:14:35 UTC 2023 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
NONE
```

**Comment by pgaskin** [comment]
Is this still an issue? If so, please re-open it with the output of `gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus --method org.freedesktop.DBus.ListNames` after closing cmus.
