### ISSUE TITLE
Artist/Album search with *//* includes title tags in view 1

### ISSUE THREAD

**Issue by zz0rk** [cmus/cmus#1262]
---

1) `uname -a`:
```
Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.9.1
```

3) `cmus --plugins`:
```
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

---------------------------------------------------------------------------------------

See man cmus:
SEARCHING: [...] Type //WORDS or ??WORDS **to search only artists/albums in view 1** and only titles in views 2-4. [...]

When I search with *//* in view 1 the results include title tags which according to the manual it should not.

Thank you

**Comment by gavtroy** [comment]
It mostly works, but it looks like we incorrectly also match against the filename of the first track in every album.

**Comment by zz0rk** [comment]
Thank you 🙇‍♀
