### ISSUE TITLE
[New Feature] youtube music support, any playlist or song

### ISSUE THREAD

**Issue by c0dehu1k** [cmus/cmus#1264]
mpv does this,
mpv --no-video 'https://music.youtube.com/watch?v=dGq_4-7sGNE'

**Comment by mrHeavenli** [comment]
There is a [plugin that can do that](https://github.com/invicnaper/cmus-youtube).

**Comment by c0dehu1k** [comment]
@mrHeavenli I tried this long time back, didnt work for me.

**Comment by viatatribal** [comment]
@c0dehu1k If you are still interested in such feature, I have uploaded a patch of my version based on that plugin above: https://github.com/viatatribal/cmus-youtube/

**Comment by c0dehu1k** [comment]
ok thanks @viatatribal , Let me take a look.

**Comment by pgaskin** [comment]
This is out of scope for cmus itself.
