### ISSUE TITLE
XDG_CACHE_HOME support

### ISSUE THREAD

**Issue by avidseeker** [cmus/cmus#1283]
cmus nicely supports xdg specs since https://github.com/cmus/cmus/pull/69.

However, cache file is still saved in `~/.config/cmus` instead of `~/.cache/cmus`.

**Comment by pgaskin** [comment]
The cmus cache isn't really a cache; it's the metadata for the files cmus is aware of, including fields like the play count. Without it, cmus is useless.

As such, there isn't currently any valid use for a cache directory for cmus.
