### ISSUE TITLE
cmus appears in monochrome if compiled with clang

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#1287]
When compiled with clang the ncurses interface is all in monochrome, otherwise everything else appears to work just fine.

Bug is reproducible, personally tested it on Gentoo and Android (termux)

1) `uname -a`:
```
Linux ryzen 6.1.41-gentoo-dist #1 SMP PREEMPT_DYNAMIC Fri Jul 28 12:29:50 WEST 2023 x86_64 AMD Ryzen 7 2700 Eight-Core Processor AuthenticAMD GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
```

**Comment by jake-g00dwin** [comment]
Same issue here on FreeBSD 14.0 When building from ports with clang the binary is monochrome.

Works fine when I compiled it using GCC however; So seems like issue with the build-system config.

**Comment by gavtroy** [comment]
This has already been fixed in #1269 but there hasn't been a release yet.

**Comment by klardotsh** [comment]
This seems critical enough to warrant at least a backport and patch release, no? (pardon my outsider moderate-spice take, I mean it with respect for releases not being trivial, but also, this is a rather big breakage for end users on systems using Clang - which is a growing pool of Linuxes and BSDs)

**Comment by nunotexbsd** [comment]
I agree with @klardotsh that a patch release is welcome.
Today I fixed FreeBSD port with one more patch:
https://cgit.freebsd.org/ports/commit/?id=4430a994eea5d6b2ed84c940963788069d6fd1d6
