### ISSUE TITLE
Cmus doesn't respond to keys on after Manjaro update.

### ISSUE THREAD

**Issue by yataghan012** [cmus/cmus#1301]
---

1) `uname -a`:
```
Linux Manjaro 6.1.60-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Oct 25 13:06:34 UTC 2023 x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.10.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```

Nothing works like before, no keys respond whatsoever, the library loads and that's that. Is there something on my system that no longer loads??

**Comment by pgaskin** [comment]
What's your terminal and ncurses version?

**Comment by yataghan012** [comment]
> What's your terminal and ncurses version?

I tried with xfce4-terminal and Konsole, same thing. 
Ncurses 6.4_20230520-1 from the official Manjaro repositories.

**Comment by gavtroy** [comment]
I'd guess you might have the same issue as #1149 where your `~/.config/cmus/autosave` was corrupted at some point and now it doesn't have the default `bind` and (less importantly) `fset` commands. I don't know what causes this though.

Assuming this is your issue, you can remove the faulty autosave file while cmus is closed and the defaults will be loaded.

**Comment by yataghan012** [comment]
> I'd guess you might have the same issue as #1149 where your `~/.config/cmus/autosave` was corrupted at some point and now it doesn't have the default `bind` and (less importantly) `fset` commands. I don't know what causes this though.
> 
> Assuming this is your issue, you can remove the faulty autosave file while cmus is closed and the defaults will be loaded.

Amazing, that was it. I also don't know what could've caused it, I can tell you that it has never happened before (I have cmus since may '22) and that it happened after series of updates (not a cmus update).
