### ISSUE TITLE
`load` command doesn't match documentation or error messages

### ISSUE THREAD

**Issue by cubicvoid** [cmus/cmus#1304]
The documentation for `load` says:

```
load [-l] [-p] <playlist>
	Loads a playlist to a view.

	@li -l
	load to library views

	@li -p
	load to playlist view

	If a view is not specified, the current view is used.
```

However, in practice:
- There is no way to load to playlist view. Running `load -p test.m3u` gives the error: `:load only works in views 1-2` (regardless of the current view). Despite this, the flag itself is considered valid.
- The `:load only works in views 1-2` error also shows when running `load test.m3u` from any view except 1-2. However `load -l test.m3u` works from anywhere, loading the active library.

It seems like `load` can only be used to load the active library, but the docs and flag processing imply otherwise. I see two ways to resolve it. Either:
- remove the `-p` flag from the documentation and argument processing (arguably make the command work from any screen even without the `-l`, since there's only one valid action), or
- decide what it should mean to load a playlist file into the playlist view, and implement that behavior in `view_load`.

I could do the first myself if someone will review the PR. For the second there'd probably need to be discussion about the intended behavior.

---

1) `uname -a`:
```
Darwin escapepod 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.10.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.10.0_3/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.10.0_3/lib/cmus/op
  coreaudio
  ao
```

**Comment by pgaskin** [comment]
The documentation was added in eec4e5e819c7af1586d544d841f1fac273796ee0. The functionality for `-l` and `-p` was added in an earlier commit, 8d3cbc51fb13d91468c768dfc683f8101f670825.

https://github.com/cmus/cmus/blob/eec4e5e819c7af1586d544d841f1fac273796ee0/command_mode.c#L174-L216

The "...only works in views..." error messages were added in [`6804243`](https://github.com/cmus/cmus/commit/6804243c6d15661d032223f10b7b0c1f985489c4#diff-db8655d28966f59a59336bf47e7812c46e86e3984ecfe94fd53b8dc481a01486L260). It still supported `-l` and `-p` at this time.

Support for loading into the playlist view was intentionally dropped in 5563e0c94bfca08c08628007abc477e47437fec3, but the documentation and arg parsing was not updated.

As such, I believe the current behaviour is correct, and `-p` should be dropped from the documentation and arg parsing.
