### ISSUE TITLE
rand fails when start_view not set to queue

### ISSUE THREAD

**Issue by avidseeker** [cmus/cmus#1308]
1. set: ~/.config/cmus/rc:

```
add -Q ~/dirs/music/q
set start_view=browser
```

2. run cmus and stay on browser view
3. run `cmus-remote -C rand`
4. queue is not shuffled

However if `start_view=queue` then the queue is shuffled.

It is also shuffled when `start_view=browser` but user changes view to queue at least once.

Edit: it seems that `start_view=queue` does not work when cmus is launched via `tmux new-session -ADds cmus /bin/cmus`. So in the end the user must "view the queue at least once" in order for shuffle to work.

**Comment by gavtroy** [comment]
That doesn't sound like a bug. `rand` will randomize the currently open view (sorted library, playlist, or queue). `start_view` works but is ignored if `resume` is set. In your case you could perhaps add `cmus-remote -C 'view queue'` to your flow.
