### ISSUE TITLE
Ignoring `artistsort` in tree view

### ISSUE THREAD

**Issue by stervel** [cmus/cmus#1311]
Not really a bug, I'm sorry if this is inappropriate, but I couldn't find a way to ignore `artistsort` (and by extension `albumartistsort`). Is this possible?

**Comment by Lagrang3** [comment]
Hi. Can you elaborate? I am not sure what is the issue.
Do you mean you want to be able to switch sort from artist to albumartist and vice versa in the tree view?

**Comment by gavtroy** [comment]
There's no setting. It would be best just to adjust the tags to your preference (i.e. remove them).

**Comment by stervel** [comment]
Ah I see then, that's my plan B. Would be nice as a feature but it's not sth that crucial. Thanks for the confirmation, though.

I'm closing this.
