### ISSUE TITLE
Not ordering wavpack discs

### ISSUE THREAD

**Issue by shakealeg** [cmus/cmus#1313]
I've recently switched to wavpacks since they have been faster and smaller for me, but I've noticed a bug or at least a misconfiguration in cmus. I've copied exact tags from my flac files to wavpack files, but cmus won't order by disc. Like it will show track 1 of disc 1, disc 2, and disc 3, then go onto track 2 and do the same thing. Where with flacs, it will show track 1 of disc 1, then go onto track 2 of disc 1. And when it gets to the final track of disc 1, it then goes onto disc 2 and shows the tracks for that.

flac screenshot: ![Feb25::122130](https://github.com/cmus/cmus/assets/123622445/a7e7a64a-5a6e-46a6-8497-59f66100dfcd)
wavpack screenshot: ![Feb25::122033](https://github.com/cmus/cmus/assets/123622445/97b2a3ab-c4a3-48c2-b9cb-af1f32789326)

1) `uname -a`:
```
Linux gentoo 5.15.147-gentoo-gnu-x86_64 #1 SMP Wed Feb 7 20:29:37 AEDT 2024 x86_64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz GenuineIntel GNU/Linux
```

2) `cmus --version`:
```
cmus v2.10.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
```

**Comment by gavtroy** [comment]
Could it be to do with how you copied the tags? It seems to work fine for me.

**Comment by shakealeg** [comment]
> Could it be to do with how you copied the tags? It seems to work fine for me.

I've double checked about 50 times and they are identical. Thanks for helping.
Here is how my wavpack and flac tags are setup:
wavpack disc 1: ![Feb26::181230](https://github.com/cmus/cmus/assets/123622445/8053fd1b-b9d0-482a-81d0-5ac631628f3c)
wavpack disc 2: ![Feb26::181243](https://github.com/cmus/cmus/assets/123622445/d30da193-2f18-40fa-9229-35544baab99f)
flac disc 1: ![Feb26::181403](https://github.com/cmus/cmus/assets/123622445/5dec26d6-dbc9-40c3-9eb5-6b13d6295523)
flac disc 2: ![Feb26::181411](https://github.com/cmus/cmus/assets/123622445/a3d6ad48-46a9-4f3e-a8f4-78a036511aa2)

**Comment by gavtroy** [comment]
Thanks, with EasyTAG I quickly saw the same behavior. Although it's not standardized, this field tends to be stored as `DISCNUMBER` in Vorbis comments (FLAC tags) and as `part` in APE (WavPack) tags. Currently cmus doesn't treat `part` as having any special meaning, but we probably should treat it as a different word for exactly the same thing.
