### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by Elserjo** [cmus/cmus#1327]
Newer versions of cmus include some fixes for pipewire https://github.com/cmus/cmus/commit/7adf497597e7ca83c866bce61c4ca7c2ac4a72d5 and other improvements.

Can you, please, make new release?

**Comment by pgaskin** [comment]
@flyingmutant?

**Comment by flyingmutant** [comment]
Done, thanks for the ping! https://github.com/cmus/cmus/releases/tag/v2.11.0
