### ISSUE TITLE
Is possible to add http and https to cmus?

### ISSUE THREAD

**Issue by texrg** [cmus/cmus#134]
Privet
I dream to write small media player. but not from my dysk only from web pages. Unencoded and play for me. 
Playlist, files, (redundation files) etc. 
What You thing about it?

**Comment by mcurly** [comment]
@texrg if you wish to pay a stream you could use the command :add "http://some.url/stream/"
and afterwards playing it like a normal regular file (with "x" key for instance)

**Comment by cprada87** [comment]
> @texrg if you wish to play a stream you could use the command :add "http://some.url/stream/"
> and afterwards playing it like a normal regular file (with "x" key for instance)

Can you explain it a bit more?...is a concatenation of another command with "|" ?

**Comment by vladimirtamayo** [comment]
Create a .pls file and add your streams URL's:

[playlist]                                                                                  
NumberOfEntries=2                                                                            
File1=http://81.88.36.42:8010/listen.pls?sid=1                                              
File2=<your URL 2>  

press '5' to find your file, open it and play your streams
