### ISSUE TITLE
Couldn't get file information for 

### ISSUE THREAD

**Issue by HalanoSiblee** [cmus/cmus#1344]
---

1) `uname -a`:
```
Linux archlinux 6.10.0-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.11.0
```
In previous version 2.10 cmus works just fine now
M4a&some other formats not showing in the browser If I tried to play it via show hidden
it gives me error massage Couldn't get file information for [filename]
flac m4a and many other give me same error massage
![image](https://github.com/user-attachments/assets/6a903d5b-b562-4307-a8f6-48b8e031014f)
<b><s>You don't need to get any information just start playing the audio via ffmpeg.</s></b>

**Comment by gavtroy** [comment]
`cmus --plugins` could be helpful. I assume you are actually installing cmus; to run out of the build directory you would  need to set CMUS_LIB_DIR.

**Comment by HalanoSiblee** [comment]
cmus --plugins
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
```
what dir CMUS_LIB_DIR supposed to be ?

**Comment by gavtroy** [comment]
CMUS_LIB_DIR overrides the plugin directory but it can be left unset in most cases.

You're probably either missing the dependencies or just don't have the matching version of them, for example after a partial upgrade. Try `pacman -S ffmpeg faad2 libmp4v2 cmus`.

Or if you're building from source make sure you ./configure again after installing the dependencies.

**Comment by HalanoSiblee** [comment]
I just updated `ffmpeg` package ,and now it's work ,my fault 
sorry for disturbing, and thanks for help.
