### ISSUE TITLE
cmus and bluealsa

### ISSUE THREAD

**Issue by favdish** [cmus/cmus#1354]
1) `uname -a`:
```
Linux makalu 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.11.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  alsa
```
I am using bluetooth speakers via bluealsa. This works in every player I've so far tried (DeaDBeeF, qmplay2, mpv, musikcube, exaile). It doesn't work with cmus. I'm pretty sure that I've either missed some element while compiling 2.11 or that I'm not using the right incantation in the settings. I've tried among other things the following for dsp.alsa.device:
```
bluealsa
bluealsa:SRV=org.bluealsa,DEV=FC:58:FA:2A:03:28,PROFILE=a2dp
SPBT
```
The last is the speaker device in my .asoundrc:
```
defaults.pcm.!card Generic_1
defaults.pcm.!device 0
defaults.pcm.!ctl Generic_1
pcm.SPBT {
	type bluealsa
	device "FC:58:FA:2A:03:28"
	profile "a2dp"
	hint { show on description "SP4BT"}
}
```

**Comment by favdish** [comment]
Hm... it seems to work if I terminate cmus, edit the autosave file:
```dsp.alsa.device=bluealsa```
and restart. It doesn't seem to work when changed from within cmus though, even after restarting. Not sure how this all hangs together and would appreciate some comments as to the required/accepted device string.

Anyway, works now, somehow :smile:

**Comment by pgaskin** [comment]
It not working without a restart (or changing to a track with a different sample format) is common for most output plugin settings since output plugins are not reopened when changing settings.

Regarding the setting not saving, is anything you change from within cmus saving?

**Comment by favdish** [comment]
It definitely works when cmus is not running and I change the setting manually to bluealsa.

If I change it from within cmus, it shows the change in the Settings tab and the file on disk changes as well... but when I restart cmus it returns to default.

OTOH I've done so many different changes and tests that I can't be 100% sure there hasn't been some other small thing that made it work. I'll get back if I run into further trouble. For now, marked as solved.
