### ISSUE TITLE
Edge cases in configure/build processes causing incorrect linkage

### ISSUE THREAD

**Issue by i0ntempest** [cmus/cmus#1366]
---

1) `uname -a`:
```
Darwin Mac-Studio.i0ntempest.home 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020 arm64
```

2) `cmus --version`:
```
cmus v2.11.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
N/A, ffmpeg enabled

I'll be honest that my system setup is kinda complicated, but there might be many user with similar configurations during to how MacPorts handles ffmpeg versions.
So, the main ffmpeg port is version 4 and installed at the usual location in the prefix. Version 6 and version 7 are in `${prefix}/libexec`. Therefore I need to set `PKG_CONFIG_PATH=${prefix}/libexec/ffmpeg7/lib/pkgconfig:${prefix}/lib/pkgconfig` for it to find the new ffmpeg. However due to some bugs in the configure script this isn't enough.

1. `libswresample` is not searched during configure but during building, therefore the same PKG_CONFIG_PATH variable need to be present in the build phase as well.
2. Because the ffmpeg v7 linker and cflags found by pkgconfig are put AFTER the main linker and cflags respectively,, if both ffmpeg v4 and v7 are installed, even when `PKG_CONFIG_PATH=${prefix}/libexec/ffmpeg7/lib/pkgconfig` is present, the resulting binary links ffmpeg v4.

**Comment by pgaskin** [comment]
I noticed the swresample oddity (introduced in fb939e5238c128ae1837430cbf838b945d4c99a9) as well while working on cleaning up the configure script yesterday, and am surprised it hasn't caused more issues than this.

I'm not entirely sure I understand what you mean in point 2. Are you referring to the implicit dependencies of swresample?

**Comment by i0ntempest** [comment]
No it's a completely separate issue (I think).
Say pkg-config gives `-L/opt/local/libexec/ffmpeg7/lib -lavcodec` ldflags for `libavcodec`, and MacPorts adds `-L/opt/local/lib` for every port which is the default prefix. The build process puts `-L/opt/local/libexec/ffmpeg7/lib -lavcodec` after `-L/opt/local/lib` so if `libavcodec.dylib` is present in both directories it links the one in `/opt/local/lib` which is incorrect. I need to manually put `-L/opt/local/libexec/ffmpeg7/lib` in the ldflags before everything else to get around this.
And it's probably the same for `-I` cflags as well.
I've attached a complete build log (without this worksround) for you to take a deeper look.
[main.log](https://github.com/user-attachments/files/17082982/main.log)

**Comment by pgaskin** [comment]
Ah, it makes much more sense now that it's clear that MacPorts adds the default prefix to LDFLAGS explicitly.

I'm not sure the second issue is something we can or should fix in configure since putting the `-L` (or other linker flags) for a library before the global ones may create even more unusual behaviour (especially if the library's path contains other conflicting libraries). See https://github.com/mesonbuild/meson/issues/1718 for an example of how it's more problematic to put library LDFLAGS before the global ones.

I will fix the libswresample thing though, as it's clearly incorrect.

**Comment by pgaskin** [comment]
@flyingmutant, am I misunderstanding something, or is there a reason why we're pulling in swresample just for *buffering*?

https://github.com/cmus/cmus/blob/3af94b77adb4fb9bc6df2df37b9d4f03569030e2/ip/ffmpeg.c#L239-L253

It's not doing any resampling, and fb939e5238c128ae1837430cbf838b945d4c99a9 claims it was added to deal with the fact we can't guarantee ffmpeg's output is smaller than a known size (and the frame is allocated with avcodec_alloc_frame -- speaking of which, why are even allocating this for every single fill call... shouldn't we just allocate one and keep it around, keeping track of the offset into it and reading it incrementally?).

Also, @gavtroy, any opinion about this?

**Comment by pgaskin** [comment]
Also, it's lucky that the ffmpeg configure ever worked after fb939e5238c128ae1837430cbf838b945d4c99a9 since the configure script attempts to compile `ip/ffmpeg.c` without the `libswresample` cflags, and the only reason why it works is since it doesn't need any.

https://github.com/cmus/cmus/blob/3af94b77adb4fb9bc6df2df37b9d4f03569030e2/configure#L472-L499

**Comment by gavtroy** [comment]
```
case AV_SAMPLE_FMT_U8:
    ...
case AV_SAMPLE_FMT_S32:
    ...
/* AV_SAMPLE_FMT_S16 */
default:
    ...
```
The comment here gives a misleading impression that the default case means the _input_ is `AV_SAMPLE_FMT_S16`, but it's also handling many other formats such as `AV_SAMPLE_FMT_FLTP`. So presumably without swresample these formats wouldn't work.

For the frame, probably yes. There's a few things we could do better when looking at https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/decode_audio.c
