### ISSUE TITLE
Patrick is absolutely killing it going through the issue backlog

### ISSUE THREAD

**Issue by cubicvoid** [cmus/cmus#1374]
This issue is to say thank you and that it's really nice to see so much activity on the project and to remind Patrick to take stretch breaks and drink plenty of water and pat himself on the back. Can be closed with no further action.

**Comment by pgaskin** [comment]
Thanks :)

**Comment by pgaskin** [comment]
Also thanks to @gavtroy for fixing some of the hard-to-find bugs, implementing well-thought-out features and changes (some of which I didn't know I needed until I tried them), and thoroughly reviewing some of my PRs.
