### ISSUE TITLE
cmus causes online videos not to start

### ISSUE THREAD

**Issue by ludblom** [cmus/cmus#1380]
If I start cmus to listen to music or just pause a track while listening, it prevents me from watching a video. Have tried many different video services, and it seems like Bing preview works, but not as soon as you launch the video. See https://www.bing.com/videos/onecolumn/landing as an example. I think the reason for this may be because they do not use any audio.

---

1) `uname -a`:
```
Linux home-pc 6.1.112-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Sep 30 19:15:46 UTC 2024 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.11.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
```

**Comment by pgaskin** [comment]
Are you using pipewire? Also, are you able to start the video first, then cmus?

**Comment by pgaskin** [comment]
I'm going to assume you are since you're on arch.

- Try starting the video first and see if cmus works.
- Ensure you have `pipewire-pulse` and `wireplumber` installed.
- Try restarting pipewire and wireplumber (`systemctl --user restart pipewire wireplumber`), then restart your browser.
- Check whether there's any errors in `journalctl --user -f` while playing videos. Also check `pw-top`.
- Ensure `pulseaudio` isn't running.

Since there hasn't been a response for more than a week, I'll close this for now, but if you still have this issue and have tried the steps above, feel free to reopen it.

**Comment by ludblom** [comment]
Sorry for late reply. But I am at the bottom sadly. I have installed/uninstalled everything and this is my log still after a reboot.

> nov 03 17:52:05 home-pc dunst[1422]: WARNING: No icon found in path: 'audio-volume-medium'
nov 03 17:53:41 home-pc pipewire[1599]: spa.alsa: 'front:0': playback open failed: Device or resource busy
nov 03 17:53:41 home-pc pipewire[1599]: spa.alsa: 'front:0': playback open failed: Device or resource busy
nov 03 17:53:41 home-pc pipewire[1599]: spa.audioadapter: params Spa:Enum:ParamId:EnumFormat: 0:0 (follower format) Device or resource busy
nov 03 17:53:41 home-pc pipewire[1599]: pw.node: (alsa_output.pci-0000_00_1f.3.analog-stereo-54) suspended -> error (Start error: Device or resource busy)
nov 03 17:53:46 home-pc pipewire[1599]: pw.node: (alsa_output.pci-0000_00_1f.3.analog-stereo-54) suspended -> error ((null))
nov 03 17:53:46 home-pc pipewire[1599]: pw.link: 0x55cc11975d90: one of the nodes is in error out:idle in:error
nov 03 17:53:46 home-pc pipewire[1599]: pw.link: 0x55cc11977320: one of the nodes is in error out:idle in:error

Also, it is not really Arch, it is Manjaro, a very bloated version of Arch. The systems I have Arch on is working fine. Could it then maybe something else that is blocking, something that comes with Manjaro?

**Comment by ludblom** [comment]
Also, I am using pipewire

**Comment by ludblom** [comment]
> Are you using pipewire? Also, are you able to start the video first, then cmus?

It was pipewire! Thank you very much!

**Comment by nefthy** [comment]
Does it work when you `:set output_plugin=pulse`?

**Comment by pgaskin** [comment]
> It was pipewire! Thank you very much! Everything got fixed by just removing it

That wasn't the fix I intended... I was asking about pipewire since if you were using it, you could run `pw-top` to see the active clients (and determine whether both cmus and the online video were at least opening a stream successfully).
