### ISSUE TITLE
cmus with pipewire only

### ISSUE THREAD

**Issue by seamusdemora** [cmus/cmus#1381]
I have a Raspberry Pi 3A+; it is running the 64-bit version of 'bookworm'. I have installed `pipewire`; version=1.2.4. 

I originally installed this system months ago; it's been through some changes, and I cannot recall the exact sequence of changes. Several months ago I installed `pipewire` (version 0.something at the time of initial install), and I also installed `cmus`.  I've become quite attached to `pipewire` and `cmus` because they provide reliable sound through my single Bluetooth speaker (I like to spend BIG on my sound systems :) 

Recently, I have noticed that the *"sound configuration"* on my RPi 3A+ system is vastly different than the configuration on another system: a Raspberry Pi Zero 2W. The RPi 02W system has the exact same OS installed, and the exact same version of `pipewire`; however **I have not installed `cmus`** on the RPi 02W. It only just occurred to me that the reason for the vastly different sound configuration might be due to `cmus`. :-P  ***This is the reason I'm here - asking questions.*** 

Q1: Can someone confirm that the `cmus` installation also pulled in *Pulse Audio*? Or, that PA has somehow been installed as a byproduct of either the `cmus` or the `pipewire` installation? 

Q2: Is it possible to use `cmus` without any PA support? ...  I should explain the motivation behind this question: 
>*I would like to use `amixer` occasionally for volume control, and it seems I cannot do that as the RPi 3A+ system is now installed/configured.* 

Thanks so much for your time!

**Comment by pgaskin** [comment]
I'm assuming the raspbian packages for cmus are the same as debian.

In debian bookworm, [`cmus`](https://packages.debian.org/bookworm/cmus) suggests [`libpulse0`](https://packages.debian.org/bookworm/libpulse0). As such, it won't automatically get installed as a dependency. The [`libpulse0`](https://packages.debian.org/bookworm/libpulse0) package suggests [`pulseaudio`](https://packages.debian.org/bookworm/pulseaudio), which also won't get automatically installed with it.

If you have [`pipewire-pulse`](https://packages.debian.org/bookworm/pipewire-pulse) installed or an equivalent pipewire configuration, libpulse will use pipewire as a backend. Otherwise, if you have a regular pulseaudio daemon running, that will be used instead.

Installing cmus would not have resulted in either pipewire or pulseaudio being installed, though it will use either one if you have it.

You can see which output plugin cmus is currently using by running `grep output_plugin ~/.config/cmus/autosave` after exiting cmus.

You can force cmus to use alsa as the output plugin by typing `:set output_plugin=alsa` within cmus. However, if all you want to do is control the volume from the command line, you can use tools like [`pulsemixer`](https://packages.debian.org/bookworm/pulsemixer) or [`pactl`](https://packages.debian.org/bookworm/pulseaudio-utils).

**Comment by seamusdemora** [comment]
Excellent answer!  However, I remain confused wrt one point (see below)

```bash
$ grep output_plugin ~/.config/cmus/autosave
set output_plugin=pulse
$ pgrep pulse
778
``` 
So it's as I suspected. I don't know how PA got in there, but as I said, it's been a while & I don't recall the sequence. I do recall that I struggled for quite a while getting Bluetooth working! I tried a lot of things. 

#### WRT my confusion:
 I did as you suggested: 

In `cmus`: I did `:set output_plugin=alsa` within `cmus` ;  it took that OK. I quit `cmus`, and re-checked `amixer`: 

```bash
$ amixer
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -1988 [78%] [-19.88dB] [on]
```

... what I was ***expecting*** to see was this (what I see on my Pi Zero 2W) :

```bash
$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 26215 [40%] [on]
  Front Right: Playback 26215 [40%] [on]
Simple mixer control 'Capture',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 65536
  Front Left: Capture 26215 [40%] [on]
  Front Right: Capture 26215 [40%] [on]
``` 

I re-booted, ...
```
$ grep output_plugin ~/.config/cmus/autosave
set output_plugin=alsa
```

So far, so good..., and re-started `cmus` via `screen -S cmus cmus` & tried playing a song from the library: 

```
Error: opening audio device: No such file or directory
```

And so I entered `:set output_plugin=pulse` from `cmus`, and it works again!!

It seems that `cmus` has an affinity for `pulse` that requires something else to break. Any idea what that might be?

**Comment by pgaskin** [comment]
If you don't want pulseaudio/pipewire, you need to remove or disable it.

You really should be using pipewire though; it's much better than plain alsa or the alternatives.

**Comment by seamusdemora** [comment]
I'll add this in a separate comment in an effort to avoid confusing things: 

You said,
>if all you want to do is control the volume from the command line, you can use tools like [pulsemixer](https://packages.debian.org/bookworm/pulsemixer) or [pactl](https://packages.debian.org/bookworm/pulseaudio-utils). 

Thanks for those suggestions. I'm trying to stick with `alsa` (`amixer` actually) for volume control on both systems as I've invested time in setting up a function and aliases in my `~/.bashrc` (on the Zero 2W) to do that... it's just easier for me to minimize the number of apps I have to deal with.

**Comment by seamusdemora** [comment]
> If you don't want pulseaudio/pipewire, you need to remove or disable it.
> 
> You really should be using pipewire though; it's much better than plain alsa or the alternatives.

Yes...  I'll just have to figure out what to remove or disable. And yeah - `pipewire` is great - so reliable.

**Comment by seamusdemora** [comment]
And one other question while I'm thinking of it: Do I need the latest version of `cmus` to be able to shuck `pulse`??

**Comment by pgaskin** [comment]
No, but why are you so determined to get rid of pulseaudio/pipewire?

**Comment by seamusdemora** [comment]
> No, but why are you so determined to get rid of pulseaudio/pipewire?

https://github.com/cmus/cmus/issues/1381#issuecomment-2433661165

**Comment by pgaskin** [comment]
Ah, sorry, I missed that when replying.

I will note that it's probably simpler for you overall to update the aliases, as everything else including bluetooth generally works better with pipewire, and most software prefers it too.

As for your aliases, the commands are pretty similar:

```
amixer -q sset Master 5%+
amixer -q sset Master 5%-
amixer -q sset Master toggle
```

```
pactl set-sink-volume @DEFAULT_SINK@ +10%
pactl set-sink-volume @DEFAULT_SINK@ -10%
pactl set-sink-mute @DEFAULT_SINK@ toggle
```

(and absolute values or specific device names work the same way for both)

**Comment by pgaskin** [comment]
Oh, another thing. I just re-read your original post and noticed that you want *pipewire* ALSA rather than pure ALSA.

You can treat the `pulse` plugin as pipewire as far as you're concerned (`libpulse` is not the `pulseaudio` daemon, it's just the protocol client library); pipewire supports the pulseaudio protocol in the same way as it supports ALSA. If you want proof of this, run `pw-top` while running cmus with the `pulse` plugin.

**Comment by seamusdemora** [comment]
OK, but then why did `cmus` fail after switching to `alsa`? 

> You can force cmus to use alsa as the output plugin by typing `:set output_plugin=alsa` within cmus. However, if all you want to do is control the volume from the command line, you can use tools like [`pulsemixer`](https://packages.debian.org/bookworm/pulsemixer) or [`pactl`](https://packages.debian.org/bookworm/pulseaudio-utils).

I'll guess this has something to do with `pipewire ALSA` vs. `pure ALSA`??

Anyway - thanks for your advice & counsel re the simpler alternative, but I'm also kinda' stubborn :)  If there's no other way to switch to `alsa` (or `pipewire ALSA`) in `cmus`, then I'll have to go through with the ***"do-over"***

**Comment by pgaskin** [comment]
> I'll guess this has something to do with pipewire ALSA vs. pure ALSA??

It's because cmus supports pulseaudio (with it having a higher priority than alsa), and pipewire implements the pulseaudio protocol.

It's still pipewire in the end, which has compatibility with ALSA, PulseAudio, and JACK, so it doesn't really matter how cmus interacts with it since you can use any of the three tools to control it.

If you really want cmus to use the alsa protocol to communicate with pipewire, add the `:set` command to the cmus rc.

> If there's no other way to switch to alsa (or pipewire ALSA) in cmus

The thing I said about pure ALSA is slightly inaccurate wrt your original question; I had originally interpreted it as you wanted to use alsa *without* pipewire or pulseaudio (or anything else) over it, but upon re-reading it, it seems you want to use pipewire via it's ALSA compatibility.

**Comment by seamusdemora** [comment]
> If you really want cmus to use the alsa protocol to communicate with pipewire, add the `:set` command to the cmus rc.

Sorry - not quite clear on the full text of that `:set` command in `cmus` - I know this is getting long, but could you clarify that for me?

**Comment by pgaskin** [comment]
`set output_plugin=alsa`

**Comment by seamusdemora** [comment]
?? OK - I guess I am being thick, but I tried that [earlier/above](https://github.com/cmus/cmus/issues/1381#issuecomment-2433640554), and it didn't work. 

I tried to get clarification on whether or not something had to be deleted/removed to make that command effective, but if I got an answer - I missed it. 

I appreciate your patience.

**Comment by pgaskin** [comment]
Try putting it in `cmus/rc`.

**Comment by nefthy** [comment]
I'd guess that something (possibly pipeire) has locked the alsa device and cmus cannot get the device. But that's from my crystal ball. Would be useful if you could provide the command you run and the output.

**Comment by seamusdemora** [comment]
> I'd guess that something (possibly pipewire) has locked the alsa device and cmus cannot get the device. But that's from my crystal ball. Would be useful if you could provide the command you run and the output.

Well, there is definitely *something else* going on, and I would be most appreciative if you guys could help me find it. 

I've been reading/studying tonight - largely from the [Debian pipewire wiki](https://wiki.debian.org/PipeWire). Part of the problem is Debian doesn't update its documentation in a timely fashion, but it's all I've got for now. 

In summary, my two systems (Zero 2W and 3A+) behave differently wrt `alsa`:

### Zero 2W: 
* Zero 2W: uses `mpg123` as its player 'cos I use this mostly for playing some sounds for sleeping
* Zero 2W: seems to use `alsa` exclusively:
```
$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 26214 [40%] [on]
  Front Right: Playback 26214 [40%] [on]
```
* Zero2W:
```
$ LANG=C aplay -L | grep -A 1 default
default
    Default ALSA Output (currently PipeWire Media Server)
```
* software installs are the same AFAIK (except for `cmus`)
```
$ dpkg -l | grep pulse
ii  libpulse0:arm64                     16.1+dfsg1-2+rpt1                arm64        PulseAudio client libraries
ii  pipewire-pulse                      1.2.4-1~bpo12+1+rpt1             arm64        PipeWire PulseAudio daemon
```

### 3A+: 
* 3A+ : has `mpg123` **and** `cmus`; `mpg123` is used only rarely to play the occasional "beep" alert
* 3A+ seems to rely on something called "PCM":
```
$ amixer
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -1988 [78%] [-19.88dB] [on]
``` 
* 3A+:
```
$ LANG=C aplay -L | grep -A 1 default
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
--
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
--
default:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
--
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
``` 
* AFAIK, both systems have exactly the same software & versions installed; e.g.
```
$ dpkg -l | grep pulse
ii  libpulse0:arm64                     16.1+dfsg1-2+rpt1                arm64        PulseAudio client libraries
ii  pipewire-pulse                      1.2.4-1~bpo12+1+rpt1             arm64        PipeWire PulseAudio daemon
```

I'm still working through this, but ***so far*** the only thing I see to account for the diff is the `cmus` install. 

My *objective* is for the 3A+ to use `alsa` in the same way the Zero 2W does. The `cmus` volume control (+/- kybd shortcuts) is brilliant, but I don't see why that same scheme can't work with `alsa`?  

Thanks for any suggestions you can offer.

**Comment by seamusdemora** [comment]
OK!  I think I've found a (v. simple) solution! This came from the [Debian pipewire wiki](https://wiki.debian.org/PipeWire): 

>ALSA
>
>Install the [pipewire-alsa](https://packages.debian.org/pipewire-alsa) package, and reboot. This will configure PipeWire to activate its !ALSA plugin. Verify that it's enabled by running:
>
>LANG=C aplay -L | grep -A 1 default
>
>If PipeWire is configured properly, this will print "Default ALSA Output (currently PipeWire Media Server)" If you still see "Playback/recording through the [PulseAudio](https://wiki.debian.org/PulseAudio) sound server" then Pulseaudio still has control of ALSA output and needs to be uninstalled. 

And that's what I did: 

```
$ sudo apt install pipewire-alsa
...
# afterwards:

$ LANG=C aplay -L | grep -A 1 default
default
    Default ALSA Output (currently PipeWire Media Server)   # <==== !!! 
--
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
--
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0 

$ amixer
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 32768 [50%] [on]
  Front Right: Playback 32768 [50%] [on]

# AND NOW: 

$ screen -S cmus cmus 

[ctrl-A + d] to close screen

$ amixer sset Master 100% 
...
$ amixer sset Master 50%
...

``` 

### IT WORKS!!  I can now control volume of `cmus` playback with `screen` detached  :)  

I'm going to sleep so well tonight :) lol

**Comment by seamusdemora** [comment]
But here's the ***ODD THING***: 

In `cmus`, one must `: set output_plugin=pulse` !?  If I set it to `alsa` (instead of `pulse`), I get an error, and playback stops! 

ALSO :  In `~/.bashrc` I've declared a function & two aliases: 
```
function vol-get() {
   amixer sget PCM | awk -F"[][]" '/Left:/ { print $2 }'
}
export -f vol-get
alias vol-up='amixer sset Master 5%+ > /dev/null && vol-get'
alias vol-dn='amixer sset Master 5%- > /dev/null && vol-get'
``` 

When I use the aliases, I get this:
```
$ vol-dn
amixer: Unable to find simple control 'PCM',0

$
```

But if I use a "normal" `amixer` command: 
```
$ amixer sset Master 75%
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 49152 [75%] [on]
  Front Right: Playback 49152 [75%] [on]
```

I do not get the 'PCM' warning... I wonder if `cmus` has a preference for PA built into the configuration somewhere? 

Maybe this is something the `cmus` team could take on???

**Comment by nefthy** [comment]
You have pipewire running, and it takes exclusive control of the alsa device, so cmus cannot get control of alsa. If you run pipewire, you will have to use the pipewire plugin.

As for you script, I think vol-get() should look like
```bash
function vol-get() {
   amixer sget Master | awk -F"[][]" '/Left:/ { print $2 }'
}
```

But that's a bit off topic here.

**Comment by seamusdemora** [comment]
> You have pipewire running, and it takes exclusive control of the alsa device, so cmus cannot get control of alsa. If you run pipewire, you will have to use the pipewire plugin.
>
> As for you script, I think vol-get() should look like
> 
> ```shell
> function vol-get() {
>    amixer sget Master | awk -F"[][]" '/Left:/ { print $2 }'
> }
> ```

Ach!  You are correct!... The `PCM` was left over from an earlier experiment trying to get that working when pulse was being used.  I carelessly copied that from `/.bashrc` - never even noticed I'd left the `PCM` bit in - sorry about that! 

> 
> But that's a bit off topic here. 

Oh sorry - I thought it might be of interest... I mean the ability to adjust the volume of a `cmus`-playing track when the `screen` session is detached. How would you do that using `cmus` controls?

**Comment by pgaskin** [comment]
>  I mean the ability to adjust the volume of a cmus-playing track when the screen session is detached. How would you do that using cmus controls?

```
cmus-remote -v +5%
cmus-remote -v -5%
cmus-remote -v 100%
```

> What do you think is going on there?

We'd need cmus debug logs.

**Comment by nefthy** [comment]
> In cmus, one must : set output_plugin=pulse !? If I set it to alsa (instead of pulse), I get an error, and playback stops!
> 
> What do you think is going on there?

Crystal ball still says: pipewire is running, so the alsa device is locked by pipewire. cmus tries to open the alsa device, but can't get a lock and fails.

**Comment by seamusdemora** [comment]
> > I mean the ability to adjust the volume of a cmus-playing track when the screen session is detached. How would you do that using cmus controls?
> 
> ```
> cmus-remote -v +5%
> cmus-remote -v -5%
> cmus-remote -v 100%
> ```

That's great! Thank you. 

> > What do you think is going on there?
> 
> We'd need cmus debug logs. 

OK, well I have to ask how to generate 'cmus debug logs' as I've searched, but found nothing for it.

**Comment by seamusdemora** [comment]
@nefthy 
> > In cmus, one must : set output_plugin=pulse !? If I set it to alsa (instead of pulse), I get an error, and playback stops!
> > What do you think is going on there?
> 
> Crystal ball still says: pipewire is running, so the alsa device is locked by pipewire. cmus tries to open the alsa device, but can't get a lock and fails.

I stopped pipewire.service, and then tried to make the change: 
```
$ systemctl stop --user pipewire.service
Warning: Stopping pipewire.service, but it can still be activated by:
  pipewire.socket
$ screen -r cmus 
[ 
    : set output_plugin=alsa 
   ctrl-a + d
] 
$ systemctl start --user pipewire.service 
$ screen -r cmus
[ 
    ... tried playing a song 
    "Error: opening audio device: No such file or directory" (red letters)
    : set output_plugin=pulse
   ... tried playing a song ==>  song plays immediately
] 
```
###  i.e. Same Result

**Comment by nefthy** [comment]
Looks like your default alsa device is not setup correctly. Have a look at the output of:
```bash
cat /proc/asound/cards
```
That will output something like that:
```
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xf6880000 irq 130
 1 [F8R            ]: USB-Audio - Fast Track Ultra 8R
                      M-Audio Fast Track Ultra 8R at usb-0000:10:00.4-1, high speed
 2 [U0x46d0x825    ]: USB-Audio - USB Device 0x46d:0x825
                      USB Device 0x46d:0x825 at usb-0000:10:00.4-2, high speed
```
Find out the number of the output device you want to use (lets say 2 for this example) and then you either create or edit  /etc/asound.conf (will set the default for all alsa application on the system) to something like:
```
defaults.pcm.card 2
defaults.ctl.card 2
```

Alternatively you can set the output device in the cmus config:
```
set dsp.alsa.device=plughw:2
```

make sure to replace 2 with the appropriate number for your system

**Comment by seamusdemora** [comment]
Here's what I see: 

```
$ cat /proc/asound/cards
 0 [Headphones     ]: bcm2835_headpho - bcm2835 Headphones
                      bcm2835 Headphones
 1 [vc4hdmi        ]: vc4-hdmi - vc4-hdmi
                      vc4-hdmi
```

But neither one is correct! I've got a single BT speaker - a JBL Flip 5. 

Also - not that it makes any difference - I have never touched that file (`/proc/asound/cards`); it must have been ***automatically generated*** at some point. Beyond that, I am at a total loss as to what is the correct entry for my hardware in that file...  can you offer any suggestions?

**Comment by nefthy** [comment]
Alsa does not do bluetooth out of the box. You'll be better of using pipewire.

**Comment by seamusdemora** [comment]
> Alsa does not do bluetooth out of the box. You'll be better of using pipewire.

### But I ***am*** using `pipewire`.

The only choice seems to ["boil down"](https://idioms.thefreedictionary.com/boil+down+to) to `alsa` or `pulse`. 

Please recall that I didn't actually "choose" anything (except `pipewire` and `cmus`). I had initially wanted to eliminate `pulse` because: 1) Didn't want any messy "extra components" lying about; 2) Didn't think it *possible* to eliminate `alsa`; 3) My other system (Zero 2W) has no `pulse` affiliation at all. 

I remain pretty much mystified by how `pulse` found its way onto the 3A+ system. And IIRC, you've said it wasn't due to `cmus` - Correct??

**Comment by pgaskin** [comment]
`pulse` == `pipewire` != `pulseaudio`

You're just using cmus `op/pulse` to use the pulseaudio protocol to access `pipewire`.

**Comment by seamusdemora** [comment]
> `pulse` == `pipewire` != `pulseaudio`
> 
> You're just using cmus `op/pulse` to use the pulseaudio protocol to access `pipewire`.

:)  I did not know that! 
But what is 'op/pulse'?...  and why do I need the "pulseaudio protocol" to access 'pipewire'? Rather than pester you guys with all of these questions, is there not some place where all of this is _written down_ for others to read?

**Comment by pgaskin** [comment]
- https://wiki.archlinux.org/title/PipeWire
- https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PulseAudio

**Comment by seamusdemora** [comment]
OK, but after reading (most of) that, I still haven't learned what 'op/pulse' is. Care to elaborate? 

I *think* archlinux documentation is mostly developed for archlinux - not debian. But here's some observations from the archlinux pipewire wiki: 

* on neither of my Debian systems does the file/folder `/etc/pipewire` exist
* on the 3A+ system, there is a folder named `~/.config` with two subfolders: `cmus` & `pulse`; `pulse` contains 1 file named `cookie` which is binary & un-readable.
* on the Zero 2W system, the `~/.config` folder has only the `pulse` folder. It also contains the `cookie` file (no `cmus` file b/c it's not installed) & a broken symlink to `/tmp/pulse-PKdhtXMmr18n` 

I don't know if this makes any sense to you, but I remain *"in the dark"* WRT: 

1. `: set output_plugin=pulse` in `cmus` throws an error & locks it up. 
2. How to generate 'cmus debug logs' 

But the good news remains: `cmus` continues to operate flawlessly on my 3A+ system - the glitch in item 1 notwithstanding.

**Comment by nefthy** [comment]
> I _think_ archlinux documentation is mostly developed for archlinux - not debian. But here's some observations from the archlinux pipewire wiki:

The documentation on the archlinux wiki page is not very specific to arch, except for the package manager commands. You need to figure out what audio setup you have on your Zero 2W, in order to select the correct output plugin for cmus. For that you need to refer to the documentation of the distro you installed on it. You can check if pipewire is running by doing something like `ps aux | grep pipewire`.

>     1. `: set output_plugin=pulse` in `cmus` throws an error & locks it up.

And the error say what?

>     2. How to generate 'cmus debug logs'

You would need to compile cmus from source and use `./configure DEBUG=2`

**Comment by seamusdemora** [comment]
> > I _think_ archlinux documentation is mostly developed for archlinux - not debian. But here's some observations from the archlinux pipewire wiki:
> 
> The documentation on the archlinux wiki page is not very specific to arch, except for the package manager commands. You need to figure out what audio setup you have on your Zero 2W, in order to select the correct output plugin for cmus. For that you need to refer to the documentation of the distro you installed on it. You can check if pipewire is running by doing something like `ps aux | grep pipewire`.
> 
> > ```
> > 1. `: set output_plugin=pulse` in `cmus` throws an error & locks it up.
> > ```
> 
> And the error say what?

From [this previous comment:](https://github.com/cmus/cmus/issues/1381#issuecomment-2439707143)

`"Error: opening audio device: No such file or directory" (red letters)`

**Comment by nefthy** [comment]
That previous comment says that `:set output_plugin=pulse` works and that `:set output_plugin=alsa` breaks. I'd suggest you stick with the one that works.

**Comment by seamusdemora** [comment]
> That previous comment says that `:set output_plugin=pulse` works and that `:set output_plugin=alsa` breaks. I'd suggest you stick with the one that works.

That sounds like good advice - but not the answer I was hoping for... it's nicer to know *why* things don't work. Don't know about you, but I find I learn more that way.

**Comment by nefthy** [comment]
> Error: opening audio device: No such file or directory

With output_pugin=alsa, that means that cmus cannot open the alsa. The alsa device it is trying to open is either the one set via `set dsp.alsa.device=XXX` if one is set or the system default.

You will need to make sure alsa is working properly with your setup. Try to get audio output with `aplay` or something similar.

**Comment by m4r35n357** [comment]
@seamusdemora 

The answer is here: https://wiki.archlinux.org/title/Cmus

I had the same issue.

**Comment by seamusdemora** [comment]
> [@seamusdemora](https://github.com/seamusdemora)
> 
> The answer is here: https://wiki.archlinux.org/title/Cmus
> 
> I had the same issue.

Thanks for the feedback. You gotta love those guys at Arch - they are so thorough, and "true believers" in good documentation! 

And while I'm thanking - I also appreciated the effort from @nefthy and @pgaskin here.
