### ISSUE TITLE
ffmpeg.c don't compile with libav10

### ISSUE THREAD

**Issue by evgkrsk** [cmus/cmus#139]
Manual compiling of ffmpeg.c yelds this:
```
 gcc ffmpeg.c -o ffmpeg -lavformat 
ffmpeg.c:40:38: fatal error: libswresample/swresample.h: No such file or directory
 #include <libswresample/swresample.h>
                                      ^
compilation terminated.
```
but according to libav documentation (http://libav.org/doxygen/master/group__lavr.html) there is no such file like swresample.h, since libav9 (seems like libav0.8 was last "good" version). Now libavresample/avresample.h must be used, as per documentation. Mapping of old swr_* to new functions is fairy simple (one hacky example: https://github.com/xbmc/xbmc/blob/Gotham/lib/xbmc-libav-hacks/swresample.c).

**Comment by tecfu** [comment]
Why was this closed? It has not been resolved.

**Comment by marcelltisdol** [comment]
Agreed, what in the hell otherwise this is the perfect music player for wherever you are

**Comment by mahkoh** [comment]
libav is not supported.

**Comment by marcelltisdol** [comment]
@mahkoh I don't understand 

So cmus was using ffmpeg to decode ALAC/m4a files, right? - and it worked in an older version.

Where does the fault lie? With ffmpeg/libav, cmus, or cmus ffmpeg plugin? 

What needs to be done in order to get decoding of ALAC/aac/m4a done man? What can I do, how can I contribute?

**Comment by marcelltisdol** [comment]
@mahkoh I think this is unacceptable for a media player that can be on a trajectory to be the defacto leader along with Foobar2k on Windows

**Comment by mahkoh** [comment]
ffmpeg and libav are distinct projects. cmus works just fine with ffmpeg.
