### ISSUE TITLE
cmus fails to run if compiled with different DESTDIR

### ISSUE THREAD

**Issue by lolnameless** [cmus/cmus#140]
$ cmus
cmus: Error: couldn't open directory `/usr/local/lib/cmus/ip': No such file or directory

cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory

cmus: loading /usr/local/share/cmus/rc: No such file or directory

---

but interestingly the installation is fine (files are installed under $DESTDIR).

**Comment by pgaskin** [comment]
Since faa291e10041081e5e72c003cf213d1c42d71bd4 ([`v2.8.0-rc1`](https://github.com/cmus/cmus/releases/v2.8.0-rc1)), the environment variable `CMUS_LIB_DIR` can be set to override the plugin dir (e.g. `CMUS_LIB_DIR=/usr/lib64/cmus ./cmus`).
