### ISSUE TITLE
OSX - Error: can't change volume: mixer is not open

### ISSUE THREAD

**Issue by neurotech** [cmus/cmus#141]
Hi

I'm getting this error when using - or + to adjust volume in OSX 10.9.3:

```
Error: can't change volume: mixer is not open
```

I tried setting `set softvol=false` as described [here](http://ppcluddite.blogspot.com.au/2013/11/ladies-and-gentlemen-your-itunes-killer.html?showComment=1384167117526#c3255470397821713034) but that doesn't seem to work.

**Comment by iromad** [comment]
Thanks @flyingmutant. Works like a charm.

**Comment by YixuanFranco** [comment]
@flyingmutant Sorry, I didn't get it. 
Could you please tell me the location of `rc` one?
I've tried cat ~/.rc but there is no such file either in my root folder or cmus's folder

**Comment by blendsoul** [comment]
@YixuanFranco Just open cmus and type `:set softvol=true`
