### ISSUE TITLE
OSX 10.9.x: brew fails to install cmus

### ISSUE THREAD

**Issue by acke** [cmus/cmus#145]
cmus 2.5.0 did not build
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1

Full log here:
https://gist.github.com/acke/187facbb3d24580f894d

brew list > Brewlist && brew remove --force brew list does not help..

Please help..

**Comment by ardenpm** [comment]
The solutions pointed to in this item didn't help me, I ended up having to do the following:

```brew link ncurses --force```
