### ISSUE TITLE
Won't play m4a (alac)

### ISSUE THREAD

**Issue by tgrrtt** [cmus/cmus#170]
Cmus adds (and plays) mp3 files just fine. Any flac or m4a (alac) that i have, wont get added. If I browse via the file browser, it tells me that it cant get information for that track.

```
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
```

Is the output for `cmus --plugins`
I notice that neither mp4 or flac have MIME types set. Could this be related to my issue?

**Comment by paulrbts** [comment]
I tried this:

> update Homebrew, then install cmus --with-ffmpeg

but `cmus --plugins` doesn't show ffmpeg. I've tried uninstalling cmus and ffmpeg, then updating Homebrew, ugpgading, cleaning up and pruning (just to be sure!) and then removing ~/.config/cmus and reinstalling by `brew install cmus --with-ffmpeg` -- but still no dice.

Further, `brew uninstall ffmpeg` (with cmus still loaded) produces:

> Error: Refusing to uninstall /usr/local/Cellar/ffmpeg/3.2.4 because it is required by cmus 2.7.1_2, which is currently installed.

Any idea how to get `ffmpeg` working with `cmus`?

cmus 2.7.1 
ffmpeg 3.2.4
