### ISSUE TITLE
warning breaks cmus layout

### ISSUE THREAD

**Issue by rnhmjoj** [cmus/cmus#191]
Some mp4 tracks I play (I think the one with ALAC audio) cause this to appear:

    FindIntegerProperty: no such property - moov.trak[0].mdia.minf.stbl.stsd.*.*.esds.decConfigDescr.objectTypeId (src/mp4file.cpp,746)
The tracks play just fine but it breaks the layout of cmus.
Is there a way to hide this warning?
![schermata 2014-09-13 alle 17 23 04](https://cloud.githubusercontent.com/assets/2817565/4261020/fb9be210-3b59-11e4-8dc3-e70c0be93e66.png)

**Comment by flyingmutant** [comment]
Fixed in #264.

**Comment by john-at-charpa** [comment]
I pulled cmus HEAD today (specifically to get around this ) and the issue appears to have returned:

FindIntegerProperty: no such property - moov.trak[0].mdia.minf.stbl.stsd.*.*.esds.decConfigDescr.objectTypeId (src/mp4file.cpp,746)

cmus is linked against mp4v2 2.0.0 (latest release). OS X 10.10.3. I'm happy to provide any other information necessary.

**Comment by john-at-charpa** [comment]
So, the fix for this turned out to simply be telling mp4v2 lib to shut up.

```
--- mp4.c       2015-06-25 11:55:16.000000000 +0900
+++ mp4.c.shutup        2015-06-25 11:56:12.000000000 +0900
@@ -68,6 +68,7 @@
 
 static MP4TrackId mp4_get_track(MP4FileHandle *handle)
 {
+       MP4LogSetLevel(0);
        MP4TrackId num_tracks;
        const char *track_type;
        uint8_t obj_type;
```
Taken from mp4v2/include/mp4v2/general.h line 20.

**Comment by flyingmutant** [comment]
@john-at-charpa, can you please verify that cmus now works OK with my latest commit?

**Comment by john-at-charpa** [comment]
@flyingmutant Initial tests look good, thank you!

**Comment by evgkrsk** [comment]
Nope, it don't compile at all (from git tag v2.6.1 to current HEAD):
```
mp4.c: In function 'mp4_open':
mp4.c:158:2: error: implicit declaration of function 'MP4LogSetLevel' [-Werror=implicit-function-declaration]
  MP4LogSetLevel(MP4_LOG_NONE);
  ^
mp4.c:158:17: error: 'MP4_LOG_NONE' undeclared (first use in this function)
  MP4LogSetLevel(MP4_LOG_NONE);
                 ^
mp4.c:158:17: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make: *** [mp4.lo] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/usr/src/RPM/BUILD/cmus-2.7.1'
```

**Comment by evgkrsk** [comment]
(result is same for libmpeg4ip-devel and libmp4v2-devel)

**Comment by john-at-charpa** [comment]
Your version of mp4v2 is too old. MP4LogSetLevel first appears in mp4v2 v2.0 (released in 2012). Can you upgrade mp4v2 and try again please? I guess we'll need a change to the configuration script to check for v2.0+.

**Comment by evgkrsk** [comment]
Thanks, will try that.

**Comment by flyingmutant** [comment]
I think we should do something like 

```C
#if MP4V2_PROJECT_version_major > 1
         MP4LogSetLevel(MP4_LOG_NONE);
#endif
```

to still be buildable with older versions of mp4v2.

**Comment by mahkoh** [comment]
@flyingmutant This hasn't been addressed since and there haven't been any complaints. Should be close this issue?

**Comment by flyingmutant** [comment]
Closing for now — please feel free to reopen if the issue still exists.
