### ISSUE TITLE
Im getting this on mac.

### ISSUE THREAD

**Issue by jorge8a** [cmus/cmus#199]
Hi, First im have to say that I'm a new, 

Im getting this error after compiling and installing cmus on a Mac os Yosemite i have this.

![cmus_1](https://cloud.githubusercontent.com/assets/9134080/4729633/e9fff66e-598a-11e4-8b4c-c21d9457c64f.jpg)

After pressing enter. i have that message (so it looks like i need some plugin i don't have installed) 

![cmus_2](https://cloud.githubusercontent.com/assets/9134080/4729634/ea0632c2-598a-11e4-984f-0d5aa6903239.jpg)

When I want to add music and i surf to my music folder i can't see any music and it also when i want to add it, it shows me that message.

![cmus_0](https://cloud.githubusercontent.com/assets/9134080/4729631/e88e1ee6-598a-11e4-8496-b4ad92957b54.jpg)

Any advice please, Thanks in advance

**Comment by niltonvasques** [comment]
Hey guys, someone have the theme that are on this page: https://cmus.github.io/ ?

Sorry for ask this here!
