### ISSUE TITLE
FR: Jump to currently playing song

### ISSUE THREAD

**Issue by gerroon** [cmus/cmus#206]
Hi

I looked around, but I cant locate it maybe there is such a feature. It would be great if there is a way to jump to the currently playing file in any view (like playlist, etc). I know I can echo it but it would be sweet if I assign a shortcut to go to the line in the playlist view for example. some other players also offer auto jumping , ie it highlights the currently playing song.

This is an issue with long and randomized playlist, hard to see where the currently playing cursor song.

thanks

**Comment by sedrubal** [comment]
Why does cmus not automatically jump to the current track when the track changes (and there was no user operation during the last x seconds)?

**Comment by mahkoh** [comment]
It does when you press f.

**Comment by sedrubal** [comment]
mh, this does not work...

**Comment by neurotech** [comment]
@sedrubal You need to add `bind common f toggle follow` to `~/.cmus/autosave` to get this working.

**Comment by sedrubal** [comment]
oh, thank you, :+1:
