### ISSUE TITLE
Feature: Scroll half page up/down and H, M, L motions.

### ISSUE THREAD

**Issue by JosephFerano** [cmus/cmus#215]
I would be very much interested in vim's equivalent to C-d and C-u, as well as H (top of page), M (middle of page), L (bottom of page). I tend to just import my music collection and browse around with C-f and C-b until I find a song I would like to play so it would be awesome to have those additional movement keys to help facilitate the browsing. I know some C, I wouldn't mind giving it a shot if someone could point me to the right place :D

**Comment by flyingmutant** [comment]
Fixed by #721.
