### ISSUE TITLE
Importing to Library failed.

### ISSUE THREAD

**Issue by aungthurhahein** [cmus/cmus#223]
Version:2.5.0
Importing music from NTFS partition failed with msg said 'segmentation fault'.

**Comment by flyingmutant** [comment]
Any updates on this one?

**Comment by hoodakaushal** [comment]
I'll add that I had that too, with the apt-get version. Building from source has solved the issue.

**Comment by flyingmutant** [comment]
OK, so the problem is probably already solved. Closing.
