### ISSUE TITLE
Track time off by 24 seconds ALSA

### ISSUE THREAD

**Issue by eat-multi** [cmus/cmus#224]
As mentioned here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=695069
When I start a track, it displays that it's at 00:24 instead of 00:00. No effect on audio. Shows next track is playing during the last 24 seconds of current track.

I tried both with ffmpeg and libmad as plugin in use, so unlikely input plugin related. It's mentioned this is related to ALSA and **not** PulseAudio. Strange that it doesn't seem to affect Banshee/Rhythmbox etc.

Compiled on Ubuntu 14.04

Idk if below is useful:
```
> cat /proc/asound/version
Advanced Linux Sound Architecture Driver Version k3.13.0-40-generic.
```

```
alsa.h from `libasound2-dev (1.0.27.2-3ubuntu7)
```

It may also be a config related issue. I checked the official cmus package from ubuntu repositories and getting same results. Let me know if any more info would be useful.

**Comment by yoyo-san** [comment]
Me too.
Arch and Alsa, with Cmus v2.6
Also, if I try to hit previous song, it will seek back, instead of jumping right to previous track. If I hold long enough, it goes back (usually more than one track, because you need to let go button at precise moment).
Will try to recompile tomorrow.

**Comment by ZygomaticB** [comment]
I've got the same issue. Archlinux with pulse audio/alsa. Didn't have this issue until I reinstalled arch with openbox pulling in alsa and pulseaudio myself. With a desktop enviorment setting up its own sound system (eg KDE, mate, gnome) I don't have this issue.

**Comment by flyingmutant** [comment]
I still don't have Arch box to try to debug this, but if someone is not afraid to dig a bit, this should be helpful.

AFAICS track time that is displayed, `player_info.pos`, is equal to either zero or `consumer_pos` from `player.c`. The only place where `consumer_pos` is set to non-zero value is [here](https://github.com/cmus/cmus/blob/master/player.c#L939) — return value of `op_write` output plugin callback is added to it. The relevant callback for ALSA OP is [op_alsa_write](https://github.com/cmus/cmus/blob/master/alsa.c#L238).

Just by looking at the code I do not see anything obviously wrong. However, it should be a good idea to add some `d_prints` to the relevant parts, and compare the output with the one for PulseAudio OP, which is working good.

**Comment by flyingmutant** [comment]
Guys — can you please test PR #244, does it fixes the issue indeed?

**Comment by ZygomaticB** [comment]
Uninstalling pulseaudio fixes the problem for me. I don't know how to test the above but it sounds like a likely problem. Seems like the problem is with pulse->alsa.

**Comment by eat-multi** [comment]
Sorry I've been gone so long :O 
I'll recompile with that patch in 5 mins :)

**Comment by eat-multi** [comment]
Ohhhhh fixed! Patch works for me.
 :+1:
