### ISSUE TITLE
cmus cygwin mp3 and mpg123

### ISSUE THREAD

**Issue by maggick** [cmus/cmus#243]
I want to use cmus in cygwin.

I have all audio packages from cygwin and build cmus from sources.

cmus play perfectly flac audio files but some of my music is mp3 files.
That is why I build the [mpg123](http://www.mpg123.de/) package in cygwin.

so in my cygwin `mpg123 <path to mp3 file>` play the file,
nevertheless cmus does not recognize mp3 file. 

Is there something I miss ?
Probably the link between cmus and mpg123 is not done with `./configure` because it is looking for libmad instead of mpg123.
What should I do to play mp3 with cmus in cygwin ?

**Comment by flyingmutant** [comment]
True — cmus uses libmad for mp3s, so you need to install it instead. cmus has no mpg123 input plugin.

**Comment by maggick** [comment]
yep thx I build it with libmad.
Is it plan to add mpg123 support in cmus ?

**Comment by flyingmutant** [comment]
There are no such plans.
