### ISSUE TITLE
relative paths for playlist (pls) files?

### ISSUE THREAD

**Issue by willtm** [cmus/cmus#245]
Hello,

I would like to use playlist (.pls) files with relative instead of absolute paths in cmus.  I would like for cmus to create relative paths to files when saving .pls files and I would like cmus to recognize those same paths.

For example, at the moment, if I have a playlist consisting of one song:

`08 Endless Endless.m4a`

And I save that playlist using the following command:

`:load ~/Music/playlist.pls`

Opening the playlist.pls file shows something like the following (on OSX):

`/Users/will/Music/audio_files/Kraftwerk/Trans Europe Express (Remastered)/08 Endless Endless.m4a`

But I would like for the playlist contents to look like this:

`~/Music/audio_files/Kraftwerk/Trans Europe Express (Remastered)/08 Endless Endless.m4a`

And I would like cmus to recognize this.  I am not sure if .pls files even permit relative paths though nor can I see options for changing any defaults in cmus.  I'm sure I'm missing something very simple but I'd appreciate advice.

Thanks,

Will

**Comment by flyingmutant** [comment]
Hi Will,

Right now cmus does not support saving relative paths in the playlist. I'll keep this issue open so that people can see it as a possible thing to contribute to cmus.

**Comment by willtmonroe** [comment]
Thanks for the reply and the inclusion as a possible future enhancement!
