### ISSUE TITLE
cmus-remote didnt work in crontab

### ISSUE THREAD

**Issue by Be-Cool-Man** [cmus/cmus#246]
}{ Following text was translated by Google }{

Hi Guys,

i cmus started in a deached screen-session. Now I want the playback control via cron (use as an alarm clock) BUT: it does nothing. 

My cron looks like
45 06 * * mon-fri     cmus-remote -p
15 07 * * mon-fri     cmus-remote -s

Two years ago, but has also worked.

Greetings
Be-Cool-Man

___________________________
OS: ArchLinux 3.18.4-1 [x86_64]
cmus: v2.6.0

**Comment by flyingmutant** [comment]
Sorry, this does not look like a problem with cmus or cmus-remote — cmus-remote has not changed at all. Do you have a simple reproducible test case that showcases a bug? If not — it might be a good idea to look at your log files and understand what your system actually does.

**Comment by Be-Cool-Man** [comment]
The log says:
cmus-remote: cmus is not running

But cmus runs in an deached screen-session.

**Comment by tkphd** [comment]
I'm also running `cmus` inside of `screen` and `tmux`, and had the same problem as @Be-Cool-Man. I just found the solution, which is to specify the socket `cmus-remote` should send commands through. Since the `cron` or `systemd` environment is bare metal, here's the script I'm using to get a `cmus` alarm clock working, for fellow travelers who stumble across this issue:

```bash
#!/bin/bash
USER=yourusername
USERNAME=yourusername
XDG_RUNTIME_DIR=/run/user/1000 # change 1000 to your user ID
/usr/bin/cmus-remote --server $XDG_RUNTIME_DIR/cmus-socket -u
```

HTH.

**Comment by harriott** [comment]
For info, unlike @tkphd, no matter where I run `cmus` here on Arch, `cmus-remote` only works from my `fcrontab` if I identify the socket. So I can backup my latest queue to file `cmusq` like this:

```
@ 1 cmus-remote --server /run/user/1000/cmus-socket -C 'save -q cmusq'
```

(Although I actually have this called from `fcron` in a script with extra conditions to avoid saving an empty queue.)
