### ISSUE TITLE
Assorted Ubuntu 14.10 Issues

### ISSUE THREAD

**Issue by CMahaff** [cmus/cmus#247]
Issue 1
----------
Running the official package (2.5), launching cmus gives these errors:
```
cmus: Error: no such option auto_expand_albums
cmus: Error: no such option follow
cmus: Error: no such option format_statusline
cmus: Error: no such option format_trackwin_album
cmus: Error: no such option format_treewin
cmus: Error: no such option format_treewin_artist
cmus: Error: no such option mouse
cmus: Error: no such option rewind_offset
cmus: Error: no such option show_all_tracks
cmus: Error: no such option show_playback_position
cmus: Press <enter> to continue.
```
Afterwards, the status bar says:
```Error: selecting output plugin '': no such plugin```
And when I attempt to play a track in my home directory:
```Error: opening audio device: couldn't initialize required output plugin```

Issue 2
----------
Adding a (large) folder (in version 2.5) causes a ```segfault```. Related to Issue #202 ?

Issue 3
---------
Running the latest git version (2.6.0-75) with
```
./configure DEBUG=2
```
gives these errors on launch:
```
./cmus: Error: couldn't open directory `/usr/local/lib/cmus/ip': No such file or directory
./cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
./cmus: Error: no such option dsp.alsa.device
./cmus: Error: no such option dsp.ao.buffer_size
./cmus: Error: no such option dsp.ao.driver
./cmus: Error: no such option dsp.ao.wav_counter
./cmus: Error: no such option dsp.ao.wav_dir
./cmus: Error: no such option input.cdio.cddb_url
./cmus: Error: no such option mixer.alsa.channel
./cmus: Error: no such option mixer.alsa.device
./cmus: Error: no such option mixer.pulse.restore_volume
```
And again, the status bar says:
```Error: selecting output plugin '': no such plugin```
<br>
If you want me to make these separate issues, I can.

**Comment by flyingmutant** [comment]
1. Config "errors" are caused by the fact that you have config files from newer version of cmus. Output plugin one — probably because you have not specified which output plugins to use, please do.
2. Please try to reproduce with the latest git version and provide a backtrace — otherwise it is impossible to debug.
3. You have not built and/or installed input and output plugins — you probably should, before trying to launch cmus.

**Comment by CMahaff** [comment]
Thank you for the response.

I was originally attempting to build it entirely because of Issue 2. I didn't realize that downloading and compiling the git version would cause conflicting configurations with the installed version.

Running a fresh install works fine output wise.

I'll see if I can get the git version running, since toniokroeger claims that 2.6 solves the external hard drive issues. If not, I'll post to that page. I hope a 2.6 stable is on the horizon!

Thanks again.

**Comment by jjzz** [comment]
I changed from debian stable version (2.5) to git version (2.7) today, and met the same error message:
- Opening audio device: couldn't initialize required output plugin

So cmus couldn't play any file. Strangely, it worked well if I login as root.
Finally I tried to delete all my old config files in ~/.cmus, and now it works well.

**Comment by Ruomenger** [comment]
> I changed from debian stable version (2.5) to git version (2.7) today, and met th

Yes, it works for me! Thank you.
