### ISSUE TITLE
awesome widget

### ISSUE THREAD

**Issue by cassiel74** [cmus/cmus#248]
Hi, just tried this morning the awesome widget and it doesn't work here...
awesome v3.4.15 on debian jessie

How can I debug this stuff?

**Comment by flyingmutant** [comment]
Sorry, no idea — Awesome DM widget is not a part of cmus. Maybe try contacting the author of the widget?

**Comment by cassiel74** [comment]
Well, I saw the widget code in the CMUS wiki (here on github) and thought it was your code - I know what CMUS and Awesome are ;-)

BTW the problem is solved. For the record, if you are interested (for the wiki), the widget must be added to the wibox.
