### ISSUE TITLE
build cmus on Linux Mint 17.1 ?

### ISSUE THREAD

**Issue by broomdodger** [cmus/cmus#249]
How can I build cmus on Linux Mint 17.1 ?
There seem to be several dependencies,
I do not how to include them.
Do you have a suggestion or script for apt-get?

**Comment by mist** [comment]
You can use `apt-get build-dep cmus` which installs all needed packages for the repository's version, I always use that to start and check if anything else is needed.

**Comment by broomdodger** [comment]
I tried your suggestion, and got an E: notification.
What should be put into the `source.list`?

sudo apt-get build-dep cmus
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: You must put some 'source' URIs in your sources.list

**Comment by mist** [comment]
In my `/etc/apt/sources.list` I have for every line starting with deb another line starting with deb-src, so e.g.:
```
deb http://ftp.de.debian.org/debian/ testing main contrib non-free
deb-src http://ftp.de.debian.org/debian/ testing main contrib non-free
```
Of course you have other repositories for mint and I don't know if mint has source-repos as well but you should give it a try.
