### ISSUE TITLE
Play count/Last played stats

### ISSUE THREAD

**Issue by hoodakaushal** [cmus/cmus#250]
It would be great if cmus could store the number of times each track is played, and we can then use that information - for sorting in the library view, or defining filters etc. It would also be useful to have a last played time for tracks.

I see that the issue was raised earlier, and is marked closed, but I could find no entry for the play counts in the format string section of the manual.

**Comment by flyingmutant** [comment]
This was implemented in f7712f285492a6fcc23a9b7483f54a6560f18cc8 — and merged a day after 2.6.0 release, so to use this feature, you'll need to compile cmus from git master branch (or wait until the next feature release).

**Comment by mahkoh** [comment]
It looks like this doesn't work with filters so this issue isn't completely resolved.

**Comment by flyingmutant** [comment]
OK — I'll need to check that, thanks. I'll reopen the issue to keep track of it here.

**Comment by mahkoh** [comment]
Looks like I was wrong. I thought you could activate filters by toggling through the ` `, `[*]`, and `[!]` modes. But apparently you first have to go to the mode you want and then press enter to activate it. It works as expected now.

**Comment by flyingmutant** [comment]
Good to know! Closing again :-)
