### ISSUE TITLE
No support for XF86 multimedia keys (play, pause, prev, next)

### ISSUE THREAD

**Issue by brettalcox** [cmus/cmus#252]

**Comment by mahkoh** [comment]
This requires Dbus support and support of the corresponding protocol. Or you can just configure your WM to call the correct cmus-remote commands.

**Comment by nogizhopaboroda** [comment]
I wrote a small plugin for this: https://github.com/nogizhopaboroda/cmus-mediakeys

**Comment by mahkoh** [comment]
Fixed in master.
