### ISSUE TITLE
Play counts not incremented for repeat current

### ISSUE THREAD

**Issue by hoodakaushal** [cmus/cmus#256]
If I set a song to repeat, then the play count only increments by 1, when I turn off the repeat and the next song plays. I don't think this is the intended behavior.

**Comment by flyingmutant** [comment]
Can you please verify that the issue is fixed now?

**Comment by hoodakaushal** [comment]
Yeah.
cmus still increments only after I turn off repeat, but it increments as many times as the song is played. Thanks for the fix!
