### ISSUE TITLE
Don't expand artists when following

### ISSUE THREAD

**Issue by mist** [cmus/cmus#258]
I'd like the feature of cmus following the currently played track but because I'm playing random all my artists are opened. Instead I would love cmus to show the currently played track in the artist overview except when the albums of the artist are already showing.

**Comment by flyingmutant** [comment]
Isn't it what `auto_expand_albums` is for?

**Comment by mist** [comment]
Not really, when I am searching I want the albums to be extended, when just playing it shouldn't open them.

**Comment by flyingmutant** [comment]
Oh, sorry, I confused albums/artists for some reason.

**Comment by mist** [comment]
I'm not getting you now. As far as I understand artists are expanded to their albums.

`auto_expand_albums` is the config key I am talking about, you are right there. Basically I want to split it into three different config keys (or for me just two): `follow`, searching, and `win-sel-cur`.

**Comment by flyingmutant** [comment]
Yeah, this is how I understood it, too — that's why I've labeled it as a «feature request».

I don't understand my previous message now either :-)

**Comment by mist** [comment]
ok :)
I think I'm trying to implement it, how should I name them? auto_expand_album_{follow,search,sel-cur} ?

**Comment by mist** [comment]
Ok, I did something and it is working. Could you have a look at it and tell me if this is a acceptable solution? Then I can create documentation and file a pull request.
https://github.com/mist/cmus/commit/9b5ffa65d759fda8ac4e460cd9d2fa89d46312ed

**Comment by mist** [comment]
I just realized it is not working... I don't know how I tested that yesterday, I guess because it was late.
Now it is working: https://github.com/cmus/cmus/compare/master...mist:auto_expand_albums

**Comment by flyingmutant** [comment]
Haven't tested this yet, but the code looks OK. Maybe no need for separate `tree_sel_track_*` functions?

**Comment by mist** [comment]
You're right, I fixed it.
Another Question is: Should cmus still read the old config key `auto_expand_albums` and use it as initial value for `auto_expand_albums_*` but not save it again? I'm not sure about how hard that would be to implement.

**Comment by flyingmutant** [comment]
I was thinking about it too. My opinion is that while this is a backward compatible change, if the backward compatibility is hard to implement in this case, we are fine with just abandoning it.
