### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by maggick** [cmus/cmus#259]
Hi,
As I said a few weeks ago, I compiled cmus for my cygwin.
It works fine but one feature (at least) is missing:
When you are on view 1, the artist and album should follow the current track.

Can you point me the (probably missing) library that should do that ?

**Comment by mist** [comment]
What is your config option `follow` set to (is there an `F` in the bottom right corner)?

**Comment by maggick** [comment]
@mist is right, THX, my bad.
