### ISSUE TITLE
Title line disappear when terminal is less than 11 lines high

### ISSUE THREAD

**Issue by srang** [cmus/cmus#261]
I've tested this in a standalone terminal session and as split window in a GNU screen session (where I use cmus primarily), but when I resize the window to be 10 lines or less and scroll up or down, the line that was displaying the current track information is replaced with another library listing line. I've checked this in views 1,2,3. I can submit images if this description isn't clear enough

**Comment by mahkoh** [comment]
https://github.com/cmus/cmus/blob/master/ui_curses.c#L1877-L1878

**Comment by srang** [comment]
Neat! Thanks @mahkoh

**Comment by flyingmutant** [comment]
I don't think there is a way for cmus to work in arbitrarily small window, and the limits from the code @mahkoh has posted are sensible enough.

I am closing this issue. Pull requests are always welcome, though.
