### ISSUE TITLE
cmus-sync

### ISSUE THREAD

**Issue by samhal** [cmus/cmus#268]
I'm a big fan of cmus who decided to create a sync extension for cmus. The extension enables you to sync a device of your choice with the cmus playlist. I would appreciate some feedback and suggestions to further improve the extension.

**Comment by flyingmutant** [comment]
Here is the link: https://github.com/samhal/cmus-sync

I think it is a good idea to add your script to cmus' wiki so that people can find it easier.

**Comment by samhal** [comment]
I will do that, thank you!
