### ISSUE TITLE
Themes on Mac

### ISSUE THREAD

**Issue by Bsd0** [cmus/cmus#269]
I'm still unsure how to install themes on Mac, several places have told me that the .theme files should be in /usr/share/cmus/, but I have been unable to navigate to that directory. I'm on OSX 10.9.4, Latest CMUS version. 

Thanks.

**Comment by flyingmutant** [comment]
It is probably `/usr/local/share/cmus/`.

**Comment by Bsd0** [comment]
Thanks!
