### ISSUE TITLE
Alsaequal and High Bit Rates

### ISSUE THREAD

**Issue by NoSuck** [cmus/cmus#273]
Playback of a file of 24-bit resolution at 96000 Hz fails when `dsp.alsa.device` is set to an alsaequal device.  The same device does not fail when using SoX's play, e.g. `export AUDIODEV="equal" ; play Ghosts.flac`, or when the file in cmus is only 16-bit resolution at 44100 Hz.

The error reads "Error: opening audio device: Invalid argument."

Cmus rocks.

> Linux 3.19.3-3-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
> cmus v2.6.0

**Comment by flyingmutant** [comment]
Thanks :-)

Reading the [SoX manual](http://sox.sourceforge.net/sox.html),

> When playing a file with a sample rate that is not supported by the audio output device, SoX will automatically invoke the rate effect to perform the necessary sample rate conversion.

Can this be the case here?

**Comment by NoSuck** [comment]
As crazy as this is going to sound, I don't think that's actually the case, as I have very sensitive ears and can tell the difference almost immediately.

... Hahaha, yeah right.  =]  I did try the following, though, and SoX played the file, with a reported sample rate of 96000 Hz:

`AUDIODEV="equal" ; play "Ghosts.flac" rate 96k`

**Comment by flyingmutant** [comment]
Wow, hard to believe this can be distinguished by ear!

The only thing I can think of is recompiling cmus with `./configure DEBUG=2` from source, and then looking at the content of `~/cmus-debug.txt` file to see which exactly ALSA call has failed.

**Comment by Azeria07** [comment]
I too am receiving the same error "Error:opening audio device: Invalid argument" when trying to play 24 bit FLAC files. Does cmus support high bit depth files?

**Comment by mnogueir** [comment]
Same here. Everything OK with 16 bit FLAC, "Error: opening audio device: Invalid argument" with 24 bit FLAC. Thanks

**Comment by pgaskin** [comment]
I'm going to close this issue since it's quite old, and there have recently been changed in cmus which may fix this issue. Feel free to reopen/comment if you still have this issue on v2.9.1 or later.
