### ISSUE TITLE
Use intelligent setting for replaygain

### ISSUE THREAD

**Issue by mist** [cmus/cmus#275]
I have set my `replaygain` config to `album-preferred` because I often play albums a a whole and I don't want the volume to change then. But when I play random or with a `Play Queue` (with different albums) I would rather have it set to `track-preferred`.

So I'd love to see another option called e.g. `intelligent` which changes between `album-` and `track-preferred` depending on the `shuffle` state, the `aaa_mode` state and the `Play Queue`.

**Comment by nefthy** [comment]
+1. seems like a sensible idea.

**Comment by sdfg2** [comment]
Yes, please, this simple functionality seems to be missing from a lot of players :-(
