### ISSUE TITLE
Meta/alt bind keys

### ISSUE THREAD

**Issue by quite** [cmus/cmus#278]
Would be nice to have us some Meta when binding keys!

**Comment by flyingmutant** [comment]
Related: #252

**Comment by quite** [comment]
Hm, vaguely related, I'd say. Meta-keys goes through the terminal tty. Other keys which pass out-of-band would have to be caught elsewhere, and appropriate actions injected into cmus by way of scripting and pipes or such.

**Comment by flyingmutant** [comment]
Yep, I mean related from the user POV (as in cmus can react to more keys on the keyboard) — technically they may be completely unrelated.

**Comment by nogizhopaboroda** [comment]
There is possibility to handle global keypress with external script and call cmus-remote commands.
I wrote a small plugin for this: https://github.com/nogizhopaboroda/cmus-mediakeys

**Comment by rien333** [comment]
Wait, cmus can't actually do bindings that use <kbd>alt</kbd>? That's weird, I guess, espcially because other terminal programs have no problem with bindings that use <kbd>alt</kbd> (emacs, shells, vim (probably)).

**Comment by ysftaha** [comment]
```shell
bind -f common M-t shell test
```
closed I think.

**Comment by quite** [comment]
Seems like that! I haven't used cmus for years.
