### ISSUE TITLE
cmus without sudo permission OSX

### ISSUE THREAD

**Issue by citin** [cmus/cmus#279]
Hi, is it possible to run cmus without sudo permissions?

![screen shot 2015-04-18 at 00 02 47](https://cloud.githubusercontent.com/assets/7233427/7213711/7a775656-e55e-11e4-8ebd-8e2195166cf2.png)

**Comment by flyingmutant** [comment]
How did you install cmus? Running cmus never requires root privileges.

**Comment by citin** [comment]
"brew install cmus"
I've tried to reinstall cmus and all its dependencies, but stills happens that "cmus: bind: Permission denied".
If i run "sudo cmus" it works perfectly

Add new screenshot, maybe it helps.
Thank's for the answer!

![screen shot 2015-04-18 at 11 10 36](https://cloud.githubusercontent.com/assets/7233427/7215763/9587033a-e5bb-11e4-8751-811c30dec308.png)

**Comment by quite** [comment]
Are you xito? Please also: ls -lL /usr/local/bin/cmus*

**Comment by citin** [comment]
Yes.
Thanks!

![screen shot 2015-04-21 at 15 11 05](https://cloud.githubusercontent.com/assets/7233427/7259294/b8d56e74-e838-11e4-9981-a2af64f57cce.png)

**Comment by citin** [comment]
I've resolved it. The owner of the folder that contains the "socket" was the root. I've changed it and works.
Thanks!

**Comment by bwmarrin** [comment]
I just want to add, that I had this problem just now on Arch Linux and the above comment helped me find the answer.  To find the socket file I did.

```
cd $XDG_RUNTIME_DIR
sudo chown cmus-socket myuser:mygroup
```

I had this problem after I accidentally ran cmus as root.  Apparently doing so changed the permissions on the socket.
