### ISSUE TITLE
(os x / homebrew) cdio plugin not installing

### ISSUE THREAD

**Issue by Lomis** [cmus/cmus#281]
I am currently trying to install cmus with the cdio plugin. The standard homebrew-formula doesn't include libcdio and libcddb as dependencies, so I edited it to include them. That did not lead to the cdio plugin being installed. I then ran configure manually to figure out why. Apparently libcdio isn't found:
```
checking for CDDB_LIBS (pkg-config)... -L/usr/local/Cellar/libcddb/1.3.2/lib -lcddb -liconv 
checking for CDDB_CFLAGS (pkg-config)... -I/usr/local/Cellar/libcddb/1.3.2/include 
checking for CDIO_LIBS (pkg-config)... no
checking for CDIO_LIBS (-lcdio_cdio -lcdio -lm)... no
```

**Comment by flyingmutant** [comment]
So, can you please tell what is the issue? If pkg-config is not configured properly, there is not much cmus can do to find the libraries.

**Comment by Lomis** [comment]
pkg-config seems to locate libcdio alright:
```shell
Dorothea:~ lukas$ pkg-config --libs libcdio
-L/usr/local/Cellar/libcdio/0.93/lib -lcdio -lm -liconv -Wl,-framework,CoreFoundation -Wl,-framework,IOKit -Wl,-framework,DiskArbitration
Dorothea:~ lukas$ pkg-config --cflags libcdio
-I/usr/local/Cellar/libcdio/0.93/include
```
I don't actually know a lot about compiling software though, so maybe this isn't what pkg-config is supposed to return.

**Comment by flyingmutant** [comment]
Thanks -- I'll try to reproduce this once I'll be near my laptop.

**Comment by flyingmutant** [comment]
cmus is looking for `libcdio_cdda`, aka libcdio-paranoia. Homebrew only contains "vanilla" libcdio, so it can not be used to build `cdio` cmus plugin.

Please consider installing libcdio-paranoia from source if you want to build the plugin.
