### ISSUE TITLE
What is the preferred cmus build system?

### ISSUE THREAD

**Issue by fossette** [cmus/cmus#282]
Hello!

On which system are the cmus github files built?  They don't compile as is under FreeBSD 64bit (without the maintainer's beastie dust).  I wish to install the same system in a virtual machine to prevent the addition of any other platform dependant artefact in the cmus source code.

Thanks!
Dominique.

**Comment by flyingmutant** [comment]
Travis CI builds are performed on some version of Ubuntu, I believe. However, cmus should compile on all common unixes without a problem — if it does not, that is a bug. Can you please create an issue on it?

**Comment by fossette** [comment]
Thanks, flyingmutant!  Since it's very popular, I need to install Ubuntu anyway.

Regarding the compilation issue, I'm not sure that it's really a bug, but rather a philosophical issue.  GNU make is feature rich in Linux (gmake), compared to the UNIX make.  Also, these two worlds have a slightly different root directory tree.  Unless everyone agree on some standard RFC recommendation in the future, a standard Makefile is hardly foreseeable.  I myself prefer the simplest oldschool Makefile that rely on default compiler options... option values which should be carefully built into the system.  The more that time passes by, the less I expect this ideal system to ever exist.

PS: Looking forward to hear from Travis CI, or seeing the exact version detailed in the Makefile docs.

Thanks again!
Dominique.

**Comment by flyingmutant** [comment]
Sorry, I don't think I understand what is the issue exactly — cmus does expect GNU make, which I believe is stated in the README. Should I close this one?

**Comment by fossette** [comment]
I'm very sorry, flyingmutant!  I assumed that the file README.md was only needed to create one of the cmus doc files, not to actually build the project.  I come from a world where this file is named README.TXT ... My bad!

Reading this file, I see that ./configure is STRONGLY recommended, which definitely help build the cmus project.  However, there are still issues at runtime, issues that I don't encounter when I build the cmus-2.6.0_1 release created by the talented FreeBSD maintainer.

So, as I mentioned in my original question, I intend to use the same Linux release as the official cmus maintainer to prevent uploading any unwanted platform dependant artifact into the cmus source code.

Dominique.

**Comment by flyingmutant** [comment]
OK, I am closing this ticket. If you'll encounter any issues with building/using cmus, please feel free to open another one.

**Comment by fossette** [comment]
To close this question with more specific details, I used the current Ubuntu 14.04 LTS, and cmus was built almost as is from the repository.

uname -a
Linux Ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

What I encountered was some required libraries that weren't visible by './configure'.  The associated -dev packages of these libraries need to be installed too.  I used the Ubuntu Software Center to install them.

At runtime, the command 'cmus --plugins' is very usefull to find out if the 'make install' process installed everything that is needed.  If not, go to the './configure' step again and check what is missing, and what more you can install.

On cmus startup, an almost criptic error message may indicate that is output plugin is ''.  For example if you use pulse, type in cmus:
:set output_plugin=pulse

Have fun compiling!
Dominique.
