### ISSUE TITLE
unknown filesystem type: afs

### ISSUE THREAD

**Issue by chrisbgit** [cmus/cmus#284]
cmus can not read openafs filesystem.  lsof | grep cmus gives "unknown file system type: afs"

System is amd64, freebsd 10.1-RELEASE-p10.

**Comment by flyingmutant** [comment]
Sorry, I don't know anything about openafs filesystem, but cmus does not contain any filesystem-specific code — so it is filesystem-agnostic.

What do you mean by `lsof | grep cmus gives "unknown file system type: afs"`?

**Comment by flyingmutant** [comment]
Any updates here?
