### ISSUE TITLE
./configure doesn't work, error "Failed to compile simple program:"

### ISSUE THREAD

**Issue by cesarpichon** [cmus/cmus#287]
I'm not an expert in program compilation (and in english too, sorry) and I think it's for that I can't install cmus. Well, I downloaded the source code, I ran the command `./configure` and I got this : 

I don't understand nothing written here, please someone can help me ? Thank you very much !

![screen shot 2015-05-24 at 15 34 05](https://cloud.githubusercontent.com/assets/5282262/7788040/6707ffec-022a-11e5-8042-6005645f1282.png)

PS : I'm on mac OSX 10.9.1 Mavericks

**Comment by flyingmutant** [comment]
Hm, that's a bit weird!

Do you really want to compile cmus yourself? If you just want to install cmus — I'd suggest using [Homebrew](http://brew.sh/): `brew install cmus` and you are set.

**Comment by cesarpichon** [comment]
It's what I've done, I used Homebrew and that worked ! Thank you for your answer :D
