### ISSUE TITLE
mad.so not recognized, yet present

### ISSUE THREAD

**Issue by tohab** [cmus/cmus#288]
Hi there,
Previously, cmus was playing mp3 files fine. However, I quit it one day, and when I reopened it could not play any .mp3 files. cmus --plugins does not say that it has the mad plugin, however when I check the directory it is looking at mad.so is clearly there. Do you have any idea what the problems could be? I have rebuilt from source and from the mac homebrew several times.

**Comment by flyingmutant** [comment]
Just to make sure — you've uninstalled cmus completely before installing it from the Homebrew? Also, can it be the case that there is something wrong with the libmad that you have?

**Comment by tohab** [comment]
I reinstalled libmad  via homebrew and it seems to be working; thank you!
