### ISSUE TITLE
wind back with <H> is the same as fast forward with <L>

### ISSUE THREAD

**Issue by k0377** [cmus/cmus#289]
Pressing h does the same as pressing l. The only way to wind back is using comma ,

**Comment by flyingmutant** [comment]
It should not be the same — default bindings are definitely different. Please check that your `~/.cmus/autosave` file contains proper bindings.

**Comment by k0377** [comment]
There is no such folder in my home dir. cmus version 2.6.0 on arch

**Comment by flyingmutant** [comment]
Ah, sorry, it should be `$XDG_CONFIG_HOME/cmus/`.

**Comment by k0377** [comment]
Hmm, there is no such env variable on my system. Also my key bindings look fine. I already had this problem back then when I used ubuntu.

```
➜  cmus  pwd
/home/thinkpad/.config/cmus
➜  cmus  printenv | grep XDG
XDG_VTNR=2
XDG_SESSION_ID=c2
XDG_SESSION_DESKTOP=gnome
XDG_MENU_PREFIX=gnome-
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=GNOME
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1000
➜  cmus  cat autosave | grep seek
bind common , seek -1m
bind common . seek +1m
bind common h seek -5
bind common l seek +5
bind common left seek -5
bind common right seek +5
```

**Comment by flyingmutant** [comment]
Well, then I definitely can not reproduce this. I have the same bindings, and they work fine for me. Do you say that they both seek forward for you? What about left/right arrow keys?

**Comment by k0377** [comment]
It is the same issue with arrow keys. The weird thing is, even seek +5 works it will actually seek +20 secs and not only 5.
