### ISSUE TITLE
timer starts at 00:24 seconds counting

### ISSUE THREAD

**Issue by k0377** [cmus/cmus#290]
Another ugly one: On every song I start playing, the timer at the bottom starts at 00:24 seconds to count and not at 00:00 as usual.

**Comment by flyingmutant** [comment]
Ah — this is the duplicate of #224. #289 is probably related to this, too.

Can you please install latest git version of cmus which has ALSA issue fixed and see if it works for you?

**Comment by k0377** [comment]
Thanks mate! This fixed everything for me - including #289! :joy_cat:
