### ISSUE TITLE
Segmentation fault when adding (m4a|aif) files

### ISSUE THREAD

**Issue by socketubs** [cmus/cmus#291]
Hi there,

When I'm trying to had an evil `.m4a` (and `.aif`) file, cmus return segmentation fault.
I have installed cmus with Ubuntu official repository, then I don't have `~/cmus-debug.txt`.

This bug remind me that I have to convert this file to `.ogg` but I'm reporting this bug at the same time.

**Comment by flyingmutant** [comment]
Hello!

Can you please:
- verify that the bug still exists with the latest (git) version of cmus
- if so, launch `gdb cmus` and provide a backtrace of the crash?

**Comment by socketubs** [comment]
Hi @flyingmutant 

Tested with latest git master branch and no bug detected.
This is a free bug for you and sorry for the annoyance.

**Comment by socketubs** [comment]
But latest cmus version on Ubuntu 14.04 seems to have this bug for information.

**Comment by flyingmutant** [comment]
OK, thanks a lot for reporting!
