### ISSUE TITLE
Now playing display out of sync with song

### ISSUE THREAD

**Issue by andrew-w-sherman** [cmus/cmus#293]
Hi, I'm having a slightly weird error, when I play a song, the seeking bar starts at 0:24, but the actual audio begins at the start of the song. If it is playing the last song, it will reach the end and then continue playing for what I assume is another 24 seconds. If it has another song scheduled to play, it will display that it is playing the next song, but not actually finish one audio stream and begin the other until 24 seconds in. This might be hard to reproduce because there's nothing particularly strange about my setup, but I'm running arch, using urxvt for terminal, running alsa, pulseaudio, and I believe mpd.

**Comment by flyingmutant** [comment]
Oh, ALSA strikes again! #224. Please use the latest git version of cmus — everything should be fine.

**Comment by nefthy** [comment]
I think it would be good to make a 2.6.1 release. The seek bug seems to affect quite a few people.

**Comment by flyingmutant** [comment]
Yes, sure — I am thinking about making a new release soon.

**Comment by andrew-w-sherman** [comment]
Darn, my bad. Don't know how I missed that issue, sorry to crowd. Working fine now.
