### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ecardoz** [cmus/cmus#294]
Segmentation fault (core dumped)

Using cmus v2.5.0

Thanks

**Comment by flyingmutant** [comment]
Please don't use v2.5.0 which is very old.

Thanks.

**Comment by flyingmutant** [comment]
Any updates here?

**Comment by johndrinkwater** [comment]
Can reproduce on 2.5.0 (sorry, that is the version that ships in latest Ubuntu), if I add this mp4 video directly, or it is in my ~/music dir. Noticed it behaves the same way on another mp4 in my podcasts, so it might just be that file format, but not crashing would be preferred. If file parsing has changed in 2.7.x, will test that and get back.

lights.toes.{acoustic}.mp4 56MiB https://drive.google.com/file/d/0B29aC-1nN5z6YnhUempPeUFsQWc/view?usp=sharing

**Comment by flyingmutant** [comment]
The file you've attached plays back fine on 2.7.0.

**Comment by johndrinkwater** [comment]
Can confirm, for the two mp4 files I have.
@ecardoz is there a possibility your crash was hitting those formats?

**Comment by flyingmutant** [comment]
Closing this issue.

If anyone will experience a segfault (with 2.6.2+/2.7.0+) — please open a separate one.
