### ISSUE TITLE
Error when search plugins

### ISSUE THREAD

**Issue by brunomacabeusbr** [cmus/cmus#295]
I downloaded the repository, and configured using the command
```./configure CONFIG_MAD=y```

But when running cmus, I get the following error:
```
cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
cmus: Press <enter> to continue.
```
So I can not run mp3

And when using the flag "--plugins" I get the message:
```
cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
```

**Comment by mahkoh** [comment]
Run `sudo make install`.

**Comment by brunomacabeusbr** [comment]
I had already run this command

**Comment by mahkoh** [comment]
Ah, I didn't see that only the output plugins are missing. Normally configure should detect the available libraries, compile the plugins, and install them. Maybe it can't detect any output plugins. Do you have ALSA or pulseaudio installed?

**Comment by brunomacabeusbr** [comment]
Sorry, but I do not know what is "ALSA" and "pulseaudio". So I guess I have not.

**Comment by mahkoh** [comment]
Can you play music with another player?

**Comment by brunomacabeusbr** [comment]
Yes, I can listen to music with the Mint's standard player.

**Comment by mahkoh** [comment]
Then you probably have both ALSA and pulseaudio installed but you are missing the development libraries. Please install `alsa-lib` and run `configure` again.

**Comment by brunomacabeusbr** [comment]
As there was not a package exactly with name ```alsa-lib```, I installed ```libalsaplayer-dev```.
Again I used ```./configure CONFIG_MAD = y``` and ```sudo make install```, but the problem persists.

**Comment by mahkoh** [comment]
Please try `libasound2-dev`.

**Comment by brunomacabeusbr** [comment]
More files were compiled and the error message disappeared:
```macabeus@macabeusacer ~/ApenasMeu/cmus $ cmus --plugins
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  alsa
```

But still I can not listen to MP3.
When I open the cmus, showed the red message in below: ```Error: selecting output plugin ': no such plugin```

**Comment by mahkoh** [comment]
That's because cmus uses pulseaudio by default. Now that we've found the problem you can also install `libpulse-dev` and recompile again. After that everything should work.

**Comment by brunomacabeusbr** [comment]
More files were compiled and appeared a new plugin:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  alsa
```

However, the error message remains the same.

**Comment by mahkoh** [comment]
Please go to the settings view (press 7 inside cmus) and look for the setting called `output_plugin`. It should say `pulse` next to it. If it doesn't say that please edit it by pressing enter. You might have to restart cmus after changing it.

**Comment by brunomacabeusbr** [comment]
Thank you! It is now running smoothly.

**Comment by flyingmutant** [comment]
Great — I'm closing the issue now.
