### ISSUE TITLE
Symlink dupes

### ISSUE THREAD

**Issue by xeverse** [cmus/cmus#298]
I have this kind of hell -- https://img.bi/#/pEBfezB!xZWijgmxu-XAGwyyfw_4wRZQWKIKCQcbup6wCm3q
On top of multiple var format dupes there's symlink dupes as well (can these be filtered out at all?).
No filtering based on hashing?

**Comment by flyingmutant** [comment]
Sorry, cmus does not have any kind of duplicate detection right now.
