### ISSUE TITLE
New Themes, like Gruvbox

### ISSUE THREAD

**Issue by anshulc95** [cmus/cmus#301]
Hey I willing to make a gruvbox themes for cmus. Its a really nice vim theme, its good for eyes and really popular these days. I would love to have it on cmus too. And I am sure many others would love it too. So can I go on making it for you guys? Or anybody else wants to take over/initiate. Or is there already an theme like that which I didn't know, because I searched a lot.

My apologies if this is not the place where I should ask this. New to git :(

**Comment by flyingmutant** [comment]
Current color schemes for cmus can be found here: https://github.com/cmus/cmus/tree/master/data. As you can see, there is no gruvbox one right now.

If you want to make it for cmus — please go ahead, and create a pull request once it is ready!

**Comment by anshulc95** [comment]
Hey, thanks. I've already started working on it.

**Comment by flyingmutant** [comment]
Great! I am closing this issue then.

**Comment by egel** [comment]
I've just made a sample gruvbox theme for cmus https://github.com/egel/cmus-gruvbox. I hope you'll enjoy it as much as I ;)
