### ISSUE TITLE
Link failure when ncurses is built with a separate terminfo library

### ISSUE THREAD

**Issue by jepio** [cmus/cmus#303]
ncurses can be built such that two libraries are created: `libncurses(w).so` and `libtinfo(w).so`. In such environments linking to one of them may not be enough as is the case for me. This manifests itself as a link failure like below:

       HOSTLD     Doc/ttman
       MAN    Doc/cmus.1
       MAN    Doc/cmus-tutorial.7
       MAN    Doc/cmus-remote.1
       LD     cmus
    /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/../../../../x86_64-pc-linux-gnu/bin/ld: ui_curses.o: undefined reference to symbol 'cbreak'
    /lib64/libtinfow.so.5: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:53: recipe for target 'cmus' failed
    make: *** [cmus] Error 1

the full compilation command in my case was:

       gcc -Wl,-O1 -Wl,--as-needed  -o cmus ape.o browser.o buffer.o cache.o 
    cmdline.o cmus.o command_mode.o comment.o channelmap.o convert.lo debug.o 
    discid.o editable.o expr.o filters.o format_print.o gbuf.o glob.o help.o 
    history.o http.o id3.o input.o job.o keys.o keyval.o lib.o load_dir.o locking.o 
    mergesort.o misc.o options.o output.o pcm.o pl.o play_queue.o player.o rbtree.o 
    read_wrapper.o server.o search.o search_mode.o spawn.o tabexp.o tabexp_file.o 
    track.o track_info.o tree.o u_collate.o uchar.o ui_curses.o window.o worker.o 
    xstrjoin.o file.o path.o prog.o xmalloc.o -lpthread -lncursesw  -ldl 
    -Wl,--export-dynamic   -lm 

To work around this it is necessary to look up the libs for ncurses with `pkg-config`. With the following patch this is done (and the way I understand it the fallback is the current behaviour).

https://gist.github.com/jepio/c8835685aa5843df5f21

After the patch everything links fine for me.

**Comment by flyingmutant** [comment]
Can you please verify that it works for you in 87d507d indeed?

**Comment by jepio** [comment]
Indeed it does, thanks!
