### ISSUE TITLE
cmus fails if ~/.config doesn’t exist

### ISSUE THREAD

**Issue by bfontaine** [cmus/cmus#305]
It should create `~/.config` if it doesn’t exist instead of failing.

On OS X, the issue is present with both v2.6.0 and v2.7.0 (I don’t know for the earlier versions). Steps to reproduce:

1. Download either the v2.6.0 or v2.7.0 archive from GitHub, and install it (here I’m using [Homebrew](brew.sh)’s conventions):

        ./configure prefix=/usr/local/Cellar/cmus/2.6.0_1 mandir=/usr/local/Cellar/cmus/2.6.0_1/share/man
        make install

2. Remove or rename `~/.config` if it exists
3. Start cmus: `cmus`

Expected output: `cmus` should start
Actual output:

```
cmus: error: creating directory `/Users/baptiste/.config/cmus': No such file or directory
```

Note that it works if `~/.config` exists but `~/.config/cmus` doesn’t.

**Comment by flyingmutant** [comment]
Can you please double-check that ce7e936 fixes the issue indeed?

**Comment by bfontaine** [comment]
Yes it does, thank you!
