### ISSUE TITLE
cmus is already listening on socket

### ISSUE THREAD

**Issue by superfunkminister** [cmus/cmus#306]
Possibly a noob question but how do you get around the following when you've accidently closed a terminal session and try to reopen cmus?

cmus: cmus is already listening on socket /Users/me/.config/cmus/socket

I've been using top and then kill by PID but seems like there must be a simpler way...

**Comment by flyingmutant** [comment]
I think the simplest way is `killall cmus`.

**Comment by superfunkminister** [comment]
Thanks!

**Comment by ingeniegro** [comment]
I have a similar case, I've rebooted the laptop, checked with ps -aux| grep cmus.
Even used killall cmus. It says no process is found, but when I try to start cmus --listen 0.0.0.0 it gives the error of already listening.

**Comment by crazy-hunter** [comment]
I'm having the same issue.

**Comment by flyingmutant** [comment]
If you ask cmus to use TCP (with `--listen 0.0.0.0` or similar) and do not specify the port, cmus defaults to 3000. Make sure that it is free.

**Comment by eccentricdz** [comment]
sudo kill -9 <PID>

where PID is the process ID for cmus application obtained via 'top' command,

works for me

**Comment by trebiano** [comment]
To find the Process ID (PID) of the cmus running terminal program, just do like this:
ps ax  | grep cmus

then, as eccentricdz suggested:
sudo kill -9 PID

**Comment by rainihall** [comment]
To quit CMus at any time, use the :q command (or press Q followed by Y).

reference : http://www.tuxarena.com/static/cmus_guide.php

**Comment by TunnelThruTime** [comment]
I understand that the reason cmus is doing this is that it creates a file in it's socket directory.
Dos that mean you can go to that directory and delete the file and you'll get results? 
I've done something similar (I know that's vague and i'm sorry since I can't recall the details)
with audacity when it tells you there is another copy of audacity already running

**Comment by grenzionky** [comment]
@trebiano id suggest doing `sudo kill -9 "$(pidof cmus)"`

**Comment by moghaazi** [comment]
> @trebiano id suggest doing `sudo kill -9 "$(pidof cmus)"`

That's the only solution worked for me.

**Comment by nefthy** [comment]
> That's the only solution worked for me.

You can only have one cmus running at any given time. If cmus gets stuck or runs somewhere in a terminal long forgotten, you have to kill it. No way around that.

**Comment by SagarKapasi099** [comment]
I am on mac, there was no ```pidof``` installed.

went inside ```htop``` and killed it manually

Inside ```htop```
searched using ```/cmus```
once selected, ```F9``` ```Enter```

**Comment by zachjensz** [comment]
Even after killing cmus I still have to wait a good 10-20 seconds to be able to run it again. Keeps thinking it's already open. Extremely annoying
