### ISSUE TITLE
(>*w*<) Could you please add more Colors?...

### ISSUE THREAD

**Issue by Penguinox** [cmus/cmus#308]
Ahmmm... maybe this sounds weird ... but could you please add more colors? coz the colors are so limited i can only use Gray,Red,Blue,Yellow,Cyan,Black and Green ... (>T^T<)...  I like this color #63b8ff but i can't use it. (>^w^<) Thanks~ (CMUS is my fav music player!)
![colors](https://cloud.githubusercontent.com/assets/13310077/8739811/4d7e9cd4-2c73-11e5-9690-e5f870c8e30b.png)

**Comment by flyingmutant** [comment]
You can use 256 colors for color schemes — integers from 0 to 255. Take a look at existing [color schemes](https://github.com/cmus/cmus/tree/master/data).
