### ISSUE TITLE
Suggestion : Place extensions in own repos

### ISSUE THREAD

**Issue by SturmDrangAltaar** [cmus/cmus#309]
Ok, so I just ran into a strange problem. I copied over the python based script for track notifications on gnome, but when I copied it, it's white space chars were completely messed up - might be my browser, dunno.
Anyway, my suggestion is to move the extensions [here](https://github.com/cmus/cmus/wiki) to their own repos under cmus, if possible? Would be good for encoding issues like I faced above and also allow the community to contribute.

**Comment by nogizhopaboroda** [comment]
I've created organisation within one repo for my needs, which contains plugins i've found on wiki: https://github.com/cmus-plugins/cmus-base-plugins

@flyingmutant and other admins, we can move this repo to cmus organisation if you want

**Comment by flyingmutant** [comment]
@nogizhopaboroda thanks for putting the plugins together. Let's see if the repo will become popular (and, more importantly, used and updated by plugin authors) — maybe then it will be a good idea to move it under cmus organization.
