### ISSUE TITLE
Installation in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by brokendisplay** [cmus/cmus#310]
Hi, I am having a weird issue with installing cmus. 

I tried installing both dependencies and the cmus package through apt:
<code>sudo apt-get build-dep cmus</code>
<code>sudo apt-get install cmus</code>
When executing, I ran into an error saying that there was no output plugin folder.
I found that <code>/usr/lib/cmus</code> contained the input plugin folder <code>/usr/lib/cmus/ip</code> but no output plugin folder <code>/usr/lib/cmus/op</code>
Trying to resolve the error, I manually created the directory 
<code>sudo mkdir /usr/lib/cmus/op</code>
Afterwards, I ran cmus, and was greeted with this error in the status bar: 
<code>Error: selecting output plugin '': no such plugin</code>

Thinking there was an issue with the Ubuntu package, I uninstalled and decided to build from the package found on [the download page](https://cmus.github.io/#download)
<code>sudo apt-get remove cmus</code>
I built using these commands
<code>./configure; make; sudo make install</code>
This put (what I think is, from Googling) the required plugins into both <code>/usr/lib/cmus/ip</code> and <code>/usr/lib/cmus/op</code>
Running cmus gave me an error, saying there was nothing in <code>/usr/local/bin</code>

Removing the install using <code>sudo make uninstall</code>, I found that <code>/usr/lib/cmus/ip</code> stayed but <code>/usr/lib/cmus/op</code> was removed. I reinstalled and copied <code>/usr/lib/cmus/op</code> contents to a different folder, uninstalled the package, then installed via apt. Because the installation through apt didn't provide me with <code>/usr/lib/cmus/op</code>, I copied the <code>*.so</code> files that the built package provided into <code>/usr/lib/cmus/op</code> and now I can run cmus without issues.

I am not very knowledgeable in building packages and diagnosing errors, but this doesn't seen like an appropriate way of installing cmus. It works, and I'm glad it does, but do you have any insight into what I did wrong to prevent any one method from working and instead requiring the use of both installation methods?

Thank you!

**Comment by flyingmutant** [comment]
After this step: `sudo apt-get install cmus`, if there are no output plugins installed, then it means that Ubuntu package is broken, unfortunately.

However, installing from source should definitely work. Can you please tell me what exactly was wrong here:
> Running cmus gave me an error, saying there was nothing in /usr/local/bin

?

Installing from source by default will place cmus and plugins in subdirectories of `/usr/local/`.

**Comment by brokendisplay** [comment]
This is the result after installing through apt and trying to run cmus ![cmus_apt_install](http://i.imgur.com/9ERTec7.png)

After uninstalling using <code>sudo apt-get remove cmus</code> and <code>sudo make uninstall</code> for the the build source, I also removed all instances of cmus (that I know of) in <code>/usr/lib/cmus</code>, <code>/usr/local/lib/cmus</code>, and <code>/usr/local/bin</code> to try to reproduce the error. The apt-get error is reproducible but I can now build from source and not run into any issues.

With 
> Running cmus gave me an error, saying there was nothing in <code>/usr/local/bin</code>

the issue is that there was no executable script/file available in that directory to open cmus. When it's installed through source, there are two scripts/files in <code>/usr/local/bin</code>, <code>cmus</code> and <code>cmus-remote</code>; neither of those files were there after installing through apt-get.

**Comment by flyingmutant** [comment]
Have you solved the installation problems?

Looking at the screenshot, apt has probably installed binary in `/usr/bin`, but your `cmus` looks to be a symlink to `/usr/local/bin/cmus` for some reason.

**Comment by geek1011** [comment]
Do you still have this issue?

**Comment by pgaskin** [comment]
@nefthy, this issue hasn't had a response for almost 2 years, and it's not a bug in cmus.
