### ISSUE TITLE
ogg/opus tags not recognized

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#313]
I have some ogg/opus files whose tags are not available inside cmus, i.e., they are placed in the `<No Name>` section. The tags are shown when I play the file with mpv.

ogg/opus files are read with ffmpeg so I deleted all other input plugins and the cache and restarted cmus. But once again all but those ogg/opus files did have their tags read properly. This includes some ogg/vorbis files.

~~I'm providing one of the affected files for the purpose of fixing this problem: http://www.mediafire.com/listen/9pl59t1dzzcdj98/Oh_Wonder_-_Landslide.ogg~~

Here is an example: http://www.mediafire.com/listen/uy98p2123ushh45/example.ogg

**Comment by flyingmutant** [comment]
Thanks for the report — I'm on a mini-vacation right now, will try to look into this next week.
