### ISSUE TITLE
fedora: VORBIS_LIBS

### ISSUE THREAD

**Issue by sedrubal** [cmus/cmus#314]
Is it possible to build cmus with vorbis on fedora? I can't find the right vorbis libs.

**Comment by flyingmutant** [comment]
I am not a Fedora user — but does installing `libvorbis-devel` and `libogg-devel` help? (Of course, you'll need to run `./configure` after that).

**Comment by sedrubal** [comment]
Thanks, but I have installed them and running `./configure` or`./configure CONFIG_VORBIS=y CONFIG_TREMOR=y` stops at:

```
checking for VORBIS_LIBS (pkg-config)... no
checking for VORBIS_LIBS (-lvorbisidec -lm)... no
configure failed.
```

Do you know the actual files `configure` is searching for?

**Comment by flyingmutant** [comment]
It does `pkg-config --libs vorbisfile`, and fallbacks to `-lvorbisfile -lvorbis -lm -logg` if that fails (see [here](https://github.com/cmus/cmus/blob/master/configure#L232)).

**Comment by flyingmutant** [comment]
BTW, why do you use `CONFIG_TREMOR=y`? I believe you'd be better off without it.

**Comment by sedrubal** [comment]
oops. I did `CONFIG_TREMOR=y`, because the example did this, too. Without this, it is working... Sorry and thank you ;)
