### ISSUE TITLE
status_display_program command not called when cmus is closed

### ISSUE THREAD

**Issue by DanielRS** [cmus/cmus#316]
Hello,

I'm using the status_display_program option to notify Lemonbar about cmus status. However, how would I notify about cmus being closed?

It would be useful to execute status_display_program command when it happens.

**Comment by flyingmutant** [comment]
Cmus can notify when it is exiting, but how can cmus notify when it is *not yet started*? It seems to me like another important part that would be missing.

Maybe better use something like systemd/launchd/upstart for this kind of stuff?

**Comment by DanielRS** [comment]
@flyingmutant When any display program starts it can use `cmus-remote -Q` for getting initial state, after that, it can rely on status_display_program for further updating.

**Comment by DanielRS** [comment]
Created a [pull-request](https://github.com/cmus/cmus/pull/325) that solves this problem; I don't know if it was the best way to do it tho.

**Comment by flyingmutant** [comment]
Can somebody else comment on this use-case, and how useful the feature would be? As I am not using `status_display_program` it is a bit hard for me to make a good judgement.

**Comment by mahkoh** [comment]
See https://github.com/cmus/cmus/pull/325#issuecomment-249477388
