### ISSUE TITLE
"light" colors not working

### ISSUE THREAD

**Issue by Terablast** [cmus/cmus#317]
When changing colors, anything color that is "light" doesn't work.
Cmus accepts the entry, but doesl not change the color; it keeps the old one.
After a restart, any will "light" colors become black.

Here is a .webm showing the issue, in case I didn't explain myself properly : http://webmup.com/d4ad6/

I'm running cmus v2.7.1, in xfce4-terminal.

**Comment by DanielRS** [comment]
Works fine for me, same cmus version and urxvt 256 colors. Are you sure you configured all your terminal colors? BG, FG, Color 0, Color 1, ..., Color 15?

**Comment by Terablast** [comment]
I think I did, unless there is another way to set them up?
![colors](https://cloud.githubusercontent.com/assets/13744678/9206919/8d9d0854-4038-11e5-9ed8-0e92889e0171.png)

**Comment by Terablast** [comment]
It's a terminal issue, not a problem with cmus, so I'm closing this.
