### ISSUE TITLE
TAK audio playback

### ISSUE THREAD

**Issue by d125q** [cmus/cmus#319]
[TAK is a lossless audio codec](http://wiki.hydrogenaud.io/index.php?title=TAK) and it is supported by FFmpeg. Is there a way to force cmus to load such files? Would it be possible to add support for them in the future?

**Comment by flyingmutant** [comment]
Hi @d125q, sorry for delayed reply — I was on vacation. 

 Can you try to write a PR similar to [this commit](https://github.com/cmus/cmus/commit/2d47150af78e918c77d0129d91d8663b3c9884ee)?

**Comment by d125q** [comment]
Hi. Sorry I have also been away. I will write a PR as soon as I can. Thanks a lot!

**Comment by flyingmutant** [comment]
Fixed in #330.
