### ISSUE TITLE
Can't update the playlist with new songs

### ISSUE THREAD

**Issue by diegoviola** [cmus/cmus#321]
I've added my music with `:add` in cmus but after adding more music to the directory and typing `u` I can't see the new songs added to it.

Do I have to use `:add` again or I'm misunderstanding this `u` feature?

I use cmus v2.7.1 from Arch Linux.

Please help.

**Comment by DanielRS** [comment]
From the manpages:
```
update-cache [-f]
              Update track metadata cache ($XDG_CONFIG_HOME/cmus/cache). Only files with changed modification time or
              removed files are considered.
```
So yeah, `u` only updates music *already added*. You can add more music using the `add` command, I think conflicting songs will not be duplicated.

**Comment by diegoviola** [comment]
Thanks.
