### ISSUE TITLE
slowed playback of high bitrate FLAC with libao backend

### ISSUE THREAD

**Issue by tidux** [cmus/cmus#328]
It looks like this issue was found and fixed earlier with the OSS backend.  The symptoms are identical to the problems I'm experiencing on OS X with libao. 

http://sourceforge.net/p/cmus/mailman/message/28289706/

**Comment by flyingmutant** [comment]
Thanks for reporting the issue here! Have you tried JACK output plugin?

**Comment by tidux** [comment]
I've tried JACK and got the same issues with the same files, so this may be CoreAudio / OS X related.

I installed JACK with `brew install jack`, started it with `jackd -d coreaudio &`, and built cmus from git sources with `./configure CONFIG_AO=n CONFIG_JACK=y && make` to make sure I wasn't defaulting back to libao accidentally.

**Comment by flyingmutant** [comment]
Have you run `:set output_plugin=jack`? libao files from older installs were probably still in the system, as well as previous `output_plugin` setting.

**Comment by Wang-Yue** [comment]
I am building a CoreAudio backend (see https://github.com/Wang-Yue/cmus). It still has a buffer corruption problem which I will fix when I have time. But for CD qualify files I can see a 70% drop of CoreAudio CPU usage already comparing to using libao. 

CoreAudio use a callback api for playback, while cmus uses synchronized call. Making these two work together is a little bit ugly, though.

**Comment by Wang-Yue** [comment]
See pull request #374.

**Comment by Wang-Yue** [comment]
This bug can be closed. I have just tested OpenGoldberg recording. It's >2000kbps, 24bit, 96kHz. When using libao plugin, it cannot play this file smoothly --- actually it sounds very bad. With CoreAudio, it could be played with no problem at all.

**Comment by flyingmutant** [comment]
Thanks for investigating!
