### ISSUE TITLE
Error make rpm for Fedora

### ISSUE THREAD

**Issue by Vascom** [cmus/cmus#329]
We try make good cmus RPM for Fedora. In spec-file we should use macros %configure that contain all parameters and flags. But error ocured https://paste.fedoraproject.org/262941/12718531/

+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info exampledir=/usr/share/doc/cmus/examples CONFIG_ROAR=n CONFIG_ARTS=n CONFIG_SUN=n
unrecognized option `--build=x86_64-redhat-linux-gnu'

Can you make so that the --build option does not cause an error?

**Comment by flyingmutant** [comment]
Why are you passing to `configure` options it does not understand?

**Comment by Vascom** [comment]
Because it option included in macros by default. And it accepted by most others configure scripts.

**Comment by flyingmutant** [comment]
I think package managers should adapt to the software they package, and not the other way around. If the macro does not fit here, do not use it.

**Comment by sedrubal** [comment]
@Vascom I don't know RPM specs well, but you can have a look at [my spec file](https://gist.github.com/sedrubal/5b8e0df42140bc616c1d#file-cmus-spec) (I found the most in the internet). This is working for me but it uses only the default configure params...

**Comment by Vascom** [comment]
@sedrubal Thanks, but in your variant not used optimisation flags for compilator. We use this spec https://github.com/RussianFedora/cmus/blob/master/cmus.spec
