### ISSUE TITLE
Cmus doesn't refresh id3 tags

### ISSUE THREAD

**Issue by AlexK-IL** [cmus/cmus#332]
I have changed a track's id3 tags using mp3info, then attempted to update and delete cache but no matter what it wouldn't recognize the changes in the tags.

Edit:
Problem solved when I used easytag instead, I think it has something to do with the fact that mp3info does not support id3v2 tags editing.

**Comment by oblitum** [comment]
This is happening for me but with easytag.... no idea what tag I need to change anymore.

**Comment by mahkoh** [comment]
Open a new ticket with the required information and provide examples.

**Comment by MettatonEX-CP1A** [comment]
Just type `:update-cache f` and `cmus` will refresh the cache for audio metadata.

**Comment by oblitum** [comment]
My issue was resolved at #697, simply `:update-cache` won't fix it, it's documented there how to fix a tag mess.

**Comment by maxkwallace** [comment]
Thank you all! I don't know if this full sequence is necessary, but clearing my library, then running `:update-cache`, rebooting, running `:update-cache` again, and then re-adding the files fixed the issue. 

I had also been using EasyTAG to correct some ID3 tags.
