### ISSUE TITLE
spectrum analyzer

### ISSUE THREAD

**Issue by sedrubal** [cmus/cmus#336]
Is it possible to provide a spectrum analyzer / music visualization like open cubic player? :smile: 

![ocp](https://cloud.githubusercontent.com/assets/5571650/10025637/7276e09a-615d-11e5-8ab3-ecb9eb67aedc.png)

**Comment by luzpaz** [comment]
:+1:

**Comment by sedrubal** [comment]
Another project is [cava](https://github.com/karlstav/cava).

Maybe one can steal code from them :P

**Comment by da-edra** [comment]
That would make it perfect.

**Comment by pgaskin** [comment]
Duplicate of #112.
