### ISSUE TITLE
terminal title setting doesn't work (tmux under cygwin)

### ISSUE THREAD

**Issue by unic0rn** [cmus/cmus#340]
the title says it all. i guess it's a matter of escape codes missing, i'm not entirely sure though how those can be specified in the format string - if at all.

cmus 2.7.1 built from source, tmux/mintty/cygwin, but i have a feeling same issue may exist under different terminal emulators under linux, perhaps under both tmux and gnu screen. for the record, print -n "\eksome text\e\" under zsh (running under tmux) works properly.

keep up the great job!

**Comment by pgaskin** [comment]
The actual title is set using terminfo capabilities and falling back to some hardcoded defaults. As such, ensure your TERM env var is being set, and that ncurses is configured correctly and supports your terminal emulator.

https://github.com/cmus/cmus/blob/a92a0424ebbc9117ed1592fdd346d64c87af5f5a/ui_curses.c#L2392-L2423
