### ISSUE TITLE
shuffle/play from multiple genres

### ISSUE THREAD

**Issue by jonasjacek** [cmus/cmus#346]
Hi everyone, 

I'd love to know how I can play/shuffle music from multiple genres? So far I use the fiter, to filter for a certain genre. E.g.:

`:filter genre="jazz"`

I've tried several alterations to achieve a multi-genre selection without success. E.g.:

`:filter genre="jazz,pop"`

Is there a solution to my problem? 
If not, I want to file a feature request...

**Comment by jayay** [comment]
You could type

```
:filter genre="jazz"|genre="pop"
```

The pipe is the OR operator, AND represented by an `&`.

**Comment by jonasjacek** [comment]
Hey Jayjay, 

thank you for your answer and clarification on the possible operators. 
Works great.

**Comment by jayay** [comment]
@jonasjacek you're welcome!
