### ISSUE TITLE
Year and time columns are offset

### ISSUE THREAD

**Issue by Sclarki** [cmus/cmus#350]
![screenshot_sun-oct-25_01-06-25-cdt-2015](https://cloud.githubusercontent.com/assets/8389374/10752143/89631172-7c54-11e5-9ef8-f3e5e2bea665.png)

Reproducible doing the following:

* Make any blank audio file with Audacity (or any editor, I suppose)
* Name it to (for example) ```プÿリペÿイドÿドÿリンク``` in the Title field (probably the filename, too; not sure)
* [optional] add other arbitrary values; year, track number

*If I just rename it to ```プリペイドドリンク```, it's fine.*

Those `ÿ` show up in the metadata (i.e., ```ffmpeg -i $filename```) and when using ```ls```.  Otherwise, they are invisible in Cmus' library list. Additionally, they turn into triplets of diamond unicode boxes if I resize the terminal window while outside of Cmus; Vim is the exception at the moment.

I can provide the original FLACs, if necessary.

This is all ran from a locally compiled tarball (v2.7.1 stable; have also tried with the most recent repo pull as of 27 Oct.) on Ubuntu 14.04.3 LTS.

*Small note*: I do have ```libncurses5[-dev]``` and ```libncursesw5[-dev]```. Just mentioning this since it might be similar to bugs #188 and #198.

**Comment by flyingmutant** [comment]
If you make an empty file named `プÿリペÿイドÿドÿリンク.mp3`, do you see it in the browser view with all the symbols?
<img width="397" alt="2015-10-28 12 47 09" src="https://cloud.githubusercontent.com/assets/73059/10784977/0a940f44-7d72-11e5-93d3-29726fe97504.png">

**Comment by Sclarki** [comment]
Yes, the symbols are still there.

**Comment by flyingmutant** [comment]
But for some reason if they are in the title tag, they are missing in the tree view (like in your screenshot above), right?

**Comment by mahkoh** [comment]
U+309A ( ゚ ) doesn't show up in @flyingmutant's image. 

プ can be written as U+30d5 U+309a or U+30d7. In the text you posted it's in the form with two codepoints which form a so called grapheme cluster. Grapheme clusters are the smallest user-visible text unit and programs have to be aware of the [rules](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) to handle those clusters properly.

I find it quite likely that, at some point, an algorithm fails to properly combine the two codepoints and the U+309a messes with the subsequent ÿ. Try to write the tags in the single codepoint form:

プÿリペÿイドÿドÿリンク

**Comment by mahkoh** [comment]
Also note that this problem is not restricted to the terminal or cmus. Audacity fails to display the two-codepoint form properly on my system.

![2015-10-28-165719_345x24_scrot](https://cloud.githubusercontent.com/assets/1882250/10794412/0cdc6a76-7d95-11e5-9e22-149640d30a61.png)

**Comment by Sclarki** [comment]
> U+309A ( ゚ ) doesn't show up in @flyingmutant's image. 

Ohh, I see that. I probably wouldn't have noticed. Yeah, it's missing from both browser and library views. Still shows up in the aforementioned programs, though.

Using the single codepoint version fixes the alignment issue for me, and it's showing the extra ` ゚ `  in cmus like it does everywhere else.

Since this doesn't seem to be cmus-specific, I'm gonna rename and tag the ones that are showing problems.
