### ISSUE TITLE
format_treewin_artist does not work with other tags

### ISSUE THREAD

**Issue by tsurezuregusa** [cmus/cmus#351]
Setting format_treewin_artist to %{composer} will show all composers in the tree as the same.

![screenshot 2015-10-28 at 10 38 06 pm](https://cloud.githubusercontent.com/assets/589440/10808699/b05d34a8-7dc4-11e5-8c96-ffb0aec07af7.png)

![screenshot 2015-10-28 at 10 38 38 pm](https://cloud.githubusercontent.com/assets/589440/10808700/b275cc5a-7dc4-11e5-8fcf-e581aa793c4c.png)

When the composers are not expanded, it does not even show the correct composer for the selected set of tracks.

![screenshot 2015-10-28 at 10 35 18 pm](https://cloud.githubusercontent.com/assets/589440/10808716/ca62b3be-7dc4-11e5-958e-c04b6ae71660.png)

I also tried to set it a few other tags that may not make sense, and the result was the same.

All other settings as default in cmus v2.7.0-19-gc5a9a78

**Comment by flyingmutant** [comment]
Thanks a lot for the detailed bug report.

Unfortunately, right now cmus' tree view is hard-coded to group by artist/album; changing the format string does not change this grouping.

Would is still be useful for you to have access to e.g. `%{composer}` in this format string? It can easily be done; just note that it will not change the grouping.

**Comment by tsurezuregusa** [comment]
Thanks for the quick reply!

I see. Despite that "Artist / Album" was hardcoded, I mistakenly assumed that taking a format string it would allow any of those listed. I can't imagine why having it display composer without changing the grouping would be useful. 

Being able to set the tree to "Composer / Album" would be a big help for managing a collection of classical music. Being able to set composer as a sort key would also be very nice, along with other tags that can be displayed but not sorted by.

Quod Libet is the only player for *nix that sufficiently supports tags for classical music. It would be nice to have cmus as an elegant alternative, since it actually recognizes them.
