### ISSUE TITLE
Change Artist/ Album to Album only view in tree mode

### ISSUE THREAD

**Issue by Szero** [cmus/cmus#355]
I have many songs that were crated by various artists so when I pick some artist, I get only part of album in track tab. Is it possible to set cmus so I only have albums in Artist/ Album tab, in which way I will have full albums lists in Track tab? ![pic_related](http://i.imgur.com/2aQEjIk.png)

**Comment by flyingmutant** [comment]
You should specify the «album artist» (TPE2 for mp3) tag for all of your tracks. Then the tracks will be grouped and displayed properly.

**Comment by Szero** [comment]
Yup that did the work, thank you very much.
