### ISSUE TITLE
Can't fix Error: selecting output plugin  on Fedora 23

### ISSUE THREAD

**Issue by andreshazard** [cmus/cmus#356]
I know that has been reported and resolved before. However I can't solved following those steps. 
When I open cmus I get : Error: selecting output plugin '': no such plugin

cmus --plugins 

```
Input Plugins: /home/andreshazard/cmus/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /home/andreshazard/cmus/lib/cmus/op
  oss

```

I have installed alsa-lib-devel and libpulse-devel and sudo make install and configure again with no success, I'm able to reproduce songs with others music players. 

I recently switch to Fedora and it will be shame to lose cmus because I really love it.

**Comment by flyingmutant** [comment]
Can you try `:set output_plugin=oss`?

**Comment by flyingmutant** [comment]
And you probably want some input plugins too – so try to install -devel packages for *all* dependencies found [here](https://cmus.github.io/#development); then run
```sh
./configure
make
sudo make install
```
again. If any of these commands fail – please post the output here.

**Comment by region51** [comment]
*@andreshazard I use Fedora 23 and I have no problems with cmus , try my package*
*https://github.com/RussianFedora/cmus/blob/master/cmus.spec*
*http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/updates/23/x86_64/*

**Comment by andreshazard** [comment]
Thanks guys. 
I installed all packages from your cmus.spec @region51 
After that it was still not working but I notice that cmus was looking for the plugins on the wrong folder : 

/home/andreshazard/cmus/lib/cmus/

Is my home so I guess I did something wrong on the process. 

The plugins were install on /usr/local/lib/cmus/

I didn't know how to change the plugins folder so I just copy everything from /usr/local/lib/cmus/ to my home /home/andreshazard/cmus/lib/cmus/ and it worked. 

Thanks a lot!
