### ISSUE TITLE
libFLAC.so: missing symbol?

### ISSUE THREAD

**Issue by wsgy** [cmus/cmus#363]
libFLAC.so: missing symbol
built flac from source and moved libFLAC.so to /usr/lib/cmus/ip and I get the same error for "missing symbol" everytime

Is it a known issue?

**Comment by flyingmutant** [comment]
Why would you move libFLAC.so to /usr/lib/cmus/ip? libFLAC.so is part of FLAC library, you should not move it anywhere.

Can you post detailed description of the issue you are having?
