### ISSUE TITLE
Terminal emulation

### ISSUE THREAD

**Issue by PeeDee** [cmus/cmus#364]
What terminal should we be emulating for proper operation? When I'm using an ssh session to run cmus via a terminal the formatting (particularly the first column) is unpredictable and the cursor loses its place and gradually leaves cruft all over the screen. I use ctrl-L a lot to clean it up again.

Are we xterm-256color? vt100? vt102? ANSI?
Other options:
 Delete sends ctrl-H?
Escape non ASCII with ctrl-V?
Paste newlines as carriage returns?

**Comment by flyingmutant** [comment]
I am usually using xterm-256color and am not aware of any issues. What theme are you using? I think some of them may assume xterm-256color.

**Comment by PeeDee** [comment]
I'm using whatever theme is on the standard apt-get install. I'm now using the xterm-256color, and have stopped fussing with the other settings. There is still the odd stranded character when I'm scrolling or changing screens, but it seems to have settled down.

Very happy with all aspects, as it lets me run a remote media player without vnc.
