### ISSUE TITLE
Error: Couldn't get file information for

### ISSUE THREAD

**Issue by galinkyuchukov** [cmus/cmus#367]
Hello

i am trying to play mp3 file and i get:

"Error: Couldn't get file information for" 

Some mp3 i am able to play and for other i get this error.

Can you suggest a solution?

**Comment by flyingmutant** [comment]
Do other music players play these files fine?

**Comment by CloudyChris** [comment]
Hi there, I've got the same problem. Mainly, I just updated to Fedora 24 through fedup and it uninstalled cmus due to a problem. I installed it from git and it does not play anything... when it did just fine on Fedora 23 a few hours ago.

**Comment by mahkoh** [comment]
@CloudyChris Please provide a file that has this problem.

**Comment by CloudyChris** [comment]
@mahkoh I have Arch now, cmus works perfectly... I do suppose the error was due to a fucked up installation of cmus in fedora... I could not play any mp3 file at all, so ... :))
