### ISSUE TITLE
Is it possible to use CMUS with a USB DAC?Any configurations required for that?

### ISSUE THREAD

**Issue by droidekas** [cmus/cmus#372]
Using OSX btw

**Comment by flyingmutant** [comment]
I have no experience with that, but maybe you can try to configure JACK to use your USB DAC for output, and use jack plugin in cmus?

**Comment by droidekas** [comment]
I currently face the issue mentioned in #345,so once I figure that out,I can try what you suggest.Shall update accordingly .

**Comment by nefthy** [comment]
AFAIK jack uses core audio on OSX to talk to the hardware. If your Hardware runs with core audio you should be able to run cmus with the usual output plugin for OSX. 

The jack ouput plugin will also do, but jack is kind of overkill if you don't already have it running anyway.

**Comment by Wang-Yue** [comment]
I can quickly come up a patch which use libao's device selection to solve this before christmas. Let me know if you'd like to incorporate my code.

**Comment by flyingmutant** [comment]
@Wang-Yue sure, that'd be great. I assume you will add a configuration option for libao's device selection?

**Comment by droidekas** [comment]
So i tried with jack,but Jack has a lot of issues with el capitan . And a libao solution would be brilliant. @flyingmutant  please modify the issue if needed and close as needed.My issue is solved, albeit not satisfactorily

**Comment by Wang-Yue** [comment]
See PR #373.

**Comment by flyingmutant** [comment]
@droidekas — can you please test the #373?

**Comment by Wang-Yue** [comment]
@droidekas please keep in mind that 
- You need to set your device interface name exactly the same to the one listed in your system sound preference. It is case sensitive. 
- cmus currently does not support plug/play. So when you attach/detach your sound interface or chang this setting when playing a track, it won't automatically switch to the new interface. You have to stop and play again (which triggers the op_open function) to make change into effect.

**Comment by droidekas** [comment]
Thanks @Wang-Yue .
@flyingmutant ,it works brilliantly.
Closing the issue since it is solved

**Comment by Wang-Yue** [comment]
See pull request #374 for a native Core Audio plugin.
