### ISSUE TITLE
flac plugin extends 24bit audio to 32bit

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#379]
When playing the Open Goldberg Variations, the flac seems to have the wrong bits (24 instead of 32 bits).

Other players (such as VOX) could correctly identify the bits.

file_changed: file: /Users/wangyue/Audio/Kimiko Ishizaka/Kimiko Ishizaka - J.S. Bach- -Open- Goldberg Variations, BWV 988 (Piano) - 12 Variatio 11 a 2 Clav..flac
metadata_cb: something else
metadata_cb: VORBISCOMMENT
metadata_cb: something else
tell_cb: 
flac_open: sr: 96000, ch: 2, bits: 32

**Comment by Wang-Yue** [comment]
Oh, If you haven't heard about Open Goldberg project, yet, those files are public domain, and could be download at http://www.opengoldbergvariations.org/

**Comment by Wang-Yue** [comment]
Oh, just occurred to me that flac.c will extend anything 24 bits to 32 bits. Is there any reason doing that? 

Since I am trying to implement device automatic bit depth switch, the extra 8 bits extension would be a problem for this feature. Since many good DACs support up to 24 bits, and it's better to set them to 24 bit rather than let them silently fail and remain at what they were.

Keeping at 24 bit also saves much more data copy.

**Comment by flyingmutant** [comment]
@Wang-Yue, can you please tell why you have closed this issue?

**Comment by Wang-Yue** [comment]
@flyingmutant Since it's not a bug. adding a few 0's to the 24bit signal and make it a 32bit signal does nothing wrong. It's just not necessary and efficient, though. (Probably some output plugins cannot handle 24 bits? I am not very familiar Linux audio except Android's stack.)

**Comment by Wang-Yue** [comment]
I know the reason why the original authors do that --- he relies on GNU's bswap_32/16 for endianness conversion. so he extend it here https://github.com/cmus/cmus/blob/master/flac.c#L278. If he does not extend the bits, he has to implement https://github.com/cmus/cmus/blob/2bfc4624ddc8961b8d1b892fb5236b874cfdfb0d/utils.h#L216 for the 24 bit. 

So instead of doing a 24bit endianness conversion macro, he just extends the bits... 

An easy fix to this is we can add 8 bits behind the 24 bit, and do the 32 bit conversion, and strip the 8 added 0s. So the format will remain intact.

**Comment by Wang-Yue** [comment]
PR in https://github.com/cmus/cmus/pull/526

still has a bug in seek though.

**Comment by flyingmutant** [comment]
Should this be closed, maybe with separate issue opened about seek?
