### ISSUE TITLE
Dose cmus support mkv ?

### ISSUE THREAD

**Issue by wenerme** [cmus/cmus#380]
Some music download from y2b is mkv, dow mkv support this ? or need other options ?like

```
--with-ffmpeg
	Build with ffmpeg support
--with-jack
	Build with jack support
--with-opusfile
	Build with opusfile support
```

**Comment by Wang-Yue** [comment]
mkv is just a container. You need to build ffmpeg first, and make sure you have flags enabled to support the audio and video format in that container. Then, you need to build cmus with ffmpeg support. 

There's chance that your file may be played without problem. For a couple of files cmus would just crash.

**Comment by wenerme** [comment]
Already reinstall with `--with-ffmpeg`, but cmus will filter mkv out.

**Comment by Wang-Yue** [comment]
As i said you need to build ffmpeg first with proper flags.

**Comment by wenerme** [comment]
```
brew reinstall ffmpeg --with-x265 --with-webp --with-tools --with-snappy --with-libvpx --with-libass --with-freetype --with-fontconfig --with-faac --with-ffplay --with-libvorbis --with-theora --with-openssl
brew reinstall cmus --with-ffmpeg
```
with no luck.

Maybe cmus just filter out the mkv file.

**Comment by Wang-Yue** [comment]
again, as I said, 
> mkv is just a container.
it's not a media encoding format.
You need first try to see if ffmpeg can read your file at the first place.

**Comment by mahkoh** [comment]
cmus doesn't support mkv. Add mkv somewhere around [here](https://github.com/cmus/cmus/blob/master/ffmpeg.c#L643) to add mkv support.
