### ISSUE TITLE
ape file with a cue sheet may start a few ms after the index

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#381]
For ripped cd converted to ape+cue, the track start position may be a few ms after the indexed time in the cue. It will also end a few ms after the indexed time. And the two times are slightly different, which result 
  - track do not start at the right position
  - when playing one by one, there will be a few ms overlap frame being played

Flac plugin does not have this problem. I'm not familiar with how ffmpeg deal with seeking but that may cause the bug. 

VOX, Cog, MPD all get this right. So definitely a cmus bug.

**Comment by Wang-Yue** [comment]
Oh, forgot to mention that VOX, Cog and mpd all get this correct.

**Comment by mahkoh** [comment]
Is this still happening?

**Comment by Wang-Yue** [comment]
I don't have the file in question now as I converted all files to flac. 
I believe this has something to do with ffmpeg rather than the cue library.  

You can mark it as not reproducable by now. if I could find a way to reproduce I'll reopen the bug.

**Comment by Wang-Yue** [comment]
Now flac with the new cue plugin will start a few ms before the index. 

Testing Glenn Gould's Goldberg Variation (https://www.amazon.com/Glenn-Gould-Complete-Goldberg-Variations/dp/B00006FI7C)

Disc 2. track 30, 31 show the behavior. 

VOX shows the correct behavior with same cue and flac. 

```
  TRACK 30 AUDIO
    TITLE "Bach: Goldberg Variations - Variation 29"
    PERFORMER "Glenn Gould"
    INDEX 01 44:57:45
  TRACK 31 AUDIO
    TITLE "Bach: Goldberg Variations - Variation 30"
    PERFORMER "Glenn Gould"
    INDEX 01 45:59:37
```

**Comment by Wang-Yue** [comment]
Please reopen.
