### ISSUE TITLE
sort by artist is broken

### ISSUE THREAD

**Issue by Silver-D** [cmus/cmus#387]
In 2.7.1 release, artists were sorted correctly from A to Z.

I just pulled the git and sort by artist starts for me at I, and after Z, it wraps around to A until it reaches the point from where the playlist sort started, at I.

I deleted cache and lib and pl to no avail.
Reinstalled 2.7.1 and sorting by artist is fine.

**Comment by flyingmutant** [comment]
Thanks for reporting the issue! Can you please post a screenshot illustrating it?

**Comment by Silver-D** [comment]
I changed this in track_info.c to fix it, as per 2.7.1 release:

 case SORT_BITRATE:
                        res = getentry(a, key, long) - getentry(b, key, long);
                        break;
                **default**:
                        av = getentry(a, key, const char \*);
                        bv = getentry(b, key, const char \*);
                        res = **strcmp0(av, bv)**;
                        break;
                }

the function strcmp0() works correctly , as opposed to strnatcmp() in the newer patches.
This isn't limited to just sort by artist. Any text, even only by 'album', didn't start with A and wrapped around to A somewhere in the middle.

I'm attaching my lib.pl which was generated by the new releases with strnatcmp() in effect.
Note that I do not have any sort id3 tags set. This list was generated with sort by 'artist' only. No smart sorting or anything was on.

[lib.txt](https://github.com/cmus/cmus/files/103672/lib.txt)

**Comment by flyingmutant** [comment]
OK, so it looks like fc3490d6e251cd38be096f7d56047ca73ac73361 is at fault here.

**Comment by jayay** [comment]
@Silver-D what's your compiler and the output of `locale`?

@flyingmutant does working with `unsigned char` make sense here?

**Comment by Silver-D** [comment]
[Alex-MBP:~]$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
[Alex-MBP:~]$ clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

**Comment by mahkoh** [comment]
Not only does this not sort correctly, it also cause segfaults. strnatcmp cannot work because it operates on collkey_X which don't look like natural strings. This can be fixed by removing the collkey_ prefixes here:

```c
#define SORT_ARTIST        	offsetof(struct track_info, collkey_artist)
#define SORT_ALBUM         	offsetof(struct track_info, collkey_album)
#define SORT_TITLE         	offsetof(struct track_info, collkey_title)
```

but then it doesn't sort non-ascii tracks properly. I think the patch that added strnatcmp should simply be reverted for now especially since it can cause segfaults.

**Comment by flyingmutant** [comment]
Yeah, looks like the patch is not master-ready yet. I've reverted it for now, and am closing this.

**Comment by flyingmutant** [comment]
@mahkoh , I do wonder — how does it cause segfaults? Code looks reasonable to me.

**Comment by mahkoh** [comment]
@flyingmutant The segfault does not happen inside the sort function but inside the rbtree implementation at program exit.

```c
ASAN:SIGSEGV
=================================================================
==30492==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000563b5e bp 0x7ffe25d88190 sp 0x7ffe25d88000 T0)
    #0 0x563b5d in rb_erase /home/julian/c/cmus/rbtree.c:231:24
    #1 0x57c471 in remove_track /home/julian/c/cmus/tree.c:1182:2
    #2 0x57c06c in tree_remove /home/julian/c/cmus/tree.c:1193:2
    #3 0x54833d in free_lib_track /home/julian/c/cmus/lib.c:317:2
    #4 0x50f1f5 in editable_remove_track /home/julian/c/cmus/editable.c:103:2
    #5 0x5105f4 in editable_clear /home/julian/c/cmus/editable.c:296:3
    #6 0x4f3b80 in view_clear /home/julian/c/cmus/command_mode.c:75:3
    #7 0x50694a in commands_exit /home/julian/c/cmus/command_mode.c:3117:2
    #8 0x59015f in exit_all /home/julian/c/cmus/ui_curses.c:2437:2
    #9 0x58dd28 in main /home/julian/c/cmus/ui_curses.c:2541:2
    #10 0x7f618534360f in __libc_start_main (/usr/lib/libc.so.6+0x2060f)
    #11 0x421958 in _start (/usr/local/bin/cmus+0x421958)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/julian/c/cmus/rbtree.c:231:24 in rb_erase
==30492==ABORTING
```

It's probably a bug elsewhere that is triggered by the result of strnatcmp not agreeing with some implicit assumption made elsewher.

**Comment by flyingmutant** [comment]
@mahkoh I see, thanks for the explanation.
