### ISSUE TITLE
play count not shown for some tracks

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#392]
I have some tracks whose metadata cannot be read by cmus for some reason. Additionally, cmus doesn't show the play count of these tracks. I don't know how the play count feature is implemented but maybe this is a bug. See the attached screenshot.

![2016-02-03-180807_599x256_scrot](https://cloud.githubusercontent.com/assets/1882250/12790213/7cebb7a0-caa1-11e5-9b38-5f3d06baf998.png)

cc @dagon666

**Comment by jayay** [comment]
I don't know why the function is being used so often, but if you change the content of function [track_info_has_tag](https://github.com/cmus/cmus/blob/bce61cbb21c9788a179b1727fc7c173dcadcb694/track_info.c#L120-L123) into `return !!ti;` everything works fine, but I don't think that's how it's supposed to be. The play count is always being recorded, even if it's not shown.

If `track_info_has_tag` returns 0 for the current `ti` the alternate output is chosen, which does not display the meta data read by the input plugin but the file name and nothing else instead. But why not?

**Comment by jayay** [comment]
Update: didn't see there is a format for that. Did you try `:set altformat_trackwin= %f%= %d %X`?

**Comment by mahkoh** [comment]
My altformat was missing %X.
