### ISSUE TITLE
everyday im shuffling

### ISSUE THREAD

**Issue by manu09** [cmus/cmus#400]
I turned off [S]huffle mode but when I press `z` or `b` it is still going on, even if the status bar won't show any `S`, no matter what I try (play all/album/artist from sorted library).

```
cmus v2.7.0-35-g1983372

```

**Comment by flyingmutant** [comment]
Can you try with current master, 591241c964e61a1bb6f6dd03f41b9f380c3099c6? I can't reproduce the issue.

**Comment by mahkoh** [comment]
Closing due to lack of feedback.
