### ISSUE TITLE
Custom library view (suggestion)

### ISSUE THREAD

**Issue by netoeuler** [cmus/cmus#401]
Instead "Artist / Album" can be created a third screen (that will access it when press Tab) with the options:
 [Artist / Album] [Year / Artist] [Album]

Artist / Album: remains unchanged
Album: only show the albums (can be useful for VA's and splits)
Year / Artist: similar to 'Artist / Album' but with year and a submenu with the artists in the year selected.

I use the 'find' command to search for music in the situation of this suggestions. Ex: when I want to see only albums for the year 2015 I open a new terminal and use 'find -name "(2015)" ' and seek the results manually in the cmus.

I'm C developer and I always think in do this but recently time is an issue to me, mainly to study the code. Is it ok if I send a PR with this?

**Comment by flyingmutant** [comment]
Hi @netoeuler, sorry for delayed reply on this. I am not sure I understand what interface changes do you propose.

As for `find`, are you familiar with filters and live-filters in cmus?

**Comment by netoeuler** [comment]
Don't worry, I really didn't explain right. Let me draw:

The main screen today:
![01](https://cloud.githubusercontent.com/assets/3870633/13372944/2a387864-dd38-11e5-9f28-55f0795eb690.png)

I try to explain to let it like this:
![screenshot from 2016-02-27 09 49 55](https://cloud.githubusercontent.com/assets/3870633/13372946/5735ace2-dd38-11e5-8f83-5ab90456f663.png)
![screenshot from 2016-02-27 09 53 02](https://cloud.githubusercontent.com/assets/3870633/13372947/57361d94-dd38-11e5-8b67-c7343263c7b9.png)
![screenshot from 2016-02-27 09 53 32](https://cloud.githubusercontent.com/assets/3870633/13372948/573f8bb8-dd38-11e5-8d44-2e14ad64a4e5.png)

Where the top left menu can be acessed pressing Tab. 
But thinking better the 'Album' could be a bad idea, the case that I explain with the Album the can done with multiple playlists but I don't know if Cmus allow to create multiple playlits.

Could you understand better now?
I'm not familiar with live-filter, with it can do my suggestion without new code implementation?

**Comment by flyingmutant** [comment]
Please read the [manual](https://github.com/cmus/cmus/blob/master/Doc/cmus.txt) (`man cmus`) regarding what live-filter does. It is a powerful feature which can do (almost) what you want.

As for your proposal – it will require major restructuring of cmus' internals. I do not think these interface changes warrant that.

P.S. Tab key is already used in cmus, as well.

**Comment by netoeuler** [comment]
Hmm! I did the tests with the filters and they all attented my case.
This player is more powerfull than I think. :)
