### ISSUE TITLE
<del> in browser view

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#41]
In the browser view, <del> allows the user to unlink files in the file system. This is undocumented and possibly harmful. I do not expect my music player to edit any files apart from its configuration. I suggest removing this function.

**Comment by diegodorado** [comment]
It is absolutely useful. it is one of my mayor complains of other music player. why couldnt i delete a track from the disk if i am not planing to listen to it anymore? or, why should a go through the file explorer to find and delete a track? it is while i am listening to it that i can make that decision.

as @flyingmutant  says,  documenting it or not binding it by default would be fine... but do not remove this feature please.
