### ISSUE TITLE
Scan directory + add to library on startup

### ISSUE THREAD

**Issue by jrcii** [cmus/cmus#410]
Hi,

Right now to update cmus' library with my new tracks I have to press 5, go to a directory, then press "a" to add new entries from my music directory. I would like to do this automatically on startup, either by launching cmus with a script that adds arguments or via a config file. However I can find neither a config file for cmus nor arguments that would make this possible. Is there a way or am I out of luck? Thanks!

**Comment by flyingmutant** [comment]
Right now there is no way to add files automatically on startup. However, you can use `cmus-remote` to re-add your music directory.

P.S. Sorry for delayed reply.

**Comment by jrcii** [comment]
Thanks!

On Mon, Mar 14, 2016 at 3:58 PM, Gregory Petrosyan <notifications@github.com
