### ISSUE TITLE
"configure failed" after ./configure prefix=$HOME/cmus

### ISSUE THREAD

**Issue by worsedoughnut** [cmus/cmus#411]
LIke the title said. Trying to install from the git clone on Debian 64bit VM in virtualbox on Windows 10 64bit.

Not sure what else to try to be honest since `make install` fails if I just ignore the issue.

**Comment by worsedoughnut** [comment]
I'm an idiot, never did `apt-get build-dep cmus`, but to be fair, it doesnt list that on this page: https://cmus.github.io/#download

**Comment by Krishna16** [comment]
> I'm an idiot, never did `apt-get build-dep cmus`, but to be fair, it doesnt list that on this page: https://cmus.github.io/#download

How did you do it? I'm running into "You must put some 'source' URIs in your sources.list" error. Can you help me out here??

**Comment by geek1011** [comment]
Don't bother with that step. It's outdated, and won't give you mpris support. You can either install my debian package from https://deb.geek1011.net/packages/stable/cmus/ or you can install the build dependencies with `sudo apt install bash-completion libao-dev libasound2-dev  libavcodec-dev libavformat-dev libswresample-dev libcddb2-dev libcdio-cdda-dev libcue-dev libdiscid-dev libfaad-dev libflac-dev libjack-dev libmad0-dev libmodplug-dev libmpcdec-dev libncursesw5-dev libopusfile-dev libpulse-dev libroar-dev libsamplerate0-dev libvorbis-dev libwavpack-dev libsystemd-dev pkg-config`.

**Comment by Traace** [comment]
Hi Geek1011. I tried your sugesstions and also handpicked a couple of other libs for my build attempt. However it does still fail:
`checking for SAMPLERATE_CFLAGS (pkg-config)... 
checking for AO_LIBS (pkg-config)... -lao
checking for AO_CFLAGS (pkg-config)... 
checking for program artsc-config... no
checking for header <sys/soundcard.h>... no
checking for SNDIO_LIBS (-lsndio)... yes
checking for header <sys/audioio.h>... no
configure failed.`

Then I tried your package but I'm unable to install it at all because of libc6 2.28 is not satisfiable.

Can you please help me?

Install is a fresh Ubuntu 18.04. Updated ofc :)

**Comment by geek1011** [comment]
@Traace can you build without any configure flags? Also, the reason why you couldn't install the package is because it was built for Debian Buster (and newer). I've built you a package which should work here: https://files.geek1011.net/Debian/Packages/cmus/2.8.0-stretch/.

**Comment by Traace** [comment]
Seems like flag 
`CONFIG_WAVEOUT=y`
dont work well. It configures fine without it.

May some other installs just get your package.

Thanks for the quick help.

**Comment by nefthy** [comment]
I think we should rework configure to be more specific when it fails. Lets say CONFIG_FOO is passed to configure but libbar required for CONFIG_FOO is not found, then the user should get a message like: "You passed CONFIG_FOO. libbar is required for this feature, but was not found. Either disable CONFIG_FOO or install libbar."

We should also print the config that configure figured out at the end in a comprehensive list. Like:
```IP:
- wav
- flac
- ogg
OP:
- jack
- alsa
...
```

**Comment by Traace** [comment]
Yes unfortunatly there are a lot of dev libs out there. Sometimes new users need to guess, use "apt search" many times or use a search engine to find proper libs.

Oh btw, may you like to know: Beside x86 ubuntu installs... I have several PowerPC systems with osx leopard installed. Cmus 2.8.0 builds fine there with a small build flag fix, its amazing ! . I think I'll gonna be new macports maintainer for cmus.

**Comment by sajan1231** [comment]
I have the same issue and i am not able to fix it.
Here is the error.


checking for program gcc... /usr/bin/gcc
checking for program gcc... /usr/bin/gcc
checking for C11 (with atomics support)... yes
checking for CFLAGS -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... yes
checking for CFLAGS -Wold-style-definition... yes
checking for CFLAGS -Wno-pointer-sign... yes
checking for CFLAGS -Werror-implicit-function-declaration... yes
checking for CFLAGS -Wno-unused-parameter... yes
checking for CFLAGS -Wno-missing-field-initializers... yes
checking if CC can generate dependency information... yes
checking byte order... little-endian
checking for DL_LIBS (-ldl -Wl,--export-dynamic)... yes
checking for PTHREAD_LIBS (-lpthread)... yes
checking for realtime scheduling... yes
checking for program pkg-config... /usr/bin/pkg-config
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lncursesw)... no
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lncurses)... no
checking for NCURSES_LIBS (pkg-config)... no
checking for NCURSES_LIBS (-lcurses)... no
configure failed.

**Comment by nefthy** [comment]
you are missing the ncurses library and development headers
