### ISSUE TITLE
cmus compilation issue

### ISSUE THREAD

**Issue by MrDini123** [cmus/cmus#412]
Hi!

I tried to compile the package with ffmpeg support, but the configure says:

```
checking for successful build of ffmpeg.c... no
configure failed.
```

But I have ffmpeg installed (from source too) and I have got ffmpeg.c at cmus's topdir...

What's wrong?

Thanks!

Ps: Sorry for my bad English...

**Comment by flyingmutant** [comment]
This probably means that brilliant minds who develop FFmpeg have once again broken backward compatibility of their wonderful library.

On a less sarcastic note, you can try to compile the plugin by hand (execute corresponding commands from `./configure` manually), and see exactly what the error is.

**Comment by MrDini123** [comment]
With the stable relase from the webpage of project and after a full ffmpeg recompile it now works!

But when I start it a lot of module load problem shows up... Like theese:

_cmus: symbol 'avcodec_decode_audio4': can't resolve symbol

cmus: symbol 'avcodec_open2': can't resolve symbol

cmus: symbol 'av_opt_set_sample_fmt': can't resolve symbol

cmus: symbol 'avcodec_close': can't resolve symbol

cmus: symbol 'av_rescale_q': can't resolve symbol

cmus: symbol 'av_log_set_level': can't resolve symbol_

**Comment by MrDini123** [comment]
Oh! I can't see ffmpeg at cmus --plugins:

_root@NSA320S:~# cmus --plugins

cmus: symbol 'avcodec_decode_audio4': can't resolve symbol

cmus: symbol 'avcodec_open2': can't resolve symbol

cmus: symbol 'av_opt_set_sample_fmt': can't resolve symbol

cmus: symbol 'avcodec_close': can't resolve symbol

cmus: symbol 'av_rescale_q': can't resolve symbol

cmus: symbol 'av_log_set_level': can't resolve symbol

cmus: symbol 'avcodec_flush_buffers': can't resolve symbol

cmus: symbol 'av_opt_set_int': can't resolve symbol

cmus: symbol 'av_dict_get': can't resolve symbol

cmus: symbol 'avcodec_find_decoder': can't resolve symbol

cmus: symbol 'av_new_packet': can't resolve symbol

cmus: symbol 'av_get_default_channel_layout': can't resolve symbol

cmus: symbol 'avcodec_alloc_frame': can't resolve symbol

cmus: symbol 'av_get_profile_name': can't resolve symbol

cmus: symbol 'av_free_packet': can't resolve symbol

cmus: symbol 'avcodec_free_frame': can't resolve symbol
Input Plugins: /ffp/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /ffp/lib/cmus/op
  alsa
  jack
  ao_

**Comment by flyingmutant** [comment]
This looks like a problem with your installation of FFmpeg, and not cmus. Please make sure you've built and installed it correctly.

**Comment by avoidr** [comment]
I had the same problem and it turns out to be a missing CFLAG.
