### ISSUE TITLE
cmus doesnt play next track in library mode

### ISSUE THREAD

**Issue by garanthal** [cmus/cmus#414]
Hello, been using cmus for a while, never had an issue with it until now.

Starting a few days ago every time a track comes to an end the next track wont play until i hit c and play it myself. Quite frustrating.

Any ideas as to why?

**Comment by flyingmutant** [comment]
Any chance you've pressed `C`, which turned off `continue` mode?

Pressing it once again should help.

**Comment by garanthal** [comment]
That got it, thank you very much. My keyboard doesn't have a led to tell me if caps is on.

Thanks again.
