### ISSUE TITLE
Question: Is it possible to open a single file from terminal?

### ISSUE THREAD

**Issue by ranranking** [cmus/cmus#419]
I am wondering how to do this: open a file simply by typing `cmus xx.mp3` in the terminal. Since I don't find relative informations in the tutorial, I am not sure whether this is possible using cmus.

**Comment by jolange** [comment]
I don't think that this is currently possible. The only thing you can do is starting cmus from the directory of `xx.mp3` and then select it from the browser view.

Maybe it might be a good feature that starting cmus like `cmus xx.mp3` would bring you to the browser view with that file automatically selected.

**Comment by darkphase** [comment]
cmus-remote -f "$DIR/$FILE"
