### ISSUE TITLE
Audio Units deprecation warning on OSX 10.11.4

### ISSUE THREAD

**Issue by tsujamin** [cmus/cmus#421]
Just built cmus from head via brew, and it appears that one of the frameworks it's using on OSX is being deprecated. The following message is printed out to terminal "on top" of cmus when I play a track (both mp3 and FLAC).

```2016-03-28 18:53:17.443 cmus[5829:202951] 18:53:17.442 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.```

1) `uname -a`:
```
Darwin Benjamin-MacOSX.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus 5fb4e79
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/HEAD/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD/lib/cmus/op
  coreaudio
  ao
```

**Comment by flyingmutant** [comment]
Make sure you are using coreaudio output plugin; it should not produce the warning.

**Comment by adamv** [comment]
The configure output out of Homebrew for me is: https://gist.github.com/adamv/df3e6eeef5fc0c94d22828201059d75a

My plugins output is then:

```
$ cmus --plugins
Input Plugins: /Users/adamv/homebrew/Cellar/cmus/2.7.1_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /Users/adamv/homebrew/Cellar/cmus/2.7.1_1/lib/cmus/op
  ao
```

I don't see the warning on stderr on this machine, though I do see it on my work machine, where I installed cmus a few weeks ago.

**Comment by tsujamin** [comment]
Maybe we should disable libao on the homebrew side for the moment and set coreaudio as default. Might look at this later.

**Comment by adamv** [comment]
@tsujamin I wrote a wrapper script for cmus that also enables media keys (from a script I found on GitHub): https://gist.github.com/adamv/b2a0aee9ac04229a4b93a0c09999f27c

**Comment by Wang-Yue** [comment]
@tsujamin @flyingmutant  you can make homebrew to built against cmus head. Currently it's not implemented.

**Comment by flyingmutant** [comment]
@adamv please make sure you use HEAD version: `brew install --HEAD cmus`.

@tsujamin Yeah, making coreaudio the default output plugin in Homebrew is a good thing to do (once we'll make an official release with coreaudio plugin).
