### ISSUE TITLE
[question] filetype and substrings in format strings

### ISSUE THREAD

**Issue by peczony** [cmus/cmus#424]
I haven’t been able to find this in the man, but it seems to be pretty obvious functionality: is there a way I can display only the filetype (mp3, m4a, flac) via format string?

If there isn’t, maybe there is some substring functionality so I can extract the filetype from filename?

**Comment by flyingmutant** [comment]
I think `%{codec}` should do the trick.

**Comment by peczony** [comment]
Thanks! I missed this one.
