### ISSUE TITLE
Don't silently delete tracks from *.pl

### ISSUE THREAD

**Issue by avoidr** [cmus/cmus#426]
If I saw that correctly, the recent version deletes playlist entries which are not playable. That's done without any notice that I saw. That should be corrected. Either don't delete, or at least notify the user in some way, be it a log file or stderr. Personally, I liked it not fucking with my shit, so I could see from cmus what doesn't play and what the issue is, to simply correct that.

Maybe I'm doing something wrong, though. Am I?

**Comment by z3t0** [comment]
Can you share what filetypes?

**Comment by avoidr** [comment]
I know it deleted tracks that didn't exist physically. I replaced the files with same ones of a different format and instead of letting me see what needs to be corrected in the playlist, cmus silently cleaned the playlist.
I can look and see whether the same happens for filetypes there is no plugin for, if that's necessary.

**Comment by flyingmutant** [comment]
When you open the playlist again, new tracks should be there, no?

**Comment by avoidr** [comment]
I created a copy of .config/cmus/, ran cmus, and diff'd. Entries were deleted from playlist.pl. I don't see why and how cmus would recognize the new tracks and add them, too.

**Comment by flyingmutant** [comment]
`playlist.pl` is a technical file, which contains current content of the «playlist» view. It is not expected to contain entries for non-existent files, by design – and it was always this way.
I am closing this issue; if there is something else wrong with cmus' playlist handling, please open a separate one.

**Comment by avoidr** [comment]
I see that nothing is deleted from not playlist.pl. That's good.
Thanks.
