### ISSUE TITLE
cmus-remote --follow option

### ISSUE THREAD

**Issue by camilstaps** [cmus/cmus#429]
For example, `tail -f` and `dmesg -w` will not finish but keep appending data to stdout. Would it be possible to add similar behaviour (through a new flag) to `cmus-remote -Q`? This would make it less heavy to add information from this to a status bar.

For example, what is suggested [here](http://joaquinlp.me/blog/cmus-data-i3bar-i3status/) is to run `cmus-remote` every 5s twice (and start grep and cut twice as well). This makes the bar depend on pids, which causes system load to increase. If we could leave cmus-remote open this would not be a problem (although a different solution than the bash script proposed in that link is needed in this case).

So, the proposal is to add a follow flag to `cmus-remote` such that for `-C` (and `-Q`) the program doesn't finish but will be updated automatically when the status of cmus changes.

**Comment by darkphase** [comment]
Using named pipes may be your solution...

**Comment by camilstaps** [comment]
Yes, but what would be needed is that the output of cmus-remote is automatically updated when the state of cmus changes. Now, if I'm not mistaken, you always have to send `status` to get this information.

**Comment by darkphase** [comment]
Until output changes pipe waits. Not much CPU or MEM usage... If still needed frequent updates read timeout is also an option...

Something like that;

`while true;do`
`read -t 5 input <> $pipe  ## nonblocking pipe read waits until it is writen or timeouts (5 secs)`
`done`

**Comment by camilstaps** [comment]
Sorry, there seems to be some kind of misunderstanding here. I know how to build a shell wrapper if cmus-remote would support it. However, if I call, say, `cmus-remote -Q`, I get a one-time output. When I call `cmus-remote` I get some kind of interactive shell. If I want to know what song is playing, I should send `status` for this.

What I need, is a program that outputs the new status every time the status changes. I need a push scheme, not a poll scheme. Maybe cmus-remote supports this and I just couldn't find it in the manpage of course...

**Comment by darkphase** [comment]
I don't think cmus as a server pushes data... You need to ask to it... 
Which is, at the end you are proposing... cmus-remote as the pusher server which constantly polls from cmus. 
You may implement this via any language (say C or bash). I don't think it would make too much difference, mem usage wise. 
Anyway I'm using it as I mentioned before... cmus-remote inside loop writes to a pipe than another process reads from it.

**Comment by camilstaps** [comment]
> I don't think cmus as a server pushes data... You need to ask to it... 

Exactly. That is what I propose to change. I am *not* proposing that cmus-remote polls cmus constantly. I'm proposing that cmus pushes this data to cmus-remote (once requested). This can be implemented in various ways. For example, a command could be added:

    push_status /tmp/cmusfifo

And from that moment cmus would push status changes to that fifo.

Alternatively, there could be a command `push_status` (no arguments), and from that moment cmus would push any status changes to that cmus-remote session.

Anything to make this possible without polling. Why not polling?

 * It is a waste of resources (system calls, cpu time, ...)
 * It is slower. For example, polling every second means your data can be up to a second delayed. Polling more often is not desirable because of the previous point (actually every second is already debatable). Pushing will guarantee that the data arrives almost instantaneously.

To be overly clear: I know that this is not possible at the moment. This is a feature request.

**Comment by camilstaps** [comment]
I don't have a use case for this any more and I suppose this would mean quite big changes and isn't worth the effort. Closing this to clean up my issues list.
