### ISSUE TITLE
[RFC] Possible multiple playlist design

### ISSUE THREAD

**Issue by losingkeys** [cmus/cmus#431]
Per [@flyingmutant's comment](https://github.com/cmus/cmus/issues/108#issuecomment-205474409), here's an initial proposal for how mulitple playlists could be supported by cmus. I haven't had a chance to talk with @z3t0 yet, but we can talk on this thread :).
## UI
```        
+---------------------------------------------------------------------+
| Playlist      	     Track                    5 tracks - 00:44:00 |
| * filename w/o extension | Song 1                                   |
|   another playlist  	   | Song 2                                   |
|                          | Song 3                                   |
|                          | Song 4                                   |
|                          | Song 5                                   |
|                          |                                          |
|                          |                                          |
|                                                                     |
| . 00:00 - 00:00 vol: 100                     all from playlist | C  |
|                                                                     |
+---------------------------------------------------------------------+
```

Some things to point out:

1. The `00:44:00` at the top. Cmus currently counts the songs in a playlist, but not the time. Counting the time would be useful for DJs, and other people planning to play these for an audience.
1. `all from playlist` at the bottom right. It'd be nice to add `playlist` to `toggle aaa_mode`. We'd stay within the currently playing playlist, or the active playlist (the one with the `*`, see the next section for more).

## Adding/Removing songs from playlists
This would be _exactly_ the same as it is now. The only new thing is the `*` near the playlist name. This indicates the "active" playlist, and is where songs go when added. We'd need a key to change the active playlist. Deleting songs would be done in the same way they are now. You'd be able to delete songs from any playlist, because you have to select them first.

### Rejected design for adding songs

Here's another design that I don't like and don't think we should use, but am including it for discussion in case someone likes it:

1. The user has more than one playlist
1. The user tries to add a song to a playlist
1. A dialog is shown with the names of all the playlists
1. The user chooses a playlist
1. The song is added to that playlist 

This didn't feel very cmus-y to me (it felt kind of tedious/slow imo). We also don't have any dialogs at the moment, so it would be new to the users.
## Other Initial Features
1. Support reading from/writing to one file format
  - I'm not sure what `.pl` is, that we're using now, but we could start by only supporting that. Preferrably it'd be a standard format that other players can read and write (so, `.m3u`, or `.pls`?).

## Open Questions
1. I'm not sure how difficult it'll be to support multiple playlist formats, or if we'll have trouble with things like relative file paths. I don't think we should provide editing support for playlists (other than adding/removing songs). [Here's a list of some playlist formats](https://en.wikipedia.org/wiki/Category:Playlist_file_formats).
1. Support creating new playlists? Renaming them? Deleting them? Create a default playlist when trying to add a song to the active playlist and they have no playlists?
  - IMO we should only allow creating new playlists, or none of these, at least for the initial version.
1. With the current design we need at least one more keybinding, to change the currently active playlist. It could be the space bar, depending on if you want to allow users to select playlists (either to combine them into another playlist, or to delete them or something).
1. As far as I know the current version of cmus doesn't let you choose where its one playlist is stored. It's automatically stored in `~/.cmus/playlist.pl` (correct me if I'm wrong). It'd be nice to have a variable for the playlist directory, so users could e.g. keep it in dropbox easily.
1. We should only support finding playlists immediatly in the playlist directory, but we could support file-browser-like functionality later if you wanted. If we did this the playlist browser would effectively be the file browser, but you could enter a playlist like a directory, and see more info (number of songs and total time, and the songs are in the playlist, possibly being stored somewhere else). Seems like a cool idea, but it seems like too much for this initial version.

### Changing
1. Replacing the current playlist UI with the one above, which has the following features;
  - Shows the total time of the playlist
  - Shows playlists from the playlists directory in the sidebar

### Adding
1. Keybinding to mark playlist to add songs to (this can just be space, but we can create an option for it. It's special in left pane of the library view anyway)
1. Random by playlist
1. ~~Setting to indicate where playlists are stored~~ (We'll use `cmus_config_dir/playlists/` instead. [Thanks @jayay for the suggestion](https://github.com/cmus/cmus/issues/431#issuecomment-209058716))
1. The ability to create a new playlist (maybe using something as simple `touch $PLAYLIST_DIR/$name.pl`)
1. Setting to controll the formatting of playlist names ([thanks: @nefthy](https://github.com/cmus/cmus/issues/431#issuecomment-208545123))

### Not changing
1. Add to playlist (it just adds to the marked playlist now, instead of the only playlist)
1. Delete song from playlist

---
Thanks for reading. Looking forward to your comments :)

**Comment by jayay** [comment]
Hey! 

I have one tiny thing to add. 
> It's automatically stored in `~/.cmus/playlist.pl`

If you have a look at the function `misc_init()` in misc.c:200 you see how `cmus_config_dir` is set.

**Comment by flyingmutant** [comment]
@losingkeys, thanks a lot for the write-up. Just a quick note: I won't be able to comment on it before next weekend, unfortunately. Hope others contributors and users will participate in the discussion, though!

**Comment by nefthy** [comment]
A format parameter for displaying the current playlist in the status bar would be usefull. It would be a huge annoyance to spend time adding songs to a playlist in one of the other views, only to find out afterwards that it is the wrong one.

**Comment by losingkeys** [comment]
@jayay thanks, I figured you could configure it somehow. We'll probably need another option for playlist directory, which will defailt to `cmus_config_dir/playlists/` when it's not set, right?

@flyingmutant no worries I'll try to read some code between then and now :)

@nefthy good idea, I've added it to the issue description

**Comment by jayay** [comment]
@losingkeys yes, or you simply use `cmus_config_dir/playlists` as cmus_config_dir is always set.

**Comment by losingkeys** [comment]
@jayay good idea! I've updated the description.

**Comment by losingkeys** [comment]
@flyingmutant do you (or another maintainer) have some time to walk me through the source? I'm having a little trouble. I haven't done C in awhile... but if you can spare some time I'll at least take lots of notes and write up a wiki page, if not be able to finish this up quicker :). If you don't have time I understand, I'll keep reading

**Comment by flyingmutant** [comment]
@losingkeys, I am very sorry for replying this late. Unfortunately, I have almost no time for anything cmus-related as of late (little kid + new job), so I can not help you here at all :-(

**Comment by losingkeys** [comment]
No worries, I'll let you know when I make more headway :)

**Comment by losingkeys** [comment]
Quick update here: I had a call with [Jakob](https://twitter.com/74k08), who learned a lot about cmus when implementing a BPM detection plugin. I've taken some notes, so now I have a starting point. It's slow going though. If someone wants to pick this up feel free, but I'll work on it occassionally and update when I make progress.

**Comment by mahkoh** [comment]
I've implemented this and will probably create a PR tomorrow. Here is a screenshot for now:

![image](https://cloud.githubusercontent.com/assets/1882250/16621546/e10c6c16-4396-11e6-8a32-036e0f95598c.png)

**Comment by mahkoh** [comment]
I'm currently rewriting a lot of the existing UI code and that will take a bit of time. Not only do I want to base the playlist feature on top of that, but I also don't want to create a PR-able commit history before I'm actually done with this.

However, since you probably don't care about those implementation details, you can try the feature here: https://github.com/mahkoh/cmus/tree/playlist. Clone, configure, make, make install should work as expected.

I haven't written any documentation yet but here are the essential commands:

* `:load <file>` while in the playlist view will load the file as a new playlist.
* `:save` saves the current playlists to `~/.cmus/playlists/`. This happens automatically when you exit.
* `:win-remove` (usually bound to the delete key) deletes a playlist.
* `:pl-create <name>` creates a new playlist with this name.
* `:pl-rename <name>` renames the currently selected playlist.

**Comment by mahkoh** [comment]
Forgot the most important one: `:win-toggle` changes the marked playlist.

**Comment by losingkeys** [comment]
Awesome work! I'm testing it now :smiley:. Some thoughts about possible default keybindings, and from my first use of it:
- `*` for `:win-toggle`. Would it make more sense if this also changed when you started playing from another playlist? I'll need to play w/it more before I have an opinion here. I know I made suggestions above, but I have more ideas now after using it
- ~~I think `DEL` on a playlist should work like `:quit -i` (where it asks you to confirm), because it's much more destructive than e.g. removing a song from a playlist~~. This already happens, fantastic!
- ~~`DEL` inside a playlist removes that song.~~ This still works, cool :smile: 
- Maybe `%` for `:pl-create`? I'm taking that from netrw in vim... but don't feel strongly about it... Others probably have better suggestions here
- Could `:load` and `:save` just be automatic? It could just load all supported playlist formats immediately (or recursively) in the playlists directory, and save changes immediately.
- I like that when you play tracks it says `playlist` in the bottom right corner, and picks songs from the current playlist. Maybe that could also be a part of the `:toggle aaa_mode` command (`m` key by default)?
- Not sure about `:pl-rename`. `r` or `R`?

Anyway thanks for implementing this! This is awesome!

**Comment by mahkoh** [comment]
>`*` for `:win-toggle`

It's already bound to space.

>Could `:load`

Playlists in the playlist folder are automatically loaded on startup. `:load` is only for loading playlists for arbitrary places.

 >and `:save` just be automatic?

cmus has never automatically saved things at runtime. When you add tracks to the library and cmus crashes, those changes will be lost on restart. cmus saves everything when it exits.

**Comment by losingkeys** [comment]
Ok cool. So playlists are saved on exit as well?

**Comment by mahkoh** [comment]
They are saved but `:load` creates a copy for the playlist folder. Changes will be made to that copy and not to the original file.

**Comment by losingkeys** [comment]
Ahh, I think I understand. So the playlist is copied to the playlists directory, where it's then automatically loaded/saved on future startups/exits. Is that in the docs? Maybe `:import` and `:export` would make more sense then? Then the user would feel like they're either bringing a playlist into cmus' automatic control (saving on exit and stuff), or when they're exporting they wouldn't expect the exported playlist to be messed with further.

**Comment by mahkoh** [comment]
I've added `:pl-import` and `:pl-export` commands.

**Comment by losingkeys** [comment]
Cool! I just tried it. Works great :smile:

**Comment by losingkeys** [comment]
(I hope it's okay that I'm still testing/commenting here)

So I've been playing with it more. I noticed that the playlists are re-ordered when cmus is restarted. This is probably a good thing as long as they're ordered the same as the library view.

I also noticed the selected playlist is forgotten on restart (the topmost playlist is always selected on startup.

**Comment by mahkoh** [comment]
I've made it so that the marked playlist is restored. The playlists are sorted by name on restart.

**Comment by flyingmutant** [comment]
@losingkeys please feel free to continue discussion here – however, I'll close the issue because a working PR is already available.

**Comment by SamyBencherif** [comment]
Just thought I would add, since this is the first Google result for "mark playlist cmus", the way to switch from marking _tracks_ to marking _playlists_ is to press TAB.

Got stuck for a fair bit there 😅
