### ISSUE TITLE
Seeking when stopped starts the player

### ISSUE THREAD

**Issue by dkagedal** [cmus/cmus#438]
When the player is stopped, seeking will will start the player. When the player is paused, seeking will not start (unpause) the player

Repro:

1) In view 1, move to a song, press return to start playing
2) Press 'v' to stop it
3) Press right key to seek +5s (or use the seek command). Music starts playing five seconds from the start.

Proposal: when seeking a stopped song, start the player but put it in the paused state.

I have a patch.

1) `uname -a`: Linux peggy 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

2) `cmus --version`: cmus v2.7.0-75-gda738ac

**Comment by jolange** [comment]
I can confirm that behaviour and I think your proposal is solid.
