### ISSUE TITLE
Allow theming of album titles in view 1

### ISSUE THREAD

**Issue by pszxzsd** [cmus/cmus#443]
Right now themes cannot change the color of album titles in the right pane of view 1, they are always bold white text on dark gray. An option to customize this would allow better themes that change the default background color.

**Comment by xeverse** [comment]
In -git 
they default to 
color_win_fg 

color_trackwin_album_fg|bg
options needed

**Comment by R4WBIT** [comment]
It seems like I don't have this option on my system.  
Running version "v2.8.0-rc0" on Fedora.  
It looks like it's from the "rpmfusion-free" repo.

Do I need to compile it from git to get these features, or has it been removed?
