### ISSUE TITLE
Seg fault when adding to path

### ISSUE THREAD

**Issue by luw** [cmus/cmus#45]
I receive "Segmentation fault (core dumped)" when adding a directory to the path, using :add /path/to/musics

/path/to/musics is a mounted NFS share.  Also it's size might be a factor, as it is 2TB and about 200k songs.

system is cmus v2.4.3 that was built from repos on a Ubuntu 12.04LTS system.

Will upgrading fix this issue and has it been seen before?  Do you need any more info?

**Comment by tkschmidt** [comment]
I still get this problem with version 2.5 by adding certain m4a. Converting it to mp3 by ffmpeg circumvents it

**Comment by flyingmutant** [comment]
Can you please try to reproduce it with current version of cmus — 2.7.1?

**Comment by remicorniere** [comment]
Can confirm it happens on 2.7.1.
Using the version from Fedora repos.

**Comment by nefthy** [comment]
can you give some more details on the circumstances or maybe even get a backtrace with gdb?

**Comment by KaffeMyers** [comment]
I have this issue currently, and my situation is similar, running Debian Jessie: music on an NFS share, adding a fairly large FLAC collection.

<pre>$ uname -rvo
3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) GNU/Linux
$ cmus --version
cmus v2.7.0-33-gbb6999e
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
$ cmus --plugin
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda

Output Plugins: /usr/local/lib/cmus/op
  pulse
  roar
  alsa
  jack
  ao
</pre>

- I open cmus, type in command <code>:clear</code>, followed up by <code>:add /path/to/nfs-music-folder</code>
- This happens after about 20+ seconds of scanning <code>[1]    15898 segmentation fault  cmus </code>

I love cmus the few times it actually works (but that's extremely rare), but this issue kinda renders it unusable as soon as I have some major changes done to the library.

**Comment by mahkoh** [comment]
Please try with the current master.
