### ISSUE TITLE
Enable gapless playback?

### ISSUE THREAD

**Issue by joaquinlpereyra** [cmus/cmus#458]
The man page doesn't contain any info on this, yet it is listed on the features on the webpage (https://cmus.github.io/#features). 

Any info on this?

**Comment by flyingmutant** [comment]
cmus automatically skips gaps in mp3, that's it — https://github.com/cmus/cmus/blob/master/nomad.c#L645

**Comment by joaquinlpereyra** [comment]
Oh, well. That about closes it, I guess.

Thanks for the info!
