### ISSUE TITLE
Network share (smbfs) and zombies

### ISSUE THREAD

**Issue by pik4ez** [cmus/cmus#46]
Cmus 2.5.0, Arch linux x86_64.

Trying to use cmus with samba share. It works fine almost always, but sometimes cmus process stops responding and trying to kill it makes no sense (zombie process with parent = 1).

I think the bug appears when remote PC with samba share sleeps for some time and it takes additional time to wake it after song starts to play.
### OS

Linux <name> 3.9.2-1-ARCH # 1 SMP PREEMPT Sat May 11 20:31:08 CEST 2013 x86_64 GNU/Linux
### cmus

<pre>
Name           : cmus
Version        : 2.5.0-2
Description    : Very feature-rich ncurses-based music player
Architecture   : x86_64
URL            : http://cmus.sourceforge.net/
Licenses       : GPL
Groups         : None
Provides       : None
Depends On     : ncurses
Optional Deps  : alsa-lib: for ALSA output plugin support [installed]
                 libao: for AO output plugin support
                 libpulse: for PulseAudio output plugin support
                 faad2: for AAC input plugin support [installed]
                 ffmpeg: for ffmpeg input plugin support
                 flac: for flac input plugin support [installed]
                 libmad: for mp3 input plugin support [installed]
                 libmodplug: for modplug input plugin support [installed]
                 libmp4v2: for mp4 input plugin support [installed]
                 libmpcdec: for musepack input plugin support [installed]
                 libvorbis: for vorbis input plugin support [installed]
                 opusfile: for opus input plugin support
                 wavpack: for wavpack input plugin support
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size : 700.00 KiB
Packager       : Bartłomiej Piotrowski <barthalion@gmail.com>
Build Date     : Sat 05 Jan 2013 03:10:55 AM NOVT
Install Date   : Tue 07 May 2013 04:46:38 PM NOVT
Install Reason : Explicitly installed
Install Script : No
Validated By   : Signature
</pre>

### cifs-utils

<pre>
Name           : cifs-utils
Version        : 6.0-2
Description    : CIFS filesystem user-space tools
Architecture   : x86_64
URL            : http://wiki.samba.org/index.php/LinuxCIFS_utils
Licenses       : GPL
Groups         : None
Provides       : None
Depends On     : libcap-ng  keyutils  krb5  talloc  libwbclient
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size : 221.00 KiB
Packager       : Tobias Powalowski <tpowa@archlinux.org>
Build Date     : Sun 19 May 2013 04:31:21 PM NOVT
Install Date   : Mon 20 May 2013 01:09:03 PM NOVT
Install Reason : Explicitly installed
Install Script : No
Validated By   : Signature
</pre>

**Comment by pgaskin** [comment]
Is this still an issue?

**Comment by pik4ez** [comment]
At least not for me. I stopped using this software.
But thank you anyway for your fast feedback :)
