### ISSUE TITLE
Error: name or integer in range 1..7 expected

### ISSUE THREAD

**Issue by buzzbo** [cmus/cmus#464]
I get this error when I try to switch to the file browser view, upon pressing `5`, either num pad or top row of my keyboard:

`Error: name or integer in range 1..7 expected`

Happens in any view. [Example screenshot](https://i.imgur.com/x1dAgt0.jpg)

---

1) `uname -a`:
```Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux```

2) `cmus --version`:
```
cmus v2.7.0-37-g733cf4e
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors

```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/local/lib/cmus/op
  pulse
  roar
  alsa
  jack
  ao

```

**Comment by intact** [comment]
Press Enter on that line and delete slashes (and press Enter again).

**Comment by buzzbo** [comment]
Aagh thanks. I'm not sure how those backslashes got there (likely my own doing)
