### ISSUE TITLE
[feature request] sort_library sorting by arbitrary tag

### ISSUE THREAD

**Issue by bzaborow** [cmus/cmus#47]
I found that there is no possibility to sort library by any tag present in my music files, in particular by TBPM (standard tag for beats per minute from ID3v2). As far as i know the sort keys are hardcoded - maybe it would be possible to allow some flexibility and use directly tag names from ID3 or flac tags? The current predefined sort keys (like title, filename and so) can become macros which will expand to specific tag names present in different file formats (or some other meta information or fallback tags).
The same could possibly go for filtering keys.

If you don't like the above idea may I ask for a bpm sorting key?

**Comment by jayay** [comment]
If this is still current - TBPM applies to ID3 tags, but not every input plugin in cmus uses ID3, for example FLAC and ffmpeg (but ffmpeg doesn't seem to support BPM it at all).
But if you're on master, the BPM tag should be read from FLAC and MP3 files if it is set.

@flyingmutant I think you can close this issue.

**Comment by igordertigor** [comment]
Is this still active? Does sorting by bpm/displaying bpm work? If yes, how?

**Comment by flyingmutant** [comment]
Yes, displaying BPM should work (`%{bpm}`), sorting as well (`bpm`/`-bpm`).
