### ISSUE TITLE
Can't recognise .mp3 files

### ISSUE THREAD

**Issue by andrewzenfoo** [cmus/cmus#473]
Compiled from source and it only recognises .wav files. I've installed all the dependencies with apt-get
---

1) `uname -a`:
```
Linux zen 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors

```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  oss
  ao

```

**Comment by flyingmutant** [comment]
You need to get the libmad development package installed, then ./configure && make again. Input plugins should list "mad", which is responsible for mp3s by default.

**Comment by ViniciusBRodrigues** [comment]
I'm using openSUSE and I have libmad development package installed. cmus doesn't recognize my files. When I press "a" to add to the library nothing happens - just jump to another line.

Linux linux-hwbe 4.4.104-39-default #1 SMP Thu Jan 4 08:11:03 UTC 2018 (7db1912) x86_64 x86_64 x86_64 GNU/Linux

cmus v2.8.0-rc0-71-g3a4ce9c

Input Plugins: /usr/lib64/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  alsa
  oss
