### ISSUE TITLE
Tearing With High Bitrate Flac Files

### ISSUE THREAD

**Issue by crockeo** [cmus/cmus#478]
---

1) `uname -a`:
```
Darwin Crockbook.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.7.1_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.7.1_1/lib/cmus/op
  ao
```

When playing a high bitrate `.flac` file (e.g. `2667 kbps` according to cmus) there is consistent audio tearing. The `.flac` file itself seems well structured as it plays correctly using Vox and on my desktop using WinAmp.

**Comment by mahkoh** [comment]
Where would I get such a flac to test this?

**Comment by crockeo** [comment]
I'm running into this issue from the album [Teens of Denial by Car Seat Headrest](https://carseatheadrest.bandcamp.com/album/teens-of-denial). Included is a copy of the last song on the album (the shortest for the sake of space):

https://drive.google.com/open?id=0B1TwLF__efvZdDBaeUlmWVN1UU0

**Comment by mahkoh** [comment]
Works fine for me with the flac plugin and both pulse and alsa. The ffmpeg plugin cannot play the file properly but you don't have that one installed.

**Comment by crockeo** [comment]
What OS are you running? It might be a platform-specific bug.

**Comment by mahkoh** [comment]
linux. Since you're using the ao output plugin that would be the first place to look.

**Comment by flyingmutant** [comment]
Yeah – I'd recommend compiling HEAD version of cmus with CoreAudio output plugin, and checking if the issue exists there.

**Comment by Wang-Yue** [comment]
@flyingmutant I'm playing the sample file with CoreAudio plugin and the problem does not present. You can close this bug.

The CoreAudio plugin's playback renderer  is carefully written. it does not do any system calls  (for locking, file reading, etc) as some other player implementations (such as the crappy mpd daemon or the Cog app) do. The ring buffer is maintained by atomic barriers rather than mutex/locks. Thus it has very low latency and pretty good performance, even for super high definition files.
