### ISSUE TITLE
libmad decoding quality is subpar

### ISSUE THREAD

**Issue by lachs0r** [cmus/cmus#480]
libmad decoding quality for e.g. MP3 is pretty bad. It seems to cause severe aliasing, which results in awful harmonics. That’s very noticeable with e.g. low-frequency bass. I think FFmpeg, which doesn’t have this problem, should be preferred when available and compiled with MPEG audio support. That would also avoid a number of other problems with libmad, such as the slow and sometimes completely broken seeking.

**Comment by flyingmutant** [comment]
Sorry, I do not really know what are you talking about...

1. Is there an open libmad issue about this?
2. Does using cmus ffmpeg plugin help?
3. Please do fill the info from the issue template:

1) `uname -a`:
```
(paste output here)
```

2) `cmus --version`:
```
(paste output here)
```

3) `cmus --plugins`:
```
(paste output here)
```

P.S. #475 is merged now, so maybe #104 or #446 can be resurrected and potentially help here?

**Comment by mahkoh** [comment]
With #475 merged you can just set the libmad priority to 0 to disable it. Then ffmpeg will be used for mp3s (if installed.)

>Is there an open libmad issue about this?

I think libmad has been dead for at least 10 years.

**Comment by mahkoh** [comment]
Closing in favor of #552.
