### ISSUE TITLE
Error: selecting output plugin '': no such plugin

### ISSUE THREAD

**Issue by pe200012** [cmus/cmus#491]
---
Error: selecting output plugin '': no such plugin
No sounds when I play a song:( 
1) `uname -a`:
```
Linux pecomputer 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

2) `cmus --version`:
```
(paste output here)
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  oss

```

**Comment by flyingmutant** [comment]
Try setting `:set output_plugin=oss`, or compiling and using another one (e.g. PulseAudio; `:set output_plugin=pulse`).
