### ISSUE TITLE
crash in bash for Windows 10

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#496]
Just default install of bash for windows 10. 
crash on every launches. 

I got cmus by apt-get install cmus. 

```
ning$ cmus
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
Aborted (core dumped)
```

1) `uname -a`:
```
Linux 19300119NN 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.5.0
```

3) `cmus --plugins`:
```
I can see ao, alsa and pulse are output plugins
```

**Comment by Wang-Yue** [comment]
selecting the alsa plugin will make the crash disappear. however it cannot find the output device.

**Comment by acke** [comment]
Same issue here.

**Comment by mahkoh** [comment]
You should open an issue with the Microsoft people.

**Comment by flyingmutant** [comment]
What about building current version from source? 2.5.0 is very old.

**Comment by mahkoh** [comment]
Can anyone with access to Windows 10 still reproduce this? If so please open an issue [here](https://github.com/Microsoft/BashOnWindows). This looks very much like an upstream bug.

**Comment by mahkoh** [comment]
I'm now quite sure that this is a bug in windows. Search the repo linked above for pulseaudio.
