### ISSUE TITLE
Seeking on mp3 files fails

### ISSUE THREAD

**Issue by futuro** [cmus/cmus#497]
When I attempt to seek on the following file http://beatoracle.net/audio/2016.07.30/bo-07.30.2016.mp3 I get some different behaviors, but none of which are a proper seek.

When I use `l` to seek, the audio will loop back to the beginning after 3 presses, though the timer advances. If I seek with the period key, the timer advances by a minute, but the audio advances by something like 10-15 seconds, though it won't loop. If I use the `:seek` command, the audio jumps ahead, but not by as much as it should. I don't know the correlation between the time I give it and how much the audio jumps. The timer is set to whatever I was seeking to.

The requested items are below, but please let me know what else I can offer up that might help.

Thank you.

1) `uname -a`:
```
Linux krikket 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  ao
```

**Comment by mahkoh** [comment]
Please disable the mad plugin by setting input.mad.priority to 0 and try again.

**Comment by mahkoh** [comment]
You don't have the ffmpeg plugin so that won't work. You'll have to recompile with ffmpeg support first.

**Comment by futuro** [comment]
Huh, that worked. Thank you @mahkoh! What's the reason for that?

**Comment by mahkoh** [comment]
libmad has not been maintained for a very long time and has some known bug.
