### ISSUE TITLE
Library view // default color for the Album name in the separator line

### ISSUE THREAD

**Issue by dstepanovsrc** [cmus/cmus#499]
1) `uname -a`:
```
Linux gnome-laptop 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

Description:
Open library view (1). From the Artist/Album side of the screen (left by default) chose any artist. Note that this artist should contain some music files and these files should contain Album tag. As soon as the artist is chosen you can see the full list of albums and tracks on the right side of the screen. The Album name is marked as:
```
 <ALBUM NAME> ---------------------------------------------------------------------------
```
Now try change the current colorsheme, for instance:
```
 :colorscheme zenburn
```
or
```
 :colorsheme gray-88
```
All the colors are changed except the Album name in the separator line. The default background/foreground pair is used for output. This behavior is hardcoded in the ui_curses.c file (line 750):
```
 744         if (track == (struct tree_track*)album) {
 745                 int pos;
 746                 struct fp_len len;
 747 
 748                 /* FIXME:
 749                  * replace A_BOLD by something useful */
 750                 bkgdset(A_BOLD);
 751 
 752                 fill_track_fopts_album(album);
 753 
 754                 len = format_print(print_buffer, track_win_w, track_win_album_format, track_fopts);
 755                 dump_print_buffer(track_win_y + row + 1, track_win_x);
```
So no color scheme is applied and only the A_BOLD attribute is used.

Maybe i'm wrong and it is an expected behavior, but it looks really bad if you are trying to have some colorscheme working and your terminal background/foreground colors are different.

The idea is to use the same color pair attribute as for showing tracks, but with the BOLD attribute:
```
 bkgdset(pairs[CURSED_WIN] | A_BOLD);
```

The proposed diff is shown below:
```
diff --git a/ui_curses.c b/ui_curses.c
index ad42e59..8246d4f 100644
--- a/ui_curses.c
+++ b/ui_curses.c
@@ -745,9 +745,9 @@ static void print_track(struct window *win, int row, struct iter *iter)
                int pos;
                struct fp_len len;
 
-               /* FIXME:
-                * replace A_BOLD by something useful */
-               bkgdset(A_BOLD);
+               /* Output the album name in the same color as unselected
+                * track name, but with BOLD attribute. */
+               bkgdset(pairs[CURSED_WIN] | A_BOLD);
 
                fill_track_fopts_album(album);
```

What do you think about such change?

**Comment by flyingmutant** [comment]
Thanks for super-detailed issue! The proposed patch is a nice fix. Do you want to submit a pull request for it, or do you prefer me to create a commit with your change?

**Comment by dstepanovsrc** [comment]
Hi! Yes, please commit the changes above, glad you like it and hope this player will continue developing ).
