### ISSUE TITLE
Various things that should be fixed before the next release

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#507]
~~1. There is a race in `track_info_{ref,unref}`. The counter needs to use atomic operations. As such the standard should be changed from `gnu99` to `gnu11`.~~

~~2. The playlist initialization accesses various systems that have not yet initialized at that point. It is pure coincidence that this does not cause problems. Initialization should be moved to the correct position.~~

~~3. The playlist initialization loads the playlists before options have been initialized. Various relevant options such as `skip_track_info` are not yet available at this point. Playlist initialization cannot be moved after the options initialization since the rc file might invoke playlist operations. Loading of playlists should be moved out of initialization.~~

4. Maybe other things?

**Comment by oleerik** [comment]
Adding https support wouldn't be the worst either, if it's not implemented yet! :)

**Comment by mahkoh** [comment]
Https support would be a major new feature. This issue is for bug fixes only.
