### ISSUE TITLE
UI is too aggressive at getting volume value

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#533]
see https://github.com/cmus/cmus/blob/1cbf070a86bbd4935bc964d5afcc699f5e1460d2/ui_curses.c#L2175

For systems that don't have mixer fd's, it will always call mixer_read_volume() aggressively. 

It happens that CoreAudio's AudioObjectGetPropertyData is pretty slow and heavy. So we end up with a lot higher CPU usage.  On my machine (a low end Macbook Pro) it went from 0.3% usage to 0.5%. CoreAudio daemon also shows similar higher usage. I can cache some result, but it's better to lower down the time value knob.

**Comment by mahkoh** [comment]
Why is it using 0.3% in the first place?

**Comment by Wang-Yue** [comment]
@mahkoh Majority of cpu cycles are used for flac decoding. Others are for AUHAL.

**Comment by mahkoh** [comment]
If music is playing then https://github.com/cmus/cmus/blob/1cbf070a86bbd4935bc964d5afcc699f5e1460d2/ui_curses.c#L2175 is irrelevent because the main loop runs 10 times per second anyway.

**Comment by Wang-Yue** [comment]
why? it's being called here:
https://github.com/cmus/cmus/blob/1cbf070a86bbd4935bc964d5afcc699f5e1460d2/ui_curses.c#L2188 

and mixer_read_volume is heavy on some systems (such as Mac OS X). 

if music itself takes 0.3% CPU that's fine---we can't optimize that away. But this is something we can optimize away.

**Comment by mahkoh** [comment]
I think the real solution is to add such an fd to the plugin. Surely coreaudio has a way to notify clients of such changes.

**Comment by Wang-Yue** [comment]
AudioUnit (AUHAL) does have event based notification. But I don't believe AudioDevice has that feature.

**Comment by Wang-Yue** [comment]
I can surely do this, but it's pretty bad in my opinion.

(I don't think AudioDevice has a way to monitor volume change. For AUHAL it's entirely possible. )

```
--- a/coreaudio.c
+++ b/coreaudio.c
@@ -246,6 +246,10 @@ static AudioStreamBasicDescription coreaudio_format_description;
 static AudioUnit coreaudio_audio_unit = NULL;
 static UInt32 coreaudio_buffer_frame_size = 1;
 static coreaudio_ring_buffer_t coreaudio_ring_buffer = {0, 0, 0, 0, 0, NULL};
+static bool coreaudio_volume_changed = true;
+static int coreaudio_left_volume = 100;
+static int coreaudio_right_volume = 100;
+
 
 static OSStatus coreaudio_play_callback(void *user_data,
                                        AudioUnitRenderActionFlags *flags,
@@ -728,6 +732,7 @@ static OSStatus coreaudio_get_device_stereo_channels(AudioDeviceID dev_id, UInt3
 
 static int coreaudio_mixer_set_volume(int l, int r)
 {
+       coreaudio_volume_changed = true;
        UInt32 channels[2];
        OSStatus err = coreaudio_get_device_stereo_channels(coreaudio_device_id, channels);
        if (err != noErr) {
@@ -765,6 +770,11 @@ static int coreaudio_mixer_set_volume(int l, int r)
 
 static int coreaudio_mixer_get_volume(int *l, int *r)
 {
+       if (!coreaudio_volume_changed) {
+               *l = coreaudio_left_volume;
+               *r = coreaudio_right_volume;
+               return OP_ERROR_SUCCESS;
+       }
        UInt32 channels[2];
        OSStatus err = coreaudio_get_device_stereo_channels(coreaudio_device_id, channels);
        if (err != noErr) {
@@ -797,6 +807,9 @@ static int coreaudio_mixer_get_volume(int *l, int *r)
                        *r = volume;
                }
        }
+       coreaudio_left_volume = *l;
+       coreaudio_right_volume = *r;
+       coreaudio_volume_changed = false;
        if (err != noErr) {
                errno = ENODEV;
                return -OP_ERROR_ERRNO;
(END)
```

**Comment by mahkoh** [comment]
>I don't think AudioDevice has a way to monitor volume change. For AUHAL it's entirely possible. 

You should find that out.

**Comment by mahkoh** [comment]
I've added mixer fds to the pulse plugin in #537. Something like that should be added to the coreaudio plugin.

**Comment by Wang-Yue** [comment]
> You should find that out.

It's just not possible. Apple doc clearly say events are for AUHAL. There's no event registration for CoreAudio AudioDevice. 

> I've added mixer fds to the pulse plugin in #537. Something like that should be added to the coreaudio plugin.


You happened to have a event for the mixer. but on CoreAudio it's just another story.

**Comment by mahkoh** [comment]
Apple never fails to disappoint. I don't know coreaudio so you'll have to figure out something yourself. If you don't want to query the time so often then maybe simply add a clock in `coreaudio_mixer_get_volume` and query at most once per second.

**Comment by Wang-Yue** [comment]
>  simply add a clock in coreaudio_mixer_get_volume and query at most once per second.

I'd rather the clock is in ui_curses. any audio plugin should not have this to walk around the problem. it's a bad design.

**Comment by mahkoh** [comment]
Any audio plugin doesn't. As far as I can tell only coreaudio has this problem. I don't want to reduce the precision of all plugins just for some questionable performance gains. You're saying this process is prohibitively expensive in the case of coreaudio. But that might not be the case for other plugins without mixer fds.

**Comment by Wang-Yue** [comment]
bottom line: It doens't hurt to have a separate timer to update volume in the UI.

**Comment by Wang-Yue** [comment]
I was wrong. Apple deprecated a method to listen property address change for audio device, but added a new one.
