### ISSUE TITLE
Configuring visible columns

### ISSUE THREAD

**Issue by DavidOliver** [cmus/cmus#547]
Is it possible to configure which meta data is available as columns in views 2, 3 and/or 4? I'd like to, for example, add Album to view 2.

I've had a look through the manual and settings but can only find sorting options. Thanks.

**Comment by mahkoh** [comment]
Use the format_ and altformat_ options.

**Comment by DavidOliver** [comment]
Many thanks. I'd incorrectly assumed the formatting options were specific to individual strings rather than list layouts. (Better reading skillz required.)
