### ISSUE TITLE
Add to top of queue

### ISSUE THREAD

**Issue by elvis-sik** [cmus/cmus#548]
I want to bind a key to add a song to the top of the queue so that I can add to both ends (effectively making it a `deque` :smile: ).

I see there is no direct support for this. Is this a reasonable feature to add to cmus, or would it be better for me to script it?

**Comment by mahkoh** [comment]
`E` adds a track to the top of the queue.

**Comment by elvis-sik** [comment]
Thank you, should have read the man page with more attention...
