### ISSUE TITLE
Option to not display leading zero in track duration

### ISSUE THREAD

**Issue by teearremm** [cmus/cmus#553]
Currently the track duration shows as MM:SS - i.e. always shows 2 digits even if the track is less than 10 minutes long (as most are):

![leading_zero](https://cloud.githubusercontent.com/assets/22779760/19289738/2cd29ba4-8fda-11e6-82f3-375f3c013ce6.png)

I think it would look nicer to only show the leading digit if it's nonzero, and a space otherwise (to preserve the alignment):

![no_leading_zero](https://cloud.githubusercontent.com/assets/22779760/19289739/2cd63bc4-8fda-11e6-9b2f-78833edb17ff.png)

This would also be more consistent with the hours display, which only shows if the value is nonzero, and only shows the necessary number of digits.

I couldn't find any configuration options to display the date differently (let me know if it exists and I'm missing it). I can see several ways this could be implemented:
1. Change the behavior of %d so it does not show a leading zero if the track is less than 10 minutes
2. Introduce a new format character for a duration without leading zeroes (%D is already used for disc number, so I'm not sure what the obvious choice would be here)
3. Introduce an additional configuration option that changes the behavior of %d to not show a leading zero

I can put in a pull request for option 1 right now, the other 2 would take a bit longer.

Let me know what you think.

Thanks,
Taylor

**Comment by mahkoh** [comment]
This looks like a reasonable feature. I would prefer option 3.
