### ISSUE TITLE
factivate outside of FILTERS_VIEW

### ISSUE THREAD

**Issue by s3rb31** [cmus/cmus#554]
Hello,

according to the man page the console command **factivate** should disable all the filters, if no argument is passed:  "If no arguments given then all filters are unactivated."

But I noticed that due to the nature of it's implementation, it would try to edit one filter after another, if no filter has changed between the calls to the function (e.g. no filter activated via view 6 or keybindings).

That of course is utterly annoying. When I am in view 1 or 2 and I am not sure if there are active filters, I will press a keybinding (factivate with no args) to disable all the filters. But if there was no filter active, this would take me to the console to edit a filter. This of course blocks any further interaction with CMus because everything will end up in the console. 

I looked into the the code and found the corresponding function which is responsible for the odd behaviour. A relatively small patch fixes the issue:

```
--- a/filters.c	2016-10-12 16:57:59.859825214 +0200
+++ b/filters.c	2016-10-12 17:03:02.147423231 +0200
@@ -27,6 +27,7 @@
 #include "file.h"
 #include "ui_curses.h"
 #include "xmalloc.h"
+#include "options.h"
 
 #include <stdio.h>
 #include <ctype.h>
@@ -142,8 +143,14 @@
 		if (f->act_stat != f->sel_stat)
 			unchanged = 0;
 	}
-	if (unchanged)
-		edit_sel_filter();
+
+    if (unchanged)
+    {
+        if (cur_view == FILTERS_VIEW)
+		    edit_sel_filter();
+        else
+            return;
+    }
 
 	/* mark visited and AND together all selected filters
 	 * mark any other filters unvisited */
```

If wanted i will create a pull request, but anyone might feel free to implement this fix. 

Thanks for the great software and regards,

s3rb31

**Comment by S3RB31** [comment]
This is not a feature request. There is no feature requested but rather one found. xD

The behaviour of the _factivate_ command is caused by the fact that both the _cmd_factivate_ function and _cmd_win_activate_ eventually will call _filters_activate_. 

_cmd_win_activate_ of course will only do it, if the current view is equal to FILTERS_VIEW. But factivate works in all views.

I don't think that it is intended to call _edit_sel_filter_ from any view but from the FILTERS_VIEW. If this is intentional, than please lets state this somewhere in the manpage.

**Comment by mahkoh** [comment]
I can't reproduce the issue. Please provide a sequence of commands that causes this.

**Comment by S3RB31** [comment]
Oh, you were slightly too fast. ;)

```
Steps to reproduce:
-    :bind common O factivate
-    go to view 1 or 2
-    Press O more than once    
```

**Comment by mahkoh** [comment]
factivate is broken because

* it behaves differently when called from the command line and via a command

* the behavior described ITT seems wrong too

**Comment by S3RB31** [comment]
I have created a pull request for this one. I think it should fix both bugs, although I am not sure where the first one originates from. The problem seems to lie somewhere deeper in the call stack than _edit_sel_filter_. Might be worth investigating.
