### ISSUE TITLE
japanese artists

### ISSUE THREAD

**Issue by bit188** [cmus/cmus#566]
hello,

i am having this issue:
https://github.com/cmus/cmus/issues/417
https://github.com/cmus/cmus/issues/103

is there a way to fix this without building cmus from source? thank you.

**Comment by Wang-Yue** [comment]
does the problem happen on other systems (such as Mac OS X or FreeBSD) that don't use glibc?

**Comment by bit188** [comment]
i have not tested it myself but a report from someone else who uses cmus is that it is not present on os x

**Comment by mahkoh** [comment]
Closing as duplicate of #418. There is currently no way to fix this without recompiling.
