### ISSUE TITLE
relicense cue.{h, c}

### ISSUE THREAD

**Issue by Wang-Yue** [cmus/cmus#570]
currently there's no non-GPL cue C library. If these two files could be relicense to BSD/MIT, we could make it a separate library that other project can use.

**Comment by mahkoh** [comment]
No.

**Comment by mahkoh** [comment]
To clarify, there are multiple reasons why I won't do this:

1. cmus has always been under a GPL license. I've written this code as part of cmus and hence it is licensed under GPL2+. cmus will always stay under this license (modulo a switch to GPL3+.) The GPL protects the freedoms and rights of small developers such as ourselves.

2. The code is not particularly comprehensive. All it can do is parse cue files and it does so in a very lazy fashion, ignoring some transgressions that violate the original spec. Furthermore it does not even provide any way to diagnose why parsing failed. As such it is not suitable for a standalone library. It does the minimal amount of work necessary to replace the old cue plugin as it was used in cmus.
