### ISSUE TITLE
Install from source Ubuntu 16.04 -- dependencies missing

### ISSUE THREAD

**Issue by thewaywest** [cmus/cmus#576]
**[SOLVED] Summary**

_Cleaned the system of previous installs_

`$ sudo apt purge cmus && sudo apt autoremove   # if installed from repo`
`$ rm -r ~/.config/cmus && rm -r ~/.cmus   # where local cmus settings may be stored`
`$ sudo updatedb   # doesn't the linux file db update automatically??`
`$ locate cmus   # identify and remove any remaining files`

_Downloaded latest build from github_

`$ cd ~/Projects && git clone https://github.com/cmus/cmus.git`
`$ cd cmus`

_Install build dependencies (r 2.7.1 rc)_

`$ sudo apt-get install libncurses5-dev libncurses5w-dev libpulse-dev libmodplugs-dev libcddb2-dev libsystemd-dev libavformat-dev libflac-dev libao-dev libcdio-dev libcdio-cdda-dev libvorbis-dev libopusfile-dev libroar-dev libdiscid-dev libsamplerate0-dev libmpcdec-dev libmad0-dev libmp4v2-dev libasound2-dev libjack-dev libcue-dev`

_Configure build and install_

`$ ./configure   # AY/YM, Wave, AAC and art streamer are missing from the above packages`
`$ sudo make install`
`$ cmus   # if all goes well.... enjoy!`

- - - 

_Linux [ ] 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux_

Having problems with the Ubuntu package for cmus, I'm building from source. I've been working through missing dependencies -- which apparently are many. I couldn't find a *packages* file to help me out here (is there one?), instead scanned the *configure* script to see what he system was searching for. 

A number of the required packages are missing. Below are the results of _configure_ :

> checking for program gcc... /usr/bin/gcc
> checking for program gcc... /usr/bin/gcc
> checking for CFLAGS -std=gnu11 -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... yes
> checking for CFLAGS -Wold-style-definition... yes
> checking for CFLAGS -Wno-pointer-sign... yes
> checking for CFLAGS -Werror-implicit-function-declaration... yes
> checking for CFLAGS -Wno-unused-parameter... yes
> checking for CFLAGS -Wno-missing-field-initializers... yes
> checking if CC can generate dependency information... yes
> checking byte order... little-endian
> checking for DL_LIBS (-ldl -Wl,--export-dynamic)... yes
> checking for PTHREAD_LIBS (-lpthread)... yes
> checking for realtime scheduling... yes
> checking for program pkg-config... /usr/bin/pkg-config
> checking for NCURSES_LIBS (pkg-config)... -lncursesw -ltinfo
> checking for NCURSES_CFLAGS (pkg-config)... -D_GNU_SOURCE -I/usr/include/ncursesw
> checking for working ncurses setup... yes
> checking for function resizeterm... yes
> checking for function use_default_colors... yes
> checking for ICONV_LIBS (-liconv)... no
> assuming libc contains iconv
> checking for working iconv... yes
> checking for header <byteswap.h>... yes
> checking for function strdup... yes
> checking for function strndup... yes
> checking for CDDB_LIBS (pkg-config)... no
> checking for CDDB_LIBS (-lcddb)... no
> checking for CDIO_LIBS (pkg-config)... no
> checking for CDIO_LIBS (-lcdio_cdio -lcdio -lm)... no
> checking for FLAC_LIBS (pkg-config)... no
> checking for FLAC_LIBS (-lFLAC -lm)... no
> checking for MAD_LIBS (pkg-config)... no
> checking for MAD_LIBS (-lmad -lm)... no
> checking for MODPLUG_LIBS (pkg-config)... no
> checking for MODPLUG_LIBS (-lmodplug -lstdc++ -lm)... no
> checking for header <mpc/mpcdec.h>... no
> checking for header <mpcdec/mpcdec.h>... no
> checking for VORBIS_LIBS (pkg-config)... no
> checking for VORBIS_LIBS (-lvorbisfile -lvorbis -lm -logg)... no
> checking for OPUS_LIBS (pkg-config)... no
> *** Package opusfile was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `opusfile.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'opusfile' found
> checking for LIBSYSTEMD_LIBS (pkg-config)... no
> *** Package libsystemd was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `libsystemd.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'libsystemd' found
> checking for WAVPACK_LIBS (pkg-config)... no
> checking for WAVPACK_LIBS (-lwavpack)... no
> checking for header <mp4v2/mp4v2.h>... no
> checking for header <mp4.h>... no
> checking for header <neaacdec.h>... no
> checking for FFMPEG_LIBS (pkg-config)... no
> *** Package libavformat was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `libavformat.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'libavformat' found
> *** Package libavcodec was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `libavcodec.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'libavcodec' found
> checking for header <ayemu.h>... no
> checking for PULSE_LIBS (pkg-config)... -lpulse
> checking for PULSE_CFLAGS (pkg-config)... -D_REENTRANT
> checking for ALSA_LIBS (pkg-config)... no
> *** Package alsa was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `alsa.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'alsa' found
> checking for JACK_LIBS (pkg-config)... no
> *** Package jack was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `jack.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'jack' found
> checking for SAMPLERATE_LIBS (pkg-config)... no
> *** Package samplerate was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `samplerate.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'samplerate' found
> checking for AO_LIBS (pkg-config)... no
> checking for AO_LIBS (-lao)... no
> checking for program artsc-config... no
> checking for header <sys/soundcard.h>... no
> checking for header <sys/audioio.h>... no
> checking for ROAR_LIBS (pkg-config)... no
> *** Package libroar was not found in the pkg-config search path.
> *** Perhaps you should add the directory containing `libroar.pc'
> *** to the PKG_CONFIG_PATH environment variable
> *** No package 'libroar' found

.. and the result of _sudo make install_:

> INSTALL /usr/local/bin/cmus
> INSTALL /usr/local/bin/cmus-remote
> INSTALL /usr/local/lib/cmus/ip/wav.so
> INSTALL /usr/local/lib/cmus/ip/cue.so
> INSTALL /usr/local/lib/cmus/op/pulse.so
> INSTALL /usr/local/share/cmus/gruvbox-alt.theme
> INSTALL /usr/local/share/cmus/rc
> INSTALL /usr/local/share/cmus/zenburn.theme
> INSTALL /usr/local/share/cmus/solarized-dark.theme
> INSTALL /usr/local/share/cmus/night.theme
> INSTALL /usr/local/share/cmus/green-mono-88.theme
> INSTALL /usr/local/share/cmus/gruvbox.theme
> INSTALL /usr/local/share/cmus/cyan.theme
> INSTALL /usr/local/share/cmus/default.theme
> INSTALL /usr/local/share/cmus/solarized-light.theme
> INSTALL /usr/local/share/cmus/gray-88.theme
> INSTALL /usr/local/share/cmus/green.theme
> INSTALL /usr/local/share/cmus/xterm-white.theme
> INSTALL /usr/local/share/cmus/jellybeans.theme
> INSTALL /usr/local/share/man/man1/cmus.1
> INSTALL /usr/local/share/man/man1/cmus-remote.1
> INSTALL /usr/local/share/man/man7/cmus-tutorial.7
> INSTALL /usr/local/share/doc/cmus/examples/cmus-status-display

... so at least the core did install, minus the ability to play almost anything :). The interface is missing something as well, however, basically a blank two-panel screen with no text, and no response to commands using ":".

To get my local env set up, any assistance appreciated. _Including_ "ohmygoddon'tbuildonubuntu", but only if your platform is really a solution to my headaches here. I am doing most of my other work on this OS, so would prefer not to switch on account of a music player I can't build.

Thanks for your experience ~

**Comment by thewaywest** [comment]
so far I have ferreted out _libncurses5-dev, libncurses5w-dev, libpulse-dev_

**Comment by thewaywest** [comment]
almost all dependencies met... but run fails with a  blank screen. when i uninstall local build, and reinstall from repo, it _also_ fails, with the following errors. Assume there isa config file hidden somewhere that needs attention. Where?

./cmus: Error: no such option dsp.ao.device_interface
./cmus: Error: no such option input.cdio.priority
./cmus: Error: no such option input.cue.priority
./cmus: Error: no such option input.ffmpeg.priority
./cmus: Error: no such option input.flac.priority
./cmus: Error: no such option input.mad.priority
./cmus: Error: no such option input.modplug.priority
./cmus: Error: no such option input.mpc.priority
./cmus: Error: no such option input.opus.priority
./cmus: Error: no such option input.vorbis.priority
./cmus: Error: no such option input.wav.priority
./cmus: Error: no such option lib_add_filter
./cmus: Error: no such option mpris

**Comment by mahkoh** [comment]
These are not serious errors. These are simply new options that are in your autosave file which don't exist in the older version.

If you're getting a blank screen then I think you've hit #337. The solution is described in there: Open `.config/cmus/rc` (or `.cmus/rc`, whichever exists) and add the following line: `set output_plugin=alsa`. Make sure to compile with alsa support.

**Comment by thewaywest** [comment]
thank mahkoh. i'll find and install the correct alsa package. meanwhile, the only RC that is created is a r/o file in /usr/local/share/cmus... seems the install should have added to ~/.config... ?

**Comment by mahkoh** [comment]
You can create either `~/.config/cmus` or `~/.cmus` and create a file named `rc` in either one of them. But you should only create one of those directories. If both exists, cmus will only look at `~/.cmus`.

**Comment by thewaywest** [comment]
installed libasound2-dev, added local _rc_ file to ~/.config/cmus, and populated with the output value. the /usr/local/shared files are r/o and owned by root due to install.

SOME SUCCESS that cmus does run as root... but is still a blank slate when run as self. 

found that files in .config/cmus had bee touched by (and owned by) root. chown -R fixes permissions, but not the problem. yet.

**Comment by mahkoh** [comment]
If your user can read `~/.config/cmus/rc` (and `~/.cmus` doesn't exist) and it contains `set output_plugin=alsa`, then cmus should at least start.

**Comment by thewaywest** [comment]
yes - starts. still working on this config issue. once i get this to build cleanly, i'll post a complete how-to as summary.

there is a problem with screen painting since the first source install -- the top edge seems to flicker and no text appears even in the command status line. the problem affects install of the packaged version as well.

**Comment by thewaywest** [comment]
ok, backed off of current master and built from latest stable 2.7.0.

**Comment by thewaywest** [comment]
Have built mostly complete. Starts without errors, plays music, and since I bound to my music partition directly, no longer has funky playlist effects.

**Could not find**
- ICONV is contained in libc -- maybe check no longer needed?
- library for naacenc  ... but don't have any .aac files anymore so left out
- artsc -- only references I can find to this file are from 2009 and before -- still in use?
- ayemu - AY/YM support... ?
- wave support... yeaaaahh

**Notes**
- I don't use alsa out on this machine, so didn't actually need the special output line in my RC file - rebuilds without that file are working without it
- is there **_really_** no Packages or Dependencies file with the source? shouldn't there be? maybe there are too many flavors of linux/etc to do so. I'll add here anyway.
- there was (and is) some problem with my Guake terminal config, that no longer presents cmus correctly -- red herring trying to debug the build
