### ISSUE TITLE
adding video playback capability

### ISSUE THREAD

**Issue by mrkapqa** [cmus/cmus#580]
Hello ,

would it be possible to combine this beautiful player with another say mpv to combine audio and video playback?

thanks for consideirng

rich

**Comment by nefthy** [comment]
No, that's not possible and there are no plans to implement anything related to video.

**Comment by mrkapqa** [comment]
not possible? why? did you build this software? sorry for insisting.

**Comment by flyingmutant** [comment]
Not sure if trolling or not — cmus is a console audio player. Playing video in console is possible, but not something a lot of people are interested in, so cmus will remain audio-only.
