### ISSUE TITLE
radio stream errors

### ISSUE THREAD

**Issue by yepstat** [cmus/cmus#582]
BUG 1

![ss](https://cloud.githubusercontent.com/assets/23515168/20375495/c4c912f0-ac7f-11e6-8f55-0bb08a4124b3.png)

BUG 1

Whenever using cmus and playing various radio streams for more than 3 hours, cmus will  stop playing anything until the **~/.config/cmus** folder is nuked followed by clearing the cache and copy buffers `sudo sysctl --write vm.drop_caches=3`.

BUG 2

If it takes more than 20 seconds to connect to some radio stream, the UI will stop working **visually** as if it freezed, except I can stop, play and choose other streams even without visual confirmaiton. Re-launching cmus doesn't resolve the freezed UI, only the nuking and buffers clearing steps are solving it.

---

Seems bug 2 have been reported https://github.com/cmus/cmus/issues/574 earlier

**Comment by mahkoh** [comment]
>folder is nuked followed by clearing the cache and copy buffers sudo sysctl --write vm.drop_caches=3

Does not sound like a cmus bug.

>If it takes more than 20 seconds to connect to some radio stream, the UI will stop working visually as if it freezed, except I can stop, play and choose other streams even without visual confirmaiton.

I don't understand what you mean by this.

>Re-launching cmus doesn't resolve the freezed UI, only the nuking and buffers clearing steps are solving it.

You probably have `resume` enabled which will try to play the same track again on startup.

**Comment by wakic** [comment]
https://www.dropbox.com/s/dze7lwgzc3607h2/yolo.mp4?dl=0

0:00 to 0:50 the freezed UI in action. Switching between the radio stream stations, changing the audio up and down, still nothing was visible to reflect the changes. 

0:50 - 2:00 Relaunching and killing cmus didn't helped.

2:00 the folder **~/.config/cmus** was deleted, followed by adding new radio stream stations by hand. The stations was launched instantly, and the UI was working as if nothing happened.

**Comment by wakic** [comment]
```bash
~ > equery uses cmus
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-sound/cmus-2.7.1:
 U I
 - - aac           : Enable support for MPEG-4 AAC Audio
 + + alsa          : Add support for media-libs/alsa-lib (Advanced Linux Sound Architecture)
 - - ao            : Use libao audio output library for sound playback
 - - cddb          : Access cddb servers to retrieve and submit information about compact disks
 - - cdio          : use libcdio for CD support 
 - - cue           : enable CUE sheet parsing
 - - debug         : Enable extra debug codepaths, like asserts and extra output. If you want to get meaningful backtraces see
                     https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces
 - - discid        : enable reading the ID of the inserted CD
 - - examples      : Install examples, usually source code
 + + ffmpeg        : Enable ffmpeg/libav-based audio/video codec support
 + + flac          : Add support for FLAC: Free Lossless Audio Codec
 - - jack          : Add support for the JACK Audio Connection Kit
 - - libsamplerate : Build with support for converting sample rates using libsamplerate
 + + mad           : Add support for mad (high-quality mp3 decoder library and cli frontend)
 - - mikmod        : Add libmikmod support to allow playing of SoundTracker-style music files
 - - modplug       : Add libmodplug support for playing SoundTracker-style music files
 - - mp4           : Support for MP4 container format
 - - musepack      : Enable support for the musepack audio codec
 + + opus          : enable support for media-libs/opusfile
 - - oss           : Add support for OSS (Open Sound System)
 - - pidgin        : install support script for net-im/pidgin
 - - pulseaudio    : Add support for PulseAudio sound server
 - - tremor        : use libivorbis from media-libs/tremor instead of media-libs/libvorbis
 + + unicode       : Add support for Unicode
 + + vorbis        : Add support for the OggVorbis audio codec
 - - wavpack       : Add support for wavpack audio compression tools
```

```bash
~ > cmus --plugins
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: ac3 aif aifc aiff ape au mka shn tta wma aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  alsa
```

**Comment by mahkoh** [comment]
Try the current HEAD.

**Comment by nefthy** [comment]
I have a live ebuild for building against latest git here: https://github.com/nefthy/gentoo-overlay/tree/master/media-sound/cmus
