### ISSUE TITLE
2.8.0 & related stuff

### ISSUE THREAD

**Issue by flyingmutant** [cmus/cmus#583]
#506 

- [x] tag 2.8.0-rc0
- [x] write release notes for 2.8.0-rc0
- [ ] put 2.8.0-rc0 on cmus.github.io
- [x] cherry-pick important fixes for 2.7.2
- [ ] tag 2.7.2
- [ ] write release notes for 2.7.2
- [ ] unbreak Travis FFMPEG (see #590)

After 2.8.0 release:
- [ ] rename `maint` branch to `main-2.7`, create new `maint` from `v2.8.0`
- [ ] retire `pu` branch

**Comment by Wang-Yue** [comment]
Congrat!

**Comment by KamranMackey** [comment]
@Wang-Yue it's `Congrats!`, dude. :) Sorry for being the grammar police but yeah 😛

Anyways, yeah @flyingmutant, can't wait for the final 2.8.0 release! :)

**Comment by mahkoh** [comment]
I've created a 2.7.2 branch here: https://github.com/mahkoh/cmus/commits/test-v2.7.2

**Comment by flyingmutant** [comment]
@mahkoh great job!

I think cf4467a, 96a1eef, 0fae0b4, 42ba8b7, 6027e87, fa7cb42, 5463c69 can go in as well.

**Comment by mahkoh** [comment]
Done

**Comment by flyingmutant** [comment]
More 2.7.2 material: e605bd00a27623b65bef3a56409b1a7cb34ed42f, 49a5a56f0be788bcfc59a7959d688e2846e5bf73, 84f33584be9150d9783751dc3ccbd726e33072c7.

**Comment by mahkoh** [comment]
Done

**Comment by mahkoh** [comment]
See also #613.

**Comment by flyingmutant** [comment]
Also https://github.com/cmus/cmus/pull/633.

**Comment by flyingmutant** [comment]
Also #647 and #652.

**Comment by Wang-Yue** [comment]
#679 and #680 are pretty significant.

**Comment by mahkoh** [comment]
All done.

**Comment by ganwell** [comment]
I use 2.8 since quite a while, works well, I'm looking forward to the release.

**Comment by mahkoh** [comment]
The only open bug that I would consider critical is #574 which was introduced in 2.8.

**Comment by mahkoh** [comment]
The only open bug that I would consider critical is #574 which was introduced in 2.8.

**Comment by Wang-Yue** [comment]
seems the release has been delayed by almost a year.

**Comment by zethra** [comment]
Any idea when 2.8 will be released?

**Comment by Wang-Yue** [comment]
I don't see #574 at all --- I use cmus daily.

**Comment by philc** [comment]
@flyingmutant given your business with the kiddo, can you ramp up another one of the recent commiters on the release process so you don't have to be gating?

**Comment by flyingmutant** [comment]
Please welcome contender for the most delayed software release ever: [cmus 2.8.0](https://github.com/cmus/cmus/releases/tag/v2.8.0)!
