### ISSUE TITLE
How to setup when pulseaudio is removed? thx

### ISSUE THREAD

**Issue by LzyAWP-Fred** [cmus/cmus#588]
I removed my pulseaudio and try to use ALSA direct output.
Like Rhythmbox working great, but cmus show "Error: opening audio device: Invalid argument".

My rc file is like this:
"""
set dsp.alsa.device=default
set mixer.alsa.device=default
set mixer.alsa.channel=PCM
set output_plugin=alsa
"""

**Comment by mahkoh** [comment]
See https://wiki.archlinux.org/index.php/Cmus#Using_cmus_with_alsa

**Comment by LzyAWP-Fred** [comment]
Thank you for your response. I tried this before, but it seems not working.

**Comment by LzyAWP-Fred** [comment]
That is the configuration of VLC. It works well.
—————————————————————————————————
# Audio output module (string)
aout=alsa

# Audio output device (string)
alsa-audio-device=hw:CARD=C20,DEV=0

# Audio output channels (integer)
#alsa-audio-channels=6
—————————————————————————————————-

How to set CMUS music player?

I tried:
set output_plugin=alsa
set dsp.alsa.device=hw:CARD=C20,DEV=0
set mixer.alsa.channel=6

Shows: Error: opening audio device: Invalid argument
