### ISSUE TITLE
How to setup cmus when pulseaudio is removed?

### ISSUE THREAD

**Issue by LzyAWP-Fred** [cmus/cmus#589]
I removed pulseaudio and edited asound.conf, so my chrome and Rhythmbox has sound.

But my cmus doesn't have sound.

My rc file is like this: 
```
set dsp.alsa.device=default
set mixer.alsa.device=default
set mixer.alsa.channel=PCM
set output_plugin=alsa
```

By the way, I don't want to use jack plugin.. 

1) `uname -a`:
```
LinuX 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
```

3) `cmus --plugins`:
```
Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by mahkoh** [comment]
I already answered your question in #588

**Comment by vinnyA3** [comment]
Thanks for this.  I forgot to set the cmus options :+1:
