### ISSUE TITLE
Remember the playlist position of the track if `resume` is on

### ISSUE THREAD

**Issue by flyingmutant** [cmus/cmus#6]
[From the cmus-devel archives]

The resume feature is nice, but I think it's usefullness could be enhanced if the resume information also included playlist position, if that's the mode that cmus was in at quit. As it is now, when cmus starts up in the playlist view/mode and resumes playing the file, there's no indication of the current track in the playlist, and after playing the file, the playlist is started playing from the beginning.

**Comment by quite** [comment]
Certainly this is how it should work.

**Comment by fossette** [comment]
I'm interested by that feature too, kind of a PERMANANT PLAY QUEUE.  Perhaps a CIRCULAR option should be added to CMUS to enqueue the song that has just been played back into the PLAY QUEUE.  Right now, I reload the play queue when it's exhausted.  I'm always plesently surprised when I powerup the computer and hear CMUS resume the play queue where it left off.

I may look into it myself, but I'm not sure how quick I'll be to understand the source code.

**Comment by fossette** [comment]
While waiting for cmus to have a resumable play list, you guys can try the cmus fork here:
https://github.com/fossette/cmus-circular/wiki
My interpretation of the resume feature is instead based on the cmus play queue in circular mode.

Dominique.

**Comment by pgaskin** [comment]
Fixed in #1325.
