### ISSUE TITLE
Bind <C-n> and <C-p> to jump to next/previous step

### ISSUE THREAD

**Issue by wikimatze** [cmus/cmus#603]
I really love your plugin instead of pressing `b` to go to the next song or `z` to go the previous song, I would like to have the common pattern of vim autocompletion pressing `<C-n>` and `<C-p>` to go to the next/previous song.

I've tried 

```
unbind -f common b
bind common Ctrl-n player-next
```

And other combinations, but I always get `cmus: Error: invalid key 'Ctrl-n'`.

**Comment by nefthy** [comment]
try ^N instead

**Comment by wikimatze** [comment]
Hi @nefthy, that is the solution:

```
bind common ^N player-next
bind common ^P player-prev
```

Thank you very much!

**Comment by nefthy** [comment]
cmus does not discriminate betwee ^n and ^N, but fails with the former. not quite that intuitive.

**Comment by wikimatze** [comment]
@nefthy thanks for the clarification.
