### ISSUE TITLE
2.8.0-rc0: Error: opening audio device: internal error

### ISSUE THREAD

**Issue by seandarcy** [cmus/cmus#607]
---
On fedora 25, output_plugin=pulse.  cmus opens, but when I try to play a file I get:

Error: opening audio device: internal error

I got this with 2.7, so got 2.8.0-rc0, and rebuilt with DEBUG=2, but cmus-debug.txt has nothing.

I'm just on the console. No  X window running.

1) `uname -a`:
```
4.9.3-200.fc25.x86_64 #1 SMP Fri Jan 13 01:01:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
2) `cmus --version`:
```
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
cmus --plugins
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  oss
  jack
  ao
  arts

```

**Comment by mahkoh** [comment]
Try starting pulse before cmus.

**Comment by seandarcy** [comment]
Yes, I forgot fedora doesn't start pulseaudio until X starts.

Works like a charm. Great program !

**Comment by mahkoh** [comment]
That shouldn't happen though. Pulseaudio should be started automatically via socket activation.

**Comment by mahkoh** [comment]
Maybe you need to `systemctl --user enable pulseaudio.socket`.

**Comment by seandarcy** [comment]
Ok, worked. Then I rebooted . Always a Bad Idea.

Now I'm getting the same error, but pulseaudio is running on boot:

[video@sixcore ~]$ pacmd stat
Memory blocks currently allocated: 1, size: 63.9 KiB.
Memory blocks allocated during the whole lifetime: 35, size: 1.9 MiB.
Memory blocks imported from other processes: 0, size: 0 B.
Memory blocks exported to other processes: 0, size: 0 B.
Total sample cache size: 0 B.
Default sample spec: s16le 2ch 44100Hz
Default channel map: front-left,front-right
Default sink name: alsa_output.usb-AudioQuest_inc._AudioQuest_DragonFly-00.analog-stereo
Default source name: alsa_output.usb-AudioQuest_inc._AudioQuest_DragonFly-00.analog-stereo.monitor
.......................

[video@sixcore ~]$ grep output  .config/cmus/autosave
set output_plugin=pulse

Sigh.

**Comment by seandarcy** [comment]
Even paplay doesn't work.

aplay /home/video/Music/Route_66.wav
Connection failure: Connection refused
pa_context_connect() failed: Connection refused 

It's not a cmus issue. I've posted on the PA discuss list. Hopefully, I'll get a response.
