### ISSUE TITLE
CUR_STREAM_VERS not defined in wavpack 5.0.0

### ISSUE THREAD

**Issue by jolange** [cmus/cmus#608]
`CUR_STREAM_VERS` is no longer defined in wavpack 5.0.0, leading to a compilation warning:
```
ip/wavpack.c: In function 'wavpack_open':
ip/wavpack.c:214:5: warning: "CUR_STREAM_VERS" is not defined [-Wundef]
 #if CUR_STREAM_VERS > 0x404
     ^~~~~~~~~~~~~~~
```

This could be solved using
```
#if defined CUR_STREAM_VERS && CUR_STREAM_VERS > 0x404
```
but [according to the developers](https://hydrogenaud.io/index.php/topic,111822.msg922950.html#msg922950) it was not intended to be used in the first place.

**Comment by nefthy** [comment]
I don't think the check was correct in the first place. `CUR_STREAM_VERS` in not intended to be a compile time version check. It reads more like a file format version and is private to Wavpack anyhow.

**Comment by jolange** [comment]
So, what should I do here? The check was introduced to allow compilation with wavpack < 4.40.0. Do we still need to support that at all? 4.40 was released > 10y ago, so IMO we can drop that check and require wavpack > 4.40.

**Comment by mahkoh** [comment]
>Do we still need to support that at all?

No.

>and require wavpack > 4.40.

This requires a check in configure.

**Comment by jolange** [comment]
OK, PR on the way...
