### ISSUE TITLE
Error while initializing MPRIS ?

### ISSUE THREAD

**Issue by wichtounet** [cmus/cmus#609]
Hi, 

Since this morning, I have a problem with cmus, everytime I run it I have this issue: 

```
cmus: Error: an error occured while initializing MPRIS: No such file or directory. MPRIS will be disabled.
cmus: Press <enter> to continue.
```

Apart from this, the complete playlist has been cleared, but it seems to be working since I can play my music if I add it back. 

Is there is something I can do to fix this ? 

Thanks

1) `uname -a`:
```
Linux frigg 4.4.26-gentoo #1 SMP Fri Dec 2 08:57:21 CET 2016 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
```

**Comment by mahkoh** [comment]
Either start a dbus session bus before cmus or disable mpris in the settings.

**Comment by wichtounet** [comment]
I've disabled MPRIS in the settings and it is working correclty now on all my machines. Thanks.

**Comment by xlwyx** [comment]
https://t.me/GNULinuxcommunity/44965
I have a problem when I start cmus on terminal...  why MPRIS is disabled?

**Comment by pualt164i** [comment]
Don't go through all theses winding roads. Just install MusikCube, it's really rocks!!!

**Comment by Griiggss** [comment]
> Don't go through all theses winding roads. Just install MusikCube, it's really rocks!!!

This one right here was the best working solution for me. Thanks, @pualt164i
