### ISSUE TITLE
FLAC support (reading CUE files)

### ISSUE THREAD

**Issue by Chinggis6** [cmus/cmus#611]
Even though, thankfully, cmus plays `.FLAC` and reads the corresponding `.CUE` file displaying the track list, it <s>doesn't</s> never plays **the last track**  on the list, ignoring it and switching immediately to the next album or artist.

I really like cmus and rely on it much but most of my music library is in FLAC/CUE format, and it is one of the few music players on Linux that supports FLAC.

For that reason, stated above, I use Clementine music player to play my files.
It is graphical with un-minimalistic interface, so I'd really like cmus to play the last song so I use it everytime and everywhere.

:sunglasses: 

---
I'm using the latest cmus version (v2.7.1), with no plugins, on Fedora 25 (under urxvt terminal on i3 window manager).

**Comment by mahkoh** [comment]
>I'm using the latest cmus version, with no plugins, on Fedora 25

Nobody here knows which version that is.

**Comment by mahkoh** [comment]
2.7.1 is ancient. Try building from source.

**Comment by Chinggis6** [comment]
Thank you, it really solved the problem.
Now the last track in the list plays thankfully.
Though I needed to reconfigure and rebuild multiple times, research more, and find the libraries and packages elsewhere for Fedora Linux that are otherwise unavailable.

I wish cmus packaged its latest binary for **Fedora**, and it to be installable through `dnf install cmus -y` without further issues, and also to port to Windows, so users won't miss cmus when on they find themselves in Windows for some reasons.

Thank you again, and I wish further improvement and enhancement for cmus project.

:headphones:

**Comment by mahkoh** [comment]
I've created two issues to track this #615, #616.

**Comment by nefthy** [comment]
> 2.7.1 is ancient. Try building from source.

while true, 2.7.1 is our official stable release. Most distros will ship that.

**Comment by ackalker** [comment]
True, but buiding from latest upstream source is always a good idea to find out if any bugs have been fixed and so those fixes will be part of the next release.
