### ISSUE TITLE
Package cmus as a flatpack

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#615]
There have been repeated issues where users had trouble compiling cmus because they didn't know how to get the needed libraries.

We should consider providing a flatpack package at least for testing. One has to think about which plugins should be contained in such a package.

**Comment by pgaskin** [comment]
A [Flatpak](https://flathub.org/apps/details/io.github.cmus.cmus) was [released](https://github.com/cmus/cmus/issues/1007#issuecomment-736326751) a while ago.
