### ISSUE TITLE
Provide compile instructions for various distributions

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#616]
On various "user-friendly" distributions it's often not clear how to get the needed libraries and header files to compile cmus. We should create wiki pages that document this for at least the following distributions:

* Ubuntu

* Fedora

**Comment by elundmark** [comment]
Just a comment/suggestion for Ubuntu (xubuntu 17.04): I run these commands to get everything working. I'm also wondering if I maybe am doing this wrong? Maybe the build deps are too out of date?

First, enable the source code channel in "Software & Updates".

```bash
sudo apt-get build-dep cmus
cd ~
git clone https://github.com/cmus/cmus.git \
	&& cd cmus \
	&& ./configure \
	&& make \
	&& sudo make install
```

**Comment by geek1011** [comment]
Here are the debian/ubuntu build deps: `bash-completion, libao-dev, libasound2-dev (>= 1.0.11), libavcodec-dev, libavformat-dev (>= 6:10~), libswresample-dev, libcddb2-dev, libcdio-cdda-dev, libcue-dev, libdiscid-dev, libfaad-dev, libflac-dev, libjack-dev, libmad0-dev, libmodplug-dev, libmpcdec-dev, libncursesw5-dev, libopusfile-dev, libpulse-dev (>= 0.9.19), libroar-dev, libsamplerate0-dev, libvorbis-dev, libwavpack-dev, libsystemd-dev, pkg-config`

Most of those can be left out if you don't use the related input plugin or feature. libsystemd is for MPRIS DBus support. I'd also suggest you leave out libjack and libroar if you don't need it.

I also have debian package code here (in which case you also need quilt, devscripts, and dh-make): https://github.com/geek1011/cmus/tree/debian-package/debian

**Comment by pgaskin** [comment]
And Fedora: https://github.com/pgaskin/rpms/tree/master/cmus-testing ([prebuilt packages](https://pgaskin.net/rpm)).

**Comment by pgaskin** [comment]
package dependencies for various distros

<table><tbody>
<tr><th align="left">Debian/Ubuntu</th><td>apt install pkg-config libncursesw5-dev libfaad-dev libao-dev libasound2-dev libcddb2-dev libcdio-cdda-dev libcue-dev libdiscid-dev libavformat-dev libavcodec-dev libswresample-dev libflac-dev libjack-dev libmad0-dev libmodplug-dev libmpcdec-dev libsystemd-dev libopusfile-dev libpulse-dev libsamplerate0-dev libsndio-dev libvorbis-dev libwavpack-dev</td></tr>
<tr><th align="left">Fedora/RHEL</th><td>dnf install 'pkgconfig(ncursesw)' 'pkgconfig(alsa)' 'pkgconfig(ao)' 'pkgconfig(libcddb)' 'pkgconfig(libcdio_cdda)' 'pkgconfig(libcue)' 'pkgconfig(libdiscid)' 'pkgconfig(libavformat)' 'pkgconfig(libavcodec)' 'pkgconfig(libswresample)' 'pkgconfig(flac)' 'pkgconfig(jack)' 'pkgconfig(mad)' 'pkgconfig(libmodplug)' libmpcdec-devel 'pkgconfig(libsystemd)' 'pkgconfig(opusfile)' 'pkgconfig(libpulse)' 'pkgconfig(samplerate)' 'pkgconfig(vorbisfile)' 'pkgconfig(wavpack)'
</td></tr>
<tr><th align="left">+ RPMFusion</th><td>dnf install faad2-devel libmp4v2-devel</td></tr>
<tr><th align="left">Arch Linux</th><td>pacman -S pkg-config ncurses libiconv faad2 alsa-lib libao libcddb libcdio-paranoia libcue libdiscid ffmpeg flac jack libmad libmodplug libmp4v2 libmpcdec systemd opusfile libpulse libsamplerate libvorbis wavpack</td></tr>
<tr><th align="left">Alpine</th><td>apk add pkgconf ncurses-dev gnu-libiconv-dev alsa-lib-dev libao-dev libcddb-dev libcue-dev ffmpeg-dev flac-dev jack-dev libmad-dev libmodplug-dev elogind-dev opus-dev opusfile-dev pulseaudio-dev libsamplerate-dev libvorbis-dev wavpack-dev</td></tr>
<tr><th align="left">Termux</th><td>apt install libandroid-support ncurses libiconv ffmpeg libmad libmodplug opusfile pulseaudio libflac libvorbis libwavpack</td></tr>
<tr><th align="left">Homebrew</th><td>brew install pkg-config ncurses faad2 libao libcddb libcdio libcue libdiscid ffmpeg flac jack mad libmodplug mp4v2 musepack opusfile libsamplerate libvorbis wavpack</td></tr>
</tbody></table>
