### ISSUE TITLE
Abort command-line mode on ESC

### ISSUE THREAD

**Issue by nefthy** [cmus/cmus#618]
When pressing ESC after having entered something in command line mode in vim, the command line is cleared and the mode is exited.

I've missed that quite often in cmus and would like to implement it. I can't think of any backwards compatibility issues here.

**Comment by mahkoh** [comment]
But that already happens.

**Comment by nefthy** [comment]
That is not the case on my system, with gf7fc733. This has been the case for a long time now. 

I removed my .cmus/autosave and .cmus/rc files, in case some of my setting have an influence on this. That is not the case.

It seems like there is an invisible character in the command-line after pressing ESC since backspace only starts deleting characters after the second key press.

Any pointers how I can debug this?

Terminal is xterm 327

**Comment by mahkoh** [comment]
See cb677fb61d03bab94ed706e2a01477fc59c67a09

**Comment by nefthy** [comment]
Indeed ESC_DELAY=25 fixes this. The default delay seems way too long. I really thought this was not implemented/broken.
