### ISSUE TITLE
Duplicate and out of order Artists in Library tree view

### ISSUE THREAD

**Issue by indeedwatson** [cmus/cmus#619]
I used picard to tag the entire `Bach` folder with `Johann Sebastian Bach` as the Artist, as you can see in the screenshot. For some reason, the tag is repeated twice and in different order, and the `Art Tatum` tag is last when it should be first.
http://i.imgur.com/7ndEGCl.png

**Comment by mahkoh** [comment]
You'll need to provide the affected files.

**Comment by indeedwatson** [comment]
The .flac files? Where should I upload them?

**Comment by mahkoh** [comment]
It doesn't matter.

**Comment by indeedwatson** [comment]
Apologies, I forgot about replying to this, but here's two files with the same artist/album artist https://mega.nz/fm/56wCjTLI

And here's how they're shown with the same label, but repeated, and for some reason out of order: http://i.imgur.com/O9tPHON.png

**Comment by mahkoh** [comment]
Link does not work.

**Comment by indeedwatson** [comment]
Updated the link, try again!

**Comment by mahkoh** [comment]
The first track has the artistsort tag set to `Shostakovich, Dmitri Dmitrievich` but the second one has not.

**Comment by indeedwatson** [comment]
Sorry, then which tag is the one that cmus utilizes for the `Artist / Album` order? Is it `Artist`, `Album Artist`, `Artist sort order`? Or is it all 3? Cause if the latter, that's very incovenient, because cmus provides no information discerning the tags, it just says `Artist`, so the expected thing is that it will display the `Artist`, not different artists displayed as the same name because of some other tag that is not even displayed.

**Comment by indeedwatson** [comment]
Will this ever be addressed?

**Comment by mahkoh** [comment]
I don't think there is anything wrong. Patches are welcome though.

**Comment by indeedwatson** [comment]
I'm sorry I wish I knew enough coding to work on this but I don't. I'll make one less effort to explain the logic of what the problem is, and if you still think there's not one, then maybe you can explain why this would be intended behavior:

Let's say I have tracks 1 & 2. Both are composed by Mozart, so I want every Mozart track to be displayed under the tag `Mozart`. Now the metadata of `track 1` says `artist: Mozart` and `album artist: Rubinstein` (the latter being the pianist) and `track 2` says `Zimerman`.

Normally, if the media program uses the `artist` tag to categorize tracks, then all tracks with the `artist` tag `Mozart` will be displayed... under `Mozart`. If instead the program is going to use `album artist` to categorize then `track one` would be under `Rubinstein` and `track 2` under `Zimerman`.

Now, what cmus does is display `track 1` under `Mozart`, and `track 2` under _another_ `Mozart` unexplicably in a different alphabetical order. It should either display all tracks with the `Mozart` tag under the `Mozart` tag, don't you think?

The only fix for this is going into a tag editor and editing _every single `artist` tag_ to be `Mozart`, which means erasing a lot of metadata (which might be useful for other programs, or simply as information).

So if this is intended behavior, I'm really curious as to why?

**Comment by flyingmutant** [comment]
@indeedwatson as @mahkoh said, the original issue is caused by the presence of `ARTISTSORT` tag in some, but not all, tracks. Tree view is sorted by `ARTISTSORT` tags, which defaults to `ARTIST` if not present. The correct solution would be to either put proper `ARTISTSORT` tags in all tracks, or do not use them at all; there is nothing cmus can do.

**Comment by indeedwatson** [comment]
@flyingmutant The correct solution would be to sort under the tag which is displayed. If the tag that is used to sort is empty, then the field should be displayed as empty, not as some other tag, repeated multiple times. Every other music player I've used is capable of this, and any music player should not require me to lose metadata because it can't properly display tags and categorize them. My tags are fine, they contain the information they're supposed to contain, not the information that cmus arbitrarily is separating into two categories with the same name, because that's not what tags are for.

If this is considered too niche an issue and no one has time to address it, I completely understand, but the responses I'm given is that I have to go into all the music files and change *every single artist tag* and lose metadata, this is not a reasonable response and I'm struggling to figure out how this can be seen as "not an issue".

**Comment by flyingmutant** [comment]
@indeedwatson no one is asking you to delete metadata, please calm down. Your tags are wrong: some of 
 the tracks are missing `ARTISTSORT`. Add them, and everything will be fine.

As for the "correct solution", -sort tags exist explicitly so that how artists are sorted is different from what is displayed. They explicitly specify the ordering of artists in the library. There can be made a case for some heuristics which try to "fix" missing/inconsistent tags, but that is beyond the scope of this issue.

**Comment by indeedwatson** [comment]
@flyingmutant I'm calm, I'm just trying to make myself as clear as possible.

I have the `Artist Sort Order` tag set to Johann Sebastian Bach, and cmus keeps taking Album Artist Sort Order, or some other tag: http://i.imgur.com/hN9XMfR.png there you can see how the tags are set in picard, and how cmus still displays `Johann Sebastian Bach; Evgeni Koroliov` as one category, and `Koroliov, Evgeni` as another, and a duplicate `Johann Sebastian Bach` as yet another. The second `Johann Sebastian Bach` is the one where i went through all the tracks and did what I described: erase every tag containing the word `artist` (hence losing the performers names) and replaced it with Johann Sebastian Bach.

I even went to the trouble of creating an `ARTISTSORT` tag to make sure I followed your instructions exactly, and I filled that field with `fufuuf`, and as you can see in the image above, it did not fix the issue.

> sort tags exist explicitly so that how artists are sorted is different from what is displayed. They explicitly specify the ordering of artists in the library

What do you mean? In what case is it necessary or beneficial to the user to have 3 different `The Beatles` artists? Why would this be desirable? And how can the user know why cmus is doing this without opening an issue?

**Comment by flyingmutant** [comment]
cmus does prefer `Album Artist Sort Order` to `Artist Sort Order`, which it prefers to `Artist` for sorting (but not display).

Current rule is simple: if you want tracks to be sorted in the same place, sort-related tags must be the same.

Avoiding splitting of the "same" artist would require ignoring inconsistent -sort tags. Which can be done (patches welcome), but why not fix the tags to be consistent instead?

**Comment by indeedwatson** [comment]
Because the player should adapt to the tags, not adapt the tags to the player. Otherwise switching players or devices would require a whole metadata rewrite, and that's the complete opposite of the functions of tags: to organize a library according to the fields you want. If you want to sort by album artist, you display the album artist and you categorize by the tag you are displaying.

>Current rule is simple: if you want tracks to be sorted in the same place, sort-related tags must be the same.

this is far from simple. Simple would be: use *one* tag for something, the same that that is displayed. Having to modify several, arbitrary, non-displayed tags (which one has to find out by opening an issue in github) is not simple by any standards.

>but why not fix the tags to be consistent instead?

Because tags *should* be inconsistent, that's the point of them. An album might have a composer, a solo performer, a director, and an orchestra, all in one track. You're not giving me any reasonable explanations why the users should delete all that metadata to "fix" something that the music player should be able to handle by itself.

Again, I apologize for not knowing enough coding to attempt to fix this myself, and I understand if you or other maintainers not having time to fix it, but to brush this off as not an issue and tell users to delete metadata is not helpful, not only will it not be potentially addressed by someone else, but if someone has the same problem and they do a search on the issues they'll be less likely to come across this "solution" (and if they care less than me about their metadata, perhaps apply it) and understand the causes of it.

**Comment by holderbp** [comment]
I have a similar issue with these two tracks.  As far as I can see in Picard, they are now identical (track 6 was originally being sorted differently than the rest because it had an "Artist" tag after ripping while the others did not). But one (track 6) is being places by cmus in "<Various Artists>/Palookaville" while the other (track 7) is being placed under the album artist "Fatboy Slim".

https://drive.google.com/drive/folders/1zDs_ZmW4NVCe5VE3UVy6VujrCHjvsMqQ?usp=share_link
