### ISSUE TITLE
Execution of a program after the current track

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#622]
That would good, if cmus could execute a script, or a shell command after playing the current track. For example: I use a command to play music before sleeping, then it suspends the computer: 
'play /music ; systemctl suspend'

**Comment by mahkoh** [comment]
Sounds like this can be done by an external program using the dbus interface.

**Comment by music-fan** [comment]
How?

**Comment by Bew78LesellB** [comment]
@music-fan You can also set the configuration option `status_display_program` to a given script, which based on current cmus status (passed as parameter) will run some command...

From the man:
> status_display_program () [command]
>       This command, if not empty, is run every time cmus' status changes. It can be used to display currently playing track on desktop background or panel for example.	 See
>       /usr/share/doc/cmus/examples/cmus-status-display.

**Comment by mahkoh** [comment]
>How?

https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by pgaskin** [comment]
Options have been listed, OP has disappeared.
