### ISSUE TITLE
Compile/ dependency problem about cmus [Fedora]

### ISSUE THREAD

**Issue by LzyAWP-Fred** [cmus/cmus#624]
I was trying to compile cmus 27 and 28. ".  I used "dnf builddep list cmus" to install dependency , but still can't pass configure checking. Can you list all the library that cmus need? I want o install Cmus from souce.

This is the dependency I installed
 --> Already installed : wavpack-devel-4.80.0-1.fc25.x86_64
 --> Already installed : pulseaudio-libs-devel-10.0-2.fc25.x86_64
 --> Already installed : opusfile-devel-0.8-1.fc25.x86_64
 --> Already installed : ncurses-devel-6.0-6.20160709.fc25.x86_64
 --> Already installed : 1:libvorbis-devel-1.3.5-1.fc25.x86_64
 --> Already installed : libsamplerate-devel-0.1.8-10.fc24.x86_64
 --> Already installed : libmpcdec-devel-1.2.6-16.fc24.x86_64
 --> Already installed : libmp4v2-devel-2.1.0-0.6.trunkREV507.fc24.x86_64
 --> Already installed : 1:libmodplug-devel-0.8.8.5-8.fc24.x86_64
 --> Already installed : libmad-devel-0.15.1b-20.fc25.x86_64
 --> Already installed : libcue-devel-2.1.0-1.fc25.x86_64
 --> Already installed : libcddb-devel-1.3.2-19.fc24.x86_64
 --> Already installed : libao-devel-1.2.0-6.fc24.x86_64
 --> Already installed : flac-devel-1.3.2-1.fc25.x86_64
 --> Already installed : ffmpeg-devel-3.1.6-1.fc25.x86_64
 --> Already installed : 1:faad2-devel-2.7-8.fc25.x86_64
 --> Already installed : alsa-lib-devel-1.1.1-2.fc25.x86_64
Getting requirements for cmus-2.7.1-4.fc25.src
 --> Already installed : wavpack-devel-4.80.0-1.fc25.x86_64
 --> Already installed : pulseaudio-libs-devel-10.0-2.fc25.x86_64
 --> Already installed : opusfile-devel-0.8-1.fc25.x86_64
 --> Already installed : ncurses-devel-6.0-6.20160709.fc25.x86_64
 --> Already installed : 1:libvorbis-devel-1.3.5-1.fc25.x86_64
 --> Already installed : libsamplerate-devel-0.1.8-10.fc24.x86_64
 --> Already installed : libmpcdec-devel-1.2.6-16.fc24.x86_64
 --> Already installed : libmp4v2-devel-2.1.0-0.6.trunkREV507.fc24.x86_64
 --> Already installed : 1:libmodplug-devel-0.8.8.5-8.fc24.x86_64
 --> Already installed : libmad-devel-0.15.1b-20.fc25.x86_64
 --> Already installed : libcue-devel-2.1.0-1.fc25.x86_64
 --> Already installed : libcddb-devel-1.3.2-19.fc24.x86_64
 --> Already installed : libao-devel-1.2.0-6.fc24.x86_64
 --> Already installed : flac-devel-1.3.2-1.fc25.x86_64
 --> Already installed : ffmpeg-devel-3.1.6-1.fc25.x86_64
 --> Already installed : 1:faad2-devel-2.7-8.fc25.x86_64
 --> Already installed : alsa-lib-devel-1.1.1-2.fc25.x86_64

My distribution: Fedora 25 x64

**Comment by mahkoh** [comment]
What's the output of configure?

**Comment by LzyAWP-Fred** [comment]
@mahkoh 
[Ava1oN@localhost cmus-2.8.0-rc0]$ ./configure
checking for program gcc... /usr/bin/gcc
checking for program gcc... /usr/bin/gcc
checking for CFLAGS -std=gnu11 -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... yes
checking for CFLAGS -Wold-style-definition... yes
checking for CFLAGS -Wno-pointer-sign... yes
checking for CFLAGS -Werror-implicit-function-declaration... yes
checking for CFLAGS -Wno-unused-parameter... yes
checking for CFLAGS -Wno-missing-field-initializers... yes
checking if CC can generate dependency information... yes
checking byte order... little-endian
checking for DL_LIBS (-ldl -Wl,--export-dynamic)... yes
checking for PTHREAD_LIBS (-lpthread)... yes
checking for realtime scheduling... yes
checking for program pkg-config... /usr/bin/pkg-config
checking for NCURSES_LIBS (pkg-config)... -lncursesw -ltinfo
checking for NCURSES_CFLAGS (pkg-config)... -D_GNU_SOURCE
checking for working ncurses setup... yes
checking for function resizeterm... yes
checking for function use_default_colors... yes
checking for ICONV_LIBS (-liconv)... no
assuming libc contains iconv
checking for working iconv... yes
checking for header <byteswap.h>... yes
checking for function strdup... yes
checking for function strndup... yes
checking for CDDB_LIBS (pkg-config)... -lcddb
checking for CDDB_CFLAGS (pkg-config)... 
checking for CDIO_LIBS (pkg-config)... no
checking for CDIO_LIBS (-lcdio_cdio -lcdio -lm)... no
checking for FLAC_LIBS (pkg-config)... -lFLAC
checking for FLAC_CFLAGS (pkg-config)... 
checking for MAD_LIBS (pkg-config)... -lmad -lm
checking for MAD_CFLAGS (pkg-config)... 
checking for MODPLUG_LIBS (pkg-config)... -lmodplug
checking for MODPLUG_CFLAGS (pkg-config)... 
checking for function ModPlug_GetModuleType... yes
checking for header <mpc/mpcdec.h>... no
checking for header <mpcdec/mpcdec.h>... yes
checking for MPC_LIBS (-lmpcdec -lm)... yes
checking for VORBIS_LIBS (pkg-config)... -lvorbisfile
checking for VORBIS_CFLAGS (pkg-config)... 
checking for OPUS_LIBS (pkg-config)... -lopusfile
checking for OPUS_CFLAGS (pkg-config)... -I/usr/include/opus
checking for LIBSYSTEMD_LIBS (pkg-config)... no
*** Package libsystemd was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libsystemd.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libsystemd' found
checking for WAVPACK_LIBS (pkg-config)... -lwavpack
checking for WAVPACK_CFLAGS (pkg-config)... 
checking for header <mp4v2/mp4v2.h>... yes
checking for header <neaacdec.h>... yes
checking for MP4_LIBS (-lmp4v2 -lfaad -lm)... yes
checking for header <neaacdec.h>... yes
checking for AAC_LIBS (-lfaad -lm)... yes
checking for FFMPEG_LIBS (pkg-config)... -lavformat -lavcodec
checking for FFMPEG_CFLAGS (pkg-config)... -I/usr/include/ffmpeg
checking for header <libavcodec/avcodec.h>... yes
checking for successful build of ffmpeg.c... yes
checking for header <ayemu.h>... no
checking for PULSE_LIBS (pkg-config)... -lpulse
checking for PULSE_CFLAGS (pkg-config)... -D_REENTRANT
checking for ALSA_LIBS (pkg-config)... -lasound
checking for ALSA_CFLAGS (pkg-config)... -I/usr/include/alsa
checking for JACK_LIBS (pkg-config)... no
*** Package jack was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `jack.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'jack' found
checking for SAMPLERATE_LIBS (pkg-config)... -lsamplerate
checking for SAMPLERATE_CFLAGS (pkg-config)... 
checking for AO_LIBS (pkg-config)... -lao
checking for AO_CFLAGS (pkg-config)... 
checking for program artsc-config... no
checking for header <sys/soundcard.h>... yes
checking for header <sys/audioio.h>... no
checking for ROAR_LIBS (pkg-config)... no
*** Package libroar was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libroar.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libroar' found
[Ava1oN@localhost cmus-2.8.0-rc0

**Comment by flyingmutant** [comment]
It looks like you are missing libsystemd, jack and libroar, but these are optional dependencies, you are not required to install them.
