### ISSUE TITLE
-I${topdir} included too late in the compiler flags

### ISSUE THREAD

**Issue by dwatteau** [cmus/cmus#625]
This is with cmus v2.8.0-rc0 on OpenBSD -current, building with clang-3.9.1.

cmus currently fails to build if the id3lib library (http://id3lib.sourceforge.net) is installed on the system:
```
ip/mad.c:125:16: error: variable has incomplete type 'struct id3tag'
        struct id3tag id3;
                      ^
```

That's because we are trying to `#include` our own `id3.h` header, but `/usr/local/include/id3.h`, from the external id3lib library, is actually included first, if it's installed when you're building cmus.

The compiler is invoked this way:
```
clang -c -O2 -pipe -Wno-system-headers -I/usr/local/include -DHAVE_DISCID -DHAVE_CONFIG -std=gnu11 -pipe [various -W flags] -MMD -MP -MF .dep-ip-mad.lo -DREALTIME_SCHEDULING -D_FILE_OFFSET_BITS=64 -I"/home/ports/cmus-2.8.0-rc0" -I/usr/local/include -fPIC -o ip/mad.lo ip/mad.c
```
`-I/usr/local/include` is set first, so it takes precedence over the following `-I` flags. It is added by `checks.sh`:128, on BSD systems.

Injecting `-I"${topdir}"` at the earliest place in the compiler flags (I'd say even before `$CFLAGS`) _might_ be a way of making sure that our own header files take precedence.

**Comment by flyingmutant** [comment]
Fixed in #629.
