### ISSUE TITLE
MPRIS, 64-bit atomic ops & portability

### ISSUE THREAD

**Issue by dwatteau** [cmus/cmus#636]
This is with cmus-2.8.0-rc0 on OpenBSD/macppc -current (I'm the port maintainer for cmus on OpenBSD).

Since commit 8d26cc875c321df5535fd46795e333d446aa3643, cmus requires 64-bit atomic ops (see ``track_info_new()``).

Unfortunately, 64-bit atomic ops are not very portable; some CPUs just lack them at the ISA level. PowerPC doesn't have them, for example, so cmus now fails to build on OpenBSD/macppc, and probably some other arches as well:
https://marc.info/?l=openbsd-ports&m=148519384202038&w=2

*32-bit* atomic ops have less portability problems, however.

I can understand that the project wants to move forwards, but 1) I just wanted to make sure that you were aware of this, and 2) I think there might be a way to work around this.

The only place where 64-bit atomic ops are used are in ``track_info_new()`` at the moment, because ``struct track_info->uid`` is an ``uint64_t``. AFAICS, this field is only used by MPRIS (which is not used on OpenBSD).

Switching this field to an ``uint32_t`` lets us switch to a simpler 32-bit atomic op, which, in turn, is enough to have cmus build on PowerPC again. So, do we really need an ``uint64_t`` for the ``uid`` field?

**Comment by mahkoh** [comment]
Afaik, gcc implements atomic operations for all types no matter their size by using locks when necessary.

**Comment by dwatteau** [comment]
Hm, unfortunately our GCC doesn't do that on PowerPC so I assumed it was a Linuxism, but it might just be a bug in our GCC port, actually (adding ``-latomic`` to ``LDFLAGS`` works around this)... I'll investigate that, thanks.

I'll come back if the OpenBSD GCC ports maintainers tell me there's still a portability issue.

**Comment by mahkoh** [comment]
It looks like nothing is happening here and adding `-latomic` seems to fix the problem on OpenBSD. So I'm closing this ticket for now.
