### ISSUE TITLE
Add option to shuffle album order.

### ISSUE THREAD

**Issue by aewdaxdxdwexdaedaexdaxdaxdddaxdddaw** [cmus/cmus#641]
Cmus currently has a shuffle feature that shuffles every track in the library. I'd like an option to shuffle the order of the albums, so the tracks belonging to each album are played in order but once the album ends it plays another album in the library.
The android music player 'Vanilla music' Has a feature identical to this, if I haven't described the request properly, then that is an example.

**Comment by jcs** [comment]
I implemented this in my [album_shuffle](https://github.com/jcs/cmus/tree/album_shuffle) branch as an `aaa_mode` but it feels wrong to have it there instead of changing `shuffle` to have 3 possible options (all/album/off).

**Comment by jcs** [comment]
@flyingmutant Any thoughts on how you'd like to handle this?  Changing `shuffle` seems very daunting.

**Comment by jcs** [comment]
I still need to add `player-next-album` and `player-prev-album` commands so that navigating albums is easier when album shuffle is on.  Once I do that, I can create a PR for it (though I still haven't heard from @flyingmutant whether this will be accepted as an `aaa_mode`).

**Comment by gavtroy** [comment]
AAA mode is confusing enough already. IMO the user facing part of this would definitely need to be tied to the shuffle option instead.
Do you plan to continue work on this @jcs?

**Comment by jcs** [comment]
@gavtroy No, sorry.  I've since switched to audacious since it already supported "shuffle by album", and I then added support for `playlist-advance-album` and `playlist-reverse-album` in their `audtool` command-line interface.

**Comment by gavtroy** [comment]
That's understandable. I'm not ramped on the codebase but I'll take a look at it.

**Comment by autoteelar** [comment]
install gentoo
