### ISSUE TITLE
Cmus just cloned and built, all my library and playlists has been deleted

### ISSUE THREAD

**Issue by Bew78LesellB** [cmus/cmus#643]
# Observations 

I just cloned the project, configured then built (but  not installed). 

First launch I get loading issues, but the player UI still starts (not showing any library or playlists), so I stop it with `:q` (normal exit). 

Little check in `~/.config/cmus/`: my `lib.pl` and `playlist.pl` are zero length files... 
I had around 500 tracks in my library, it should not take 0 bytes ^^

# What I have so far:

I am on Archlinux and am using the cmus package from official repositories. 

On the first start, I had some issues with configuration, library and plugins loading :
- (1) plugins loading: on Archlinux, the official cmus package don't store the libs and datas in the same directory than the cmus I just built. 
- configuration & library loading: I didn't dig into those issues, but I think it's kinda related to the plugins loading or maybe to some environment variables not set correctly.. 

So the functions `ip_load_plugins` and `op_load_plugins` silently failed (because of (1): cmus cannot open the directories where plugins are normally stored), and when cmus finally exits, it goes through  the `exit_all` function which will auto save the loaded configuration, library & playlists. As there were loading issues, I had no playlists loaded in memory, and it saved that! This overwrites my playlists file with a zero length file, so my playlists are...  just gone.. 

Don't worry, I never used playlists at the moment, but some might do! 

# one way to fix (I think) 

1. Stop cmus as soon as there is a critical loading issue
2. Or at least do not overwrite files that didn't get loaded!

I think 1. is better though. Maybe I'll do a PR somewhere this week to fix this (if you agree with my findings)

**Comment by Bew78LesellB** [comment]
I tried to strace cmus , and I found that the file `~/.config/cmus/lib.pl` is only opened once, at the end, when exiting:
```strace
open("/home/lesell_b/.config/cmus/lib.pl", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
close(5)                                = 0
```
It seems that it didn't even tried to load it..

Here is my computer config for reference:
```
Linux BB-8 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux
```

And my cmus version:
```
Via the official package manager:
cmus v2.7.1

Via git:
cmus v2.8.0-rc0-41-gf524d38
```

**Comment by mahkoh** [comment]
Use `strace -f` to trace all threads.

**Comment by mahkoh** [comment]
>First launch I get loading issues,

The plugin ABI changed since 2.7.1. Since you didn't install the plugins cmus was unable to load a single plugin. Since the cache ABI also changed it was unable to load track information from the cache. With no possibility to load track information, it discarded all entries in your library.

**Comment by Bew78LesellB** [comment]
Thanks for the explanation!
> Since the cache ABI also changed it was unable to load track information from the cache.
> With no possibility to load track information, it discarded all entries in your library.

I would not think it that way:
> Since the cache ABI also changed it was unable to load track information from the cache.

I should have discarded the cache (not the library)

The library file is only a list of path, if the library file format does not change it should not be discarded (if it does, I think there should be a migration from older format to newer format)
