### ISSUE TITLE
ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0

### ISSUE THREAD

**Issue by schvabodka-man** [cmus/cmus#644]
Hi there! Seems like i got myself a little bug.  In a track "Corrupt system"(By VHS Glitch, album is Moral Decay), i'm getting this after some time of playing and cmus crashes

```
ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0
```
It seems that some of the tracks in this album is causing this bug too. The other ones is playing absolutely great. I'm actually listening CD-rip in flac with ~1500 kbps, so it's not caused by some badly converted song.

1) `uname -a`:
```
Linux laptop.scvh 4.9.5-200.fc25.x86_64 #1 SMP Fri Jan 20 12:24:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  ffmpeg:
    Priority: 300
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao
```

**Comment by mahkoh** [comment]
For the bug to be fixed you need to upload one of the affected files.

**Comment by schvabodka-man** [comment]
https://transfer.sh/Q5kxg/03-corrupt-system.flac
Ok here it goes

**Comment by mahkoh** [comment]
You should reduce the priority of the ffmpeg plugin below the one of the flac plugin.

**Comment by schvabodka-man** [comment]
Well, how can i do that?

**Comment by mahkoh** [comment]
Read the manual.

**Comment by flyingmutant** [comment]
@schvabodka-man can this issue be closed?

**Comment by mahkoh** [comment]
No, this is a bug.

**Comment by schvabodka-man** [comment]
Ok, now I'm trying to set the priority for ffmpeg by set input.ffmpeg.priority=30, but instead i'm getting this
Error: no such option input.ffmpeg.priority on cmus startup. What i'm doing wrong?

**Comment by mahkoh** [comment]
Priorities are only supported in cmus 2.8.

**Comment by mtreinish** [comment]
I'm hitting this issue too, cmus is crashing (although I'm not paying enough attention to see if it's the same file, or type of file when it happens) and the same 'ip_read: BUG:' is being printed. I don't have the ffpmeg plugin installed though:

```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  ao
```
I'm also on cmus v2.7.1

**Comment by Lagrang3** [comment]
The problem is not "High Definition Tracks" but multichannel tracks. 
I tried with a file encoded with flac at 192 kHz 24 bits 2 channels and had no problems.
On the other hand another track encoded with flac at 96 kHz 24 bits 6 channels makes cmus crash with the message `ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0`

**Comment by nefthy** [comment]
@Lagrang3 thanks, I can reproduce it with that spec.

**Comment by nefthy** [comment]
Related: #379

**Comment by nefthy** [comment]
@Lagrang3 could you compile and test https://github.com/nefthy/cmus/tree/issue_644?

**Comment by Lagrang3** [comment]
@nefthy I did, same problem.

**Comment by nefthy** [comment]
sorry I had not pushed the changes.

**Comment by Lagrang3** [comment]
Still the same problem. I told you, is not the bitrate---like I thought at the begining---but the number of channels.

**Comment by nefthy** [comment]
It is the bitrate in combination with the channels that triggers the BUG call. The commit cd106055 fixes the BUG call for me.

**Comment by nefthy** [comment]
The problem here is that the flac input plugin, extends 24bit flacs to 32 bit. The assertion that is failing is ment to check that the chunk read from the input plugin is a multiple of the frame size:

```BUG_ON(rc % sf_get_frame_size(ip->data.sf) != 0)```

frame size is number of channels times the number of bytes (3 x 6 = 18). The bit depth set by the flac plugin, matches the files 24bit, but does not match the decoded streams 32bit. The input plugin actually returns (n x 4 x 6 = n x 24 bytes).

I am not entirely clear if the sample_format_t structure is supposed to describe the decoded stream or data encoded by the file. If the first one is the case, then the bits should be set to 32 not 24.

**Comment by geek1011** [comment]
@nefthy I think `sample_format_t` is supposed to describe the decoded stream sent to the output plugins, as it's used to initialize the various outputs. The rate in it is also used for seeking. Also, after taking a quick glance at some of the input plugins, such as the wav one, it appears to be set based on the decoded stream. I think your commit (btw, it doesn't appear to even be part of any branch) should fix this.

**Comment by flyingmutant** [comment]
@Lagrang3 can you (and everyone else experiencing this issue) please confirm that #867 does indeed fix it?

**Comment by Lagrang3** [comment]
That's weird, I cannot build cmus from this branch https://github.com/nefthy/cmus/tree/issue_644
After `make` linker complains:
```
   LD     cmus
ape.o: In function `ape_parse_one':
ape.c:(.text+0x4ef): undefined reference to `xstrndup'
browser.o: In function `browser_up':
browser.c:(.text+0xd2f): undefined reference to `xstrndup'
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'cmus' failed
make: *** [cmus] Error 1
```

**Comment by geek1011** [comment]
@Lagrang3 which OS are you using?

**Comment by Lagrang3** [comment]
$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by geek1011** [comment]
Hmm. That should work fine, as I use it too when compiling my packages. I'll see if I can compile this when I get to a computer (in an hour or so).

**Comment by Lagrang3** [comment]
ok thanks.

**Comment by nefthy** [comment]
@Lagrang3 could you disable ape for now. the missing references are unrelated and we should solve that in a separate issue.

**Comment by geek1011** [comment]
Here are the Debian packages I have built (one on Buster with GCC 8, and one on Stretch with GCC 6). They both work fine, including ape, so I think it is something wrong with your setup. Here are the built packages: https://files.geek1011.net/Debian/Packages/cmus/pr867 . The source is here: https://github.com/geek1011/cmus/tree/build_867/debian/

If you want to build the packages yourself, you can clone https://github.com/geek1011/cmus , then checkout build_867, make it into a tarball named cmus_2.8.1.orig.tar.gz in the parent dir, then run `debuild -us -uc`.

**Comment by geek1011** [comment]
@flyingmutant @nefthy, I tested nefthy's fix and can confirm it works with a file generated with `sox -n -r 96k -b 24 -c 6 buggy-synth.flac synth 3 sine 500`, and a few files converted with `sox orig.flac -r 96k -b 24 -c 6 buggy-test.flac`. They all crashed with the bug call on 2.8.0 and worked after nefthy's fix.

**Comment by Lagrang3** [comment]
> @Lagrang3 can you (and everyone else experiencing this issue) please confirm that #867 does indeed fix it?

I can confirm the fix solved the issue for my case.
