### ISSUE TITLE
cmus sound is "choppy" and strange (crackles, pops or glitches

### ISSUE THREAD

**Issue by extrowerk** [cmus/cmus#646]
---

1) `uname -a`:
```
Haiku shredder 1 hrev50971 Feb 21 2017 20:02:14 x86_64 x86_64 Haiku
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /packages/cmus-2.7.1-2/.self/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp

Output Plugins: /packages/cmus-2.7.1-2/.self/lib/cmus/op
  ao
```
The cmus port using libao for audio output. As i made my test i used VM, so i thought it is just the VMWare emulation problem, but as i tested on real iron i've heard the same glitches.
It could be a cmus or a libao problem too, it need investigation.

Every other libao based player works correctly on Haiku AFAIK.

Current recipe for cmus: https://github.com/haikuports/haikuports/pull/1166

**Comment by mahkoh** [comment]
If you want this to get fixed you need to debug it yourself.

**Comment by pgaskin** [comment]
I'm going to close this issue since it hasn't had a response for over 4 years. @extrowerk, feel free to reopen it if you still have this issue on the latest version of cmus.
