### ISSUE TITLE
'No such plugin' error in Debian

### ISSUE THREAD

**Issue by Najahiri** [cmus/cmus#649]
After downloading and installing cmus I tried to execute it and it gives me the error 
```
Error: selecting output plugin '': no such plugin
```

If I check `cmus --plugins` the output is
```
Input Plugins: /usr/local/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
```

What should I do?

**Comment by mahkoh** [comment]
https://wiki.debian.org/BuildingTutorial#Get_the_build_dependencies

**Comment by Najahiri** [comment]
Thanks for the quick reply!

It's not clear to me what you are suggesting. I tried to execute 
```sudo apt-get build-dep cmus```
but that didn't solve the issue.
Could you please explain yourself a little bit more for me?

**Comment by mahkoh** [comment]
You need to recompile cmus.
