### ISSUE TITLE
Error with output plugin 'oss'

### ISSUE THREAD

**Issue by mikeygthegod** [cmus/cmus#651]
---

1) `uname -a`:
```
Linux localhost.localdomain 4.8.6-300.fc25.x86_64 #1 SMP Tue Nov 1 12:36:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1

```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  oss

```
I'm using Fedora 25 (Workstation Edition) x86_64 and when trying to :set output_plugin=oss, I receive the error: Error: selecting output plugin 'oss': couldn't initialize required output plugin.

**Comment by mahkoh** [comment]
Are you sure about using oss?

**Comment by mikeygthegod** [comment]
It's the only plugin I have installed as i also get this error when trying to use pulse, even after reinstalling it: `Error: selecting output plugin 'pulse': no such plugin`

**Comment by mahkoh** [comment]
Nobody's using OSS in the current year. Consult your distro's documentation for how to install cmus and the necessary libraries.

**Comment by mikeygthegod** [comment]
I've installed pulseaudio but am unable to test it due to another issue, the mp3's in my library are not 'seen' by cmus.

**Comment by jolange** [comment]
You are missing the mad plugin for mp3
