### ISSUE TITLE
Distinguish between selected song color and selected artist color

### ISSUE THREAD

**Issue by siftra** [cmus/cmus#656]
Is it possible to change the selection color so that it only affects the selected song color or only the selected artist color? The only parameter I can find (`color_win_sel_bg`) just changes the selected color regardless of whether it is an artist or a song. 
The reason I would like to do this is because my file manager (ranger) has a different highlight color depending on what is highlighted and I wished to make the same distinction it was making between directories (artists) and files (songs) in cmus.

**Comment by mahkoh** [comment]
>Is it possible to change the selection color so that it only affects the selected song color or only the selected artist color?

No.
