### ISSUE TITLE
Radio streaming not working

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#66]
I'm not sure where the issue stems from, but I cannot access the radio stream of: http://www.morow.com/morow.m3u

I get error when I try to access the stream from the file system browser:
Error: Couldn't get file information for http://stream.morow.com:8080/morow_med.mp3

I can provide other info if needed.

**Comment by willtmonroe** [comment]
Hello, 

I have the same issue as the earlier poster but I already have the mad plugin installed (see output of cmus --plugins below):

Input Plugins: /usr/local/Cellar/cmus/2.6.0_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.6.0_1/lib/cmus/op
  ao

Can you advise me on what troubleshooting steps to take next?

**Comment by thehodapp** [comment]
@willtmonroe You gotta build it. Read the docs on the README here how to build:

https://github.com/cmus/cmus

**Comment by willtmonroe** [comment]
Thanks, I've got an install of cmus on Ubuntu and then README instructions
are straightforward but I've also got an OSX instance that's less so.
Luckily, cmus installed via brew seems to include libmad already.

But now that I can successfully add and play a m3u stream is there any way
to rename it?  Its just displaying as <Stream>.  I'd like to assign a name,
if possible.

**Comment by flyingmutant** [comment]
No, it is not currently possible to assign names to streams. However, cmus should use streaming metadata to name them automatically.

**Comment by Kabouik** [comment]
Sorry to unburry this old issue but I just want to ask a question about it, not report another bug. Time have passed since this was opened, just wanted to check if there are now alternatives to `libmad` for streaming .mp3? I compiled and packaged cmus 2.8.0 for SailfishOS and I couldn't get around compiling `libmad`, so it's just using `ffmpeg` at the moment. But perhaps there would be other plugins now that would be easier to build on this sytem?
