### ISSUE TITLE
Subreddit created. 

### ISSUE THREAD

**Issue by bishisht** [cmus/cmus#663]
After searching for a united community on internet for cmus. I haven't found anyone. 
So, I have created one. https://www.reddit.com/r/cmus/ 
If anyone is interested in moderating this, please let me know. Also we can add link to subreddit on readme so that new users have a definate place to look for community. 

PS: I've be using cmus for last 4 days. I am impressed. Looking to give back to community in way I can. You can say creating this subreddit is small gift if you consider.

**Comment by mahkoh** [comment]
Feel free to add a link in the wiki.
