### ISSUE TITLE
Cmus is unresponsive/frozen after keeping it running couple days

### ISSUE THREAD

**Issue by gerroon** [cmus/cmus#670]
Hi

I use cmus with  cmus --listen 0.0.0.0. It works but it gets frozen or unresponsive after it runs for couple days. Now you cna imagine this is a bit of hard to track bug because I do not know when or how it gets frozen/stops/. The ui is pretty much unresponsive and the only way is to kill it and restart it. One thing that is curious is that this seems to be happening when nothing is playing. So cmus is open, it can access ot the network and the libraries but no remote playing or playing of any song is happening. At some point it decides to freeze. 

The other custom usage is that I forward PULSE_SERVER in the termianal prior to running the command so that I can get the song play on my actual desktop.

here is ps auxf (while it is unresonsive)
```30544  0.0  0.4 651196 61060 pts/7    Sl+  Apr09   2:39  |       \_ cmus --listen 0.0.0.0```

I run the command inside a tmux session. Nd the tmux sessions generally are responsive and no issues with any other process that is running within the same tmux session(but they run on different tmux windows). 

If you can give me some directions on how to debug it i can try producing more evicence.

1) `uname -a`:
```
Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.6.0-53-g3b151cb
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Author
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp

Output Plugins: /usr/local/lib/cmus/op
  roar
  pulse
  alsa
  oss
  jack
  ao

```

**Comment by mahkoh** [comment]
>cmus v2.6.0

This version of cmus is no longer supported.
