### ISSUE TITLE
Random: Am I doing it right?

### ISSUE THREAD

**Issue by skrillybilly** [cmus/cmus#685]
The random function isn't working well for me, even on small playlists (less than 100 tracks). I end up hearing the same tracks sever times, while not hearing some at all. Is this user error, or maybe part of something greater than me?

![screen shot 2017-05-02 at 7 59 18 pm](https://cloud.githubusercontent.com/assets/28295674/25614618/dfe60adc-2f71-11e7-8241-2cafc01694a1.png)

**Comment by nefthy** [comment]
Random does not mean that each track gets played equally often in the short run. The distribution should even out as more songs are played.

However user expectations from a random function, are more along the lines of:

1. Make a random permutation of the playlist
2. Play it
3. Goto 1

So we might want to consider this a bug. @flyingmutant, @mahkoh what is your take on this?

**Comment by mahkoh** [comment]
>1. Make a random permutation of the playlist
>2. Play it
>3. Goto 1

That's how it's implemented.
