### ISSUE TITLE
Pulseaudio: CANNOT LINK EXECUTABLE: Cannot locate symbol "glob" ...

### ISSUE THREAD

**Issue by EralpCelebi** [cmus/cmus#688]
1) `uname -a`:

Linux localhost 3.10.49-9483602 #1 SMP PREEMPT Wed Oct 12 19:16:33 KST 2016 armv7l Android

2) `cmus --version`:

cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors

3) `cmus --plugins`:

Input Plugins: /data/data/com.termux/files/usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /data/data/com.termux/files/usr/lib/cmus/op
  pulse

![ekran goruntusu 1](https://cloud.githubusercontent.com/assets/25103939/25771109/b995f43c-3250-11e7-8a77-54095be3ebe1.png)

![ekran goruntusu 2](https://cloud.githubusercontent.com/assets/25103939/25771112/d21c5b22-3250-11e7-9b26-3bf946da4d8e.png)

I have been searching a solution for this but could't find any. Can somebody help me.
(btw. I am using termux)

**Comment by mahkoh** [comment]
What's the output of `ldd cmus`?

**Comment by bbesim** [comment]
I have the same version of **cmus** and observing the same problem. It appears to be an issue with pulseaudio.  Termux currently does not support other sound libraries.

**pulseaudio --start**
CANNOT LINK EXECUTABLE "pulseaudio": cannot locate symbol "glob" referenced by "/data/data/com.termux/files/usr/lib/pulseaudio/libpulsecore-10.0.so"...
Aborted

$ **ldd /data/data/com.termux/files/usr/bin/cmus**
libandroid-support.so
libncursesw.so.6
libiconv.so
libdl.so
libcue.so
libm.so
libc.so

**Comment by mahkoh** [comment]
Does libc.so contain the glob symbol?

**Comment by Grimler91** [comment]
This has been fixed in the latest version of cmus in termux. Glob isn't in libc but is provided by the termux package libandroid-glob.

**Comment by mahkoh** [comment]
Gleat news.
