### ISSUE TITLE
I can't use cmus

### ISSUE THREAD

**Issue by New1997** [cmus/cmus#690]
Hello
I have a latest raspbian, I install cmus via sudo apt-get install cmus then when I try to luanch the application:
![image](https://cloud.githubusercontent.com/assets/27694657/25782698/411d71dc-3350-11e7-93d9-9d5d22c9be78.png)

**Comment by New1997** [comment]
I try to check the file in /etc/decnet.conf , the file doesn't exist so I don't know what to do. please help

**Comment by tagniam** [comment]
See #375, looks like a similar issue.

**Comment by New1997** [comment]
thanks

**Comment by New1997** [comment]
sorry don't understand a thing

**Comment by tagniam** [comment]
Try adding `set output_plugin=pulse` to the file `~/.cmus/rc` or `~/.config/cmus/rc` [(what they tried to do here)](https://github.com/cmus/cmus/issues/375#issuecomment-166315503). If the file doesn't exist, create it.
