### ISSUE TITLE
Can cmus library view sort according to arbitrary tags?

### ISSUE THREAD

**Issue by crocket** [cmus/cmus#691]
I'm looking for a command line/ncurses music player that supports sorting according to arbitrary tags.

AlbumArtist, Compilation, Album, and Artist tags are not comprehensive when I want to find songs that belong to certain movies or animations.

I considered adding something like copyright tag to songs so that I can find songs specific to certain movies or animations.

Does cmus support sorting based on arbitrary tags?

**Comment by mahkoh** [comment]
>Does cmus support sorting based on arbitrary tags?

No.

**Comment by crocket** [comment]
What does cmus do with regard to categorizing songs?
