### ISSUE TITLE
repeat-current is not working

### ISSUE THREAD

**Issue by nagracks** [cmus/cmus#695]
I've `Continue, Repeat, Shuffle` is enabled.

---

1) `uname -a`:
```
Linux macbook 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  ffmpeg:
    Priority: 300
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao
```

**Comment by mahkoh** [comment]
Works on my machine.

**Comment by nagracks** [comment]
It just stops after playing song. Repeat playlist works fine. How can I debug why it is not working?

**Comment by fsd-taha** [comment]
@nagracks  _repeat current_ is bound to `Ctrl-r` by default

**Comment by MettatonEX-CP1A** [comment]
Mine's works perfectly fine.
Maybe it's just an error in compiling `cmus`. Try to uninstall then compile and install it.

**Comment by asamsulfat** [comment]
Mine working fine, with ctrl-r

**Comment by fakedeltatime** [comment]
I was having the same problem, but changing `continue` to `true` fixed it.

**Comment by nefthy** [comment]
The logic is along the lines:
if continue is false, stop playing after the song, else figure out what happens next (in this case repeat).

So the correct behaviour would be to disable the repeat_current / repeat_all switches, when continue is set to false and restore them to their previous state, when continue is set to true again. Also an error message should be displayed when continue is false and one tries to enable any of the repeat modes.

Are any other switches affected by continue?

**Comment by aaleksu** [comment]
Yes, Continue mode solves repeat_current issue (was just about to report that I am having the same problem).

**Comment by JJFrampton** [comment]
As others have stated, "continue" needs to be enabled.
Commands:
`shift + c` - "continue"
`ctrl + r` - "repeat current"
Bottom right status should look something like this:
`repeat current  |  C`
