### ISSUE TITLE
Unable to get correct mp3 tags loaded for some files

### ISSUE THREAD

**Issue by oblitum** [cmus/cmus#697]
---

1) `uname -a`:
```
Linux leibniz 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  ao
```

I have some files for which updated mp3 tags are never loaded, no matter which software I use to set the tags. I've tried both easytag and puddletag.

On each tag change I closed `cmus` and deleted `~/.config/cmus`, I've also tried `:update-cache`. Nothing works.

**Comment by oblitum** [comment]
For some of the affected files I have this behaviour:

- puddletag correctly displays artist name and music name without artist name following inside parenthesis.
- cmus displays artist name in the artist window as ?????
- cmus places the correct artist name besides the song name inside parenthesis.

**Comment by oblitum** [comment]
![screenshot from 2017-05-13 16-43-12](https://cloud.githubusercontent.com/assets/1269815/26028639/4cdcefca-37fb-11e7-9505-5e5c148855e9.png)

**Comment by oblitum** [comment]
I was able to find the cause using yet another mp3 tag editor. With the Kid3 (Qt version) tag editor I was able to view detailed mp3 tags. The issue comes from mismatching "Album Artist" between ID3v1.1 and ID3v2.4.0 tags. cmus was always putting ID3v2.4.0 information in the artist window and ID3v1.1 information between parenthesis in the music list window.

I don't know whether this is the behavior to be expected, as I have figured it out, feel free to close in case a behavior change isn't more useful than the current state. Both previous tag programs I tried showed and edited solely the v1.1 tags, so I couldn't realize from where the other information was coming from.

**Comment by oblitum** [comment]
In another case, the issue was different: mismatching "Artist" vs "Album Artist" for ID3v2.4.0 solely. Left kept with "Album Artist", right in parenthesis with "Artist", and ID3v1.1 just prevented me from editing those correctly with the other tag editors.

**Comment by oblitum** [comment]
Another issue that I noticed. The order of the tracks is not followed if the songs have additional tags. Instead of simply sorting according to the track number, it gets random because of unrelated tags like encoder, etc.

**Comment by oblitum** [comment]
@mahkoh with the above information I believe it's fairly easy to reproduce those behaviors by editing flags of any music file using Kid3.

**Comment by mahkoh** [comment]
Please provide an affected file.
