### ISSUE TITLE
Format settings not honoured for every file. 

### ISSUE THREAD

**Issue by jottr** [cmus/cmus#699]
I am not sure if this is a misconfiguration on my part, or an issue with `cmus`. 
I have completely cleared my library, and removed the `~/.cmus/cache`.
In library-view many of the track listings are not properly formatted: 

![bildschirmfoto 2017-05-17 um 23 30 20](https://cloud.githubusercontent.com/assets/2744198/26177143/d671299e-3b58-11e7-9b83-cce5deb24a0a.png)

In above screenshot, everything except tracks by 'Full Quantic Pass' and 'Future Islands' is incorrectly formatted. 
Here's my format string: 

```bash
set format_playlist=%-20A   %{?l?%-60l}  %{?n?%02n.}  %-60t %d %= %{?g?%g} %{?D>0?    Disc: %02D}   %10{?y?%y} %5{bitrate} kBps
```

**Comment by mahkoh** [comment]
Compare `altformat_playlist` and `format_playlist_va`.

**Comment by jottr** [comment]
@mahkoh Thank you, adding `format_playlist_va` fixed it.
