### ISSUE TITLE
Library save sort incorrect

### ISSUE THREAD

**Issue by criztovyl** [cmus/cmus#706]
Hello,

one album in my library is sorted wrong in `cmus-remote -C "save -l -e -"`: [output1.txt](https://gist.github.com/criztovyl/0f5cc94a036904c2996c2090e206d0e6#file-output1-txt)
This does not happen for other albums afaik.

In a playlist it looks like this:
![bildschirmfoto vom 2017-06-11 16-24-04](https://user-images.githubusercontent.com/2174918/27011773-7cb4b758-4ec3-11e7-86a5-f3a2c39811e0.png)

In library-view everything is ordered correctly:
![bildschirmfoto vom 2017-06-11 16-36-20](https://user-images.githubusercontent.com/2174918/27011811-1cff5f60-4ec4-11e7-9ee0-ba1b3a547926.png)

Files: https://chsc.de/batterie.zip (80M) (~~still uploading ETA 2:30~~ uploaded)

Is this a bug or a feature I expect that's not there?

Thank you.

---

1) `uname -a`:
```
Linux [hostname] 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0-60-g0da3472
```
(built from master not long ago)

3) `cmus --plugins`:
[output2.txt](https://gist.github.com/criztovyl/0f5cc94a036904c2996c2090e206d0e6#file-output2-txt)

**Comment by mahkoh** [comment]
`save -l` uses the sorting configured by the `lib_sort` option.

**Comment by criztovyl** [comment]
Ok, there lays the error, `date` in my (default) `lib_sort` is messed up by messed up date values.

`lib_sort=albumartist date album discnumber tracknumber title filename play_count`

Thx for your help.
