### ISSUE TITLE
Color by column in playlist view

### ISSUE THREAD

**Issue by GhostValk** [cmus/cmus#707]
Is possible to change the color of each column by separate in the playlist view? Like.. Artist in one color, title of the songs in another color, length in another, etc.

Or is there any branch of cmus that allows that?

**Comment by GhostValk** [comment]
Hello?

**Comment by jolange** [comment]
No, that's not possible. There are no actual "columns", but what's shown is simply controlled by the `format_playlist` setting. So you cannot colorize the single contents separately.
