### ISSUE TITLE
Error missing config file ? 

### ISSUE THREAD

**Issue by jasontangfocus** [cmus/cmus#713]
---

when make install

error as follows, macOS Sierra

   CC     command_mode.o
In file included from command_mode.c:49:
./mpris.h:22:10: fatal error: 'config/mpris.h' file not found
#include "config/mpris.h"
         ^
1 error generated.
make: *** [command_mode.o] Error 1
<img width="896" alt="screen shot 2017-07-03 at 10 59 48 am" src="https://user-images.githubusercontent.com/17569604/27800374-c1003140-5fde-11e7-8ac6-b3b2f235862c.png">

**Comment by flyingmutant** [comment]
If you are unfamiliar with building C programs, please consider installing cmus via Homebrew.

**Comment by Almyk** [comment]
Have been using cmus for a while now and recently became aware that there is a newer version that supports multiple playlists which seems cool([#485](https://github.com/cmus/cmus/pull/485)).

I am getting a similar error when doing make install. It seems like there are, in multiple files, headers included that are supposed to be in a folder "config", but there is no such folder. Is it something more than "make install" I need to do to make it work?


almyk@mini:\~/Downloads/cmus-master$ make install
   CC     misc.o
misc.c:24:27: fatal error: config/libdir.h: No such file or directory
compilation terminated.
scripts/lib.mk:66: recipe for target 'misc.o' failed
make: *** [misc.o] Error 1
almyk@mini:~/Downloads/cmus-master$ 

OS:
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

**Comment by xplshn** [comment]
@jasontangfocus Could you provide some help. I'm struggling too.

**Comment by slpng** [comment]
For anyone running into this, you have to generate a config file by running `./configure` first
