### ISSUE TITLE
Support for collection of playlists

### ISSUE THREAD

**Issue by sshu0** [cmus/cmus#719]
The current playlist view is flat, with all playlists laid out at one level. It'd be quite convenient (for neater organisation) to have collections of playlists implemented in playlist view as artists in library view:

       +---------------------------------------------------------------------+
       | Collection / Playlist     Track                               00:00 |
       |   Pls i                  |                                          |
       |   Pls ii                 |                                          |
       | Col A                    |                                          |
       | * Pls 1                  |                                          |
       |   Pls 2                  |                                          |
       | Col B                    |                                          |
       | Col C                    |                                          |
       |                          |                                          |
       |                          |                                          |
       |                                                                     |
       | . 00:00 - 00:00 vol: 100                     all from library | C   |
       |                                                                     |
       +---------------------------------------------------------------------+

with the track window formatted similarly to that in library view.

**Comment by nefthy** [comment]
implemented in 2.8.0
