### ISSUE TITLE
Track blocks playing next track

### ISSUE THREAD

**Issue by Nothing4You** [cmus/cmus#72]
Hey there,
I just noticed this odd problem: I have some track (at 1st position in the playlist) which causes palyback for some reason to stop after playing it.

```
 Playlist ~/.cmus/playlist.pl - 63 tracks
 /home/rschwab/soundcloud.com/tobiaslueke/Andi Teller - Bloodsport ( O.B.I. Remix )-79084705.mp3                                                                                            02:35
...
 > 00:02 / 02:35 - 19:01:04 vol: 89                                                                                                                                               playlist | C  S
```

I can go to previous track and go forward again, no way to get past this track. Playback stops and telling cmus to skip to next track is ignored, neither works via -remote nor via `player-next`.

I'm currently using version `v2.5.0.67.gde9e9bd` (version generated with `git describe --tags | sed "s/-/./g"` on Arch Linux x64.

Track was obtained from https://soundcloud.com/tobiaslueke/andi-teller-bloodsport-o-b-i using youtube-dl.

**Comment by Grandclosing** [comment]
Hey @Nothing4You - I'm looking to add Soundcloud functionality to cmus, does this post indicate that you have already done this, or is the issue still open?

**Comment by nefthy** [comment]
I don't think this has anything to do with soundcloud functionality. The directory is just called soundcloud.com
