### ISSUE TITLE
Duplicated Artist in Library view

### ISSUE THREAD

**Issue by avorop** [cmus/cmus#727]
Hello!

There's somewhat strange thing. I have 2 sets of mp3 files. Both are from the same artist (Russian name). The name of the artist is the same for both sets (set using TPE1 frame). But in the Library view (1) I get that name twice, once for each set. No matter what I do with ID3 frames, the artist is listed 2 times. This appears like mystery because everything works fine for all other collections that I have. So, my question would be, what may cause such glitch? I've attached the picture showing double names.
![cmus](https://user-images.githubusercontent.com/32192493/30737040-7487de44-9f85-11e7-8ed3-7e36313f7f62.png)

**Comment by mahkoh** [comment]
Try `LC_COLLATE=C cmus`.

**Comment by avorop** [comment]
Does not help. As I said, it works for all other artists, which are also in Russian, and also have multiple albums. Just this particular artist has problem. Which leads me to believe, that there might be something in MP3 files that prevents these albums from being assigned to the same artist, despite TPE1 being equal.

**Comment by mahkoh** [comment]
Please provide two affected files.

**Comment by avorop** [comment]
Ok. Seems like I can not attach mp3 files here, so I've placed them to my site. Check 
http://vandal.sdf-eu.org/stuff/ Don't pay attention to names, looks like web-server applies additional UTF-8 conversion to produce link names. At least download produces correct file names.

**Comment by mahkoh** [comment]
There is a space at the end of one of the artist tags.

**Comment by avorop** [comment]
That can not be. I've used script to set TPE1 frame, so all frames are identical. I've checked it one more time, there's no spaces in the artist name.

**Comment by avorop** [comment]
Looks like I've found  the problem. The frame TXXX contained subfield which defined that different artist. I guess cmus respects that field more than TPE1 or TPE2, as result the artists appeared to be different. Now I've removed TXXX frame and the problem went away.

**Comment by indeedwatson** [comment]
@avorop What is TXXX frame? I'm asking because I stopped using cmus because I have the same issue and I was told it was "invalid" https://github.com/cmus/cmus/issues/619

**Comment by avorop** [comment]
Well. I've written small perl script that lists all of the ID3v2 tags in the file. Then I've noticed, that next to "standard" TIT2 or TPE1, there are also tags TXXX and XXX. When I've checked content of TXXX tag, I saw that it contains title as well. Simple googling revealed this http://id3.org/id3v2.3.0 page that contains description of this tag and its content.

**Comment by indeedwatson** [comment]
So the solution was to remove some tags? I ask because I don't think it's reasonable for a media player to ask of the user to delete tags in order to display what it should display.

**Comment by inspell** [comment]
Hi,

Can you upload some of these files somewhere?
I want to check them.

**Comment by avorop** [comment]
Sorry, are you talking about my files, or those of indeedwatson? I believe
both of us have uploaded our files in corresponding issue threads. If not,
then I can try to find my tomorrow.

Best regards.

**Comment by inspell** [comment]
Yes I was talking about your files avorop\.
Sorry, I didn't realize that this is an old thread.
I was just curious about the media files, I wanted to see how the tags are written.
The files are not on your website anymore.
You can share them with me if you happen to find them and have time to look for them ; )

**Comment by indeedwatson** [comment]
@avorop a media player should *never* ask the user to delete metadata, much less wait for the user to realize that some obscure tag confusion is happening behind the curtains. Every other player I've used has handled my tags fine, if I sort them by artists it displays them by artist, if I sort by composer it displays composer, etc. Cmus is the only time I've seen duplicate tags displayed.

However I realize I'm hijacking this, but it's mainly cause I still have not found a music library program that satisfies my need and cmus came closest, were it not for this bug.

**Comment by avorop** [comment]
@inspell Sorry, looks like I can't find original files. My files are already without TXXX tag (or should I say "frame"?). I'll try to dig in backups, but this takes time.

@indeedwatson I understand your frustration, but there are so many users, maybe some of them prefer to use TXXX instead of TPE1, probably because it  has better handling for international characters. If you get it your way, then they start complaining about "bug" because of that. So at the end, there will be always some unhappy users :)

As personal opinion, I would prefer to have some way to see the source of information that cmus uses. Maybe some external tool that would tell me which tags/frames cmus would use as "track name", "album", "performer", etc. Even good documentation would be sufficient.

**Comment by indeedwatson** [comment]
@avorop Agreed, the problem is two-fold. The fact that it's displaying duplicate tags is one issue, the fact that it doesn't explain why is another.

**Comment by avorop** [comment]
@inspell Finally, I've found the files in backup. The TXXX frame is there. I've placed sample file back into http://vandal.sdf-eu.org/stuff/

**Comment by inspell** [comment]
Thank you!
I will take a look at it when I go back home.
