### ISSUE TITLE
Key bindings for command line mode

### ISSUE THREAD

**Issue by gmoshkin** [cmus/cmus#728]
First of all I really enjoy the program. But it is very frustrating when I try to browse the command line history using the **Ctrl-P** and **Ctrl-N** keys as I'm used to doing in **bash** and **vim**, but they don't work in cmus. And I'm kind of surprised to find out that nobody before me requested this feature (perhaps I didn't look well enough?). I don't think I'm the only one who would find this to be very useful.

**Comment by tagniam** [comment]
Hi, this is addressed in #667, but I don't think it's been shipped yet.

**Comment by gmoshkin** [comment]
@tagniam oh, great! Don't know if the ticket should be closed though as there is a point in adding customizable command line key bindings.

**Comment by flyingmutant** [comment]
I'll close this issue, since I don't remember custom command mode key bindings being requested often.

**Comment by gmoshkin** [comment]
ok, thanks a lot
