### ISSUE TITLE
Remember the last-played track in the playlist view across invocations of cmus 

### ISSUE THREAD

**Issue by philc** [cmus/cmus#729]
I restart cmus multiple times per day because it [hangs](https://github.com/cmus/cmus/issues/391), [stops playing](https://github.com/cmus/cmus/issues/481) through my sound card, or because of normal reboots due to OSX system updates. I have a very long playlist of ambient background music I listen to at work and have to manually find where I left off and resume playing each time I restart cmus.

It would be nice if cmus remembered its cursor position in the playlist view.

```
cmus --version
cmus v2.7.1
```

**Comment by jareksprysz** [comment]
Try this: in cmus just write:

:set resume=true

**Comment by philc** [comment]
The `resume` option resumes playback of the last-playing song. What I'm instead looking for is for the cursor position in the playlist to be saved. With resume=true, after cmus starts, once the resumed song finishes playing, the first song in the playlist is played rather than the song in the playlist which is after the currently playing song.

An artifact of this is that in the playlist view, the song that resumes playing after a cmus restart is not highlighted in yellow.

**Comment by forthrin** [comment]
@jareksprysz: I would also like this feature. I too have to restart cmus occasionally because it hangs (see #771) or because of occasional severe distortion when using eqMac2 (resolves when restarting cmus). Regardless it's a good idea to remember your position rather than always starting at first artist/album in the alphabet, which is rather arbitrary.

**Comment by maiermic** [comment]
It already works to resume playing the library (see [`resume_load`](https://github.com/cmus/cmus/blob/15b5c5b538a1a07cb7705f742407052304dd7dde/options.c#L1662-L1680)). I suppose we need something like `resume.pl_index` that works kind of similar to `resume.lib_filename` for the playlist.

**Comment by aksh1618** [comment]
+1 for this feature request. I'd also like this feature, as I use a playlist for recently added tracks and would like it to be resumable.

**Comment by emilBeBri** [comment]
+1 here, would be awesome

**Comment by carlwarnick** [comment]
+1 also would like this

**Comment by ebpetway** [comment]
It appears that this functionality works now with `:set resume=true`.

**Comment by mathieu-lemay** [comment]
@ebpetway That option has been present for a long time. It doesn't fix this current issue. See https://github.com/cmus/cmus/issues/729#issuecomment-366335165

**Comment by ebpetway** [comment]
> @ebpetway That option has been present for a long time. It doesn't fix this current issue. See [#729 (comment)](https://github.com/cmus/cmus/issues/729#issuecomment-366335165)

Ah, I misunderstood the thread. :+1:
