### ISSUE TITLE
Displays old ID3 tags even after clearing library

### ISSUE THREAD

**Issue by lead0r** [cmus/cmus#730]
Hello,

I had some mistakes in ID3 tags. I corrected them (both in ID3v1 and ID3v2) and the new, correct versions are also displayed with other players (e.g. VLC). However, even after clearing my library in cmus (:clear) and adding it again, the old, wrong tags are displayed.

Is this an issue with cmus (e.g. even after using :clear there are still information saved about tracks somwhere) or are the tags still somewhere in the files?

**Comment by criztovyl** [comment]
Maybe try `:update-cache -f` (or similar).

**Comment by lead0r** [comment]
Thank you, I think that worked
