### ISSUE TITLE
Wrong sorting discnumber filenumber

### ISSUE THREAD

**Issue by xeverse** [cmus/cmus#734]
https://github.com/cmus/cmus/blob/master/Doc/cmus.txt
@h1 LIBRARY VIEW SORTING

Wrong sorting in this particular case
01A1_III.flac
02A2_TheBloatedPope.flac
03A3_ToadiAcceleratio.flac
04B1_PigsOfTheRomanEmpire.flac
05C1_PinkBat.flac
06C2_ZzzzBest.flac
07C3_SafetyThird.flac
08D1_IdolatrousApostate.flac
09D2_.flac
10D3_SafetyThird_altVersion.flac

https://share.riseup.net/#UqvdezbR8m3TuuHmlt1Hmg

**Comment by xeverse** [comment]
A1_III.flac
A2_TheBloatedPope.flac
A3_ToadiAcceleratio.flac
B1_PigsOfTheRomanEmpire.flac
C1_PinkBat.flac
C2_ZzzzBest.flac
C3_SafetyThird.flac
D1_IdolatrousApostate.flac
D2_.flac
D3_SafetyThird_altVersion.flac

**Comment by xeverse** [comment]
1.
10.
11.
12.
13.
2.
3.
4.
5.
6.
7.
8.
9.

**Comment by nefthy** [comment]
`:set lib_sort=albumartist date album discnumber tracknumber title filename play_count`
