### ISSUE TITLE
Change the Default Keys

### ISSUE THREAD

**Issue by SethArchambault** [cmus/cmus#741]
I really enjoy Cmus, and I've been using it for a while now, and I usually make an effort to learn the default keys of a program before I begin customizing, but after a few weeks of frustration trying to remember how to quickly stop a track from playing, I'm customizing since I can't seem to internalize these keys. 

They make no sense to my brain - they're not intuitive to remember as none of the letters match the name of the relevant function. This would be fine if their positioning on the board had some meaning - for example, having play, stop, prev, next near each other like a tape recorder, or matching vim keybindings for navigating around. 

It's great that there's robust customization options, but there's definitely people rage quiting this app after 5 minutes of frustration.

I'm certain others are having similar problems, highly recommend you change the defaults and make it simple to use first, then let people customize. 
Thanks!

**Comment by AffanIndo** [comment]
Aren't they are already next each other?
z c b is prev, pause, next.

**Comment by SethArchambault** [comment]
Perhaps we're using different keyboards here..
The bottom row of my keyboard looks like:
zxcvb
(Each of those characters have a character between them - it's standard in the US)

**Comment by SethArchambault** [comment]
Perhaps we're using different keyboards here..
The bottom row of my keyboard looks like:
zxcvb
(Each of those characters have a character between them - it's standard in the US)

**Comment by AffanIndo** [comment]
I use that keyboard too. But I think changing default keys could cause too much confusion especially for people that has use this for years.

**Comment by jolange** [comment]
Exactly, this will certainly not be changed.

**Comment by Rhundom** [comment]
The program is open source ( inb4 no shit GitHub )  Just do it yourself

**Comment by nefthy** [comment]
wont change.
