### ISSUE TITLE
rc rules don't override autosave

### ISSUE THREAD

**Issue by rlue** [cmus/cmus#742]
From the manpage:

```
$XDG_CONFIG_HOME/cmus/rc
      Static config file. This file is read immediately after the autosave file, and is
      never modified by cmus.  You can override auto-saved settings in this file.  This
      file is not limited to options, it can contain other commands too.
```

However, if cmus finds duplicate or conflicting settings in `rc` and `autosave` files (_e.g.,_ `bind common q quit` defined in both), it raises the following error on launch:

```
cmus: Error: key q already bound in context common
cmus: Press <enter> to continue.
```

---

1) `uname -a`:
```
Darwin liberte 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.7.1_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.7.1_2/lib/cmus/op
```

**Comment by ForTheReallys** [comment]
Use `bind -f`

**Comment by rlue** [comment]
Great! What do the maintainers think about either mentioning this in the manpage or applying `-f` by default to all `bind` and `unbind` directives found in the `rc` file?

**Comment by geek1011** [comment]
@nefthy @flyingmutant would you rather have this added to the documentation under the config file, added to the documentation under `bind`, or default to `-f` when loading from `rc`?

**Comment by nefthy** [comment]
I do not think that defaulting to `-f` is a viable option. I do not like behaviour that changes depending on the file the command is in. Also IIRC one has to use bind -f in the vim rc files too.

documentation under `bind` would be a good thing.

**Comment by geek1011** [comment]
I've opened a PR.

**Comment by nefthy** [comment]
thanks.
