### ISSUE TITLE
Problem with accented characters

### ISSUE THREAD

**Issue by SimonLefort** [cmus/cmus#743]
Hello, 

I have a problem with accented characters in **cmus** => [image](https://simonlefort.be/images/photos/divers/Capture%20du%202017-11-15%2009-20-25-cmus2.png)

I tried to compile myself but I have probably missing something ?
There are the options I use : 
```
$ ./configure DEBUG=2 CONFIG_OSS=y
```

I did'nt see an option about special characteds... :-/ 

Thanks in advance for your help!

---
1) `uname -a`:
```
$ uname -a
Linux hostname 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux
```

2) `cmus --version`:
```
$ cmus --version
cmus v2.8.0-rc0-71-g3a4ce9c
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
$ cmus --plugins 
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  roar
```

**Comment by slinkeepy** [comment]
I am also having this problem...

**Case 1**:
One file has this name as artist data: 
> Binärpilot

In the library artist column however, it shows as: 
> Bin\<e4\>rpilot

If I play it, it will start playing, however all the rest of the functionality crashes (pressing CTL-C will prompt me to enter ":quit" command, however no key presses will work, and I have to close the terminal.

(slightly strange, as another couple of albums by the same artist appear to have the same artist data, and display fine in CMUS, but appear on a different line - maybe there's an invisible difference I can't see).

**Case 2**:
One file has some (corrupted?) gibberish as artist/title tag:

Title: 

> adqrdqj -e-

Artist: 

> ½òi

This track will also play but crash the program.

While I could probably modify those files, it doesn't explain why they were playable in 2.7.1 but not in 2.8.0...

### uname -a
`Linux X58A-UD3R 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
### cmus --version

```
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```
### ./configure

```
checking for program gcc... /usr/bin/gcc
checking for program gcc... /usr/bin/gcc
checking for C11 (with atomics support)... yes
checking for CFLAGS -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... yes
checking for CFLAGS -Wold-style-definition... yes
checking for CFLAGS -Wno-pointer-sign... yes
checking for CFLAGS -Werror-implicit-function-declaration... yes
checking for CFLAGS -Wno-unused-parameter... yes
checking for CFLAGS -Wno-missing-field-initializers... yes
checking if CC can generate dependency information... yes
checking byte order... little-endian
checking for DL_LIBS (-ldl -Wl,--export-dynamic)... yes
checking for PTHREAD_LIBS (-lpthread)... yes
checking for realtime scheduling... yes
checking for program pkg-config... /usr/bin/pkg-config
checking for NCURSES_LIBS (pkg-config)... -lncursesw -ltinfo
checking for NCURSES_CFLAGS (pkg-config)... -D_GNU_SOURCE -I/usr/include/ncursesw
checking for working ncurses setup... yes
checking for function resizeterm... yes
checking for function use_default_colors... yes
checking for ICONV_LIBS (-liconv)... no
assuming libc contains iconv
checking for working iconv... yes
checking for header <byteswap.h>... yes
checking for function strdup... yes
checking for function strndup... yes
checking for CDDB_LIBS (pkg-config)... no
checking for CDDB_LIBS (-lcddb)... no
checking for CDIO_LIBS (pkg-config)... no
checking for CDIO_LIBS (-lcdio_cdio -lcdio -lm)... no
checking for FLAC_LIBS (pkg-config)... no
checking for FLAC_LIBS (-lFLAC -lm)... no
checking for MAD_LIBS (pkg-config)... no
checking for MAD_LIBS (-lmad -lm)... no
checking for MODPLUG_LIBS (pkg-config)... no
checking for MODPLUG_LIBS (-lmodplug -lstdc++ -lm)... no
checking for header <mpc/mpcdec.h>... no
checking for header <mpcdec/mpcdec.h>... no
checking for VORBIS_LIBS (pkg-config)... no
checking for VORBIS_LIBS (-lvorbisfile -lvorbis -lm -logg)... no
checking for OPUS_LIBS (pkg-config)... no
*** Package opusfile was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `opusfile.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'opusfile' found
checking for LIBSYSTEMD_LIBS (pkg-config)... -lsystemd
checking for LIBSYSTEMD_CFLAGS (pkg-config)... 
checking for WAVPACK_LIBS (pkg-config)... no
checking for WAVPACK_LIBS (-lwavpack)... no
checking for header <mp4v2/mp4v2.h>... no
checking for header <mp4.h>... no
checking for header <neaacdec.h>... no
checking for FFMPEG_LIBS (pkg-config)... -lavformat-ffmpeg -lavcodec-ffmpeg
checking for FFMPEG_CFLAGS (pkg-config)... -I/usr/include/x86_64-linux-gnu
checking for header <libavcodec/avcodec.h>... yes
checking for successful build of ffmpeg.c... yes
checking for header <ayemu.h>... no
checking for PULSE_LIBS (pkg-config)... no
*** Package libpulse was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libpulse.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libpulse' found
checking for ALSA_LIBS (pkg-config)... -lasound
checking for ALSA_CFLAGS (pkg-config)... -I/usr/include/alsa
checking for JACK_LIBS (pkg-config)... no
*** Package jack was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `jack.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'jack' found
checking for SAMPLERATE_LIBS (pkg-config)... no
*** Package samplerate was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `samplerate.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'samplerate' found
checking for AO_LIBS (pkg-config)... no
checking for AO_LIBS (-lao)... no
checking for program artsc-config... no
checking for header <sys/soundcard.h>... yes
checking for SNDIO_LIBS (-lsndio)... no
checking for header <sys/audioio.h>... no
checking for ROAR_LIBS (pkg-config)... no
*** Package libroar was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libroar.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libroar' found
```

### cmus --plugins

```
Input Plugins: /usr/local/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  alsa
  oss
```

Thanks for the awesome program, I would love to donate somehow but not sure where... if there is an official development fund, please let me know.

**Comment by SimonLefort** [comment]
I am not the only one who have this kind of problem. We have to find a solution. :-) 

Do you try to compile yourself? What parameters did you use?

**Comment by SimonLefort** [comment]
I am not the only one who have this kind of problem. We have to find a solution. :-) 

Do you try to compile yourself? What parameters did you use?

**Comment by slinkeepy** [comment]
No parameters, just limited dependencies for ALSA and NCURSES and FFMPEG I think (just what I thought I needed).

Output of ./configure should hopefully allow the devs to see what might be causing it.

Before I installed all the correct Ncurses packages, it was not displaying unicode Japanese.... so, I am wondering if I have a missing dependency? (However it seems unlikely given the ./configure output...).

**Comment by SimonLefort** [comment]
Nodoby can help us ? Even with just something to try ?

**Comment by ForTheReallys** [comment]
Could you upload (or email forthereallys@hotmail.com) the files giving you problems? I'll take a look at it later today

**Comment by inspell** [comment]
If you are building cmus by yourself you should probably build it against
libncursesw instead of libncurses. I
had similar issue before with cyrillic characters. See if this could help:
https://github.com/cmus/cmus/issues/18

**Comment by slinkeepy** [comment]
[berserk_forces.mp3.zip](https://github.com/cmus/cmus/files/1507156/berserk_forces.mp3.zip)
NOTE: "ffmpeg -i ..."  mentions "[mp3 @ 0x10ac920] Skipping 0 bytes of junk at 0." for the above file

[05-binaerpilot-cornered.mp3.zip](https://github.com/cmus/cmus/files/1507191/05-binaerpilot-cornered.mp3.zip)
NOTE: "ffmpeg -i ..." mentions "[mp3 @ 0x10ac920] Skipping 0 bytes of junk at 0." for the above file

The issue isn't whether these may or may not be corrupted in some way, more that they played perfectly in the 2.7.1 version from the repo.

Even so, thanks for the link inspell, thought that might lead to a solution, but seems not.
I did try:

"; ))) Thank you, after removing libncurses5-dev (note: libncurses5 still exists because lots of applications depend on it) and installing libncursesw5-dev cmus is showing cyrillic titles - see screenshot."

However pretty sire those 2 files weren't displayed properly in the previous version either, so it might be an issue with handling corruption. I will double-check when I have some time though, as I have to head off to work.

Thanks for any attention given to this relatively small issue, appreciate it! :)

(Also still would like a way to officially donate to the project, if it exists...).

**Comment by ForTheReallys** [comment]
@slinkeepy did you compile from the latest commit.  The tags have bad characters but I didn't have a problem playing the mp3 or quitting.

**Comment by slinkeepy** [comment]
Unfortunately it only says "cmus v2.8.0-rc0" when i do --version, however I might be able to get more info from source files when I'm home. (I don't know if it's a weird dependency problem, since it's working for you?)

**Comment by amangrewal** [comment]
I also have this issue. The characters appear fine in the browser view, but they appear as <f0> or similarly in the play queue view.

````
 > cmus --version

cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
````

````
 > uname -a

Linux hostname 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
````

**Comment by fluoroom** [comment]
Hi! I'm running Manjaro and have the same problem, files with accented characters will play but crash the interface until i close the terminal with the pointer or alt+f4. I searched linbcursesw5-dev but apparently this package doesn't exist on Arch.
`$ uname -a
Linux LP 4.20.6-1-ck-silvermont #1 SMP PREEMPT Thu Jan 31 15:46:30 EST 2019 x86_64 GNU/Linux
`
`$ cmus --version
cmus v2.8.0-1-g7f12156`

**Comment by amangrewal** [comment]
@fluoroom, you're issue sounds more like #847. A workaround might be to make sure all your tags are encoded in UTF-8, but I haven't tested that.

**Comment by nefthy** [comment]
>berserk_forces.mp3.zip
>NOTE: "ffmpeg -i ..." mentions "[mp3 @ 0x10ac920] Skipping 0 bytes of junk at 0." for the above file

>05-binaerpilot-cornered.mp3.zip
>NOTE: "ffmpeg -i ..." mentions "[mp3 @ 0x10ac920] Skipping 0 bytes of junk at 0." for the above file

Both files play fine, tags containing broken chars are considered as being empty. No "junk" bytes reported.

- Which version of ffmpeg do you have?
- What is the output of `locale`?
- Which terminal is cmus running in?

**Comment by fluoroom** [comment]
@amangrewal you were right, there were other song with special characters that played fine. This problem was because the .cue file that contained the song names was not UTF-8. Thanks!
