### ISSUE TITLE
Built-in equalizer

### ISSUE THREAD

**Issue by spywhere** [cmus/cmus#745]
It would be nice to have an equalizer to adjust the particular range of frequencies. As my preference would crank up the bass and high frequency a lot. And also compensate for a low headphone quality.

**Comment by Rhundom** [comment]
Yeah man, Hopefully something like this comes with new update.
But I honestly don't see the problem in just using another equaliser at the same time as using cmus?

**Comment by gordio** [comment]
But, please, if someone try to implement this. Do it enable/disable.

P.S. For now you can check [ArchLinux Wiki: ALSAEqual](https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#Using_ALSAEqual_.28provides_UI.29)

**Comment by nefthy** [comment]
This would require significant changes to implement.
