### ISSUE TITLE
sync cmus library with external device?

### ISSUE THREAD

**Issue by lukeoftheaura** [cmus/cmus#746]
Is it possible to sync my cmus music library with an external device (a portable music player) or would I have to do it manually by copying the files from all my music folders?

**Comment by criztovyl** [comment]
I think you will have to copy them manually, cmus is mostly a player not a synchronizer. :)

Anyway, under GNU/Linux it should only be a simple `rsync src1 src2 src3 dest`. ^^

**Comment by lukeoftheaura** [comment]
How did I not think of using rsync? Thanks!
