### ISSUE TITLE
Progress visualization on :add, and maybe multiple threads? [enhancement]

### ISSUE THREAD

**Issue by josefson** [cmus/cmus#747]
Maybe there should be a visual progression when :adding something. I just tried to add my 80GB library and i had no idea of what was happening, or even if anything was happening. Actually i have started it 5 hours ago and it hasn't yet finished.
Maybe a cli option where we could import the library from outside the application and the cli could print whatever was going on with the inclusion process.
```mcus --command 'add /path'; mcus -c 'add /path'```
This way, i imagine it would not require too much plugging into the gui itself. Maybe some, multiprocess/threaded thing here would also work for it would split the job into N parts.

**Comment by pgaskin** [comment]
Fixed by 67cbbe287bc5b2c7db68c6b97372383a19085a2f (#1317), which adds a track count to the view title while an update is in progress.
