### ISSUE TITLE
pl-* commands not being recognised

### ISSUE THREAD

**Issue by lukeoftheaura** [cmus/cmus#750]
cmus won't recognise all the pl- commands `pl-create` `pl-export` etc, that are mentioned in the documentation. They're also not listed in the manpage.

**Comment by criztovyl** [comment]
Which version of cmus are you using?

**Comment by lukeoftheaura** [comment]
2.7.1

**Comment by criztovyl** [comment]
`pl-` commands will be introduced in 2.8.0 but you can try to use `cmus-git` (AUR). :)

**Comment by lukeoftheaura** [comment]
ok.
