### ISSUE TITLE
How to bind control keys (esp ^Z)

### ISSUE THREAD

**Issue by JoshCheek** [cmus/cmus#751]
**Use a caret and a capitol letter.** Eg to bind C-p to behave like emacs / readline, you would do:

```
:bind common ^P win-up
```

---

Figured the above out while writing this, so figured I'd save any other search engine readers some confusion. BUT, my actual goal is  to make the [detachable-cmus](https://github.com/cmus/cmus/wiki/detachable-cmus) work with ^Z, because that's more consistent with how my other programs work (eg detaching is more like backgrounding than quitting).

When I enter it as "^Z", it shows up in the keybindings list, but does nothing. Also note that when I tried to type it directly, it did nothing, I had to type it with `^V ^Z` to get it to show up (it displayed as `<1a>`, which seems correct but didn't do anything useful). Maybe that means that `^Z` is somehow treated special?  I don't see it bound to anything on the list, but I was expecting it to be bound to a function that sent the current process "SIGSTOP" or something, so again, further evidence that it's somehow an edge case.

**Comment by nefthy** [comment]
^Z is special and cannot be bound as it is intercepted by the terminal.

**Comment by JoshCheek** [comment]
I checked and my terminal is passing `^Z` through:

```sh
$ ruby -r io/console -e 'p $stdin.getch'
"\u001A"
```

Are you sure it's the terminal and not whatever lib is reading the lines?

**Comment by JoshCheek** [comment]
Got it, thank you :)
