### ISSUE TITLE
Allow to raise the window

### ISSUE THREAD

**Issue by kitsunyan** [cmus/cmus#756]
A lot of terminal emulator applications place `WINDOWID` envvar with X window id. This can be used to raise the terminal window with running cmus application.

I want to suggest implementing `Raise` method of MPRIS proto using this envvar.

Using `shell` command it's possible even now: `shell xdotool windowraise $WINDOWID` (can be useful with `cmus-remote`). Probably this long command could be implemented natively as well.

**Comment by flyingmutant** [comment]
Fixed in #757.
