### ISSUE TITLE
Any ETA on multiple playlists feature?

### ISSUE THREAD

**Issue by Yodzeity** [cmus/cmus#766]
In my opinion, the one last feature cmus needs to top any other music players

**Comment by ForTheReallys** [comment]
It actually has that feature but you have to compile it yourself

**Comment by qcom** [comment]
Are there any instructions for compiling with the multiple playlist feature?

I scanned the Options & Optional Features listed from: `./configure --help` but didn't see a relevant option.

Let me know if I'm looking in the wrong place it's been a while since I've compiled a C project!

**Comment by Yodzeity** [comment]
Pretty sure it's still in the list of to-do features. Would really like that to be made official.

**Comment by criztovyl** [comment]
IIRC I have multiple playlists in my cmus, where did you install from?
Most likely it's in upcoming 2.8.0 (master) and does not require any configure option - try cloning master, `./configure` and `make`.
