### ISSUE TITLE
Is there a way to make playlist list smaller?

### ISSUE THREAD

**Issue by deseven** [cmus/cmus#772]
So, here is what it looks like right now:
![](http://eri.deseven.info/scr/PentaploidicExpiscatorDendrocoele.png)

As you can see the left part takes too much space. Is it configurable?  
If it's not then it would be a very nice addition.

**Comment by pgaskin** [comment]
@deseven:

```
set tree_width_percent=100
set tree_width_max=<width>
```

Replace `<width>` with your desired width.

**Comment by deseven** [comment]
@pgaskin
Thank you! Unfortunately i don't use cmus anymore, but hopefully others will find it useful too.
