### ISSUE TITLE
A few questions (feel free to close)

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#773]
New release when? It's been a while. I'm especially looking forward to this feature #712 

Also, can't find any info on (perhaps I'm looking in wrong places) whether it's possible to change some behavior - I don't like that when I press Z (that is "previous song") it doesn't play the previous song, but starts the current one from the beginning. Any way to change this?

And the last question: is it possible to play songs from Browser exclusively, without adding the songs to the library? When I start a song in Browser, it plays, what plays next is not the next file (which would be intuitive, imo), but songs from the library

**Comment by nefthy** [comment]
>  New release when? It's been a while. I'm especially looking forward to this feature #712
https://github.com/cmus/cmus/releases/tag/v2.8.0
> Also, can't find any info on (perhaps I'm looking in wrong places) whether it's possible to change some behavior - I don't like that when I press Z (that is "previous song") it doesn't play the previous song, but starts the current one from the beginning. Any way to change this?
I do not think so, but as behavior does not match documentation it can be considered a bug.
> And the last question: is it possible to play songs from Browser exclusively, without adding the songs to the library? When I start a song in Browser, it plays, what plays next is not the next file (which would be intuitive, imo), but songs from the library
I don't think that there is any option for this at this time.
