### ISSUE TITLE
Cmus using wrong font for non-selected songs/playlists

### ISSUE THREAD

**Issue by The-Soulless** [cmus/cmus#779]
1) `uname -a`:
```
Linux Mercury 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```
Image related
![2018-02-17-223452_1366x768_scrot](https://user-images.githubusercontent.com/29988574/36348327-c9f026da-1432-11e8-9d91-c1768bad706f.png)

**Comment by criztovyl** [comment]
You mean the difference between "The Script" and "The Script" in the album list?

**Comment by The-Soulless** [comment]
Sort of, I guess the image wasn't too good as you can't really see it. When not selected it's the terminus font, but when I do select it, it becomes Scientifica (The font I have set for the rest of the Terminal)
In the image attached to this you can see that "Panic! At the Disco" is the Scientifica font, while Maroon 5 and Putzel are terminus
![2018-02-18-141114_1366x768_scrot](https://user-images.githubusercontent.com/29988574/36356277-987fea62-14b5-11e8-8ff8-c51727c00f0b.png)

**Comment by ForTheReallys** [comment]
That looks like more of a terminal issue. What terminal are you using?

**Comment by The-Soulless** [comment]
I'm just really silly, I didn't realize until last last night that it was just the bold version of my font.
