### ISSUE TITLE
RFE: A config option to set "Various Artists" instead of "<Various Artists>"

### ISSUE THREAD

**Issue by kevinclevenger** [cmus/cmus#781]
I find the positioning of <Various Artists> at the top pretty functionally and visually annoying. It would be great of there was a config option to just in-line it in the regular Artist/Album list.

(Awesome piece of software btw, very well done).

**Comment by kevinclevenger** [comment]
This is in my current version (2.7.1-9), closing this request

**Comment by kevinclevenger** [comment]
I refreshed my library and <Various Artists> is present again. Not sure why it disappeared in the first place.

**Comment by nefthy** [comment]
Please see "LIBRARY VIEW SORTING" in the manual. It is working as described.
