### ISSUE TITLE
(pemanently)deleting track

### ISSUE THREAD

**Issue by DrDonkey** [cmus/cmus#783]
How can you delete currently playing track?
Also can you delete tracks from view 1 and 2?

**Comment by criztovyl** [comment]
Regarding view 1 and 2, I think <kbd>DELETE</kbd> (`:win-remove`) is what you are searching for.

Note that this deletes it only from the library, not from the file system.

Not sure if there is a command for removing the currently playing track, but you can select the currently playing track via <kbd>I</kbd> (`:win-sel-cur`).

Also note that cmus has an integrated help screen in view 7. You can search there by <kbd>/</kbd> (`:start-search`).

**Comment by DrDonkey** [comment]
It deletes only from library(except browser view).
is there a command that takes me to currently playing song in browser view.?

**Comment by nefthy** [comment]
Deletion from file system is not and will not implemented, as media files are treated read-only.

Removing currently playing file from library is also not implemented currently.

**Comment by kklot** [comment]
> Deletion from file system ... will not implemented

Why is that, is there a way to do this from the user end, my need is not relevant but this is the first thing I need from a music player and is the only reason keep me from using `cmus`. For reference, IINA is perfect for this.

**Comment by grenzionky** [comment]
@aasutossh you can permanently delete the currently *highlighted* file by doing `:run rm -f {}`

or you can bind it to a key (like delete) by doing `:bind -f common delete run trash {}`

**Comment by aasutossh** [comment]
Can't try this now. Not using cmus anymore.

**Comment by ekaunt** [comment]
Out of curiosity, what do you use now?

**Comment by grenzionky** [comment]
Out of curiosity, what do you use now?

**Comment by aasutossh** [comment]
I used mpd with Manjaro KDE's default music player (I don't even remember the name). I use VLC too.

**Comment by anton-rs** [comment]
> @aasutossh you can permanently delete the currently _highlighted_ file by doing `:run rm -f {}`
> 
> although id recommend only putting it into the trash (with something like `trash-cli`)
> 
> you can bind it to a key (like delete) by doing `:bind -f common delete run trash {}`

this is amazing. Even after I close cmus, the delete button still working. I thought it was only working for a session.

**Comment by skafiend** [comment]
if you run trash on an album, you might want to delete the empty folder as well:

`bind library D run sh -c 'trash "$@"; find /media/stuff/Music -type d -empty -delete' -- {}`

or you might need to delete a file while browsing a playlist:
`bind playlist D run sh -c 'trash "$@" && cmus-remote -C -P "win-remove" &' -- {}`
