### ISSUE TITLE
[Question] Problem with Cmus plugin

### ISSUE THREAD

**Issue by azzamsa** [cmus/cmus#792]
I tried building cmus from source with the curent git commit.

I got some error. But fortunately this issue (https://github.com/cmus/cmus/issues/468) help me a lot.

The problem is:

1) I have installed all depedency. I run `./configure` with no depedency missing.

2) After running `make`. Cmus doesn't find `/usr/local/lib/cmus/op` and `ip`. So I created both folder manually *with root as owner*

3) Running `make` again in fresh cmus clone. But still cmus doesn't have output of `./cmus --plugin`.

4) then I tried to copy my current installed cmus plugin `/usr/lib/cmus/ip` & `op`. But it comes that the plugin doesn't compatible

5) I tried to change `local` `ip` and `op` folder to non-root owner but no luck.

6) tried to see what happened if I do `sudo make`. But nothing works.

Thanks.

PS: *I have current working cmus installed from Debian 9 repo. But I want the last cmus cause the current doesn't have `repeat song` working*

**Comment by azzamsa** [comment]
I can't find the solution. 

Since then, I move to mpd with mingus as client.

Thanks lot for cmus.

**Comment by jayay** [comment]
You should try giving `./configure` the `--prefix` parameter. For example:
`./configure --prefix=/usr`

Then you run `make`, then `sudo make install` which will copy the compiled binaries to the appropriate places.

**Comment by lee-tts** [comment]
Quick correction: that's `./configure prefix=/usr`.

It does not take any dashes `--`.

Thanks!
