### ISSUE TITLE
CMUS controls on Solus 3

### ISSUE THREAD

**Issue by deSalier** [cmus/cmus#794]
Hi,

I recently installed CMUS on Solus 3, and ran into a problem.
The F1 to F7 keys are not doing what I expected of them. F1 opens the help for the Terminal, and the rest of the keys do nothing.

Is there anyway I can change the controls, as I don't have any way of controlling the pages in CMUS now.

I asked the same question at Solus, but so far no answer.

**Comment by nefthy** [comment]
The cmus views are bound to 1 through 7 per default.
