### ISSUE TITLE
Any way to use cmus with osdlyrics?

### ISSUE THREAD

**Issue by DrDonkey** [cmus/cmus#795]
And I found one patch file that allows the use of osdlyrics with cmus.
[This is the one](https://code.google.com/archive/p/osd-lyrics/issues/262).
But I don't know how to/ what to do now. How do you apply patch file?

**Comment by nefthy** [comment]
There is no build in support for osdlyrics. 

The patch you found is unofficial and quite old. if you do not already know how to apply patches, chances are that this is too advanced for you.
