### ISSUE TITLE
cmus freezing (Fedora 28)

### ISSUE THREAD

**Issue by sttyru** [cmus/cmus#798]
---

1) `uname -a`:
```
Linux e2e4 4.16.6-302.fc28.x86_64 #1 SMP Wed May 2 00:07:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao
```
**_cmus was installed from rpmfusion repository._**

**Description:**
Installation was an ok and application was started by normal. But after of some tracks has been played cmus gonna "freezing" and do not responding by signals from the keyboard. All of tracks are have of MOD or XM format (chiptune music). Freezings are a random sequence. The sound don't break until the track has been ended. After the track has been ending I can't jump to another song and application do not starting of the next file too by automatically. The process is stilling and can be terminated by manually by a command only (e.g. by SIGTERM).

Where I can find of the stable version of `cmus` for Fedora 28? In my sorry I can't build of the software from src because have an error linked with MODPLUG_LIBS and another libraries).

**Comment by nefthy** [comment]
Is this still happening with the 2.8.0 release?

**Comment by pgaskin** [comment]
I'm going to close this issue since it hasn't had a response for over 2 years. @sttyru, feel free to reopen it if you still have issues with the latest RPMFusion package on a recent Fedora version.
