### ISSUE TITLE
Multiple artists

### ISSUE THREAD

**Issue by Clyme** [cmus/cmus#806]
I have a rather large music collection and I also have pretty much all releases of every artist in there. Some artists published hundreds of tracks, with the occasional collaboration this results in a LOT of duplicates (as seen in the screenshot). I wonder if it is possible, or if not if it could be added, that instead of having every track by artist A, B and C listed separately as `A/B/C - track`, the track is shown under A, B and C. This worked fine in Foobar2k, which i used on my laptop when I started my collection, but since i moved it to my Arch PC i haven't been able to find an application that supports this
![screenshot_2018-06-15_04-18-45](https://user-images.githubusercontent.com/40283399/41447125-2df061ce-7043-11e8-9f06-20b5ec2ce459.png)

**Comment by jtl999** [comment]
I have the same issue. Something needs to be done, both mp3 and FLAC files.

**Comment by Clyme** [comment]
Sure thing, is the attached file ok?
[tags.txt](https://github.com/cmus/cmus/files/2833286/tags.txt)

**Comment by nefthy** [comment]
Ok now I understand. This is not possible in cmus. The artist in your id3tags is "A / B / C". For cmus this is one artist with that name, not 3 artists. Assigning the song to all artists, requires guesswork and interpreting tags in ways, that go beyond what the standard says. I do not think that such a feature would be accepted.

**Comment by RodrigoLeiteF** [comment]
Since Picard 1.3, it's used a multi-valued tag named "artists" to deal with this problem. Would it be possible to implement this functionality in cmus? According to [the documentation](https://picard.musicbrainz.org/docs/tags/) they're separated by a semicolon (`;`).
