### ISSUE TITLE
Can't Add Music (Arch Linux)

### ISSUE THREAD

**Issue by joshuarosato** [cmus/cmus#809]
Using cmus v2.7.1 on Arch Linux.

Tried adding music via browser and :add command. Both seem to do nothing.

**Comment by maggick** [comment]
Can you give us more information
1) `uname -a`
2) `cmus --version`
3) `cmus --plugins`
(it's working on the latest version available on the repository)

**Comment by joshuarosato** [comment]
Installed version 2.8 from AUR and everything seems to be working now.
