### ISSUE TITLE
Can't add m3u8 streams

### ISSUE THREAD

**Issue by arun-oo7-xx** [cmus/cmus#810]

**Comment by nefthy** [comment]
Please provide details

**Comment by pjlbyrne** [comment]
Can this be reopened please? It is still an issue. Example:

$ ffplay -nodisp http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/high/cf/bbc_radio_fourfm.m3u8
This plays BBC Radio 4 correctly.

 $ cmus --listen http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/high/cf/bbc_radio_fourfm.m3u8           cmus: bind: No such file or directory
This fails.
