### ISSUE TITLE
Bit Perfect Playback (dsp.alsa.resample=false)

### ISSUE THREAD

**Issue by shoober420** [cmus/cmus#811]
---

1) `uname -a`:
```
Linux archlinuxdayum 4.17.8-1-zen #1 ZEN SMP PREEMPT Wed Jul 18 09:56:17 UTC 2018 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0-90-g17bf542
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```
I've been googling how to get bit perfect audio playback with cmus, and have changed the following options.

output_plugin=alsa
dsp.alsa.device=plughw:0,0
mixer.alsa.device=front
mixer.alsa.channel=:blank:
softvol=false

It appears to be bit perfect, but there is an option in the Deadbeef audio player that has the ability to disable ALSA resampling in the plugins settings menu. I don't see any option in my config to completely disable ALSA resampling. Could you add an option to disable ALSA resampling, as does the deadbeef audio player allows? Also, maybe offer more information on setting up cmus for bit perfect audio playback?

I have no Pulseaudio software installed.

**Comment by shoober420** [comment]
I thought I should share how I acquired this information, and maybe a suggestion on an added option.

I read a thread about bit perfect audio playback for numerous Linux audio players, and one post mentioned cmus. I've come across this thread when searching for how to get deadbeef setup for bit perfect audio.

It mentions the "dsp.alsa.device" setting should be set to "plughw:0,0" or something similar like "hw:0,0". I tried the "plughw:0,0" setting, and cmus automatically changed it to "hw:0,0".

It also says to leave the "mixer.alsa.device" and "mixer.alsa.channel" blank or delete any setting thats assigned to them. I disagree with this.

I literally got called into work, FML. I will edit and continue this when I get home.

**Comment by shoober420** [comment]
To clarify further, I should state my specs. I have an ASUS Xonar Essence STX sound card. I will have different options then you will more then likely.

The "dsp.alsa.device" setting correlates with all the devices listed with "aplay -L". Generic sound cards will have names such as "plughw" and "hw0,0". My sound card is above average, so it has different names. For example, for my sound card, I want this set to "front:CARD=STX,DEV=0"

Next is "mixer.alsa.channel". This is for changing the volume via the alsamixer program without actually opening it and running it. The value for this setting is usually what is the name of the first bar on the left. Most people probably have it named "PCM". Mine though, is named "Master".

In all honestly, I feel it would be ok to assign "mixer.alsa.channel" the name of your volume bar and "mixer.alsa.device" the same as "dsp.alsa.device", but for the sake of cmus not talking to the alsa mixer in anyway to avoid dmix, lets leave both "mixer.alsa.channel" and "mixer.alsa.device" completely blank.

In the end, my config now looks like this:

output_plugin=alsa
dsp.alsa.device=front:CARD=STX,DEV=0
mixer.alsa.channel=
mixer.alsa.device=
softvol=false

With these settings, or similar for other sound cards, one should have bit perfect audio playback.

There is one discrepancy. The deadbeef audio player has an option to disable alsa resampling completely via the ALSA plugin settings menu. I propose an idea of having a similar option, like for example:

**dsp.alsa.resampler=false**

Just to ensure bit perfect audio playback.

**Comment by jtl999** [comment]
One thing to add. If dmix is disabled and cmus is "locking" the audio device, it is bit perfect.

How to do the same programmaticly with dmix.

```
[jtl@jtl-desktop ~]$ cat /proc/asound/card1/pcm0p/sub0/hw_params 
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 221
buffer_size: 13230
[jtl@jtl-desktop ~]$ cat /proc/asound/card1/pcm0p/sub0/hw_params 
access: RW_INTERLEAVED
format: S24_3LE
subformat: STD
channels: 2
rate: 96000 (96000/1)
period_size: 481
buffer_size: 28800
```

**Comment by shoober420** [comment]
Thank you for commenting jtl999. It gave me the courage to disable dmix again. I disabled dmix in the past, but it also gave me issues with some games having no sound. One I can particulary remember is all GoldSrc games (Counter-Strike 1.6), so I enabled it again. This was because the sound files for that game (22kHz) are not supported by my sound card. My sound card only does 32kHz and up. So when purchasing a new DAC, one may want to keep this in mind.

Anyway, I googled and was looking for the best solution to disable dmix, and got a example to share. This will guide someone to disable dmix themselfs if they so desire.

You can get the actually name of your audio devices as Linux sees them, by using the following command.

cat /proc/asound/card*/id

More than likely, "card0" is going to be your main audio device. On my machine "card0" is "STX", which is my ASUS Xonar Essence STX card, and "card1" is "NVidia", which is the HDMI audio output on my GeForce GTX 760 video card.

Knowing this, you won't have to use "(hw:0,0)" to identify which audio device to use. "hw:0,0" being the STX sound card, and "hw:1,0" be the NVidia video card.

We must create an "asound.conf" file in the "/etc" directory, or a ".asound.conf" file in your home directory if you don't want this to be a global setting, and just a user setting.

Now, since we know what the name of our sound card is, we can create a pcm handle named after our sound card we want to use. To do this, here is an example code.

pcm.STX {
type hw
card "STX"
}

Next, we will bind the default ctl to the hw driver.

ctl.!default {
type hw
card "STX"

Finally, we will create the default pcm, and use the "plug" wrapper to adjust sample formats when needed (when going from a redbook audio file to 24/96). Then we will force it to never change the sample rates under any condition.

pcm.!default {
type plug
slave {
pcm "STX"
rate "unchanged"
}
}

This method is the most modern, and logical example I found on the internet. If someone has another method they feel is better, please share.

**Comment by fdf92441** [comment]
Try to add this setting but damage my cmus and now I get this error: Error: opening audio device: No such file or directory.

**Comment by shoober420** [comment]
@fdf92441 
Which setting?

**Comment by fdf92441** [comment]
Now it works, but I had to put this setting.
`output_plugin=alsa
dsp.alsa.device=default
mixer.alsa.channel=Master
mixer.alsa.device=default
softvol=false`

I think with this I no longer have a bitperfect.

But I have a problem that haunts me for a long time.

Whenever I turn on my computer I must add my music directory. Because all my music is on an HHD hard drive and Ubuntu is on an SSD. And I don't know how to prevent this from happening.

**Comment by shoober420** [comment]
@fdf92441 
The big setting that was causing that issue, is "dsp.alsa.device". So heres whats going on, depending on what sound card/DAC you have, what it does is use "zero padding" to playback 24bit audio using 32-bit. My last sound card, the ASUS Xonar Essence STX had a burr brown DAC, i cant remember which one, but it played 24bit audio at 32bits using "zero padding".

My new Topping D50s has a ESS Sabre DAC, and even zero pads 16bit audio to 32bit. This is still technically bit perfect, so its nothing to worry about. Its just very odd. On my Xonar Essence card, I could use "hw:0,0" with 16bit audio, but needed to use "plughw:0,0" for 24bit files.

The best way to test your DAC if it uses zero padding, and for which bits, is to play files with aplay. Using "aplay", are you talking directly to your sound card. Read the man page for aplay (man aplay) for more info. I do remember using the "--disable-resample" launch option for aplay to attempt to play audio files back without zero padding.

**Comment by nefthy** [comment]
> On my Xonar Essence card, I could use "hw:0,0" with 16bit audio, but needed to use "plughw:0,0" for 24bit files.
if you do not use plughw alsa can only playback bit depths and sampling rates directly supported by the hardware. In your case 24 bit is not supported in hardware, so you'd need plughw to convert that something your card can play.

**Comment by shoober420** [comment]
@nefthy 

The Xonar card advertises support for 24bit audio (https://www.asus.com/us/Essence-Hi-Fi-Audio/Xonar_Essence_STX/specifications/). Although I can't playback 24but audio files unless I use "plughw:0,0", which zero pads it to 32bit for some reason. I remember using arecord to check the available modes, and it listed "S16_LE" and "S32_LE" for my Xonar card. My new Topping D50s which supports 32bit, zero pads everything to 32bit audio, and only lists "S32_LE".

**Comment by nefthy** [comment]
@shoober420 Either your card or the driver does not support 24 bit. There is really no information loss, when zero padding to 32 bit, so I would not get headaches over it.

**Comment by shoober420** [comment]
@nefthy 
Yes, zero padding seems to be a technique used in a lot of DACs apparently to get 24/32bits. It should still be bit perfect anyway, so its ok. Thank you.
