### ISSUE TITLE
better PRNG

### ISSUE THREAD

**Issue by xeverse** [cmus/cmus#819]
shuffle-random mode 
def needs improvement..

**Comment by nefthy** [comment]
could you elaborate?

**Comment by xeverse** [comment]
well quite often i get the same pattern    
over & over in the shuffle mode. i guess  
i can produce a small gif next time it occurs..

**Comment by Nomarian** [comment]
Whenever I erase a song, the shuffle actually restarts, as if it just generated a list of random tracks to play and then it replays again. This is from the library view.

**Comment by gavtroy** [comment]
We do generate a shuffle list and then play through it, and we do lose position and reset to the start when the currently playing track is removed or filtered out. There is certainly some room for improvement here.

That said, as of 2.10.0 we do at least reshuffle the list when we lose our position so the repeating patterns shouldn't happen anymore.

**Comment by pgaskin** [comment]
> xeverse: well quite often i get the same pattern

> gavtroy: as of 2.10.0 we do at least reshuffle the list when we lose our position so the repeating patterns shouldn't happen anymore

Seems like the OP's complaint has been resolved.
