### ISSUE TITLE
Multi-Disc/Part albums don't display properly

### ISSUE THREAD

**Issue by 31j** [cmus/cmus#821]
Some albums are out of order, so if it is a 3 part album it goes 1.1, 2.1, 3.1, 1.2, 2.2, 3.2 etc. instead of putting them in the normal 1.1, 1.2, 1.3 order. 

I know for a fact that the metadata for everything is correct, I checked in iTunes as well as on my phone, and my Arch desktop. Not sure why it is doing that? 

The other problem is within the main Artist/Album pane, any album that contains multiple discs, records, or mixtapes does not correctly display. They are displayed as one album that isn't divided by a line that says 1, 2, 3 etc. OR by the name of each part e.g. HouseOfBalloons, Thursday, and EchoesOfSilence 

---

1) `uname -a`:
```
Darwin James-Owens-MacBook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0-rc0_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.8.0-rc0_2/lib/cmus/op
  coreaudio
  ao
```

**Comment by nefthy** [comment]
```:set lib_sort=albumartist date album discnumber tracknumber title filename play_count```
