### ISSUE TITLE
Implementing Cmus UI on top of Deadbeef

### ISSUE THREAD

**Issue by Shellcat-Zero** [cmus/cmus#822]
I would like to submit a feature request to implement the Cmus UI on top of the [Deadbeef music player](https://github.com/DeaDBeeF-Player/deadbeef), motivated by the [very large file format support](http://deadbeef.sourceforge.net/about.html) that it has.  Their [wiki](https://github.com/DeaDBeeF-Player/deadbeef/wiki/Developing-your-own-plugin) appears to describe how one might go about this, as various UIs and other plugins have been implemented for Deadbeef.

**I would be willing to pay a $500 USD bounty for this feature.**

**Comment by Shellcat-Zero** [comment]
For a basic console interface on Deadbeef, see:
https://github.com/kuba160/ddb_gui_prompt

**Comment by jtl999** [comment]
I might try and take a look at this later, but how much functionality is missing from deadbeef that's in cmus?

**Comment by nefthy** [comment]
Plugin another player into the cmus UI is probably a dounting task as cmus is resonably complicated and idiosyncratic and it would result in a fork. 

Your bounty will be more usefull for the cmus project, if it is used to implement the features you are missing from cmus.

**Comment by davestechshop** [comment]
@Shellcat-Zero This is a very interesting idea. I will also contribute to the bounty. I can pledge $50 for sure and maybe more later. 

I am also interested in @nefthy 's alternative suggestion if the original proposal can't be done.

**Comment by Shellcat-Zero** [comment]
Agreed, @davestechshop and @nefthy.  I would be willing to allocate the bounty for this work in Cmus even if it isn't reasonable to plug the Cmus interface into Deadbeef.  My suggestion to use Deadbeef as a back-end was primarily because the components in Deadbeef for the aforementioned missing features are very actively maintained by their developers and in some cases have been made available in other music players ( [Kode54](https://github.com/kode54)'s work in Deadbeef & Foobar2000, for example).  In contrast, I had gotten the impression that the core team in Cmus has very little interest in supporting these features.  

In any case, Cmus is my favorite music player and I appreciate all the work that has gone into it, and I am more than happy to provide the bounty for these features however the dev team chooses to implement them.

**Comment by davestechshop** [comment]
@Shellcat-Zero - great! Count me in too with my contribution to the bounty. 

FYI, the features most important to me are:
- **high quality sound**. I play only lossless formats like FLAC
- convenient **playlist management**. I like to switch between multiple playlists with a single shortcut key.

**Comment by nefthy** [comment]
Closing since this is not an issue with cmus as such. Wish you best of luck with the undertaking.
