### ISSUE TITLE
Question: how to distribute tracks?

### ISSUE THREAD

**Issue by NewbProgrammer101** [cmus/cmus#829]
I have three playlists: Classical, Vitas, and Other.

I'm trying to add three tracks to Classical. But I have no idea how to add other tracks to these other playlists. They remain empty.

**Comment by Lagrang3** [comment]
@NewbProgrammer101 
1) go to playlist view;
2) use <space> to activate the playlist you would like to use;
3) go to any library view (1 or 2) and use the <y> key to add tracks to the playlist you activated in step (2).

**Comment by NewbProgrammer101** [comment]
Ok thanks.
