### ISSUE TITLE
build dependencies

### ISSUE THREAD

**Issue by ovitus** [cmus/cmus#835]
Having trouble installing this from source. There doesn't seem to be any repos available with cmus on Centos 7. Gets stuck looking on "C11 (with atomics support)."

[root@localhost cmus]# ./configure
checking for program gcc... /usr/bin/gcc
checking for program gcc... /usr/bin/gcc
checking for C11 (with atomics support)... no
configure failed.

---

1) `uname -a`:
```
Linux localhost.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
n/a
```

3) `cmus --plugins`:
```
n/a
```

**Comment by dwatteau** [comment]
Hi @ovitus,

If you're cloning HEAD, yes, you need a compiler with `stdatomic.h` support:
https://gcc.gnu.org/wiki/C11Status

Looks like you need at least GCC 4.9, but CentOS 7 provides GCC 4.8 AFAIK.

Either build cmus 2.7.0 (which doesn't require GCC 4.9), or you really want to use the current HEAD Git version, you need to find a way to build with a newer compiler on CentOS 7.

**Comment by nefthy** [comment]
You have to use a compiler with stdatomic.h support. No way arround that.
