### ISSUE TITLE
pywal colour support

### ISSUE THREAD

**Issue by Nine-H** [cmus/cmus#842]
I've been running cmus in i3 with a procedural color scheme created from my wallpaper by pywal, the problem is that the color aliases I need to use to theme the interface are meaningless because pywal schemes don't necesarily cover all the colours or have them in the same order, ideally there'd be some secondary aliases like color1, color2, etc.

![2018-11-28-102715_498x268_scrot](https://user-images.githubusercontent.com/20123543/49118446-5237cd00-f2f8-11e8-9bab-2bff79cfd978.png)

**Comment by nefthy** [comment]
I do not think that interoperability with pywal is with the scope of cmus.
