### ISSUE TITLE
elogind support

### ISSUE THREAD

**Issue by shibotto** [cmus/cmus#844]
Hi all! Could you please add elogind support for MPRIS? It supports sd-bus and I'm using it right now. The only thing I needed to change was https://github.com/cmus/cmus/blob/f5a442a041ee30b8a6bf8a171fa295b02d07481e/configure#L292 to
`pkg_config LIBSYSTEMD "libelogind"`

**Comment by geek1011** [comment]
@nefthy, shouldn't this issue be closed?

**Comment by nefthy** [comment]
Yes, it has been merged, but did not have the "Fixes #XXX" in the description, that does the closing automagic.
