### ISSUE TITLE
Cmus doesn't display anything in tty

### ISSUE THREAD

**Issue by amangrewal** [cmus/cmus#845]
---

1) `uname -a`:
```
Linux hostname 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.1
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
```

Issue:
In the virtual terminals, cmus has no output. The entire screen is just blank. Music plays, and I'm able to control it.
Other ncurses based applications (I tried htop and vi) work without issue.

**Comment by jayay** [comment]
Does this occur if you rebuild from current master?

**Comment by amangrewal** [comment]
No, it displays fine.

**Comment by amangrewal** [comment]
I was able to reproduce it on 
```cmus v2.8.0-rc0-93-gf5a442a```

It seems to occur when switching themes. Switching the scheme back to default (typing ```:colorscheme default``` into the blank screen) and restarting cmus causes the display to appear again.

**Comment by amangrewal** [comment]
After a little more digging, the issue seems to be that ttys don't support many colors. None of the themes that identify colors by number work, but the ones that identify them by name do work.

**Comment by nefthy** [comment]
For future reference: Which terminal do you use?
