### ISSUE TITLE
Cmus Refuses to play OGG Opus files

### ISSUE THREAD

**Issue by ibrokemypie** [cmus/cmus#848]
---

1) `uname -a`:
```
Darwin Conors-MBP.codenix.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.7.1_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.7.1_2/lib/cmus/op
  ao
```

When playing ogg opus files, which I have verified are fine by playing in other programs such as mpv, cmus reports ``Error: Couldn't get file information for`` then the path to the file

**Comment by nefthy** [comment]
Could you provide the said file somehow?

**Comment by nefthy** [comment]
I cannot reproduce this. The file you send works fine with cmus 2.8.0 on my system. 

- What version of libopusfile do you have installed?
- What version of libvorbis?

**Comment by joemaro** [comment]
I have the exact same error with cmus version 2.7.1 (is still latest on arch).

other versions are:
opus 1.3-1
opusfile 0.11-1
libvorbis 1.3.6-1

i have also found the solution now :P when renaming it to .opus it works (it was .ogg before)  @ibrokemypie does that work for you as well?

**Comment by nefthy** [comment]
2.7.1 is a bit dated. Maybe request a version bump for that package in arch now that 2.8.0 is released.

**Comment by ibrokemypie** [comment]
cmus 2.7.1, libvorbis 1.3.6, opusfile 0.11
this is on macOs installed through homebrew

**Comment by joemaro** [comment]
cmus is flagged as outdated since a while in the arch packages, it's probably on its way...

did the files in question have an .ogg extension @ibrokemypie ? try renaming them to .opus

**Comment by tomty89** [comment]
https://github.com/cmus/cmus/blob/9a0723f7a90dc7de0898be87963d5105a999aa6c/ip/opus.c#L331

Although `ogg` can be added here, apparently opus files **should not** have .ogg as extension: https://wiki.xiph.org/MIME_Types_and_File_Extensions

Btw, we should probably add `opus` here:
https://github.com/cmus/cmus/blob/9a0723f7a90dc7de0898be87963d5105a999aa6c/ip/ffmpeg.c#L522

**Comment by nefthy** [comment]
@tomty89 thanks for pointing out that opus files should not end with .ogg

Please make a PR for the ffmpeg.c

**Comment by ibrokemypie** [comment]
opus files almost exclusively *do* have an ogg extension, i guess they may have changed the recommendation recently, which is fair enough, but for a long time opus files have been encapsulated in an ogg container, and all opus files i have encountered are encapsulated in .ogg. on top of that, some players do not recognize .opus files yet, only .ogg, meaning that renaming an entire library to .opus because of a recent recommendation seems like a bad idea

"On Android and Microsoft Windows, the .opus filename extension isn't recognized by Android's MediaScanner service and Universal Windows Platform apps. A pseudo extension of another audio format (such as .ogg or .m4a) is required to detect and playback files."

https://en.wikipedia.org/wiki/Opus_(audio_format)#Notes
https://en.wikipedia.org/wiki/Opus_(audio_format)#Containers
https://en.wikipedia.org/wiki/Ogg#Ogg_codecs

**Comment by tomty89** [comment]
Note that unlike FLAC, which can be encapsulated in its native container or ogg, there's no such thing as native opus. It is always encapsulated in ogg (well, or webm or whatsoever), so it's just a matter of extension.

Platforms not supporting opus properly is IMHO not quite a reason for that we should recognize `.ogg` for opus (just like we don't do that for `.mp4` just because it "works" somewhere else).

I think the real problem is cmus simply should not rely on extension, but that would need someone work it out.

**Comment by nefthy** [comment]
@tomty89 I am with you on this. cmus should determine the actual mime-type and decide on the input plugin based on that. This will require significant amounts of change and testing however.

As is, this bug is invalid, as the .ogg extension for opus encoded files, does not adhere to the xiph recommendation.
