### ISSUE TITLE
Need troubleshoot info for "internal error"

### ISSUE THREAD

**Issue by seandarcy** [cmus/cmus#851]
---

1) `uname -a`:
```
Linux sixcore.server 4.19.13-200.fc28.x86_64 #1 SMP Sat Dec 29 23:10:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  ao

```
set output: set output_plugin=pulse
systemctl --user status pulseaudio.socket
Failed to dump process list, ignoring: No such file or directory
● pulseaudio.socket - Sound System
   Loaded: loaded (/usr/lib/systemd/user/pulseaudio.socket; enabled; vendor pre>
   Active: active (running) since Sat 2019-01-12 16:58:57 EST; 28s ago
   Listen: /run/user/501/pulse/native (Stream)
   CGroup: /user.slice/user-501.slice/user@501.service/pulseaudio.socket

Jan 12 16:58:57 sixcore.server systemd[5160]: Listening on Sound System.

pacmd play-file <file.wav> 0    works.

But, if I try to play from cmus:
Error: opening audio device: internal error

So pulseaudio is working, but cmus can't find/open the audio device ("sink"?). cmus should provide at least some info on what failed. Is it a pulseaudio config problem ? Maybe, but pulseaudio can play music. What was cmus looking for it didn't find ? Without some more info, I can't see how to troubleshoot.

**Comment by seandarcy** [comment]
For instance, what arguments were used in connecting to PA ?

**Comment by geek1011** [comment]
Can I see the contents of `/etc/pulse/client.conf`?

**Comment by pgaskin** [comment]
@nefthy, this issue hasn't had a response, so it should probably be closed.
