### ISSUE TITLE
Themes are Not Working

### ISSUE THREAD

**Issue by bilge-Kagan** [cmus/cmus#872]
Themes which are applied by `:colorscheme <name>` are not working  as expected; except the _default.theme_.
---

**default.theme:**
![default](https://user-images.githubusercontent.com/20368886/52911777-bba4f780-32b9-11e9-9ff7-57f7a21d414f.png)

**gruvbox.theme:**
![gruvbox](https://user-images.githubusercontent.com/20368886/52911784-d24b4e80-32b9-11e9-80f1-381e5b953cbf.png)

**night.theme:**
![night](https://user-images.githubusercontent.com/20368886/52911786-d8412f80-32b9-11e9-8ea4-026cd25383a5.png)

**zenburn.theme:**
![zenburn](https://user-images.githubusercontent.com/20368886/52911788-dd05e380-32b9-11e9-8d94-04488785c546.png)

1) `uname -a`:
```
Linux kamufle 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.7.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors

```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa ac3 aif aifc aiff ape au mka shn tak tta wma webm aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by geek1011** [comment]
Which terminal emulator are you using?

**Comment by nefthy** [comment]
Probably duplicate of this: #845

**Comment by nefthy** [comment]
@bilge-Kagan are you on a linux terminal without X?

**Comment by bilge-Kagan** [comment]
@geek1011 `xterm`

**Comment by bilge-Kagan** [comment]
@nefthy nope, i'm on xserver.. When I'm using _mint18.3_ there was no such a problem. Now, at _19.1_ .. maybe the emulator is cause of the problem..

**Comment by amangrewal** [comment]
What is the value of $TERM?

**Comment by bilge-Kagan** [comment]
@amangrewal 
```
$ echo $TERM
xterm
```

**Comment by amangrewal** [comment]
Does it work if you add
`XTerm.termName: xterm-256color`
to your .Xresources?

**Comment by bilge-Kagan** [comment]
```
$ cat .Xresources
xTerm.termname: xterm-256color

$ xrdb .Xresources
```
After re-open the terminal window:

`$ cmus`
**>>** (_night.theme_)
![ss](https://user-images.githubusercontent.com/20368886/54848958-c35e1e80-4cf3-11e9-935b-d0ed0dd6cc76.png)

**Comment by amangrewal** [comment]
> ```
> $ cat .Xresources
> xTerm.termname: xterm-256color
>```

Should be ```XTerm.termName```

Check $TERM to make sure it's set correctly.

**Comment by bilge-Kagan** [comment]
@amangrewal 
It works; but, not with your way. I could not set `xerm-256color` via `.Xresources`.
I used [this](https://codeyarns.com/2015/03/18/how-to-set-term-to-xterm-256color/) way.
Thanks everyone..
