### ISSUE TITLE
Latests Homebrew update breaks --with-ffmpeg

### ISSUE THREAD

**Issue by stylerw** [cmus/cmus#873]
I'm not sure what has changed, and whether it's at the homebrew level or the cmus level, but in the latest version, `brew install cmus --HEAD --with-ffmpeg` breaks with `Error: invalid option: --with-ffmpeg`.

I noticed this once CMUS updated recently and the ability to play ALAC files disappeared.  Thanks!

**Comment by nefthy** [comment]
It seems to me that this is a brew specific issue and you will have to report the bug to whomever is maintaining the brew cmus package.

**Comment by skyfaller** [comment]
Has this been reported to whoever maintains the Homebrew package? I'm too much of a noob to find where to report this bug. I really need --with-ffmpeg to play ALAC files, it appears.
