### ISSUE TITLE
Help request: how to report track duration from custom input plugin?

### ISSUE THREAD

**Issue by jpcima** [cmus/cmus#891]
Hi. I try to develop a custom ip plugin whose source is at this location:
https://github.com/jpcima/cmus-plugin-vgm/blob/master/sources/vgm.cc

My problem: cmus does not report the track duration which I expect.

For example, I expect this file to produce a duration of 3-4 seconds. [example](https://vgmrips.net/packs/vgm/Other/Akumajo_Dracula_%28Sharp_X68000%29/01%20Konami%20Logo.vgz)
On my build of cmus, it reports 11s; despite that the track playback is indeed stopping around 3.

My observation so far, based on debug logging made in both cmus and the plugin: 
- my `vgm_duration` callback is never called
- in fact, I find cmus `ip_duration` to never be called either

What is the origin of the value of 11s produced ? and how to override it?
or, is there a deeper mistake which I am missing?

Thanks for help.

`cmus v2.8.0-16-ge429ddf`

**Comment by nefthy** [comment]
ip_duration is called when adding files to the library not when playing them.

**Comment by jpcima** [comment]
Oh, could it be the case that this information is determined from the cache?

In my plugin I expose an `input_plugin_opt` to define the number of times the music track is looped.
According to this option, the track length will vary.
Is caching going to going to cause trouble with this functionality?

**Comment by nefthy** [comment]
It is cached. The value will not change if you change the option.

**Comment by jpcima** [comment]
It makes sense. Thanks for the information
