### ISSUE TITLE
playback ends early when in shuffle mode

### ISSUE THREAD

**Issue by badbetty** [cmus/cmus#893]
---

1) `uname -a`:
```
Linux asus1225b 4.4.157-habs1 #1 SMP PREEMPT Mon Feb 4 02:04:17 GMT 2019 x86_64 AMD C-60 APU with Radeon(tm) HD Graphics AuthenticAMD GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0   (also same issue with v2.8.0)
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib64/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib64/cmus/op
  pulse
  alsa
  oss
  ao

```

Playback ends early when in shuffle mode and the playlist is not completed. It seems to have started happening when multiple play lists were introduced?

There is difference in code file track.c after v.2.7.1, a version last known (and checked again) to me to be working fine with respect to this issue, so I wonder if this change is the cause of the problem?

As an aside perhaps, pressing 'b' (play-next) to jump through the playlist when in shuffle mode also gets to an early point where it stops going to the next song before all the tracks have been visited.

If I were competent (my apologies for not being) in C lang. I would try to investigate further, I feel that someone generally more familiar and/or originally involved in that part of the code change will have more rapid success at spotting any issue.

Irrespective of this issue, thank you to all involved with cMus over the years and keeping it going now - sincerely it is a lovely piece of kit and long may it continue...please !

**Comment by pgaskin** [comment]
I can confirm this issue with the latest commit on master.
