### ISSUE TITLE
mainly saying "thanks" :)

### ISSUE THREAD

**Issue by localhostdotdev** [cmus/cmus#896]
feel free to close this, but I wanted to say thanks, it's been forever I'm having a hard time having some great music player (tried pretty much every popular thing out there) and this just works so well.

a few remarks:

- I wanted to add a web radio, still haven't figured out how to do that (but reading the manual and shouldn't be too hard (it's a https://host.domain/path/file.mp3)
- when I opened it I tried a few commands like `:open my_url` and `:o my_url` and it didn't work, was expecting it to work
- cmus-tutorial is not a program but only a man page (was expecting something like vimtutor)
- in general i read as little docs as possible (just because I'm lazy) so I try to scan/parse it quickly to find what I need, and this seems to rely heavily on documentation
- not sure why ctrl-c / ctrl-d doesn't work as it doesn't seem to bind to anything
- there doesn't seem to be some kind of package manager for plugins (would be nice)
- main thing seems to know about 1/2/3/4/5/6/etc.
- mp4 files (from youtube-dl) are not mapped as artist/song, e.g. `Al Green-Lets Stay Together-COiIC3A0ROM.mp4`
- when I activate a filter (6) it doesn't seem to do anything
- maybe `q` two times could quit? (I use :q now :) )
- kind of weird that space is not mapped to play/pause as it's the case in most players
- `cmus url` doesn't open the url :( (ok, it was `:add url`)

anyway, nothing that a little customization, getting used to it and reading some bits of docs can't fix :)

---

1) `uname -a`:
```
Darwin d 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/op
  coreaudio
  ao
```

Thanks!

**Comment by nefthy** [comment]
Well you will have to read the documentation. It answers most if not all of your questions. You can usualy search by pressing `/` followed by the term you are interested in.

**Comment by nefthy** [comment]
A lot of the things you want to change can already be configured.

**Comment by localhostdotdev** [comment]
there is a huge difference between having things work out of the box and having to configure (I guess it's my "convention over configuration" side that's showing :D)
