### ISSUE TITLE
Stream name missing in cmus 

### ISSUE THREAD

**Issue by dirtbag** [cmus/cmus#901]
I can add streams and play them fine, but they all show up as a "." under <Stream>
can I rename them somehow?

1) `uname -a`:
```
Darwin peskymac 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/op
  coreaudio
  ao
```
![screenshot](https://user-images.githubusercontent.com/808514/57025667-d7a40e00-6c05-11e9-8921-bca4b05f1f6e.jpg)

**Comment by dirtbag** [comment]
nobody home eh?  oh well..

**Comment by kajzersoze** [comment]
Depends on a station, but yeah I found this as a problem as well on one station, problem is that I really like that one.
tag title is empty for this one, that's why there's only a . shown, but I guess it's very easy for devs to fix this with a check if that tag is empty then show url instead.
