### ISSUE TITLE
Bizarre Fonts display in MacOS

### ISSUE THREAD

**Issue by galgot** [cmus/cmus#907]
1) `uname -a`:
```
Darwin Jack-Torrance.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /opt/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mikmod:
    Priority: 40
    File Types: mod s3m xm it 669 amf dsm far med mtm stm ult
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /opt/local/lib/cmus/op
  coreaudio
  ao
```
Hi,
After changing from cmus 2.7.xx installed via Brew to 2.8.0 installed via Macports,
cmus displays ^@ characters instead of a | (pipe) to make separations, see screenshots 
![Capture d’écran 2019-05-18 à 15 30 28](https://user-images.githubusercontent.com/12213521/57970621-ed466100-7983-11e9-87c4-3b8312749264.png)
This is iTerm2, but it does in any term I use, here is the Mac Terminal
![Capture d’écran 2019-05-18 à 15 34 35](https://user-images.githubusercontent.com/12213521/57970646-1961e200-7984-11e9-88a5-ccee431f7eda.png)

Dunno if its a setting I should change (but how) ...
Term is set to "xterm-256color".
Any idea ?

**Comment by pgaskin** [comment]
@galgot, can you post your cmus `autosave` file, and a screenshot of the terminal settings? Also, does this issue happen with other ncurses applications?

**Comment by galgot** [comment]
Sure ,

![iTerm2Settings](https://user-images.githubusercontent.com/12213521/120802126-5cc72300-c542-11eb-907e-72a5ff1f6ee5.jpg)

the autosave file ,
[autosave.txt](https://github.com/cmus/cmus/files/6598503/autosave.txt)

And I've tried MC (Midnight Commander) file manager, which I think uses ncurses. Displays fine.

**Comment by pgaskin** [comment]
This is definitely a problem with how ncurses is interacting with the terminal. There have been many ncurses fixes since this issue was reported, so if you still have this problem with the latest version of cmus and ncurses (try the homebrew package), please re-open this issue.
