### ISSUE TITLE
cmus need systemd??? you must be kidding me! why???

### ISSUE THREAD

**Issue by unixbhaskar** [cmus/cmus#908]
---

1) `uname -a`:
```
 Linux ArchLinux 5.1.5-1ArchLinux-5.1.5 #1 SMP PREEMPT Sun May 26 10:10:17 IST 2019 x86_64 GNU/Linux

```

2) `cmus --version`:
```
2.8.0-3
```

3) `cmus --plugins`:
```

```

Well, I am getting this ...not sure why...

`bhaskar@ArchLinux_10:38:23_Tue May 28:~>cmus
cmus: /usr/lib/libsystemd.so.0: version `LIBSYSTEMD_243' not found (required by cmus)`

**Comment by geek1011** [comment]
Systemd-dbus is used for MPRIS support. Elogind can be used instead, and systemd can also be disabled during the build.

**Comment by unixbhaskar** [comment]
> Systemd-dbus is used for MPRIS support. Elogind can be used instead, and systemd can also be disabled during the build.

Thank you. But I got the binary package of it from the respective distros package manager, I do run at least 8 of them ..

Now, none of them gave me trouble, in fact, in Debian and OpenSuse, Fedora all run smoothly, which is having systemd only in Arch ...

I believe Arch packager probably build with systemd by default enabled, but with wrong dependency or missed out dependency.

**Comment by unixbhaskar** [comment]
>     1. `uname -a`:
> 
> 
> ```
>  Linux ArchLinux 5.1.5-1ArchLinux-5.1.5 #1 SMP PREEMPT Sun May 26 10:10:17 IST 2019 x86_64 GNU/Linux
> ```
> 
>     1. `cmus --version`:
> 
> 
> ```
> 2.8.0-3
> ```
> 
>     1. `cmus --plugins`:
> 
> 
> ```
> 
> ```
> 
> Well, I am getting this ...not sure why...
> 
> `bhaskar@ArchLinux_10:38:23_Tue May 28:~>cmus cmus: /usr/lib/libsystemd.so.0: version `LIBSYSTEMD_243' not found (required by cmus)`

Well, it seems me getting overly conservative. The long story short, systemd had the bug and which was hanging the boot, so I masked those related packages in package manager config file and avoid those get pulled in for some time. Somebody, point me out and I checked it (lack of interest ) that bug gets squashed sometime back and ask me to merge those package enhancement again. So I did, and voila! it runs like a charm! 
 In few words "updated systemd systemd-libs and sysvcompat" , which was kept back.
