### ISSUE TITLE
View 1's album sort order doesn't suit

### ISSUE THREAD

**Issue by hjrdizwell** [cmus/cmus#909]
[I apologise in advance for possible duplication: I added the below as a comment on a different issue, before realising it had been closed].

I would really like the library view to not sort albums by date: it would be really helpful to be able to actually configure the precise ordering, instead of it being hard-coded. It's easy enough to alter the sort order for View 2 ("Sorted Library") to remove reference to date, for example. Something similar for view 1 would be highly desirable.

For example:

![Screenshot from 2019-05-31 18-51-58](https://user-images.githubusercontent.com/44903401/58725130-542d3680-83d6-11e9-8343-72166ddac8b8.png)

The fact that my recording of Berg's violin concerto is quite an early one shouldn't mandate that it appears at the top of the list! Violin concertos should be somewhere down the end of the list, and 'Adagio' should be at the top. For me, obviously, not everyone... but the basic point is that the album ordering on view 1 should (I feel) be amendable by each user as the mood takes him/her -and, in my specific case, date of recording shouldn't come into it at all.

Being rather new to cmus, it is entirely possible I'm using it wrong ...and if my album sorting order problem can be resolved by other means, I'd really appreciate knowing how!

Cheers.

**Comment by Siegfried-SvR** [comment]
Hi hjrdizwell!

First of all, i must clarify that i'm just a casual cmus user and something could be wrong in my doings, but maybe this helps you as your thread helped me.

I also have a lot of classical music loaded on cmus and not having a proper way to sort it is really annoying, specially when having to look through 40 CDs of the same composer. Lately I have try to take the bull by the horns and started editing the CUE files with simple python routines but it didn't solve the whole problem till i saw this thread (thank you) cause i thought the sorting was alphabetical, not through dates.

In the case it helps someone in the future, the flags that (i think) one should be editing in the CUE files are:
TITLE " "
REM DATE 
PERFORMER "  "  -> I generally put the composer here, and i think it should be replicated on the info of every track

I understand this doesn't solve the problem, but it did helped me a lot on going around it.
