### ISSUE TITLE
Gapless network playback

### ISSUE THREAD

**Issue by svenper** [cmus/cmus#910]
I have my music library on an NFS mounted filesystem. On gapless albums the next track only starts playing after a short delay, where playing files on the same filesystem has no delay.

Is there a setting for preloading the next track while the current is playing? If not, that would be nice.

(m4a ALAC files with ffmpeg decoder)

---

1) `uname -a`:
```
Linux hostname 4.14.122_1 #1 SMP PREEMPT Sun May 26 16:54:49 UTC 2019 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  alsa
```

**Comment by nefthy** [comment]
There is no preloading for network files. Cmus does not even know, that the files are not on the local machine.
