### ISSUE TITLE
cmus crashes terminal even after being uninstalled

### ISSUE THREAD

**Issue by rydealexander** [cmus/cmus#911]
cmus had a problem where when I quit the terminal, it wouldn't reopen, saying it was running somewhere else. I uninstalled cmus and reinstalled it, however now when I type cmus into the terminal it doesn't go to the cmus setup as before it now opens and closes new terminal windows, with cmus never appearing. I get this in the output
# Option "-e" is deprecated and might be removed in a later version of gnome-terminal.
#Use "--" to terminate the options and put the command line to execute after it.
#_g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for 'gio-vfs'
#_g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for 'gsettings-backend'
#watch_fast: "/org/gnome/terminal/legacy/: (establishing: 0, active: 0)
#unwatch_fast: "/org/gnome/terminal/legacy/: (active: 0, establish: 1)
#watch_established: "/org/gnome/terminal/legacy/: (establishing: 0)
The same happens after typing cmus into the terminal, even if cmus is uninstalled
![Screenshot from 2019-06-19 01-01-36](https://user-images.githubusercontent.com/50197899/59684324-db2f3b00-922d-11e9-89ed-dc4402aff66f.png)

**Comment by nefthy** [comment]
I'd quess that "cmus" is not the cmus executable, but rather some wrapper script installed by ubuntu. You can check this by running `file  $(which cmus)` in a terminal. If it is indeed a shell script, you will have to file the bug at the provider of that shell script.
