### ISSUE TITLE
Flac tracknumber not recognised

### ISSUE THREAD

**Issue by dmlemos** [cmus/cmus#917]
I have an album that I converted from flac+cue to flac files using a combination of `shtool` + `cuetools`. Some tags were messed up.

In this case the track number is incorrect. I've fixed it with:
```
$ metaflac --remove-tag=tracknumber '02 - Angelica.flac'
$ metaflac --set-tag=tracknumber=02 '02 - Angelica.flac'

$ ffprobe '02 - Angelica.flac'
Input #0, flac, from '02 - Angelica.flac':
Metadata:
ALBUM : Eternity [Peaceville Records-Pony Canyon Inc PCCY-01050]
TRACKTOTAL : 15
ARTIST : Anathema
PERFORMER : Anathema
GENRE : "Doom metal"
DATE : 1996
TITLE : Angelica
track : 02
Duration: 00:05:50.40, start: 0.000000, bitrate: 809 kb/s
Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```
All the tags in the album were fixed.

After having them fixed I added the folder album to cmus. Unfortunately the are not being recognised and instead it shows something like this:
```
1. Sentient.flac
1. Angelica.flac
1. The Beloved.flac
...
```

NOTE: It took me a while to understand why the track number as not being set. It turns out that `ffprobe` lists _tracknumber_ as _track (lowercase)_, and _track_ as _TRACK (uppercase)_. Only using metaflac I realised the tags were different:
```
$ metaflac --list '02 - Angelica.flac'
...
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 233
  vendor string: reference libFLAC 1.3.2 20170101
  comments: 8
    comment[0]: ALBUM=Eternity [Peaceville Records-Pony Canyon Inc PCCY-01050]
    comment[1]: TRACKNUMBER=02
    comment[2]: TRACKTOTAL=15
    comment[3]: ARTIST=Anathema
    comment[4]: PERFORMER=Anathema
    comment[5]: GENRE=Doom Metal
    comment[6]: DATE=1996
    comment[7]: TITLE=Angelica
```

Just for reference, moc identifies the tracknumbers correctly.

---

1) `uname -a`:
```
Darwin Kenshin.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/op
  coreaudio
  ao
```

**Comment by dmlemos** [comment]
I was having issues with other tags as well later today. After investigating further, it turns out to be the cache.

Deleted the cache file `~/.cmus/cache` and restarted `cmus` and everything is back to normal again.

**Comment by nefthy** [comment]
that is expected behaviour. you have to `:update-cache` if you change the metadata for files already in the library.

**Comment by dmlemos** [comment]
That I did. I pressed `u` and `update-cache` occasionally to confirm the case.
In my opinion it is premature to close the issue.

**Comment by dmlemos** [comment]
The files in question reside in an external USB drive.

**Comment by nefthy** [comment]
Well the tags are recognized correctly, when the tags are read, which is upon adding them and when updating the cache. If you change the tags in beetween, cmus has no knowledge about this event.

**Comment by dmlemos** [comment]
Ah! What you mention makes perfect sense.
I forgot to mention a crucial step. Every time the tags were changed I actually cleared the whole library and ran `update-cache`. With this I thought it would clear the cached tags.

Shouldn't `cmus` force a cache clear (as I did manually) with one of these events?
