### ISSUE TITLE
Cmus does not honor symlinked config

### ISSUE THREAD

**Issue by dmlemos** [cmus/cmus#918]
My dotfiles are all symlinked from a repository. The `.cmus/autosave` is included.

When editing the config, cmus automatically overwrites the autosave file, thus removing the symlink. This does not happen to anything else, for example `.tmux.conf`, `.vimrc`, etc.

I hope there is something that can be done to resolve this.

---

1) `uname -a`:
```
Darwin Kenshin.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg

Output Plugins: /usr/local/Cellar/cmus/2.8.0/lib/cmus/op
  coreaudio
  ao
```

**Comment by jetomit** [comment]
Could you use `.cmus/rc` instead of `autosave` for your config? Settings in `rc` override whatever is in `autosave`, and `rc` is never written to by cmus.

**Comment by nefthy** [comment]
Using the rc file is the way to go.

**Comment by dmlemos** [comment]
Solution works as expected. Thank you
