### ISSUE TITLE
Can not add Internet-Radio streaming address

### ISSUE THREAD

**Issue by jolinux** [cmus/cmus#920]
Hello,
I can not add Radio-Stream in cmus.
Version 2.5 from Debian / 2.8.0 /2.8.x from Git  self compiled.

If I use this command
: add http://www.ndr.de/resources/metadaten/audio/m3u/ndr903.m3u 
or other http://- Sites there are no Errors-answer and cmus not include the Stream at the Track-Window. In every Site-View   1, 2, 3 ,4
Also a saved m3u-File, Ioad from Browser-View with first-Return I see 
 http://ndr-ndr903-hamburg.cast.addradio.de/ndr/ndr903/hamburg/mp3/128/stream.mp3
and second-Return
Error: Couldn't get file information for http://ndr-ndr903-hamburg.cast.addradio.de/ndr/ndr903/hamburg/mp3/128/stream.mp3

Try this Stream-address and more, all addresses run with mplayer !!! 

Please help, cmus ist a nice software.  
---

1) `uname -a`:
```
(paste output here)
```
Linux debian 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
2) `cmus --version`:
```
(paste output here)
`cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Author``

3) `cmus --plugins`:
```
(paste output here)
```
Input Plugins: /home/jo/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /home/jo/lib/cmus/op
  pulse
  alsa
  oss
  jack

**Comment by pgaskin** [comment]
@jolinux, if you still have this issue, can you post a debug log from cmus?

**Comment by jolinux** [comment]
Am Fri, 04 Jun 2021 03:09:57 -0700
schrieb Patrick Gaskin ***@***.***>:

> @jolinux, if you still have this issue, can you post a debug log from
> cmus?
>

Sorry two years. No debug log file

Use today no more cmus, perhaps later again  -))

cu
