### ISSUE TITLE
Strange playback issue

### ISSUE THREAD

**Issue by zbits** [cmus/cmus#921]
I just switched to a HifiBerry Digi as my output device and am experiencing an odd playback issue.  If I try to play back most any file in my library (mostly flac) I get the error message "Error: opening audio device: Invalid argument".  If I play one particular ogg file in my library it plays fine. I can then, without stopping playback, play any other file in my library.  If I stop playback the problem repeats with the same error message, until I play the magic ogg file again.  Very strange.

```
% aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_digi], device 0: HifiBerry Digi HiFi wm8804-spdif-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

% amixer
Simple mixer control 'Tx Source',0
  Capabilities: enum
  Items: 'S/PDIF RX' 'AIF'
  Item0: 'AIF'
```

```
% cat rc
set output_plugin=alsa
set dsp.alsa.device=default
set mixer.alsa.device=default
set mixer.alsa.channel=AIF
```

1) `uname -a`:
```
Linux rpi2 4.19.58-1-ARCH #1 SMP PREEMPT Tue Jul 16 01:25:23 UTC 2019 armv7l GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

**Comment by nefthy** [comment]
It could be that your flac files are in a sampleformat that your audio device does not support. You could try `set dsp.alsa.device=plughw:0` (0 being the alsa card number) and see if it helps.

**Comment by zbits** [comment]
No change.  If the FLAC files are in an unsupported format I would expect them never to work, but they all play fine after playing any OGG file (provided I don't stop playback between).

I've tested with MOC and that will play everything without issue.

Thanks for the help.

**Comment by nefthy** [comment]
plughw does samplerate and bitrate conversion, thus my sugestion.

**Comment by zbits** [comment]
FWIW;

The OGG files that start playback and allow all other files to play are 48k:

````
% cat /proc/asound/sndrpihifiberry/pcm0p/sub0/hw_params 
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 288
buffer_size: 14400
````
The FLAC files are all 44.1k:
````
% cat /proc/asound/sndrpihifiberry/pcm0p/sub0/hw_params 
access: RW_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 245
buffer_size: 13230
````

**Comment by tomty89** [comment]
Cannot reproduce here at all. In fact, if you are really using `default` as `dsp.alsa.device` (assuming you don't have any `/etc/asound.conf` or `~/.asoundrc`), your audio device should always be opened with the same sample spec (a certain spec that the device supports). At least this is the behavior with both my Essence STX and USB DAC. (With `plughw:N` it would be another story though.)

If you want to help find out the cause of your problem further, you may want to convert some of the problematic FLAC files to WAV files (with `flac -d`, i.e. `flac -d /path/to/file.flac -o /path/to/output.wav`, instead of `ffmpeg` or so, which might change the original sample spec) and see if they will trigger the problem as well.

**Comment by pgaskin** [comment]
Closing due to lack of response.
