### ISSUE TITLE
zip file support

### ISSUE THREAD

**Issue by shoober420** [cmus/cmus#923]
1):
```
Linux archlinuxw00t 5.2.4-zen1-1-zen #1 ZEN SMP PREEMPT Sun Jul 28 10:52:59 UTC 2019 x86_64 GNU/Linux
```

2):
```
cmus v2.8.0-18-g1ed60b5
```

3):
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss

```

I request the support for zip file playback, whether the zip files include mp3s, FLACs, or WAVs. This would be similar behavior to how Deadbeef has the ability to play audio files within zip files.

**Comment by castrated** [comment]
for what purpose

**Comment by shoober420** [comment]
@castrated You know, for things.

An example would be bandcamp downloads are zipped by default. Having them kept in the zip saves the hassle of creating a directory and unzipping them into that directory for each album download on bandcamp. It saves space keeping them zipped, and does things.

**Comment by pgaskin** [comment]
This is unlikely to be implemented due to the current architecture of the input plugins, since it would require extracting tracks to a real filesystem path, or making significant changes to allow for multiple layers of input plugins.

In addition, zip archives are unlikely to save any notable amount of space for most audio formats (which are usually compressed already).
