### ISSUE TITLE
CMUS status display over bluetooth

### ISSUE THREAD

**Issue by doggydoggywoofwoof** [cmus/cmus#925]
I  play music using cmus on termux. When connecting to the car over  bluetooth no track, album, artist or album art information is  transmitted. Is there a way to do this? Do I need a specific status  display program?

 It would also be nice to have status display in an android  notification about the current song, with album art displayed, and that  might be part of what I need anyway.

I opened this issue for Termux but a complete jerk and egotist who didn't understand anything about CMUS closed it and claimed it shouldn't be done, not letting anyone else say anything. What a jerk.

**Comment by nefthy** [comment]
cmus does not know anything about bluetooth. You would have to write a status display script. Have a look here for some inspiration:

https://github.com/cmus/cmus/wiki/status-display-programs
