### ISSUE TITLE
How to active MPRIS function?

### ISSUE THREAD

**Issue by pqks** [cmus/cmus#928]
---

1) OS:

Debian 10, XFCE

2) `cmus --version`:

Installed from `deb-multimedia` repository

```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors

```
Well, on XFCE you can control any audio app with pulseaudio plugin (volumen icon on panel), that plugin can handle MPRIS. But, when **cmus** runs doesn't appears. I've wrote the next command on cmus:

```
set: mpris=true
```

**Comment by rien333** [comment]
What value is listed for mpris in the preferences tab (accesed by pressing '7' key)?

Also, you should probably type:

```
:set mpris=true
```
(note the location of the colon)

**Comment by geek1011** [comment]
The deb-multimedia package was not updated properly to depend on systemd or elogind, so it wasn't built with dbus (and thus, MPRIS) support. I have a updated package [here](https://deb.geek1011.net/packages/stable/cmus), and the sources are [here](https://github.com/geek1011/cmus/tree/debian-package/debian).

**Comment by pgaskin** [comment]
@nefthy or @flyingmutant, this issue should probably be closed since it's not a problem with cmus itself.
