### ISSUE TITLE
24bit Audio Files Unsupported On Certain Chipsets That Require 32bit Padding

### ISSUE THREAD

**Issue by shoober420** [cmus/cmus#940]
1) `uname -a`:
```
Linux archlinux 5.3.11-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 12 Nov 2019 22:19:44 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-22-g354625c
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
```

I've been meaning to post about this for some time. Certain chipsets (CMI8788 in my case), require 24bit audio files to be converted to 32bit by adding eight extra bits that get zeroed out (padding). Deadbeef plays these files properly on CMI8788 hardware, because it understands the requirements for these chipsets, and does 32bit padding for 24bit audio files. Could cmus incorporate the same behavior for 24bit files for people who use CMI8788 chipsets or similar? 

I have an ASUS Xonar Essence STX. It does support 24bit audio files, but requires 32bit padding for 24bit audio files. I use the following settings to disable ALSA resampling and enable bit perfect playback with cmus.

/etc/asound.conf
```
pcm.STX {
type hw
card "STX"
}

ctl.!default {
type hw
card "STX"
}

pcm.!default {
type plug
slave {
pcm "STX"
rate "unchanged"
}
}
```

~/.config/cmus/rc
```
set mouse=false
set mpris=true
set output_plugin=alsa
set replaygain=disabled
set softvol=false
set dsp.alsa.device=front
set mixer.alsa.channel=
set mixer.alsa.device=
set mixer.pulse.restore_volume=0
```

The following error is displayed when trying to play 24bit audio files.

```
Error: opening audio device: Invalid argument
```

More info here.

http://ossnext.trueinstruments.com/forum/viewtopic.php?t=4710#p18380

https://github.com/cmus/cmus/issues/379
https://github.com/DeaDBeeF-Player/deadbeef/issues/1895
https://github.com/DeaDBeeF-Player/deadbeef/issues/1907

**Comment by reeeemus** [comment]
I'm having the same issue after upgrading to 2.8.0. ran 2.7.x for years with no issues but tried to fix what wasn't broken by upgrading wanting the multiple playlist support. now I cannot for the life of my figure out how to get my 24bit files to play. after upgrading previously and with no troubleshooting (recompiling, upgrading plugins), they would play but it sounded terribly scratchy. Now I have been able to get 16 bit flacs to play, I get shoober's error when attempting to play 24bit files. Ubuntu 18.04.3


 dsp.alsa.device               hw:1,3

 mixer.alsa.channel
 mixer.alsa.device             default
 mouse                         false
 mpris                         true
 output_plugin                 alsa

results of aplay -l

`x@XPC:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC269VB Analog [ALC269VB Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
`
asound.conf

`pcm.!default {
    type hw
    card 1
}

ctl.!default {
    type hw
    card 1
}
defaults.pcm.card 1
defaults.pcm.device 3
defaults.ctl.card 1
`

**Comment by reeeemus** [comment]
I feel dumb, was able to get them to play by changing "dsp.alsa.device hw:1,3" to "dsp.alsa.device plughw:1,3"

**Comment by shoober420** [comment]
Essentially, this should only occur for people with certain chipsets. More so, people with “audiophile” sound cards. If you do go to the extreme end of the audiophile spectrum, you will get true audiophile DACs that don’t require 32bit padding for 24bit audio files.

**Comment by nefthy** [comment]
`plughw:` is the way to go here

**Comment by shoober420** [comment]
@nefthy 

If you do that, resampling is used, and you won’t have but perfect playback. If a 24bit audio file is padded to 32bit by adding 8 zeros, it’s still technically but perfect. Please reopen.

**Comment by nefthy** [comment]
There is only going to be resampling if the samplerate does not match the hardware. 24bit to 32bit conversion is just going to padd with zeros.

**Comment by shoober420** [comment]
Even if I used “plughw” instead of “hw”, the conversion will still be disabled because I use the “front” speaker setup for my card with ALSA, which will disable all resampling and bit conversions.

Maybe this git commit which fixed it for me on Deadbeef can help.
https://github.com/DeaDBeeF-Player/deadbeef/commit/3677eb8787bf2dc54c08271ac55dc6f90e0018ca

**Comment by shoober420** [comment]
Just to further elaborate, I don't have Pulseaudio installed.

Here is the output of ```aplay -l```

```
**** List of PLAYBACK Hardware Devices ****
card 0: STX [Xonar STX], device 0: Multichannel [Multichannel]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: STX [Xonar STX], device 1: Digital [Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Here is the output for ```aplay -L```

```
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
sysdefault:CARD=STX
    Xonar STX, Multichannel
    Default Audio Device
front:CARD=STX,DEV=0
    Xonar STX, Multichannel
    Front speakers
surround21:CARD=STX,DEV=0
    Xonar STX, Multichannel
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=STX,DEV=0
    Xonar STX, Multichannel
    4.0 Surround output to Front and Rear speakers
surround41:CARD=STX,DEV=0
    Xonar STX, Multichannel
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=STX,DEV=0
    Xonar STX, Multichannel
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=STX,DEV=0
    Xonar STX, Multichannel
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=STX,DEV=0
    Xonar STX, Multichannel
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=STX,DEV=0
    Xonar STX, Multichannel
    IEC958 (S/PDIF) Digital Audio Output
usbstream:CARD=STX
    Xonar STX
    USB Stream Output
```

Its kind of annoying to have to switch between ```hw:0,0``` and ```plughw:0,0``` using ```:set dsp.alsa.device=hw:0,0``` for 16bit redbook files, and ```:set dsp.alsa.device=plughw:0,0``` for 24bit audio files, but thats the price I pay for not getting a true audiophile sound card.

It makes me wonder what Deadbeef is using then when I set it to the ```front``` option. All the other options, like those surround sound options you see, don't even work, and I'm almost for certain are just Pulseaudio presets. I would hope Deadbeef is using ```hw:0,0```, especially since I have the "Enable ALSA Resampling" option unchecked in the ALSA plugin menu.

**Comment by shoober420** [comment]
Ok, interesting results. cmus will correctly keep the bit rate and sample rate, and harmlessly changes the buffers and access type. So Deadbeef does indeed use ```plughw:0,0```.

Deadbeef:
```
cat /proc/asound/card0/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 1024
buffer_size: 8192
```

cmus:
```
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 224
buffer_size: 13228
```
