### ISSUE TITLE
[Feature request] Remember last open folder in browser window after quitting

### ISSUE THREAD

**Issue by dmlemos** [cmus/cmus#942]
Feature request to remember the browser window last folder/position after quitting the program.

Would be great to open cmus, go to the browser window and being able to start from where I left of before quitting.
People familiar with other browsing programs (directly or indirectly), understand this is the default behaviour.

**Comment by larrasket** [comment]
Set `resume` to true.

**Comment by pgaskin** [comment]
The `resume` option is correct. For reference, here's the part which loads it:

https://github.com/cmus/cmus/blob/a92a0424ebbc9117ed1592fdd346d64c87af5f5a/options.c#L2029-L2065
