### ISSUE TITLE
Support for bluetooth controls

### ISSUE THREAD

**Issue by angrykoala** [cmus/cmus#948]
Some GUI music players (such as rythmbox) support using Bluetooth headset buttons for play/pause/next (1 click play/pause, 2 clicks for next), 

I was wondering if there is a way (or hack) to achieve this with cmus or cmus-remote

**Comment by grenzionky** [comment]
cmus is recognized a media player by linux, so u just need to call it through a media controller program to get it to do things. so for example `playerctl -p cmus play-pause` will toggle play/pause for cmus.

**Comment by angrykoala** [comment]
@grenzionky I'm probably missing something, but trying what you are mentioning only returns `No players found`

I've seen the project and it looks like it should work as you said (currently running cmus v2.8.0) is there something else I need to make this work?

Thanks

**Comment by grenzionky** [comment]
u need to have cmus open when u do that.  
try doing `playerctl -l` to see all available players

**Comment by angrykoala** [comment]
Yeah, I though about that, with cmus open playertctl list returns the following:
```
chrome.instance2289
```
no cmus listed :disappointed:

**Comment by zsugabubus** [comment]
`cmus` needs `MPRIS` support enabled in order to being able to communicate with `playerctl`. Is it enabled for you? Try `./configure CONFIG_MPRIS=y ...` (and build from source).

**Comment by angrykoala** [comment]
No idea if that's enabled, I'm using cmus installed from ubuntu repository (tbh, I've never build it from source) I'll try as you say though I would like to know if there is a way to enable MPRIS without rebuilding :/

Thanks a lot for your help

**Comment by angrykoala** [comment]
Default `./configure` seems to work

`./configure CONFIG_MPRIS=y`

Fails with the following error:

```
checking for OPUS_LIBS (pkg-config)... no
*** Package opusfile was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `opusfile.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'opusfile' found
checking for LIBSYSTEMD_LIBS (pkg-config)... no
*** Package libsystemd was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libsystemd.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libsystemd' found
checking for LIBSYSTEMD_LIBS (pkg-config)... no
*** Package libelogind was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libelogind.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libelogind' found
configure failed.
```
Trying to install libelogind try tries to remove 83 packages with a scary warning message. :confused:

**Comment by zsugabubus** [comment]
https://www.freedesktop.org/wiki/Specifications/mpris-spec/:
> The Media Player Remote Interfacing Specification (MPRIS) is a standard D-Bus interface which aims to provide a common programmatic API for controlling media players. 

> Default ./configure seems to work

Yeah, it all makes sense if you don't use `systemd`–it gets disabled by default. (Unfortunatelly,) `cmus` depends on `libsystemd` that implements this `dbus` communication thing.

As far as I can tell you, I fear your only way is to use `cmus-remote`.

**Comment by angrykoala** [comment]
@zsugabubus that actually sounds like a reasonable workaround, is there any built-in / recommended way of doing this binding with cmus or just with the default OS binding should be enough?

**Comment by zsugabubus** [comment]
The only choice is `cmus-remote --prev/--next/--pause`. I don't know what system do you using, but surely there is a way to bind media keys globally.

**Comment by makar47** [comment]
> cmus is recognized a media player by linux, so u just need to call it through a media controller program to get it to do things. so for example
> `playerctl -p cmus play-pause`
> will toggle play/pause for cmus.


which program can intercept the keystrokes of a bluetooth device? For example in Ubuntu?

**Comment by zsugabubus** [comment]
Search for "ubuntu keybindings". You should be able to create custom bindings in the keyboard settings.

**Comment by grenzionky** [comment]
sxhkd should work no matter the desktop environment. its what i use for all my keyboard shortcuts

**Comment by angrykoala** [comment]
Although I cannot exactly replicate my ideal behavior, using sxhkd with the following configuration:
```
XF86AudioPlay
	cmus-remote --next
```

Althoug I'm not sure how to do it when double-clicking and toggle (pause-play)

**Comment by zsugabubus** [comment]
> Althoug I'm not sure how to do it when double-clicking and toggle

Which part do you need help exactly? You can use `xev` (or `evtest`...) to find out the key names, then you can use `cmus-remote --pause` to toggle. Or the question is how to distinguish single-clicks from double-clicks (because you receive the same key)?

**Comment by angrykoala** [comment]
@zsugabubus The exact behaviour I want is:

* Single click: Play-pause (the toggling is not a problem)
* Double click: next

My problem is, first detecting the double click and second having also a single click. Being naive I tried with `XF86AudioPlay;XF86AudioPlay` to detect double click and It didn't work as expected (I needed 2 clicks, but I had to wait a bit before the second click and following single clicks where also detected). I haven't had a lot of time to tinker around yet

**Comment by grenzionky** [comment]
you can use `xev` to detect if double clicking sends a different key than a single click. or check evtest to see the full list of keys ur bluetooth device has, and see if one of them might be what double clicking does. (ie `XF86AudioPrev` or `XF86AudioNext`)

**Comment by zsugabubus** [comment]
I'm a bit bored, so just in case the headset sends the same keys... try this:

```bash
#!/bin/bash
PIDFILE=${TMP:-/tmp}/click.pid
INTERVAL=.3

if [ -f "$PIDFILE" ]; then
  pkill -F "$PIDFILE" -USR1 && exit
fi

echo >"$PIDFILE" $$

clicks=1
trap 'clicks=$((clicks+1)); echo Click!' USR1

while :; do
  sleep $INTERVAL &
  wait && break
done
rm -f "$PIDFILE"

echo Clicks: $clicks
case $clicks in
1) cmus-remote --pause ;;
2) cmus-remote --next ;;
*) cmus-remote ... ;;
esac
```

**Comment by JezerM** [comment]
I also had this problem with `playerctl` and this kind of music players, but as it's said in #1043, It's recommendable to install these dependencies to build with `./configure CONFIG_MPRIS=y`
> https://github.com/cmus/cmus/blob/0aceac178204c6398e86edf30bdbe001dc88649b/.github/workflows/build.yml#L29-L35

Also, there should be a list of dependencies in README, it's not helpful without them.

**Comment by pgaskin** [comment]
Bluetooth controls are supported via MPRIS like with other media players. This specific issue is due to missing/misconfigured DBus support, and as such, is not a bug in cmus itself.
