### ISSUE TITLE
How to get back a win-removed song?

### ISSUE THREAD

**Issue by grenzionky** [cmus/cmus#950]
I by mistake pressed `D` on a track, so it disappeared, and i cant figure out how to get it back into my library. Doing `a` on the track in the directory view doesnt add it back, neither does pressing `:add /dir/to/song.mp3`. even after doing `win-update` it still doesnt show up. Im not sure what im missing… It would be nice if there would be a keyboard shortcut that can undo a `D` right after doing it

**Comment by pgaskin** [comment]
Closing due to a lack of response.

Note that if you accidentally removed some tracks, you can also force-kill (`killall -9 cmus`) cmus to prevent the updated library being saved to disk. This will revert all changes made since cmus was started.
