### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by nkh** [cmus/cmus#961]
1) `uname -a`:
```
Linux nadim-GS40-6QE-Phantom 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-24-gd1290d5
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
Input Plugins: /usr/local/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/local/lib/cmus/op

```
Hi, 
running KDE if that has any importance

I couldn't install with the package manager (repository not found) that would be enough for me but I tried to install from source, I cloned the repo and build (see BUILD OUTPUT below)

./configure complains about missing libs, but compilation goes fine and so does starting the program.  

53 ~/3/cmus ■ ./cmus
./cmus: Error: couldn't open directory `/usr/local/lib/cmus/op': No such file or directory
./cmus: Press <enter> to continue.

then in the main view this message
 . 00:00 - 00:00
Error: selecting output plugin '': no such plugin

when adding music directories, no files are visible

I looked to see if libraries are installed (ffmpeg ...) and they seem to be.

Help highly appreciated. 

BUILD OUTPUT:
----------------------
22 ~/3/cmus ■ ./configure
checking for program gcc... /usr/bin/gcc
checking for program gcc... /usr/bin/gcc
checking for C11 (with atomics support)... yes
checking for CFLAGS -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... yes
checking for CFLAGS -Wold-style-definition... yes
checking for CFLAGS -Wno-pointer-sign... yes
checking for CFLAGS -Werror-implicit-function-declaration... yes
checking for CFLAGS -Wno-unused-parameter... yes
checking for CFLAGS -Wno-missing-field-initializers... yes
checking if CC can generate dependency information... yes
checking byte order... little-endian
checking for DL_LIBS (-ldl -Wl,--export-dynamic)... yes
checking for PTHREAD_LIBS (-lpthread)... yes
checking for realtime scheduling... yes
checking for program pkg-config... /usr/bin/pkg-config
checking for NCURSES_LIBS (pkg-config)... -lncursesw -ltinfo
checking for NCURSES_CFLAGS (pkg-config)... -D_GNU_SOURCE -D_DEFAULT_SOURCE
checking for working ncurses setup... yes
checking for function resizeterm... yes
checking for function use_default_colors... yes
checking for ICONV_LIBS (-liconv)... no
assuming libc contains iconv
checking for working iconv... yes
checking for header <byteswap.h>... yes
checking for function strdup... yes
checking for function strndup... yes
checking for CDDB_LIBS (pkg-config)... no
checking for CDDB_LIBS (-lcddb)... no
checking for CDIO_LIBS (pkg-config)... no
checking for CDIO_LIBS (-lcdio_cdio -lcdio -lm)... no
checking for FLAC_LIBS (pkg-config)... no
checking for FLAC_LIBS (-lFLAC -lm)... no
checking for MAD_LIBS (pkg-config)... no
checking for MAD_LIBS (-lmad -lm)... no
checking for MODPLUG_LIBS (pkg-config)... no
checking for MODPLUG_LIBS (-lmodplug -lstdc++ -lm)... no
checking for header <mpc/mpcdec.h>... no
checking for header <mpcdec/mpcdec.h>... no
checking for VORBIS_LIBS (pkg-config)... no
checking for VORBIS_LIBS (-lvorbisfile -lvorbis -lm -logg)... no
checking for OPUS_LIBS (pkg-config)... no
*** Package opusfile was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `opusfile.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'opusfile' found
checking for LIBSYSTEMD_LIBS (pkg-config)... no
*** Package libsystemd was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libsystemd.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libsystemd' found
checking for LIBSYSTEMD_LIBS (pkg-config)... no
*** Package libelogind was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libelogind.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libelogind' found
checking for WAVPACK_LIBS (pkg-config)... no
checking for WAVPACK_LIBS (-lwavpack)... no
checking for header <mp4v2/mp4v2.h>... no
checking for header <mp4.h>... no
checking for header <neaacdec.h>... no
checking for FFMPEG_LIBS (pkg-config)... no
*** Package libavformat was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libavformat.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libavformat' found
*** Package libavcodec was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libavcodec.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libavcodec' found
checking for header <ayemu.h>... no
checking for PULSE_LIBS (pkg-config)... no
*** Package libpulse was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libpulse.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libpulse' found
checking for ALSA_LIBS (pkg-config)... no
*** Package alsa was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `alsa.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'alsa' found
checking for JACK_LIBS (pkg-config)... no
*** Package jack was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `jack.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'jack' found
checking for SAMPLERATE_LIBS (pkg-config)... no
*** Package samplerate was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `samplerate.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'samplerate' found
checking for AO_LIBS (pkg-config)... no
checking for AO_LIBS (-lao)... no
checking for program artsc-config... no
checking for header <sys/soundcard.h>... no
checking for SNDIO_LIBS (-lsndio)... no
checking for header <sys/audioio.h>... no
checking for ROAR_LIBS (pkg-config)... no
*** Package libroar was not found in the pkg-config search path.
*** Perhaps you should add the directory containing `libroar.pc'
*** to the PKG_CONFIG_PATH environment variable
*** No package 'libroar' found
23 ~/3/cmus ■ make -j 8
   CC     ape.o
   CC     browser.o
   CC     buffer.o

... everything compiles fine ...
 
   HOSTLD     Doc/ttman
   MAN    Doc/cmus.1
   MAN    Doc/cmus-remote.1
   MAN    Doc/cmus-tutorial.7
   LD     cmus

27 ~/3/cmus ■ sudo make install
INSTALL /usr/local/bin/cmus
INSTALL /usr/local/bin/cmus-remote
INSTALL /usr/local/lib/cmus/ip/wav.so
INSTALL /usr/local/lib/cmus/ip/cue.so
INSTALL /usr/local/share/cmus/gruvbox-alt.theme
INSTALL /usr/local/share/cmus/rc
INSTALL /usr/local/share/cmus/zenburn.theme
INSTALL /usr/local/share/cmus/solarized-dark.theme
INSTALL /usr/local/share/cmus/night.theme
INSTALL /usr/local/share/cmus/green-mono-88.theme
INSTALL /usr/local/share/cmus/gruvbox.theme
INSTALL /usr/local/share/cmus/cyan.theme
INSTALL /usr/local/share/cmus/solarized-light.theme
INSTALL /usr/local/share/cmus/gray-88.theme
INSTALL /usr/local/share/cmus/dracula.theme
INSTALL /usr/local/share/cmus/green.theme
INSTALL /usr/local/share/cmus/xterm-white.theme
INSTALL /usr/local/share/cmus/default.theme
INSTALL /usr/local/share/cmus/jellybeans.theme
INSTALL /usr/local/share/man/man1/cmus.1
INSTALL /usr/local/share/man/man1/cmus-remote.1
INSTALL /usr/local/share/man/man7/cmus-tutorial.7
INSTALL /usr/local/share/doc/cmus/examples/cmus-status-display

**Comment by jayay** [comment]
Did you check if the development packages (`-dev`) of pulseaudio or alsa are installed?

**Comment by pgaskin** [comment]
@nefthy or @flyingmutant, this issue should probably be closed since it's not a problem with cmus itself and there hasn't been a response for 8 months.
