### ISSUE TITLE
Cmus won't add or recognize mp3 files?

### ISSUE THREAD

**Issue by trophystitch** [cmus/cmus#970]
I have mp3 files in my Downloads folder, it plays in the GUI player and shows up in ls, but in Cmus it is not recognized in the :add command or in the browser view. Does anyone know how to fix this?

1) `uname -a`:
```
Linux zacbook 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.7.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa ac3 aif aifc aiff ape au mka shn tak tta wma webm aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao
```

**Comment by jasonmendes** [comment]
I recently pulled the repo and compiled and ran into this as well. I thought I must have configured it incorrectly

**Comment by AnoRebel** [comment]
I had the same issue a few days ago as i was trying to build the latest(2.8) from the repo..
I fixed it by installing a library, i think its the "mad" (libmad) and its corresponding -dev package(if any) or something, am not sure what its named in your distro repo, but after installing and rebuilding, mp3 files could play.. I'm on Mint 20..
Hope this helps..

**Comment by pgaskin** [comment]
I'm closing this since there hasn't been a response for a year. @trophystitch, if you still have this issue, can you give a bit more detail on the exact command you used to attempt to add the tracks?
