### ISSUE TITLE
cmus: unrecognized option `--passwd'

### ISSUE THREAD

**Issue by gotbletu** [cmus/cmus#971]
think you guys are missing an extra dash for the **passwd** flag
> $ man cmus
> --passwd PASSWD
> Set the password for TCP/IP connections.  Must be set if you are listening from host[:port].  Used in conjunction with --listen.

NOT WORKING
> $ cmus --listen localhost:3050 --passwd abc123
> cmus: unrecognized option `--passwd'

WORKING
> $ cmus --listen localhost:3050 -passwd abc123

---

1) `uname -a`:
```
Linux heOyeA-ant 5.5.6-arch1-1 #1 SMP PREEMPT Mon, 24 Feb 2020 12:20:16 +0000 x86_64 GNU/Linux

```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors

```

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```

**Comment by dirdi** [comment]
I can confirm this bug. The `passwd` option is missing in this struct: https://github.com/cmus/cmus/blob/d1290d50f9f7585c43b9e1326c0d6d1e0b4583f6/ui_curses.c#L2472

Therefore the `long_option` function will raise the observed error:
https://github.com/cmus/cmus/blob/17bf542c6b120d9dcf6642b259d78badfc1143eb/prog.c#L91

**Comment by eshrh** [comment]
Strange how this hasn't been caught earlier...

**Comment by pgaskin** [comment]
The server password should be set in the options rather than the CLI options. I'll update the documentation.
