### ISSUE TITLE
undefined __atomic_fetch_add_8

### ISSUE THREAD

**Issue by nguxx** [cmus/cmus#976]
1) `uname -a`:
```
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

```

2) `cmus --version`:
```
last
```
on `make` I get 
```
/usr/bin/ld: track_info.o: in function `track_info_new':
/home/pi/cmus/track_info.c:47: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make: *** [Makefile:52: cmus] Error 1
```
I'm not very good at compiling... I cannot remeber how I succed to get cmus on my former Raspberry Pi... but i know i'ld like to use it again...
Any idea to go beyond...

**Comment by geek1011** [comment]
Try adding `-latomic` to the LDFLAGS.

**Comment by nguxx** [comment]
Thanks. It works with 
`make LDFLAGS=-latomic`
(I write it down for n00bs like me, cause I was a little bit puzzle with "adding to LDFLAGS")

**Comment by pgaskin** [comment]
@nefthy or @flyingmutant, this issue should probably be closed since it's been resolved and it's not a problem with cmus itself.
