### ISSUE TITLE
win-page-down doesn't work in Track list

### ISSUE THREAD

**Issue by jchook** [cmus/cmus#977]
In the Artist/Album/Track view, I can browse artists by `win-page-down`, `win-half-page-down`, etc. However, when I press `win-next` (tab) to the "Track" column / split, I cannot use `win-page-down`, etc anymore.

I tried binding the keys explicitly in the "browser" mode.

I also have the same issue playlists, file browser, and filters views.

---

1) `uname -a`:
```
Linux nanos 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

**Comment by jamesblissett** [comment]
For me, win-page-down only works when the screen has enough text that it can be scrolled i.e there is text that is not displayed. Maybe this is causing you not to be able to scroll?

**Comment by jchook** [comment]
Yes, thanks.

Hoping it wouldn't be too hard to let these commands work even without multiple pages.

**Comment by jchook** [comment]
So to summarize...

- When on the first page, page-up should bring the highlighted row to the top of the list
- When on the last page, page-down should bring the highlighted row to the bottom of the list
- When pressing half-page-up / down it should jump that many list items, even without pages

Other ncurses apps I use work this way, such as mutt and newsboat.

**Comment by jchook** [comment]
I just realized I can use <kbd>g</kbd> and <kbd>G</kbd> to go to the top and bottom of lists!
