### ISSUE TITLE
How to change treeview width

### ISSUE THREAD

**Issue by 38569459** [cmus/cmus#990]
---
I don't find the option to change treeview width anywhere? How can i change treeview width (the list that is always show on the left)

1) `uname -a`:
```
5.7.10-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

**Comment by pgaskin** [comment]
@38569459:

You can use the new `tree_width_percent` and `tree_width_max` options.
