### ISSUE TITLE
cmus-status-display

### ISSUE THREAD

**Issue by kajzersoze** [cmus/cmus#991]
So I've been reading man page and I'm curious about status_display_program () [command]

It says this
> This command, if not empty, is run every time cmus' status changes. It can be used to display currently playing track on desktop background or panel for example.	 See /usr/share/doc/cmus/examples/cmus-status-display.

I don't have examples dir in /usr/share/doc/cmus, neither can I find this file in other locations, tried to find it here but no luck, can I find it somewhere and read ti ?

**Comment by laMudri** [comment]
The wiki has some useful examples: https://github.com/cmus/cmus/wiki/status-display-programs

**Comment by kajzersoze** [comment]
Yeah, I guess man page should be updated.
