### ISSUE TITLE
Homebrew cmus v2.8.0 fails to start on macOS 

### ISSUE THREAD

**Issue by mjsteinbaugh** [cmus/cmus#995]
Installed cmus using `brew install cmus`. Attempting to run `cmus` generates this error:

```
cmus: bind: No such file or directory
```

---

1) `uname -a`:
```
Darwin goose-pond.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,2 Darwin
```

2) `cmus --version`:
```
cmus v2.8.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.8.0_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.8.0_1/lib/cmus/op
  coreaudio
```

**Comment by mjsteinbaugh** [comment]
Troubleshooting, this seems to work:

```sh
cmus --listen 127.0.0.1
```

**Comment by pgaskin** [comment]
What is the output of `echo $XDG_RUNTIME_DIR`? If this isn't empty, cmus expects this directory to already exist. The same applies to `$CMUS_SOCKET`.

**Comment by mjsteinbaugh** [comment]
Thanks @pgaskin , that is the issue. I set XDG configuration automatically using my [koopa](https://koopa.acidgenomics.com) shell bootloader.

```sh
echo $XDG_RUNTIME_DIR
# /tmp/run/user/501
```

I can confirm that cmus errors when `XDG_RUNTIME_DIR` doesn't exist, but will launch successfully when you create the directory. We should fix this in the program to create the directory, if necessary.

Unsetting `XDG_RUNTIME_DIR` resolves the issue.

```sh
unset -v XDG_RUNTIME_DIR
cmus
```

**Comment by pgaskin** [comment]
> We should fix this in the program to create the directory, if necessary.

That wouldn't be compliant with [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

>  $XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. The directory MUST be owned by the user, and he MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.
>
> The **lifetime of the directory MUST be bound to the user being logged in. It MUST be created when the user first logs in** and if the user fully logs out the directory MUST be removed. If the user logs in more than once he should get pointed to the same directory, and it is mandatory that the directory continues to exist from his first login to his last logout on the system, and not removed in between. Files in the directory MUST not survive reboot or a full logout/login cycle. 

So, if anything creates the directory, it should probably be koopa.

**Comment by mjsteinbaugh** [comment]
OK thanks that makes sense. I'll fix the configuration in koopa to better support this.
