### ISSUE TITLE
How to manage plugins for different format of files

### ISSUE THREAD

**Issue by nguxx** [cmus/cmus#999]
---

1) `uname -a`:
```
Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux

```

2) `cmus --version`:
```
cmus v2.8.0-24-gd1290d5
```

3) `cmus --plugins`:
```
Input Plugins: /home/pi/cmus/lib/cmus/ip
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /home/pi/cmus/lib/cmus/op
  alsa

```
As it shows in cmus --plugins I can only see .wav
How to manage plugins to get .flac .mp3 and so on

I've just compiled cmus from source and theses libs are installed
```
 libmad0 cmus-plugin-ffmpeg
```
thanks

**Comment by alzee** [comment]
Easiset way:

```
apt install cmus
cp /usr/lib/cmus/ip/* /usr/local/lib/cmus/ip/
apt remove cmus
cmus --plugins
```

**Comment by pgaskin** [comment]
@nefthy or @flyingmutant, this issue should probably be closed since it's not a problem with cmus itself and there hasn't been a response for 2 months.
